### ISSUE TITLE
Question: using cmake for windows/osx/unix builds

### ISSUE THREAD

**Issue by boxerab** [libjpeg-turbo/libjpeg-turbo#111]
Hello,

First of all, very very cool project here : thanks for building this and sharing.

I would like to add libjpeg-turbo to another cmake project:

https://github.com/GrokImageCompression/grok

Since grok uses cmake for all platform builds, I would prefer to also use cmake for all
libjpeg-turbo builds, so that the two projects can be built together.

Will this work?

Thanks,
Aaron

**Comment by dcommander** [comment]
Noted, but this is a complicated issue.  Refer to https://github.com/libjpeg-turbo/libjpeg-turbo/issues/56 and https://sourceforge.net/p/libjpeg-turbo/mailman/libjpeg-turbo-devel/thread/cd9be8d2-0006-f7d1-e1a4-54f4ba4643ac%40users.sourceforge.net/#msg35406702.  Basically, for the moment, it's best to pretend that CMakeLists.txt doesn't exist on non-Windows platforms.  That build system was introduced originally so I could support Visual Studio users without having to check in raw Visual Studio files into the project.  It would take a lot of work to ensure that all of the features of the autotools Un\*x build system are supported in the CMake build system.  I'm unwilling to do that work unless someone pays for it, and even then, I would very strongly prefer to have only one build system on each platform.  Thus, fully supporting CMake implies eliminating autotools, which is an unpopular proposal among many Linux developers.

I have agreed to migrate the OS X build system to CMake in libjpeg-turbo 1.6, so really we're just arguing over whether to do the same for Linux, FreeBSD, and other non-Mac Un\*x implementations.  If you have any arguments to add in that regard, please add them under #56.  Personally, I would be in favor of using CMake for everything, but it's going to take a lot of work to port all of the features and change the documentation and train everyone as to how to perform various cross-compilation tasks with CMake and field numerous pieces of hate mail from the Linux distributors who prefer autotools, etc.  At the moment, the issue is deadlocked, which means that it's not going to move forward unless something changes.

**Comment by boxerab** [comment]
Thanks for the update on this issue :)
