### ISSUE TITLE
decoding jpeg with custom data failed

### ISSUE THREAD

**Issue by bournex** [libjpeg-turbo/libjpeg-turbo#112]
im developing a imagecodec with libjpeg-turbo. the source jpeg is not a 'pure' jpeg, there are some custom data between 0xFF headers...just like:

00000000h: **FF D8 FF E1** 00 40 01 00 10 06 03 2F 0B 26 29 30 ;
00000010h: 32 33 2C 30 30 30 30 30 30 30 32 2C 30 30 30 30 ;
00000020h: 30 30 30 2C 30 30 30 30 30 2C 30 39 31 33 2C 30 ;
00000030h: 30 37 36 2C 02 2C 30 31 2C 30 30 30 30 32 32 38 ;
00000040h: 30 39 36 32 00 00 01 00 20 20 20 20 20 20 20 20 ;
00000050h: 20 20 20 20 BB A6 4B 39 39 37 36 32 2C 63 3D 30 ;
00000060h: 32 2C 77 3D 30 31 36 33 2C 68 3D 30 30 33 30 2C ;
00000070h: 73 3D 31 31 35 35 2C 31 31 38 35 2C 30 35 38 35 ;
00000080h: 2C 30 37 34 38 2C 70 3D 30 39 39 36 2C 74 3D 30 ;
00000090h: 32 2C 62 63 3D 30 31 2C 30 32 2C BA DA C9 AB 2C ;
000000a0h: C9 EE C9 AB 2C 41 3D 30 32 30 30 2C 30 35 30 30 ;
000000b0h: 2C 31 32 30 30 2C 30 36 30 30 2C 70 74 3D 30 31 ;
000000c0h: 2C 72 74 3D 30 31 35 32 20 20 20 20 20 20 20 20 ;
000000d0h: 20 20 20 20 BB A6 4B 39 39 37 36 32 2C 70 3D 30 ;
000000e0h: 39 39 36 2C 54 3D 30 32 37 66 61 62 62 65 3B 20 ;
000000f0h: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 ;
00000100h: 20 20 20 2C 70 3D 30 30 30 30 2C 54 3D 30 30 30 ;
00000110h: 30 30 30 30 30 3B 20 20 20 20 20 20 20 20 20 20 ;
00000120h: 20 20 20 20 20 20 20 20 20 20 2C 70 3D 30 30 30 ;
00000130h: 30 2C 54 3D 30 30 30 30 30 30 30 30 3B 00 30 30 ;
00000140h: 30 30 30 30 30 30 **FF E3** 00 40 53 3D 33 36 30 75 ;

this cause a decode error when im invoking tjDecompressHeader3..
i trace the code to "jdmarker.c", and found out if change "WARNMS2" to "TRACEMS2" in line 926, the image will be decoded successfully. 

i was wondering, if libjpeg-turbo could skip the custom data, then why not let decode success.

**Comment by dcommander** [comment]
The libjpeg API will not throw a warning unless there is something structurally wrong with the JPEG image.  It is impossible for me to say what might be wrong with the image without seeing the entire image, but I can tell you that the libjpeg API works correctly (without warnings) on several JPEG+EXIF images I tested.

The TurboJPEG API continues decoding the image if it encounters a libjpeg warning, but it still returns -1 to indicate that you should check the error message.  A possible enhancement to that API would be to return a different error code for warnings as opposed to errors, thus allowing programmers to more easily decide whether to ignore the warnings or not.  However, referring to http://www.libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf, there are some good reasons why security-conscious applications should not ignore libjpeg warnings.

If this is an image you generated, then apparently something about the image is incorrectly encoded.  If it's an image that was generated by another program, then please provide details about the program, and I will try to reproduce the issue.  That's the best I can do, unfortunately.  The code in question has existed since 1994, so it's canonical at this point.

**Comment by bournex** [comment]
a return code which indicate fatal and non-fatal error would be nice. some high level application need fault-tolerant ability, this can make the process continue when get a warning which the program don't care.

**Comment by dcommander** [comment]
OK, I'll look into that for 1.6.
