### ISSUE TITLE
expected '=', ',', ';', 'asm' or '__attribute__' before 'static'  #define LOCAL(type)             static type

### ISSUE THREAD

**Issue by indrasenakatam** [libjpeg-turbo/libjpeg-turbo#115]
Hi All,
I have tried to implement **libjpeg-turbo[BUILD "20161115 ,  VERSION "1.5.2]** in Android Studio JNI project. I have successfully compiled project **Ubutnu 14.04 LTS  64- bit command prompt** . 

But ,While adding to  this library to Android JNI project. I am getting errors like this.

**1 :** Android Source project/jni/libjpeg-turbo/src/jmorecfg.h:209:33: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'static'    #define LOCAL(type)             static type

**2:** /jni/libjpeg-turbo/src/jccolext.c:31:1: note: in expansion of macro 'LOCAL'  LOCAL(void)

**3:** jccolext.c:31:1: note: in expansion of macro 'LOCAL'  LOCAL(void)

**4:** jccolext.c:125:1: note: in expansion of macro 'LOCAL'   LOCAL(void)

So could please help to resolve this issues in Android Studio 2.2 . And could please provide any document  **if exist**  which related to integrate in Android Studio JNI apps. It helps great to me.

please find the attached complete errors.txt file and make file which used to compile the library  .
[errors.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/files/592442/errors.txt)
[Android.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/files/592470/Android.txt)

Thank you so much in Advance

**Comment by dcommander** [comment]
I have no idea, but the error messages would suggest that the "static" keyword is not being accepted by the compiler, perhaps because some other header is defining "static" as a macro.  I have no specific experience with Android Studio, unfortunately.  Our build instructions demonstrate how to build an Android version of libjpeg-turbo from the command line.  That might offer some clues as to why it's failing in Android Studio-- or you could simply build libjpeg-turbo from the command line and then include the binary library in your Android Studio project.  Hopefully someone else in the community will see this and chime in.

**Comment by dcommander** [comment]
Closing due to lack of response.  Please try to build libjpeg-turbo using the build instructions in BUILDING.md.  If those instructions do not work, or if you feel you cannot use them for some specific reason, then please provide further information.  Otherwise there's not much I can do here.

**Comment by peergine-admin** [comment]
f**k , I read BUILDING.md  ，bat no help

**Comment by dcommander** [comment]
@peergine-admin how specifically is the build failing?  I revisited the Android NDK build recently, and the instructions in the latest version of BUILDING.md available in Git master should work (the Android instructions in the 1.5.3 version of BUILDING.md only work if you're using NDK r15 or earlier.)

**Comment by peergine-admin** [comment]
@dcommander sorry .
I found the reason, I cloned the warehouse to the windows disk, and then mount to build on Ubuntu, and then how can not compile, there has been this error. Later I cloned to Ubuntu disk just fine.
