### ISSUE TITLE
How to compile libjpeg-turbo [ version : 1.5.2  latest ]  for Android

### ISSUE THREAD

**Issue by indrasenakatam** [libjpeg-turbo/libjpeg-turbo#117]
Hi, I am working on Android application which required to integrate libjpeg-turbo [ **version : 1.5.2**  latest ]  Using Android NDK/JNI along with Android.mk  files. So, Could you please provide any help to compile  libjpeg-turbo [ I have an idea about Android NDK/JNI compile process to .so library].

I have successfully compiled  **libjpeg-turbo [ version : 1.5.2  latest ]**    through the Linux Ubuntu 14.04 LTS 64-bit OS Command prompt (Terminal). But how can I use these headers and source files to generate **.so** library using Android NDK build. 

Thank you so much in advance.

**Comment by dcommander** [comment]
Have you tried the instructions in BUILDING.md?  There is a section that explains how to build an Android version of the library using autotools.

**Comment by dcommander** [comment]
Closing due to lack of response.  If you want a more specific answer or technical assistance, then please provide additional information.  Android NDK builds of libjpeg-turbo are well-tested and well-documented, and if you prefer not to use autotools, you can try building from the dev branch using CMake.  If the instructions in BUILDING.md don't work, then please provide more specific information as to how the build procedure is failing.
