### ISSUE TITLE
Arithmetic coded JPEG decoding (suspension support)

### ISSUE THREAD

**Issue by vrubleg** [libjpeg-turbo/libjpeg-turbo#120]
Someone tried to build Firefox with arithmetic coded JPEG support. He encountered a problem:

> Found the problem, unfortunately no solution:
> The arithmetic decoder in libjpeg does not support suspension. That´s how I understood it: Firefox calls libjpeg to decode everything it can with the available data (libjpeg request data via callback function). Problem is that the arithmetic decoder needs all data and cannot be suspended. In case firefox tells libjpeg no data, arithmetic decoder fails.
> Small images with arithmetic coding - saved locally - work.
> Basically the problem is libjpeg.

It seems that the problem is still here, as `jdarith.c` says:
`/* Read next input byte; we do not support suspension in this module. */`

It seems that the same problem occurs [to this user](https://bugs.chromium.org/p/chromium/issues/detail?id=669501#c5) of Chrome: when an arithmetic coded image is loaded the first time, it is displayed only partly. But when he tries to load it second time, the image is displayed correctly (probably, because of the browser cache).

Currently, browsers don't support arithmetic coded JPEGs officially. But it can be changed and it would be nice if libjpeg-turbo, which is used by the Firefox and Chrome, will be ready for it.

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=680385
https://bugs.chromium.org/p/chromium/issues/detail?id=669501

**Comment by dcommander** [comment]
Guido, the current IJG maintainer, wrote the arithmetic codec some years ago.  The implementation we use is not his latest & greatest code, but a cursory glance at jpeg-9b shows the same comment about suspension not being supported.  Past experience with him suggests that he wouldn't be willing to help out unless Mozilla would be willing to switch from libjpeg-turbo to libjpeg, which isn't going to happen.

This feature is not likely to happen unless someone else contributes the code.  I don't have a lot of expertise with the arithmetic codec, so it would take me an inordinate amount of time to develop the necessary expertise to get productive with it.  No one is likely to pay for that labor, for reasons I stated under the Mozilla bug report above (in a nutshell, there just isn't a demand for these images, and there isn't likely to be in the near future.)

One of my other OSS projects, TurboVNC, could actually benefit from arithmetic coding, because I control both the server and client end, but the arithmetic codec would have to be at least twice as fast before it could be useful for that project.  I already know how to make progressive JPEG fast enough to serve the same purpose, and it gives us about 11% better compression compared to 15% for arithmetic.  So the argument for arithmetic coding is really just a matter of a few percent better compression.

**Comment by TPS** [comment]
@dcommander Just FYI, I agree & await developments from all the associated groups for all the points you've made.

FWIW & as a point of clarity, progressive & arithmetic features of JPEG are independent, &, iIuc, the gains are multiplicative, so, from the figures of your last post, & assuming lossless conversions from a 100%-sized (___NOT___ quality) baseline-encoded JPEG:
- 89% progressive, non-arithmetic JPEG
- 85% arithmetic, non-progressive JPEG
- ~76% (75.65% says math) progressive, arithmetic JPEG

Still, that's not enough to overcome the streaming vs. decoding #s from above. However, for online _bandwidth/storage_, I'd consider a 24% gain significantly better than just 11% or 15%, right?

**Comment by dcommander** [comment]
Yes, you are correct that progressive arithmetic compresses better than arithmetic alone, but the average is more like 19%, not 24%, using the same test images whose results I cited above.  And the performance is worse (6x slower compression, 7x slower decompression relative to baseline.)

mozjpeg compresses with about the same 20% gain that progressive arithmetic does, and it produces files that are 100% compatible with all existing software and decode much more quickly than arithmetic-coded JPEGs ... but they take a ridiculously long time to compress, which is the trade-off-- definitely not something that would be suitable for real-time use.  The fact that mozjpeg hasn't made any more inroads than it has is evidence that there isn't much of a market for improved offline compression, even if you're talking about images that are 100% compatible with existing software.

For the case of improved online compression (i.e. web sites), why not just reduce the quality of the JPEG images a little?  It's a lossy format.  That's what it's for.  For most images, you can dial down the quality an imperceptible amount and save a lot more than 20% (the difference between, for instance, Q95 and Q90 is about 35% on average, at least for the types of images I deal with.)  And in fact, if you look at the typical web design workflow, that is how it works-- you design around a target bandwidth, and that determines the quality of JPEG images that you generate.

The geek in me agrees that arithmetic coding does produce the best compression, and if the technical issues associated with that codec (poor performance, lack of suspension) could be addressed, then it would probably become much more useful, but the business owner in me recognizes that the cost/benefit trade-off just isn't there.  If someone wants to go off and implement suspension in our arithmetic codec and submit a PR, that's great.  I'll gladly integrate and test it, assuming it doesn't create a performance loss or other issues.  But the odds of me working on this for free are exactly zero, and the odds of someone stepping up to pay me to implement it are pretty close to zero, so any discussion of the technical merits are irrelevant unless a business case for the feature can be formulated.

**Comment by vrubleg** [comment]
> For the case of improved online compression (i.e. web sites), why not just reduce the quality of the JPEG images a little? It's a lossy format. That's what it's for. For most images, you can dial down the quality an imperceptible amount and save a lot more than 20% (the difference between, for instance, Q95 and Q90 is about 35% on average, at least for the types of images I deal with.)

Yeah, just recompress it again... again... and again.

![... and again](https://cloud.githubusercontent.com/assets/2157439/20784763/5d23fd16-b7ad-11e6-901c-3080f51f1e41.jpg).

**Comment by ssvb** [comment]
@vrubleg Just always keep your original images in some lossless format (PNG?) and you are good. It's exactly the same as with the source code and compiled binaries.

**Comment by vrubleg** [comment]
@ssvb often JPG is the only original image. For example, when a user uploads a photo. I've seen enouth overrecompressed JPEGs to say that lossy recompression of an existing JPEG is a destructive way to do things.

**Comment by ssvb** [comment]
@vrubleg Keep a copy of your original image if that's the best what you have. You can even convert it to PNG (and feel better about getting rid of the evil lossy compression), but this is obviously an unnecessary step.

You have been explained that arithmetic coding currently has issues (bad performance and missing suspension support among other things). Somebody has to address these issues first. Feel free to either do this work yourself or consider sponsoring it if you don't have time or skills.

**Comment by TPS** [comment]
> Yeah, just recompress it again... again... and again.

@vrubleg Ok. :stuck_out_tongue_winking_eye:
![overjpeged](https://github.com/user-attachments/assets/0266c0cc-01b8-427b-96b3-5fabd691cc6e)

**Comment by TPS** [comment]
It was never noted here, but for the sake of completeness, main arithmetic support is implemented since [v.1.0.90](https://github.com/libjpeg-turbo/libjpeg-turbo/commit/1e247ac854f8e33682bcfea475f6bccc42377208).

**Comment by vrubleg** [comment]
@TPS this ticket was about suspension support for arithmetic JPEG.

**Comment by AlbertNashr** [comment]
@vrubleg 
> Currently, browsers don't support arithmetic coded JPEGs officially.

As of now, epiphany-browser and Chromium on Debian trixie do. (Not sure about “officially”: I don't see it in the current Debian changelogs, so they might use the system library.)

**Comment by dcommander** [comment]
> As of now, epiphany-browser and Chromium on Debian trixie do. (Not sure about “officially”: I don't see it in the current Debian changelogs, so they might use the system library.) 

Since arithmetic coding is enabled in libjpeg-turbo by default, the browser would have to use a static build of libjpeg-turbo and explicitly disable arithmetic coding in order to forego it. I know that Mozilla did that at one time, but that was 15 years ago. Once the patent expired, the argument I heard most often was a chicken-and-egg argument. Basically, from a web developer's point of view, you can't use a particular type of image unless a wide variety of browsers support it. So if only one browser supports arithmetic-coded JPEG, then a developer might test that browser and falsely assume that others support arithmetic-coded JPEG. Personally, I've always found that to be a specious argument, because if all browsers have to adopt a new image format in lock-step, then no new formats will ever be adopted. Hopefully there has been enough momentum in 15 years to address that chicken-and-eggism, but it wouldn't surprise me if many programs still forego arithmetic-coded JPEG. Even fewer support 12-bit and lossless. All I can do is continue to provide a fast, free/libre, widely compatible, and easy-to-use library for handling those JPEG variants and hope that application developers eventually realize that they're no longer limited to the feature set of libjpeg v6b.
