### ISSUE TITLE
jpegtran: Add option to overwrite the input file, if size is smaller

### ISSUE THREAD

**Issue by dmak** [libjpeg-turbo/libjpeg-turbo#128]
Would be nice if `jpegtran` could overwrite input file preserving it's modification timestamp in case if transformation step had resulted a smaller file (e.g. subsequent invocations of `jpegtran` with same arguments should not modify file as it would obviously be the same).

This is a clone of [issue 231 in mozjpeg](https://github.com/mozilla/mozjpeg/issues/231).

**Comment by dcommander** [comment]
I can't think of a way to accomplish that within the constraints of the libjpeg architecture.  The libjpeg API was designed back in the MS-DOS days, so its architecture is geared toward minimal memory usage.  That's why it has the concept of "source" and "destination" managers, user-definable objects that allow the API to compress/decompress only small chunks of data at a time using arbitrary data sources/destinations.  jpegtran, cjpeg, and djpeg all use buffered I/O.  In the case of jpegtran, it reads from stdin and writes to stdout, so it doesn't actually know how big the destination JPEG will be until the program finishes, and by that time, everything has been written to the output stream and is no longer available in memory.  There is no way for it to write to the input file, because it's reading from the input stream and writing to the output stream at the same time.  You could just as easily wrap jpegtran in a script that transforms the input file to a temporary file, compares it to the original, and copies it back to the original file if the output is smaller.  That would actually be more efficient than trying to accomplish what you propose using the C code.  Furthermore, jpegtran isn't always used for size reduction.  It can be used to losslessly rotate or crop a JPEG file as well, which has nothing to do with size.  It can also be used to transform a progressive JPEG to a baseline JPEG, which would actually increase its size.  There is no guarantee that the output of jpegtran will be pixel-identical to the input, because lossless transformations may have been applied.  Furthermore, the tool is designed not to modify the input file (which I personally consider to be a feature, not a bug.)

I would say your best bet is to write an external tool that does what you want.  libjpeg-turbo's two overarching goals are performance and backward compatibility with jpeg-6b.  Although I am open to accepting enhancements to improve compression without adversely compromising performance, maximum compression (a la mozjpeg) has never been one of our goals.  These simple tools (cjpeg, djpeg, jpegtran) were never intended to provide a comprehensive image processing framework (that's ImageMagick's job.)  They're mainly intended to demonstrate the usage of the libjpeg API.

**Comment by dmak** [comment]
Indeed you can't write to the same file... You need to write to temporary file, and then rename it. I understand that utility can be used in many different ways, so please just introduce the option for this particular usecase. Otherwise indeed I need to wrap the utility into the script something like this:
```
jpegtran -copy all "$1" > "$1.new"

if [ `stat -c %s "$1.new"` -lt `stat -c %s "$1"` ]
then
	touch -r "$1" "$1.new"
	mv "$1.new" "$1"
else
	# Optimization for file $1 has filed...
	rm "$1.new"
fi
```

**Comment by dcommander** [comment]
In order for me to consider adding this to libjpeg-turbo, there would need to be:

1. A clear performance advantage or some other technical advantage to including the feature in the C code rather than using a wrapper script.  I personally do not see that.  I don't think I could improve upon what your script is doing, so adding the feature to the C code would do nothing but unnecessarily increase its complexity and make it more difficult to maintain.
2. A clear case for why this feature would benefit the larger libjpeg-turbo community.  I'm just not seeing that, either.  You are obviously able to implement the same feature using a very simple script, so why does it need to be included in jpegtran?  You may very well be the only user of libjpeg-turbo who ever needs to do this.  If you want my attention, then please make a case for why people other than you would need this feature (i.e. demonstrate how the feature would improve a common workflow.)

libjpeg-turbo cannot be all things to all people.  These programs and the underlying library have operated basically the same way for 20+ years, so they're canonical at this point.  I started this project because my own software (VirtualGL and TurboVNC) needed a high-speed open source JPEG codec.  Over the years, others have adopted libjpeg-turbo, and it has become a de facto industry standard.  I am happy that it is helping a lot of people, but at the same time, as it has gained in popularity, the community has demanded more and more of my unpaid time.  I simply cannot implement new features for free anymore unless those features are very compelling or unless the features would benefit my other projects.

**Comment by dmak** [comment]
In generally I agree with you. There should be a kind of resistance to add new features, because finally the tool will turn to universal utility that can do anything. However you may agree that if given scenario is used by many users it makes sense to implement it at "higher" level to avoid coding efforts at "lower" levels. Otherwise every C project would start from implementing it's own `fprintf()` function. In general I can make a pull-request to save your time.
Let's keep the issue closed as it is now and see what is the demand from the users' community. I feel you're right and I am perhaps the only one who uses `jpegtran` that way.
Thanks for you input, verbose comments and contribution.
