### ISSUE TITLE
Add Guetzli JPEG encoder (~30% more efficient enconding)

### ISSUE THREAD

**Issue by pbogdanov** [libjpeg-turbo/libjpeg-turbo#144]
https://github.com/google/guetzli/

**Comment by dcommander** [comment]
You're joking, right?  Guetzli seems to be doing something similar to what DCTune once did--
computing custom quantization tables based on the actual image content, rather than using the stock quantization tables provided by the JPEG spec.  Their goals are similar to those of mozjpeg, except that Guezli is not a lossless process (mozjpeg was at least "mostly" lossless.)  As with mozjpeg, they're sacrificing compression speed for compression ratio, so their project goals are quite different than ours.  Guezli does not appear to have any SIMD acceleration at all, and it requires 300 MB (!) of memory for every 1 megapixel of image content.  As with mozjpeg, I wonder what the potential market for it is.  At least mozjpeg could re-encode existing JPEG files without significant loss, which made it useful for sites like Facebook-- sites where people upload a lot of JPEG images, and those images are re-encoded on the server to save space.  Guetzli appears to be only useful for initial compression rather than re-compression, so that limits its overall utility relative to mozjpeg.  I guess we'll see whether it catches on, but suggesting that we "add" the Guetzli encoder fundamentally misunderstands the purpose of libjpeg-turbo.  Our project goal is clearly stated in our project name:  to provide compatibility with libjpeg but with the maximum possible performance.  libjpeg-turbo without maximum performance is not libjpeg-TURBO.  Tricks to increase compression ratio at the expense of performance have never been part of our project goal.  Furthermore, there is nothing about Guetzli that is compatible with the libjpeg API.  I can't just "add" a completely different encoder with a completely different architecture.  If you want maximum compression ratio and are willing to take a severe performance hit, then use Guetzli or mozjpeg to encode your image.  If you want maximum performance and compatibility with libjpeg, then use libjpeg-turbo.  We are a general-purpose JPEG codec that supports the standard JPEG encoder behavior.  You can, of course, compute your own custom quantization tables and feed those into libjpeg-turbo while encoding, but the computation of those tables based on image content is out of scope for this project.
