### ISSUE TITLE
we meet one cirtical performance issue on andoird 7.0 + version caused by jpeg_skip_scanlines

### ISSUE THREAD

**Issue by typhoonzb** [libjpeg-turbo/libjpeg-turbo#147]
We have one jpeg file, and the size is about 6000*8000, when we do zoom in/zoom out, we can see libjpeg-turbo begin to scan from the bottom of the region and then to the top,  this will cause huge time,  may about 2-3s.....   This impacts user experience a lot.

i find that,  in the code,  decode_mcu is triggered huge times in one jpeg_skip_lines call,  about 20000+ to 200000+,   and all calles are in serial.....

  for (i = 0; i < lines_to_skip; i += lines_per_iMCU_row) {
    for (y = 0; y < coef->MCU_rows_per_iMCU_row; y++) {
      for (x = 0; x < cinfo->MCUs_per_row; x++) {
        /* Calling decode_mcu() with a NULL pointer causes it to discard the
         * decoded coefficients.  This is ~5% faster for large subsets, but
         * it's tough to tell a difference for smaller images.
         */
        (*cinfo->entropy->decode_mcu) (cinfo, NULL);
      }
    }
    cinfo->input_iMCU_row++;
    cinfo->output_iMCU_row++;
    if (cinfo->input_iMCU_row < cinfo->total_iMCU_rows)
      start_iMCU_row(cinfo);
    else
      (*cinfo->inputctl->finish_input_pass) (cinfo);
  }

Could you please help take a look at this,   i prefer we should do optimization for this loop,   can we use like 8-10 threads to do this in parallel??

**Comment by dcommander** [comment]
I'd like @mattsarett, who designed the partial image decompression feature, to render a second opinion, but my assessment is that there probably isn't anything we can do about this.  Entropy (Huffman or arithmetic) decoding is an inherently serial task, because the starting value of each encoded MCU in the JPEG image depends on the final value of the previous encoded MCU.  The JPEG decompressor doesn't actually know where the MCU boundaries are within the encoded entropy stream unless restart markers are inserted, and the more restart markers are used, the less efficient the compression is.  If the source image contains restart markers, then they're generally placed sparsely (like 8-10 per image), but most JPEG images don't have them.  Thus, for the general case of decompressing an image that may or may not contain restart markers, there is no easy way to parallelize the entropy decoding-- and probably no way within the scope of the libjpeg architecture at all, since that API is so fine-grained.  A 48-megapixel image is huge.  It contains 750,000 8x8 MCU blocks, and since the state of the entropy decoder is cumulative, it is necessary to entropy decode all of the blocks for the skipped scanlines.  Using partial image decompression is better than the alternative (decompressing the entire image and cropping it in image space), because partial image decompression will not perform the IDCT, upsampling, and color conversion tasks for any blocks it doesn't need, nor will it perform any tasks at all for the blocks beyond the last scanline that you want to decompress.  However, there's no way that I know of for it to avoid entropy decoding the blocks corresponding to the skipped scanlines.

**Comment by typhoonzb** [comment]
@dcommander @mattsarett  thank you very much for your quick reply.  Google uses this lib since android 7.0,  and for android 8.0,  it still uses libjpeg-turbo,  and we also find on some devices, like Huawei Mate 9,  the jpeg decoding solution seems totally different, and we can see the decoding is in parallel,  many small block with same size is decoded at the same time. We don't know how they do that.  Do you get more details about this?

And even on Google Pixel/Nexus devices,  we find that on android 6.0,  the partial image decompression is much faster than current solution of libjpeg-turbo.  Sometimes,  the end user may care more about the user experience (decode speed) than the miner image qulity improving. By now,  more and more users complain such issue..... BTW, i'm R&D in mobile phone industry.

**Comment by mattsarett** [comment]
The current libjpeg-turbo approach is best for decoding for decoding a single subset of an image.  Where you'll potentially run into trouble is if you're splitting the image into tiles.  Each tiled decode will redo some of the same work as the other tiles.  If you really want to use tiles, it may help to make the tiles bigger :) - this may be the single easiest way to improve your performance.

Are you also using jpeg_crop_scanline()?  That may help some as well.

But if you're going to eventually want the full image, the fastest way to get that is just a full image decode.

android 6.0 would do the entire Huffman decode in a single pass and hold onto pointers to the start of the all the blocks.  This was, in some cases, more useful for tiling because the work of the Huffman decode was not repeated as often - you could just "jump" to the block that you wanted.  There were various reasons why this approach didn't seem right for libjpeg-turbo, but it did have these advantages.  @dcommander might have thoughts on whether it is worth reconsidering.

@dcommander also mentioned restart markers which I think are a really interesting idea.  I wonder if jpeg_skip_scanlines() could scan ahead ahead for a restart marker and jump to it if appropriate.  It would only work sometimes and only if the client provided enough of the stream, but might be a cool way to improve further.

I'm not sure what Huawei is doing.  Maybe it is possible to improve performance with a parallel approach to jpeg decoding?  I'd be interested to know performance numbers for a libjpeg-turbo full image decode vs. Huawei parallel image decode.

**Comment by typhoonzb** [comment]
@mattsarett thank you very much for your kindly help and quick response.  
For Huawei solution,  we didn't compare the full image decoding time,  but for the subset of the image decoding,  Huawei's solution is really much better,  and it seems 3x than libjpeg-turbo.  And i think Huawei's solution should be based on Android 6.0, not 7.0.

The subset decoding time is really crazy on latest android version,  and could you please share some info why you dropped the approach of android 6.0,  actually, we didn't receive jpeg related issue from customers.  but on android 7.0,  customers reported a lot of the subset decoding latency issues. 

For your idea of using full image decoding to improve the performance, i think we may meet memory issue,  for such big pictures, like 8000x6000,  the size is really big,  but we can have a try.  And for the tile size changing, we may also meet the same memory issue.

So is it possible to use jpeg lib of android 6.0 to replace the lib on 7.0.  I did some trying, we also need change skia related code.  It seems high risk exists.  Could you please help provide some ideas?

**Comment by dcommander** [comment]
Given the fine-grained nature of the libjpeg API (the fact that decompression occurs on a line-by-line basis using `jpeg_read_scanlines()`, `jpeg_skip_scanlines()`, and `jpeg_crop_scanline()`), there is unfortunately no way for the library to know what the user intends to do with the image.  If the application is running on a mobile platform and intends to display a large JPEG image and then zoom in to a particular region of the image, then the appropriate strategy for minimizing memory usage might be:

1. Decompress the large JPEG image, using IDCT scaling so that the output image is as close as possible to the screen resolution.
2. Use image-space scaling to exactly fit the output image to the screen resolution.
3. When zooming in, use partial image decompression, IDCT scaling, and image-space scaling to display only a subset of the image.

In this case, you won't use much more memory than if you had decompressed an image the size of your screen, but the above algorithm is also not going to be the fastest approach.  As @mattsarett points out, in this case it is more efficient in terms of CPU time to perform entropy decoding on the entire image and maintain a map of decoded DCT blocks in memory.  However, the problem there is that (to the best of my understanding) those blocks would have to be maintained in decompressed form, which would take 16 bits per component (288 Megabytes for the entire 8000x6000 image if it's not using chroma subsampling, or 144 Megabytes if it's using 4:2:0 subsampling.)  That's a lot of memory for a mobile application and somewhat defeats the purpose of using IDCT scaling and partial image decompression in the first place-- since those features are primarily a means of saving memory.  If you had that much memory to work with, you could just decompress the entire image into a buffer and use image-space algorithms to crop, zoom, and scale it at your leisure.  The libjpeg API, owing to its early 1990s heritage, is really focused on minimizing memory usage, because it used to run on 640k machines.  That same aspect makes it useful for displaying large images on mobile platforms, but unfortunately, the trade-off of this sort of problem is always going to be memory vs. CPU time.  You can make the zoom operation on the 48-megapixel image faster by caching a lot of the image data, but you would end up keeping a copy of either the whole image or (even worse) its 16-bit DCT coefficients in memory.

Or would you?  @mattsarett, when you talk about Android 6.0 holding onto the pointers for the MCU blocks, did it cache those blocks in decoded form?  Because if it was holding onto pointers to the blocks in the encoded entropy stream, I'm not sure how that would work.  I think you'd still have to perform a full entropy decode prior to the point that you wanted to start decompressing, because the state of the entropy decoder is cumulative (?)

**Comment by mattsarett** [comment]
> And i think Huawei's solution should be based on Android 6.0, not 7.0.

It may be relevant to know what Android version is running.  Also, sometimes vendors will use hardware jpeg decoders instead of framework version, so this might not be a relevant comparison.

> Could you please help provide some ideas?

Replacing the jpeg library won't work.

You might try:
(1) Increase tile size.  At least 1024x1024.  I'd recommend 2048x2048.
(2) Experiment with scaled decodes.

In general, I think you want to consider changing your approach above the jpeg library level.

> Or would you? @mattsarett, when you talk about Android 6.0 holding onto the pointers for the MCU blocks, did it cache those blocks in decoded form? Because if it was holding onto pointers to the blocks in the encoded entropy stream, I'm not sure how that would work. I think you'd still have to perform a full entropy decode prior to the point that you wanted to start decompressing, because the state of the entropy decoder is cumulative (?)

I'm hazy on the details.  I imagine that the relevant state was also stored.

**Comment by dcommander** [comment]
> I'm hazy on the details. I imagine that the relevant state was also stored.

That seems at least possible with libjpeg-turbo, but I suspect it would be very disruptive, and I wonder aloud whether it would impact performance for the more common case of decompressing the entire image.  It would probably be necessary to implement some new function or mode that tells the codec to cache the MCU pointers/state.  I'm not sure how that would interact with buffered image I/O and/or custom source/destination managers, but it's likely to be complicated.

To be completely honest, I feel that the libjpeg API has outlived its usefulness somewhat.  It's essentially a legacy API at this point, and I would dearly love it if the community could start coming together to design a more modern API to replace it.  I don't necessarily feel that the TurboJPEG API is going to meet all of the needs of that standard, and since that API wasn't so much designed as evolved, we can probably do better.  However, TurboJPEG might be a useful starting point.  Basically, we need an API that allows the application to more effectively communicate its intent to the library.  If it intends to decompress the image into tiles, then it can invoke a particular function or mode to tell the library to do this, and the library can implement additional optimizations to make that workflow faster.  The new API would also, of course, use opaque rather than exposed structures, so it could be expanded without breaking ABI compatibility.  It would need to preserve the ability to do buffered I/O and such, as well as to access the raw DCT coefficients or unconverted YCbCr planes, but it need not be as fine-grained as the libjpeg API.

**Comment by mattsarett** [comment]
> That seems at least possible with libjpeg-turbo, but I suspect it would be very disruptive, and I wonder aloud whether it would impact performance for the more common case of decompressing the entire image. It would probably be necessary to implement some new function or mode that tells the codec to cache the MCU pointers/state. I'm not sure how that would interact with buffered image I/O and/or custom source/destination managers, but it's likely to be complicated.

Agreed, I'm not advocating for that.  The implementation was very complicated and also very buggy.  But I think noting how the approach worked is interesting - potentially for a next gen API (as you suggest below).

> To be completely honest, I feel that the libjpeg API has outlived its usefulness somewhat. It's essentially a legacy API at this point, and I would dearly love it if the community could start coming together to design a more modern API to replace it. I don't necessarily feel that the TurboJPEG API is going to meet all of the needs of that standard, and since that API wasn't so much designed as evolved, we can probably do better. However, TurboJPEG might be a useful starting point. Basically, we need an API that allows the application to more effectively communicate its intent to the library. If it intends to decompress the image into tiles, then it can invoke a particular function or mode to tell the library to do this, and the library can implement additional optimizations to make that workflow faster. The new API would also, of course, use opaque rather than exposed structures, so it could be expanded without breaking ABI compatibility. It would need to preserve the ability to do buffered I/O and such, as well as to access the raw DCT coefficients or unconverted YCbCr planes, but it need not be as fine-grained as the libjpeg API.

Sounds like a cool idea.  Would be interesting to gather together various use cases.

**Comment by dcommander** [comment]
> Sounds like a cool idea. Would be interesting to gather together various use cases.

Yeah, this would likely need to happen in a multi-day conference setting, with key players participating.  I'm just not entirely sure who those key players are.  I could provide a great deal of insight into what I personally think this new API should do, functionality wise-- basically some reasonable union of the TurboJPEG and libjpeg APIs-- but there are others who probably have more insight into API design.

**Comment by typhoonzb** [comment]
@dcommander @mattsarett 
It's really nice to see that you decide to consider the new API to improve this.  We just take a look at the android O code, no more changes on skia/jpeg parts. Could you please share some info if we have chance to have the new API on android O?  How long will it take to finish the design of it?

**Comment by dcommander** [comment]
It won't be designed unless we can arrange a "meeting of the minds" among some key stakeholders in the open source community.  I don't personally have the ability to arrange that.  I couldn't even afford my own airfare to such a hypothetical conference.  I'm just floating the idea in case someone else reading this has the ability and desire to pursue it.  All I can really do on my own is shore up some of the deficiencies in the TurboJPEG API relative to the libjpeg API and float that as a possible replacement.  It's already there, it already has a full-featured Java interface, and a lot of new applications are choosing to use the TurboJPEG API instead of the libjpeg API because of its simplicity.  However, to a certain degree, I was also floating the idea of a completely new library that is free of the libjpeg legacy.  Without the need to support the fine-grained architecture of libjpeg, it would be possible to make some performance enhancements that we can't currently make, including the aforementioned tiled decoding enhancement.  I'm dreaming aloud here, though.  I think the reality is that libjpeg-turbo will soon reach a point at which it's fast enough for most purposes, and focus in the community will shift toward accelerating newer formats that achieve better compression.

**Comment by dcommander** [comment]
Closing as WNF, at least for now, since this is basically outside of the scope of libjpeg-turbo.  The aforementioned MCU caching optimization in Android 6.0 was developed downstream, and as Matt indicated, it was buggy and complicated.  I can at least partially testify to that, since Linaro wanted me to integrate that code into libjpeg-turbo back in 2011.  I refused on the basis of how disruptive it was to the libjpeg API code (that is, despite being bounded by `#ifdef ANDROID`, the changes were likely to introduce hard-to-diagnose bugs unrelated to the feature), the fact that it introduced backward ABI incompatibilities (by extending the exposed libjpeg structures), and the fact that there were no available ways to test its correctness at the low level.

The partial image decompression feature was developed as a more project-friendly (i.e. less disruptive) way of facilitating the integration of libjpeg-turbo into Android, but I have no control of the specific implementation within Android-- that is, whether the Android API functions are implemented using libjpeg-turbo or dedicated hardware, how the Android APIs use libjpeg-turbo features, etc.  I see no straightforward path for fixing this specific problem without either a very disruptive (and expensive to develop) feature in libjpeg-turbo or an entirely new JPEG codec architecture.  I think the best approach for now is to understand how the library behaves and modify your application, as much as possible, to accommodate that behavior.  Since the underlying library is processing MCU rows, the application should probably cache the MCU rows corresponding to the zoom region, so if the user pans left or right while zooming, that can be satisfied from the cache without doing any further decoding of MCUs.  But how to avoid decoding the MCUs above the tile?  At the moment, I unfortunately don't have an answer to that.  Your application will need to somehow intelligently cache the image data, since Android is no longer doing that for you.
