### ISSUE TITLE
Overflow issue?

### ISSUE THREAD

**Issue by pieter3d** [libjpeg-turbo/libjpeg-turbo#150]
In this code:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdhuff.c#L483

Isn't it possible for `code` to be much larger than the the array size of 256? It would require a hand-crafted huffman table, but such a table is certainly possible (i.e. 2 codes of length 2, 160 codes of length 16).
In that case, two codes are `00` and `01`,  the rest look like `10000000xxxxxxxx`

**Comment by dcommander** [comment]
My best answer is:  try it and see.  I unfortunately couldn't come up with a more definitive answer after 30 minutes of staring at the code.

A similar overflow did once exist in the fast Huffman decode path:
https://sourceforge.net/p/libjpeg-turbo/bugs/7/
If memory serves, the slow Huffman decode path (jpeg_huff_decode()) did not experience the same overflow because of the bounds check here:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdhuff.c#L478-L481
but I can't remember exactly why that was the case.

The slow Huffman decode path is nearly 20 years old, has undergone intense scrutiny over the years (including quite a bit of fuzzing), and no such overflow has ever been detected.  If you are able to craft a JPEG image that causes such an overflow, however, then it would be easy to apply a similar fix to the one that was used in the fast path.  Note that, if an overflow is possible in jpeg_huff_decode(), then it would be easier to reproduce in libjpeg, since it always uses that function.  libjpeg-turbo only uses jpeg_huff_decode() if an unread marker is encountered in the fast path or if there is insufficient space in the output buffer to accommodate the worst-case decoded MCU size.

**Comment by pieter3d** [comment]
Alright, was able to craft a stream to hit this case, where code is very large. Happily, htbl->valoffset[l] is correspondingly very negative, so all is well.
