### ISSUE TITLE
TurboJPEG: Indicate severity of decompression failures

### ISSUE THREAD

**Issue by twest820** [libjpeg-turbo/libjpeg-turbo#151]
I've an image where something went a little funky when the originating camera laid it down and the pixels are shifted slightly from where they should be.  Other jpeg decoders produce the same pixel output as libjpeg-turbo does, with some of them raising warnings and others not.  tjDecompress2() consistently returns -1 and reports the jpeg buffer as incomplete.

This is correct but, as the caller, my problem is there's no way to tell how mangled the image is.  In this case the image is only slightly damaged and is still fully usable for its intended purpose, so it's best my code proceeds to display it to the user.  If it was mostly missing then the code should behave differently.  If the API exposed an indicator such as the number of pixels decompressed or number of blocks read it would be possible to implement such behaviors.  With the 1.5.15 API I don't really have a choice other than to ignore tjDecompress2()'s return code and carry on, though I am going to replumb my call stack to propagate a "pixel buffer may be invalid" flag.

As with #113, there's the question of how to make such state available.  Rather than a lot of return codes it might be simpler and more maintainable to expand tjGetErrorStr() to something like tjGetErrorState(tjhandle), which has the advantage of being thread safe.  The decompression process I'm using is below for reference.

    Decompress(unsigned __int8* jpeg, __int32 jpegLength, __int32 requestedWidth)
    {
        tjhandle decompressor = tjInitDecompress();
        __int32 colorspace, height, subsampling, width;
        __int32 result = tjDecompressHeader3(decompressor, jpeg, jpegLength, &width, &height, &subsampling, &colorspace);
        if (result != 0)
        {
            throw std::runtime_error(tjGetErrorStr());
        }

        pixels = (unsigned __int8 *)_aligned_malloc(bytesToAllocate, alignof(__m256i));

        result = tjDecompress2(decompressor, jpeg, jpegLength, pixels, width, 4 * width, height, TJPF_BGRA, 0);
        tjDestroy(decompressor);
        if (result != 0)
        {
            throw std::runtime_error(tjGetErrorStr());
        }
    }

**Comment by dcommander** [comment]
I'll have to do some more thinking about this, but the possibilities are unfortunately limited.  The underlying libjpeg API can only tell me whether there was a warning or an error.  The former means that there was a recoverable error and that the image may be corrupted, but it's unclear how much.  The latter means that a fatal, unexpected, unrecoverable error occurred.  AFAIK, there isn't a way to figure out how many pixels decompressed correctly.  Thus, the TurboJPEG API doesn't really have any way to judge the severity of an error.  It just knows whether the libjpeg API has sent back a JWRN code or a JERR code. 

There are really two things that need to happen:
1. TurboJPEG needs to somehow communicate back to the caller whether a warning or an error has occurred-- so the caller can decide whether to ignore the warning or treat it as fatal.  This is to address issues like the one you describe-- i.e. the need to distinguish recoverable decompression errors from fatal ones, so as many pixels as possible can be decoded.
2. TurboJPEG needs to have an optional setting that makes it immediately abort decompression if it encounters a warning.  This is mainly for security-sensitive applications that need to work around issues like the ones described in [this report](http://www.libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf).  Such a feature could easily be implemented using a flag (`TJFLAG_ABORTONWARNING` or something like that), and it wouldn't really be necessary to have another flag for ignoring warnings.  As long as the API is communicating to the caller whether a warning or an error has been encountered, the caller can decide whether to ignore the warnings or treat them as fatal.

Making `tjGetErrorStr()` thread-safe should be a straightforward matter of moving the errStr buffer into the my_error_mgr structure, and I agree that that needs to happen along with whatever solution we come up with for differentiating warnings from errors.

I am starting to see your point about the need for a function that returns the error code-- much like errno in POSIX or Microsoft's GetLastError().  That would be much more extensible than returning -2 for warnings, and it could be implemented in libjpeg-turbo 1.5.2 without requiring new TurboJPEG function signatures.  Perhaps something like:

```
char *tjGetErrorStr2(tjhandle handle);  /* New thread-safe tjGetErrorStr() */
int tjGetErrorCode(tjhandle handle);  /* would currently return TJERR_FATAL or TJERR_NONFATAL, but this could easily be expanded in the future */
```

**Comment by twest820** [comment]
Cool, thanks for the consideration.  Fair enough on the underlying plumbing.  Just so I know where to set my design, any chance of eventually getting more telemetry from the libjpeg API?

Being able to get a thread safe TJERR_FATAL/NONFATAL plus appropriate error string sounds like a good increment.  The code I'm converting to libjpeg-turbo does a bunch of bulk image processing with one decompressor per core.  Since decompression is an expensive operation the odds of one thread stepping on another's error message is low.  But I'm always happy to get away from race conditions.

**Comment by dcommander** [comment]
The chances of getting more telemetry from the libjpeg API are pretty low, in my assessment, and I'm not sure whether we could draw meaningful conclusions from that telemetry anyhow.  For instance, a common warning is `JWRN_HIT_MARKER`, which means that an unexpected marker has been encountered in the middle of the entropy stream.  However, although that warning tends to occur when the image has missing or corrupted data, it can also occur under circumstances in which the data stream is in tact.  AFAICT, the only additional metric available to us right now is how many bytes were decoded from the JPEG stream prior to the warning being encountered, but that's not necessarily meaningful.  You could encounter a bad Huffman code near the start of the image, for instance, but if it's only a few bytes prior to a restart marker, only a couple of pixels might be affected.  On the other hand, you could encounter a bad Huffman code near the end of the image that would cause entire MCU rows to be corrupted.  There's no easy way to tell.

**Comment by dcommander** [comment]
Complication:

Upon closer examination, there is a good reason why tjGetErrorStr() works the way it does.  There are several of the API functions that are non-instance-specific-- tjBufSizeYUV(), for instance, or tjPlaneWidth().  Also, errors can be thrown prior to the TurboJPEG instance being initialized, or if a bad instance handle or other invalid argument is passed to a function.  In those cases, there is no place to store the error message other than in the global buffer.  Any attempt to work around this-- by using the global buffer in some cases and an instance-specific buffer in others-- would introduce more issues than it would solve, since the new tjGetErrorStr2() function would have to check both locations.

I think the best approach would be to make errStr thread-local, using __thread on Un*x or __declspec(thread) on Windows.  That's going to require some testing, however, to make sure that there aren't any unintended consequences (on some platforms, __thread is implemented using a mutex.)  tjGetErrorCode() could still be structured as specified above, because only instance-specific functions will ever throw a warning.

**Comment by dcommander** [comment]
Blerg.  Well, it's even worse.  `__thread` appears to work on Linux, Solaris, and FreeBSD, but it is problematic on other platforms.  Specifically, with OS X and MinGW, using TLS causes the libjpeg-turbo binaries to depend on libgcc_s (and libwinpthread, in the case of MinGW.)  On OS X, this dependency means that, when building the TurboJPEG API library as a static library using GCC 5 (GCC 5 is used to produce our "official" binaries), the library can't subsequently be linked with clang.

My concern is that there may be similar compatibility issues on some Linux/Un*x platforms that I just haven't discovered yet.  That concern, plus a general project philosophy of keeping functionality equal across all supported platforms, is enough for me to give up on a thread-safe `tjGetErrorStr()` for now, but if anyone reading this has any bright ideas, let me know.

I will proceed with looking into `tjGetErrorCode()`.

**Comment by twest820** [comment]
Sounds like thread safe access might be easiest in the form of

     tjDecompressN(..., tjErrorState*)

style overloads.  Another option is a static error collection indexed by thread ID---.NET uses this approach in marshalling Win32 error codes, for example---but that's a fair bit of plumbing to accomplish the same thing as passing another argument and getting the thread affinity right can get complex.

**Comment by dcommander** [comment]
It isn't the compress/decompress/transform functions that are the problem.  It would actually be straightforward to make error handling thread-safe if all of the functions accepted a tjhandle argument.  Then I could stash the error in the tjinstance structure, and it could be recalled by:

```
char *tjGetError2(tjhandle handle);
```

However, the basic problem is how to deal with functions that don't accept a tjhandle argument.  Now that I think about it again, one solution would be to maintain both a global and instance-specific error buffer, then have `tjGetErrorStr2()` return the global one if the instance-specific one isn't valid.  This would at least make the most common cases thread-safe.  It would still be thread-unsafe to get an error string thrown by any of the `tjInit*()` functions or the `tj*Size*()` functions or `tjPlaneWidth()`/`tjPlaneHeight]()`, but that's probably OK, because those functions will only throw errors if the arguments to them are invalid or if a memory allocation failure occurs.  In that case, the calling program probably has bigger problems to worry about than thread safety.

I think I need to push all of this to 1.6, however, since introducing new API functions will necessitate incrementing the libtool SO age.

**Comment by twest820** [comment]
So far as calling the API goes I don't have a particular preference either way.  From a design standpoint much of what we're discussing here is the mismatch between what are effectively member functions (a tjhandle is basically a this pointer) and static functions independent of an object handle.  Falling back from a handle to static state increases the intermix, which may not be the most desirable outcome long term.

**Comment by dcommander** [comment]
Yeah, I realize it's less than ideal, but it's at least an improvement.  I'm going to go ahead and implement it as described and push it to dev, and there will be plenty of time for you and others to evaluate it and make specific suggestions for improvement.

**Comment by dcommander** [comment]
Requested features pushed to dev.  Please test.
