### ISSUE TITLE
Allow rendering when height is > JPEG_MAX_DIMENSION

### ISSUE THREAD

**Issue by npm1** [libjpeg-turbo/libjpeg-turbo#156]
We recently moved to using libjpeg-turbo on the PDF renderer for Chrome. We encountered a regression with an image with a stated height of 65535. I can't share the image as it was privately shared to me by a user. Could we be a bit more forgiving with such images? Here is a suggested patch that would fix our problem (it basically trims the width/height when the obtained value surpasses the maximum allowed):

diff --git a/jdmarker.c b/jdmarker.c
index e3b612c..c54247e 100644
--- a/jdmarker.c
+++ b/jdmarker.c
@@ -255,6 +255,12 @@ get_sof (j_decompress_ptr cinfo, boolean is_prog, boolean is_arith)
   INPUT_2BYTES(cinfo, cinfo->image_width, return FALSE);
   INPUT_BYTE(cinfo, cinfo->num_components, return FALSE);
 
\+  if (cinfo->image_width > JPEG_MAX_DIMENSION)
\+    cinfo->image_width = JPEG_MAX_DIMENSION;
\+
\+  if (cinfo->image_height > JPEG_MAX_DIMENSION)
\+    cinfo->image_height = JPEG_MAX_DIMENSION;
\+
   length -= 8;
 
   TRACEMS4(cinfo, 1, JTRC_SOF, cinfo->unread_marker,

**Comment by dcommander** [comment]
Your use of the words "stated height" make me suspect that the image in question is malformed or corrupt, in which case we can't really be expected to handle it as if it were a correct image.  If the image is a proper JPEG image, then my next question would be:  why in is someone embedding a 65535-pixel-high image into a PDF file?  I wouldn't think that such a file would be in any way usable on most machines, and it may in fact produce a DoS-like condition in which decoding the JPEG sucks up all available memory (refer to http://www.libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf.)

The behavior of libjpeg-turbo in this regard is the same as libjpeg, and the code in question dates to libjpeg v6 in 1995.  Your patch may eliminate the error, but it would not result in a successful decode of the image, since the dimensions reported in the jpeg_decompress_struct structure would no longer match the actual image data embedded in the JPEG file.  I can think of several potentially dangerous ramifications of that, actually.

I am open to being convinced otherwise, but thus far, I don't buy your argument.

**Comment by guest512** [comment]
Hi @dcommander, I'm a user who found a problem with rendering a particular PDF file. It's a quite old file (from 2012 year), and it was created with Adobe tools, according to its metadata. I find your concerns about security and resource consumption convincing. However, with this patch to the libjpeg-turbo, this particular file renders successfully, as I can see it.

It would be great, if you can investigate this file, and probably propose a better solution, how to render it, or not render it all. Unfortunately, it contains a personal information and I can't upload it to this thread, but I can share it with you privately.

**Comment by dcommander** [comment]
That would not be fruitful until/unless I understand a couple of things:

* The OP (@npm1) mentioned that the PDF renderer for Chrome started using libjpeg-turbo recently.  What codec was it using before that?  It obviously wasn't using libjpeg, because libjpeg would have thrown exactly the same error.
* With the previous codec, was the image decoded successfully?  That is, does the image contain valid JPEG image data that was correctly displayed?  If so, then how?  I don't understand how an image with incorrect width/height fields can be correctly displayed.

If this is in fact a valid JPEG image, and there's a reasonable way to handle it, I can look into that, but it sounds like you're expecting us to decode an invalid JPEG image.  If the embedded JPEG image is erroneously setting its width and height to value > `JPEG_MAX_DIMENSION`, then there is no way around that.  Like I said, libjpeg won't render it either, and that's been the case since 1995.  libjpeg and libjpeg-turbo are de facto industry standards, and it isn't unreasonable at this point to expect other software to conform to the behavior of those libraries, inasmuch as the behavior has been consistent for well over two decades.  The PDF rendering software can take steps to catch this error and make it non-fatal if it so chooses.

**Comment by npm1** [comment]
It was a version of libjpeg modified by the original coders. The method was changed to set cinfo->image_width (and height) only when the value read did not exceed JPEG_MAX_DIMENSION. Since we had that change for a long time and Chrome has fuzzers I'm curious what the security bugs mentioned by @dcommander would be. And obviously the image contains valid data despite incorrect width/height values read from that method, that's the reason we filed this bug.

But I understand if the incorrect values read from the image make it invalid to libjpeg-turbo (despite the fact that there is a way around that).

**Comment by dcommander** [comment]
Help me understand how the image can be correctly decoded without knowing its correct width and height.  The codec needs to know that information in order to properly allocate buffers to receive the decoded pixels, and in order to properly place the pixels within those buffers.  This would go a lot more smoothly if someone could simply supply the image in question.  Not the PDF file, just the JPEG image.  Feel free to e-mail me directly: http://www.libjpeg-turbo.org/About/Contact.

If Chrome was using a modified version of libjpeg, then it can also use a modified version of libjpeg-turbo. That's what Mozilla is doing.  Chrome could also trap this error (by using a custom libjpeg error manager) and treat it as non-fatal.  So I don't buy the argument that this is our problem unless you can demonstrate how valid image data can successfully be decoded from the improper JPEG in question.  Otherwise, we're really just arguing over whether libjpeg-turbo should treat this error as fatal or non-fatal, and it's the convention of the library (and its predecessor, libjpeg) to leave that decision up to the application by way of allowing applications to implement custom error managers.

There may be a way around this, but on the surface, your code looks like a hack with some potentially bad ramifications.  I need to have a better understanding of how the image is (incorrectly) structured and what the best-case scenario is for decompressing it before I can evaluate whether your solution is appropriate for libjpeg-turbo.  For instance, `JPEG_MAX_DIMENSION` is a limit that libjpeg set in order to avoid 32-bit overflow, but we have other ways of avoiding that these days, so perhaps we can replace that limit with some additional checks that restore the ability to decode images all the way up to 64k x 64k.  But I need to fully understand the problem first before I can determine the best approach to solving it, or even if it's appropriate for us to solve it.

**Comment by dcommander** [comment]
@guest512 please send me the file.  I included a link to my contact info above.

**Comment by guest512** [comment]
Sorry, for the delay. I extracted an image from the first page of the PDF and sent it to you as a JPEG file.

**Comment by dcommander** [comment]
I looked at the image.  The height field in the JFIF header is definitely bogus.  The image appears to contain 1689 x 2208 pixels of valid data, but the height is set to 65535.  I can change the height to 08A0 using a hex editor and thus produce a valid JFIF file that decodes without error.  However, that only works because I was able to examine the image by hand and figure out that it only had 2208 scanlines of usable data.  There is no way for libjpeg-turbo to figure that out automatically.  Furthermore, this only works because the image is valid along the width dimension.  If the situation were reversed and the image had a valid height but a width that was incorrectly set to 65535, then there would be no conceivable way for any codec to get usable image data out of it.  Furthermore, even with your patch, the original image triggers a warning when decompressing: `Corrupt JPEG data: premature end of data segment`.  This indicates that it ran out of image data before decoding the last scanline.

In short, the image is corrupt, and no codec can reasonably be expected to decompress it correctly.  I'm not interested in competing for the title of "Codec That Is Most Tolerant of Corrupt Images."  Ours behaves like libjpeg has always behaved in this regard, and I'm satisfied that there is nothing libjpeg-turbo can do to automatically determine how to correctly decode this image-- and the fact that it can be correctly decoded at all is a fluke.  Applying your patch allows the image to decode, but it decodes into 330 MB of image data, of which only about 11 MB is valid.

There are only two explanations:
1. This file genuinely is corrupt.  The original post is still unclear to me.  @npm1 says, "We recently moved to using libjpeg-turbo on the PDF renderer for Chrome", but it's unclear what codec library was being used before.  It's also unclear whether the PDF in question was properly displayed by Chrome before the switch to libjpeg-turbo.  If it was, then I have no idea how.  Browsers would be ill advised to allow any JPEG images with that large of a width or height anyhow, because it opens up the possibility for a small progressive JPEG file to be crafted that exhausts all of the client's memory as the browser tries to decode it (http://www.libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf).
2. This file is some sort of pseudo-standard of which I'm unaware.  If other files like this exist and are commonly generated by a particular piece of software, then I would be open to the possibility of decoding them, but it's still unclear how libjpeg-turbo could do so.  The libjpeg architecture in general makes it virtually impossible to do the right thing unless you know the actual height of the image.

Closing until/unless more information comes to light.

**Comment by npm1** [comment]
Thanks for taking a look dcommander@. As I already mentioned before, we were using a (slightly) modified version of libjpeg, and the PDF was rendering properly in Chrome before our move to libjpegturbo. Unless we find many more examples like these, I agree that rejecting the image is the correct choice here.

**Comment by dcommander** [comment]
NOTE:  If you want to continue displaying it, as you did with your modified version of libjpeg, you can still do so.  It would just require:

1. Setting up a custom libjpeg error manager.
2. Setting a flag prior to the call to `jpeg_read_header()` that instructs the custom error manager to ignore `JERR_IMAGE_TOO_BIG`.
3. Unsetting the flag after the call to `jpeg_read_header()`.
