### ISSUE TITLE
JPEGLib: Backing store not supported in 1.5.2

### ISSUE THREAD

**Issue by Malvineous** [libjpeg-turbo/libjpeg-turbo#162]
Just got upgraded to v1.5.2 in Arch Linux, and `tiff2pdf` can no longer produce PDF files:
```
$ tiff2pdf -j -q 75 scan.tif > out.pdf
JPEGLib: Backing store not supported.
tiff2pdf: Error writing encoded strip to output PDF -.
tiff2pdf: An error occurred creating output PDF file.
```
Reverting back to 1.5.1 fixes the problem.

**Comment by dcommander** [comment]
Backing store is a legacy feature of libjpeg that essentially implemented a kind of virtual memory on old Messy-DOS machines.  That feature has never been available with libjpeg-turbo, since our library only uses the malloc()/free() (jmemnobs) memory manager from libjpeg.

However, what that error message really means is that the application configured a memory limit by setting `cinfo.mem.max_memory_to_use`, and the image you're trying to compress exceeded that memory limit.  Previous versions of libjpeg-turbo ignored `cinfo.mem.max_memory_to_use`, but 1.5.2 now honors it, thus allowing applications to define a limit on the amount of memory that can be used for decompression or multi-pass (including progressive) compression.

For instance, this is what happens when I try to compress a file that is 18.9 MB in size:

```
./cjpeg -progressive artificial.ppm >out.jpg
```
(succeeds because `cinfo.mem.max_memory_to_use` isn't set, meaning there is no limit)

```
./cjpeg -maxmemory 18000 -progressive artificial.ppm >out.jpg
Backing store not supported
```
(fails because 18.9 MB > 18000 kB, the memory limit defined using the `-maxmemory` argument to cjpeg)

```
./cjpeg -maxmemory 19000 -progressive artificial.ppm >out.jpg
```
(succeeds because 18.9 MB < 19000 kB)

The default is unlimited, but unfortunately libtiff is explicitly setting the limit to 10 MB:

https://github.com/vadz/libtiff/blob/master/libtiff/tif_jpeg.c#L2434-L2443

and doesn't seem to provide a way of overriding that.  In libjpeg-turbo, the `JPEGMEM` environment variable can be used to define a memory limit if the application doesn't define one, but it can't be used to override the application-imposed limit.

Closing as SEP, since this is really a libtiff problem that was merely exposed by the fact that libjpeg-turbo decided to start honoring `max_memory_to_use` with the malloc()/free() memory manager instead of ignoring it.  libtiff needs to raise its memory limit and/or provide a way for the user to override that limit.

**Comment by rouault** [comment]
@dcommander > libtiff needs to raise its memory limit and/or provide a way for the user to override that limit.
Just was pointed to that issue now. For a next time, you can contact libtiff developers at tiff@lists.maptools.org. / http://lists.maptools.org/mailman/listinfo/tiff .

**Comment by dcommander** [comment]
@rouault that would be the responsibility of @Malvineous, who was experiencing the issue.  I don't personally use libtiff.

**Comment by Malvineous** [comment]
FYI I [asked my distro maintainers to do this](https://bugs.archlinux.org/task/54989) as I couldn't find libtiff contact details at the time.  @rouault: Are you willing to contact libtiff or would you prefer I do?

**Comment by rouault** [comment]
> Are you willing to contact libtiff or would you prefer I do?

I'm a libtiff maintainer. I've already fixed the issue in libtiff CVS. This should reflect in the https://github.com/vadz/libtiff/commits/master mirror within a day or so

**Comment by JohannPopper** [comment]
It's back. But I don't see any libtiff changes since 2017. Why on Earth would one ever cap jpg to ~7mb in the year 2022? Certainly another accidental oversight that is now affecting distros like Fedora, which can no longer deal with jpgs, which is going to result in a lot of confused bug reports.

**Comment by dcommander** [comment]
@JohannPopper This is the libjpeg-turbo bug tracker, but this issue is not in libjpeg-turbo.  I would suggest filing a new issue here: https://gitlab.com/libtiff/libtiff.

**Comment by JohannPopper** [comment]
@dcommander Ok. Sorry. Thanks.
