### ISSUE TITLE
Error opening panorama pictures taken with a Samsung S7

### ISSUE THREAD

**Issue by Der-Zohan** [libjpeg-turbo/libjpeg-turbo#163]
Hi,

I've took some panorama pictures with my Android phone (Samsung Galaxy S7) with the build in panorama mode. The pictures are displayed in digiKam (which uses libjpeg-turbo) without a thumb. After double clicking on the image or using the context menu --> open the application crashes.
Picture works fine with win10 image viewer.

Link to initial digiKam bugreport
https://bugs.kde.org/show_bug.cgi?id=382174

Sample-picutre
https://drive.google.com/file/d/0B9j2-FraTQYjSTVfZDJmb0UxcjA/view?usp=sharing

Log:
Fully reproducible :

digikam.general: scan mode: ScheduleCollectionScan ::  ("/mnt/data/TEST_IMAGES/")
digikam.dimg: "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg"  : JPEG file identified
digikam.dimg: "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg"  : QIMAGE file identified
Invalid SOS parameters for sequential JPEG
digikam.general: Event is dispatched to desktop notifier through DBUS
digikam.dimg: "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg"  : JPEG file identified
digikam.metaengine: DateTime => Exif.Photo.DateTimeOriginal =>  QDateTime(2017-07-04 14:50:55.000 CEST Qt::TimeSpec(LocalTime))
digikam.metaengine: Cannot find Exif key 'Xmp.exif.ISOSpeedRatings' into image using Exiv2   (Error # 6 :  Invalid key `Xmp.exif.ISOSpeedRatings'
digikam.metaengine: Cannot find Exif key 'Xmp.exif.ExposureIndex' into image using Exiv2   (Error # 6 :  Invalid key `Xmp.exif.ExposureIndex'
digikam.metaengine: XMP String Seq ( Xmp.digiKam.TagsList ):  ("2017", "Sommer", "Juli", "Friends", "Urlaub", "Landschaft", "Stadt", "Tschechien", "Juni", "Prag")
Unsupported marker type 0x65
digikam.dimg.qimage: Can not load " "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg" " using DImg::QImageLoader!
digikam.general: Trying to load Embedded preview with libraw
digikam.rawengine: Failed to load embedded RAW preview
digikam.general: Trying to load half preview with libraw
digikam.general: Trying to load Embedded preview with Exiv2
digikam.dimg: "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg"  : JPEG file identified
digikam.dimg: "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg"  : QIMAGE file identified
Invalid SOS parameters for sequential JPEG
Unsupported marker type 0x65
digikam.dimg.qimage: Can not load " "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg" " using DImg::QImageLoader!
digikam.general: Cannot create thumbnail for  "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg"
digikam.general: Thumbnail is null for  "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg"
digikam.general: Request to get thumbnail for  "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg"
digikam.general: Mime type is not video or audio/mpeg from  "20170702_Prag-1140.jpg"
digikam.general: Failed to extract video thumbnail for  "/mnt/data/TEST_IMAGES/20170702_Prag-1140.jpg"

The JPEG file has a unknown marker that libjpeg cannot decode.

**Comment by dcommander** [comment]
It decodes with no errors for me using the latest libjpeg-turbo code.  I tried with both the libjpeg API (djpeg) and the TurboJPEG API (tjbench.)  In order for me to pursue this as a bug against libjpeg-turbo, it needs to be reproducible using only our code.

**Comment by Der-Zohan** [comment]
Thank you for your quick reply. I gave your answer to the digiKam team. Maybe it's solved if they use your latest code or they can give us more detailed informations. 

Regards

**Comment by imsodin** [comment]
I just compiled with libjpeg 0.15.2 and master, and can reproduce the problem with both:

djpeg:

```
djpeg -outfile test.jpg 20170702_Prag-1140.jpg 
Invalid SOS parameters for sequential JPEG
Unsupported marker type 0x65
```

tjbench:

```
tjbench 20170702_Prag-1140.jpg 

>>>>>  JPEG 4:2:0 --> BGR (Top-down)  <<<<<

Image size: 7040 x 2240
ERROR in line 176 while executing tjDecompress2():
Unsupported marker type 0x65
```

I compiled without any additional flags and nasm 2.13.01

**Comment by dcommander** [comment]
I can now reproduce it as well.  Apparently I couldn't before because I was downloading the preview image from Google Drive instead of the actual image.

Regardless, this is not a bug in libjpeg-turbo.  libjpeg-turbo is printing a warning that it encountered a JFIF marker it doesn't understand.  The default behavior of the library is to continue decoding the image when such a warning is encountered.  Applications are free to ignore those warnings or to treat them as fatal.  Both can be accomplished by creating a custom error manager using the libjpeg API, and modifications to the TurboJPEG API in dev/1.6 evolving make it possible to ignore warnings or treat them as fatal in that API as well.

Thus, there isn't anything we can do about this.  If digiKam is treating the warning as fatal, then digiKam needs to be modified.  Otherwise, if digiKam is continuing to decode the image after the warning, then it's a non-issue.

From your error log, it appears that digiKam might not be aborting because of this warning.  Rather, it seems to be erroring out because of this:

digikam.metaengine: Cannot find Exif key 'Xmp.exif.ISOSpeedRatings' into image using Exiv2 (Error # 6 : Invalid key 'Xmp.exif.ISOSpeedRatings' digikam.metaengine: Cannot find Exif key 'Xmp.exif.ExposureIndex' into image using Exiv2 (Error # 6 : Invalid keyXmp.exif.ExposureIndex'

That error is not coming from libjpeg-turbo.

**Comment by lambdapioneer** [comment]
Hey, I've debugged this as I am seeing this for similar images. The root cause is that the underlying JPEG file misses an EOI tag. This breaks compatibility with ISO/IEC 10918-1:1994 p48 which mandates an EOI. So, the problem is with the JPEG file and not libjpeg-turbo.

**The problem**

The image has no EOI tag after the last image data and is immediately followed by a "samsung trailer" containing a mp4 (10 Mib!) and other data. See (paste below). This isn't causing any problems while one is reading the scanlines. However, in `finish_decompress` we are trying to consume markers until EOI (which does not exist).

 https://github.com/libjpeg-turbo/libjpeg-turbo/blob/1095b822b07a484c70fd40078f3e39485585a80d/jdapimin.c#L397-L401 

The underlying `read_markers` will eventually call into `ERREXIT1` here

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/1095b822b07a484c70fd40078f3e39485585a80d/jdmarker.c#L1102-L1109

The called `jpeg_error_mgr->error_exit` method is supposed to not return (but either exit(1) or jongjmp). Also djpeg.c will exit(1) at this point.

However, it might be save to ignore as the image has already been read. And djpeg.c usually finishes to flush the output image before it exists with an error.

**Solution**

I think the error behavior of lijpeg-turbo is technically correct as the input file is not a valid JPEG file. However, it's sufficiently common that it causes some friction and burden for the library user here.

For now, a workaround for the application developer could be to ignore any errors when they are thrown after reading the last scanline. An alternative is to make libjpeg believe it had already seen EOI (e.g. inserting it into the stream). Both are dirty.

@dcommander let me know if you have a good idea to make libjpeg-turbo a bit more robust against bad input. However, that robustness might silence other legit errors and the status-quo might be what is best. So, I'm looking for a bit of guidance here :)

I'm happy to further debug and create a PR based on your input.

**Extra info**

```
[username:samsung_jpeg_repro]$ exiftool -v 20170702_Prag-1140.jpg
  ExifToolVersion = 10.80

...

JPEG SOF0 (15 bytes):
  ImageWidth = 7040
  ImageHeight = 2240
  EncodingProcess = 0
  BitsPerSample = 8
  ColorComponents = 3
JPEG DHT (29 bytes):
JPEG DHT (179 bytes):
JPEG DHT (29 bytes):
JPEG DHT (179 bytes):
JPEG DRI (2 bytes):
JPEG SOS
Samsung trailer (10731635 bytes at offset 0x50870f):
  SamsungTrailer_0x0201Name = Motion_Panorama_MP4_000
  SamsungTrailer_0x0201 = .ftyp3gp53gp5isom...mdat...e.N...@.S..}q.vIZ$...%2.M...o.....[snip]
  SamsungTrailer_0x08e1Name = Motion_Panorama_Info
  SamsungTrailer_0x08e1 = ..8......6.......@B.@B.Pf..@T.@B.@B.@B.W.0...!.@B.@B.?B.Pe..F[snip]
  Samsung_Trailer_0x0a01-name = Image_UTC_Data
  TimeStamp = 1499172656138
  SamsungTrailer_0x08e0Name = Panorama_Shot_Info
  SamsungTrailer_0x08e0 = PanoramaShot
```

**Comment by dcommander** [comment]
There’s a concept in U.S. law known as “moving to the nuisance”, which means basically that if you choose to build your house next to a factory that has been there for decades, you can’t complain about the noise. With regard to error handling, libjpeg-turbo behaves identically to libjpeg, and libjpeg has behaved that way for decades. Thus, if an application is generating an image that doesn’t decode properly with either, that application is creating an image that is incompatible with Linux and other major operating system families, as well as popular web browsers. The application is always free to install a custom error manager that ignores warnings or even errors from the libjpeg API at a particular point in the decompression pipeline, thus making the application more tolerant of bad input (but this behavior is actually less robust, not more.) If the application chooses to continue decoding after the warning/error rather than aborting, that is also its choice.

I really appreciate the time you spent debugging this, but there is really nothing I can do about the problem. As you said, an application can choose to ignore libjpeg API warnings or even errors at any time. If it wants to tolerate these errant images, then there are ways to do that without modifying the 20-year-old libjpeg API.

**Comment by lambdapioneer** [comment]
Absolutely! Just wanted to check if there was another solution that I missed :)

And wanted to leave this here for the next soul that faces those JPEG files.
