### ISSUE TITLE
jpeglib.h uses FILE but does not include stdio.h

### ISSUE THREAD

**Issue by Corin-EU** [libjpeg-turbo/libjpeg-turbo#17]
libjepg-turbo installs the header file jpeglib.h which uses "FILE" 

     jpeglib.h:EXTERN(void) jpeg_stdio_dest (j_compress_ptr cinfo, FILE * outfile);
     jpeglib.h:EXTERN(void) jpeg_stdio_src (j_decompress_ptr cinfo, FILE * infile);

but does NOT include <stdio.h>  which leads to compilation errors when included in compiling other software eg

     In file included from /usr/include/libmng_types.h:210:0,
                      from /usr/include/libmng.h:386,
                      from /var/tmp/root/mplayer-configure--4021/tmp.c:1:
     /usr/local/X11R6/include/jpeglib.h:914:53: error: unknown type name 'FILE'
      EXTERN(void) jpeg_stdio_dest (j_compress_ptr cinfo, FILE * outfile);
                                                          ^
     /usr/local/X11R6/include/jpeglib.h:915:54: error: unknown type name 'FILE'
    EXTERN(void) jpeg_stdio_src (j_decompress_ptr cinfo, FILE * infile);
                                                      ^

Including the stdio header file resolves the problem.

     --- jpeglib.h.orig	2015-09-11 17:40:00.539706398 +0100
     +++ jpeglib.h	2015-09-11 17:40:00.539706398 +0100
     @@ -28,6 +28,8 @@
      #endif
      #include "jmorecfg.h"           /* seldom changed options */
      
     +#include <stdio.h>
     +
 
     #ifdef __cplusplus
      #ifndef DONT_USE_EXTERN_C

**Comment by dcommander** [comment]
Inherited behavior from libjpeg.  libjpeg requires that you include jinclude.h before including jpeglib.h.  Theoretically you could build libjpeg without stdio support, which is why stdio.h isn't included from jpeglib.h.

I understand that these are primarily legacy behaviors, and it may not make sense to continue supporting them, but the reason why we do is because libjpeg-turbo is supposed to be backward compatible with libjpeg.  Thus, I don't want to create a situation in which a program compiles with our library but doesn't compile with libjpeg.
