### ISSUE TITLE
parallel decoding

### ISSUE THREAD

**Issue by drevilt** [libjpeg-turbo/libjpeg-turbo#170]
It would be great if this library would support parallel decoding of a jpeg file as this could greatly
improve decompression speeds.

I understand that the Huffman decoding cannot be done in parallel. Although the DCT of each 8x8 image block can be. If i understand it correctly the Huffman decoding is not what consumes most of the time. So a parallel conversion of the DCT's would still bring a lot of benefits. If you think this can be achieved then next step would be to decide on an implementation strategy.

A possible approach would be to use [OpenMP](https://en.wikipedia.org/wiki/OpenMP). The advantages of it is that it provides optional ( meaning compile-time optional ) parallelism. It can be activated/deactivated using an environment variable and gives less risk of making a mistake in the coding of parallel tasks, which can be easy to get wrong. Also it should not break ABI compatibility.

If you think there are any obstacles that completely prevent parallel jpeg decoding please let me know.
Otherwise I would be happy to try to draft a first implementation of it.

**Comment by dcommander** [comment]
A relevant thread from the mailing list:
https://sourceforge.net/p/libjpeg-turbo/mailman/message/35560538/

There are several reasons why multithreading in libjpeg-turbo is probably not ever going to happen.

Entropy decoding accounts for a disproportionate amount of the time spent decompressing a JPEG image, so even if linear parallelism could be achieved with multithreading, the overall speedup would not be that great (because of Amdahl's Law.)  The best case right now is using Huffman decoding with x86-64 code and SSE2 instructions.  In that case, entropy decoding accounts for about 50% of the total execution time (at least on the machine I primarily use for benchmarking.)  That means that, even with a linear speedup from two threads, your overall speedup could not exceed 25% (and, realistically, it's going to be less than that.)  Even with a linear speedup from four threads, your overall speedup could not exceed 37.5%.  Thus, the ideal incremental speedup from doubling the number of CPUs would be only 20%.

I expect to get a 25% speedup from the use of AVX2 instructions, once that project is complete (I finally secured funding for it, so I'll be working on it actively within the next month with an eye toward releasing libjpeg-turbo 1.6 this Fall.)  So not only does that eliminate some of the justification for multithreading (I mean, we're going to be pushing 300 megapixels/sec in many cases after the AVX2 enhancements-- how much faster do JPEGs need to get?), but it also further reduces the amount of speedup that can be achieved with multithreading.  Once the AVX2 enhancements are completed, entropy decoding will probably account for more like 2/3 of the execution time rather than 1/2, so an ideal dual-threaded decompressor could only speed up performance by 17%, and an ideal quad-threaded decompressor could only speed up performance by 26%.

It is possible to do entropy decoding in parallel, but it requires generating the source image with restart markers.  The number of decompressor threads would be limited by the number of restart markers.  The problem with this approach is that most JPEG images don't have restart markers.  Thus, the use of restart markers to improve scalability in a hypothetical multithreaded JPEG decompressor is only really viable if you control the compressor as well as the decompressor.  And if you control the compressor, you can much more easily and effectively implement data parallelism at a higher level-- by compressing the source image into multiple JPEG tiles and decompressing those tiles independently.

My own OSS projects/products (VirtualGL and TurboVNC, which pay the lion's share of my bills) use the latter approach, so there is little strategic benefit to me personally from attempting to implement multithreading within libjpeg-turbo, and there are a tremendous number of drawbacks.  libjpeg-turbo has grown in popularity to the point that it is considered to be a critical piece of infrastructure, and making broad, sweeping changes to it is likely to introduce a lot of bugs (including some security-related bugs.)  Without any kind of general fund to pull from when fixing those bugs, I would end up doing a lot of pro bono labor to integrate, debug, and maintain a feature that I am not personally using.  I do have some funding from Mozilla to finish up the tasks necessary to release 1.6, but a multithreading implementation would be a much larger project, and it's entirely possible that it could create esoteric bugs that don't pop up for years to come.  I would only be willing to engage in such a project if an organization was willing to fully fund all of my labor related to it-- including long-term maintenance and support of the feature.  Even the best-written patches and PRs require a great deal of labor on my part to test and integrate.  That's the only way I can maintain the high standards of quality that libjpeg-turbo users have come to expect.  Even if a patch is well-written and I do the best job I can integrating and testing it, there will still be bugs that pop up, and I'm usually the one who has to fix them, since the feature's author has usually moved on.

Thus far, those are two big nails in the coffin:  (1) lack of potential scalability and (2) lack of funding for long-term support of the feature.

The final nail is the libjpeg architecture itself.  libjpeg is more than 25 years old at this point, and the API was originally designed to accommodate 640k Messy-DOS machines.  The default source manager implements buffered/streaming decompression, whereby only a certain amount of compressed JPEG data is read into memory at a time.  Most applications that use the libjpeg API use this form of buffered decompression for historical reasons.  There is really no reason not to, because buffered decompression has no significant performance penalty if the buffer is sufficiently large.  But "sufficiently large" might only mean 128k, which is not large enough to get any kind of significant benefit from multithreading-- particularly given the aforementioned challenges with entropy decoding.  So that already limits the number of applications that might take advantage of multithreading in libjpeg-turbo.  We would probably have to stipulate that the in-memory source manager must be used in order for multithreading to be enabled.  If restart markers were used to split up the source JPEG, then it would absolutely be necessary to buffer the whole image, because that would be the only way of knowing where the restart markers were prior to decompression.

Furthermore, take this simple example of how an application uses the libjpeg API to decompress an image:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/example.c#L300-L399

The decompression task is driven by the application calling `jpeg_read_scanlines()` multiple times.  The application is well within its rights to ask for only one scanline at a time, which would kill any chance for parallelism.  libjpeg-turbo could conceivably buffer the entire image behind the scenes when the application makes its first call to `jpeg_read_scanlines()`, but this would be an abuse of the library's architecture and would create unexpected behavior for applications (particularly mobile applications) that are trying to control their memory footprint as much as possible.  So that would place a further limit on the number of applications that could take advantage of multithreading.

BTW, I can say (and have said) basically the same things about OpenCL.  AMD contracted me several years ago to help them attempt to accelerate libjpeg-turbo using OpenCL, but the project ultimately did not bear fruit because of the aforementioned libjpeg API/architecture limitations.  Basically, you need a full-image API like TurboJPEG in order to make coarse-grained parallelism (multithreading, OpenCL) work.  With a fine-grained API such as libjpeg, you have to use fine-grained parallelism (SIMD instructions.)

I am certainly open to enhancing the libjpeg API to make it easier for higher-level APIs to implement multithreading-- assuming that such could be accomplished without major disruption to the existing code-- but I really feel that the implementation of multithreading needs to occur within those higher-level APIs, not within libjpeg-turbo.

**Comment by drevilt** [comment]
Thank you for the detailed explanation. That cleared up a lot of things for me.
