### ISSUE TITLE
[FAQ] How to change image resolution 

### ISSUE THREAD

**Issue by kirantpatil** [libjpeg-turbo/libjpeg-turbo#177]
Hi,

I would like to change the jpeg image resolution from 96 to 100.

How to do it, please share the command details ?

Thanks.

**Comment by dcommander** [comment]
Your question makes no sense.  Please clarify.  The JPEG image resolution is based on the resolution of the source image.  Do you mean that you want to change the resolution of an *existing* JPEG image from 96x96 to 100x100?  Are you referring to DPI?  There is literally no technically meaningful way to parse your question.

**Comment by kirantpatil** [comment]
Yes I am referring dpi.

**Comment by kirantpatil** [comment]
Yes, I want to change the resolution of an existing JPEG image from 96x96 to 100x100

**Comment by dcommander** [comment]
The libjpeg API supports this, by modifying the "density_unit", "X_density", and "Y_density" parameters in jpeg_compress_struct.  However, that functionality is not exposed in cjpeg, djpeg, or jpegtran.  You will have to write your own program to do this, or take advantage of an external program (such as IrfanView, ImageMagick, Photoshop, etc.) to do it.
https://www.photo.net/discuss/threads/lossless-change-of-dpi-of-a-jpeg-photo.336490/

**Comment by kirantpatil** [comment]
Hi,

Thanks.

May I know if there is a sample program to do it ?

**Comment by kirantpatil** [comment]
I would like to know the API and its details.

**Comment by dcommander** [comment]
There is not a sample program in libjpeg-turbo to do this.  You could start by modifying one or more of the existing sample programs (cjpeg, djpeg, jpegtran.)  I googled this issue and found several possible solutions using external programs, and I suggest you do likewise.  For instance, exiftool can apparently modify the DPI fields in both the JPEG header and the EXIF header.  libjpeg-turbo cannot modify the EXIF header, so even if we had an example of how to modify the DPI fields in the JPEG header, it wouldn't be a complete solution if your JPEG images store the DPI using EXIF.

**Comment by kirantpatil** [comment]
@dcommander: Thanks for your detailed answer.

Please clarify my last doubts.

What you mentioned above "X_density", and "Y_density" parameters, are they same as shown in below TJCompressor api ?

Please correct me, If I make use of TJCompressor api, I should be able to set X and Y density of the image.

public TJCompressor(byte[] srcImage,
            int x,
            int y,
            int width,
            int pitch,
            int height,
            int pixelFormat)

Create a TurboJPEG compressor instance and associate the uncompressed source image stored in srcImage with the newly created instance.

#### Parameters:
srcImage - see setSourceImage(byte[], int, int, int, int, int, int) for description
x - see setSourceImage(byte[], int, int, int, int, int, int) for description
y - see setSourceImage(byte[], int, int, int, int, int, int) for description
width - see setSourceImage(byte[], int, int, int, int, int, int) for description
pitch - see setSourceImage(byte[], int, int, int, int, int, int) for description
height - see setSourceImage(byte[], int, int, int, int, int, int) for description
pixelFormat - pixel format of the source image (one of TJ.PF_*)

#### x and y parameter definition is below :
----
public void setSourceImage(java.awt.image.BufferedImage srcImage,
                  int x,
                  int y,
                  int width,
                  int height)

Associate an uncompressed RGB or grayscale source image with this compressor instance.

#### Parameters:
srcImage - a BufferedImage instance containing RGB or grayscale pixels to be compressed or encoded. This image is not modified.
x - x offset (in pixels) of the region in the source image from which the JPEG or YUV image should be compressed/encoded
y - y offset (in pixels) of the region in the source image from which the JPEG or YUV image should be compressed/encoded
width - width (in pixels) of the region in the source image from which the JPEG or YUV image should be compressed/encoded (0 = use the width of the source image)
height - height (in pixels) of the region in the source image from which the JPEG or YUV image should be compressed/encoded (0 = use the height of the source image)

**Comment by dcommander** [comment]
No, the DPI cannot be set through Java.  If that was a requirement, then you should have specified it in your initial question, and I wouldn't have wasted time talking about the libjpeg API (which cannot be accessed through Java.)  The Java API, and most of the other major features that have been added to libjpeg-turbo since the project's creation 7 1/2 years ago, have been paid for by companies that needed those features.  Thus, libjpeg-turbo has largely evolved in response to commercial need, and thus far, no one has had sufficient need for the ability to change the DPI through Java that they were willing to pay me for the development of that feature.  I don't get paid for most of my work on this project, and in most years, I donate hundreds of pro bono hours toward its continued maintenance-- primarily because it feeds into my other open source projects, which are paying most of my bills.  Thus, in order for a new feature to be introduced in libjpeg-turbo, I generally need either a well-crafted patch/PR from the community, funding for my labor to implement the feature, or a business case for how the feature will benefit my other projects.

Since the Java API is built on top of the TurboJPEG C API (not the libjpeg API), it would be necessary to extend the TurboJPEG C API first prior to extending the Java API.  You also never specified whether you are trying to set the DPI for existing JPEG images or for new JPEG images that you are creating.  If you're trying to modify the DPI of existing images, then libjpeg-turbo is probably not the best solution for that.  There are two places in which the DPI can be stored:  the JPEG header and the EXIF metadata.  libjpeg-turbo does not have the ability to modify EXIF metadata in general, so it would be an incomplete solution at best for modifying the DPI of existing images.

**Comment by dcommander** [comment]
I should clarify that you can't change the DPI through the existing Java API.  You could, of course, write your own JNI wrapper that does this operation using the libjpeg C API, but I am certainly in no position to provide you with instruction on how to do that.
