### ISSUE TITLE
Make SIMD symbols private

### ISSUE THREAD

**Issue by Nomis101** [libjpeg-turbo/libjpeg-turbo#180]
6 years ago it was discussed about making the SIMD symbols private at mozillla and it was seen as a good idea: https://bugzilla.mozilla.org/show_bug.cgi?id=698519#c76
Google is still doing this for chromium: https://chromium.googlesource.com/chromium/deps/libjpeg_turbo/+/master/simd/
Since than I'm using a patch to make the SIMD symbols private, but it is always a lot of work to patch all this files, so I think it could also be beneficial upstream. Find attached the patch for doing so.
[patch.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/files/1315053/patch.txt)

**Comment by dcommander** [comment]
You forgot to include this important bit of code in your patch:
https://chromium.googlesource.com/chromium/deps/libjpeg_turbo/+/master/simd/jsimdext.inc#371

Also, unfortunately those directives appear to be YASM-specific, so they can't be included in libjpeg-turbo.  I handle the issue of symbol visibility on Linux by using a version script (AKA "map file".)  This doesn't address the issue of symbol visibility when linking libjpeg-turbo statically, nor does it address the issue on Mac, so your solution would be nice to have if it worked with NASM.

**Comment by mayeut** [comment]
@dcommander,

When trying to upgrade from 1.5.1 to 1.5.3 at work, I stumbled upon this issue. I forgot that I patched 1.3.x a while back and a colleague has been patching all versions since then.

Given your previous comment, I'm not quite sure you'd integrate a patch, at least, in the form it's been proposed until now.

Would you be willing to integrate a patch given the following conditions ?
1. x86/x64 ELF => works with both YASM and NASM
2. x86/x64 MACH-O => works with both YASM and NASM (this one might need a NASM update - which will require a patch to be submitted/integrated to/by NASM team)
3. ARM/ARM64 ELF => Already done with `asm_function` macro
4. ARM/ARM64 MACH-O => works when following `BUILDING.md` (iOS), from .S file, I don't think symbol is marked as private external. Need to check
5. MIPS ELF =>  works when following `BUILDING.md` (Android - no section in `Building.md` as of now - / Linux). I did not find `.hidden` in MIPS assembly.

Other related point, shall this be made optional (maybe that would allow to relax constraint on 2 for the time being) or shall it always build assembly with hidden/private symbols ?

I'd rather have your input on this matter before patching NASM and MIPS.

**Comment by dcommander** [comment]
I will accept a patch that meets the follow requirements:

**x86/x86-64**
* Must support both NASM and YASM
* The feature can be enabled by default if it doesn't appreciably change the NASM/YASM requirements.  Currently these are (for the upcoming 1.6 release): NASM 2.10 or later-- except 2.11.08 on Mac-- or YASM 1.2.0 or later.  If doing this, for instance, required upgrading to a slightly newer NASM or YASM, that would be OK.
* If a patched/bleeding-edge version of NASM or YASM is required, then the feature must be build-time optional (using a CMake flag) and disabled by default.

**iOS/Android**
* It is acceptable to patch the MIPS assembly so that it works similarly to the ARM assembly, as long as doing so doesn't appreciably change the build requirements.
* It is acceptable to require a specific, documented build procedure to enable this feature on iOS, as long as the code can still be built without that specific procedure.

The patch should be against the dev branch, and it needs to land probably within the next month in order to be included in the upcoming 1.6 beta release.

**Comment by mayeut** [comment]
Thanks for the feedback. It might be a bit short to get something within the next month for NASM on Mac. I'll check what can be done.

**Comment by dcommander** [comment]
Is it technically possible to implement a solution for Linux using existing versions of NASM?  If so, then I would focus on that platform first.  Save the NASM customizations for last.  If it can be made to work currently on Mac using YASM, then we can make it build-time optional and disabled by default on that platform, then we can add support for NASM on Mac later.

**Comment by mayeut** [comment]
Yes, it's possible on Linux using NASM syntax (supported by YASM as well, at least 1.3.0, need to check with 1.2.0). I tested only x86_64 at the moment, using your official docker image with NASM 2.10.09

**Comment by mayeut** [comment]
MacOS update:
I filed an enhancement request for NASM: https://bugzilla.nasm.us/show_bug.cgi?id=3392463
In the meantime, I will make that optional for macho assembly.

**Comment by dcommander** [comment]
Integrated for all of the assembly language SIMD extensions and the supported platforms that use those extensions.  macOS currently requires YASM in order to make the symbols private.
