### ISSUE TITLE
Windows binaries 1.5.2 dynamically linked with gcc runtime (libgcc_s_dw2-1.dll)

### ISSUE THREAD

**Issue by zedxxx** [libjpeg-turbo/libjpeg-turbo#183]
I found that latest  Windows binaries for x86 (libjpeg-turbo-1.5.2-gcc.exe) dynamically linked with gcc run-time `libgcc_s_dw2-1.dll`, but all previews versions was linked statically. 

Is it happened accidentally or intentionally?

Also, I found that `libjpeg-62.dll` size increased from 568 kB (1.5.1) to 828 kB in 1.5.2. 

Maybe you made Debug build instead of Release in this version?

**Comment by dcommander** [comment]
I use the same [build scripts](https://github.com/libjpeg-turbo/buildscripts) to generate our pre-release (CI) and final release builds, so no, I didn't generate a Debug version.  I'm guessing that this issue was introduced when upgrading the MinGW compiler in the official build environment to GCC 6.1.0.  I was able to work around the issue by adding `-static-libgcc` to the official 32-bit MinGW build script for libjpeg-turbo.  The resulting build, which I pushed to https://sourceforge.net/projects/libjpeg-turbo/files/1.5.2, seems to work fine, but please watch for any issues that might surface when using `jpeg_stdio_src()` and `jpeg_stdio_dest()`.  libjpeg-62.dll and jpeg62.dll have to depend on the C run-time DLL because, when using the libjpeg API DLL, the aforementioned stdio source/destination managers pass FILE handles across the DLL boundary.  Thus both the DLL and the application have to use the C run-time DLL so that they share the same mapping between file handles and the opaque structures that those handles point to.  I don't think that it's necessary for the application and the libjpeg API DLL to link dynamically with libgcc, because none of the libgcc features are used across the DLL boundary, but I'm not 100% sure of that.
