### ISSUE TITLE
Cropping corrupts dest_mgr struct

### ISSUE THREAD

**Issue by pornel** [libjpeg-turbo/libjpeg-turbo#185]
Second problem reported in https://github.com/mozilla/mozjpeg/issues/268 and not solved by #182

Cropping options assume the input is using PPM dest mgr:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/1b385f37f3f166c046b6a73e7d3346eabd36ef76/djpeg.c#L716

which is not true for TGA dest mgr, and corrupts the struct.

What fix for this would you prefer?

* Addition of buffer_width to public dest_mgr? Or set_buffer_width callback in public dest_mgr? (elegant, but ABI breakage)
* An enum+switch that remembers what type of dest_mgr was used? (and still mess with casts and private buffes)
* Place buffer_width at the same offset in all related structs (super fragile)
* When non-PPM file is used with cropping option, abort or ignore the option? (theoretically compatible, because it never worked properly anyway)

**Comment by dcommander** [comment]
I will have to dig into this.  Stand by.

**Comment by dcommander** [comment]
For the moment, I opted to take the easy way out and simply throw an error if the user attempts to use `-crop` with a non-PPM output image format.  I also documented the fact that `-crop` only works with PPM/PGM output images.  I went down the path of attempting to fix this the right way, by adding a calc_buffer_width() method to the exposed (but project-private) djpeg_dest_struct structure in cdjpeg.h, but that was insufficient to make BMP images work properly (I kept getting virtual array access errors.)  At the moment, I'm not in the mood to figure out how to make this work with non-PPM images, since this was Google's feature to begin with (a prerequisite for including libjpeg-turbo in Android) and I have no use for the feature in my own projects.
