### ISSUE TITLE
a plan for cuda version?

### ISSUE THREAD

**Issue by cysin** [libjpeg-turbo/libjpeg-turbo#186]
Is there a plan to use cuda to accelerate this library?

**Comment by dcommander** [comment]
No.  AMD paid me several years ago to investigate accelerating libjpeg-turbo using OpenCL, which would be similar in concept to CUDA, but the fine-grained nature of the libjpeg API makes it unsuitable for that type of acceleration.  Basically, GPGPU solutions have a certain amount of overhead involved with transferring the images back & forth from main memory, so you need to be able to compress/decompress a large image in a single throw in order to overcome that overhead.  The higher-level TurboJPEG API would be suitable for CUDA or OpenCL acceleration, since it's a whole-image API and compresses/decompresses in main memory.  However, the libjpeg API operates on image rows, and it is perfectly legal to compress or decompress a single row of pixels at a time, do something else, compress or decompress another row, etc.  The libjpeg API also has to work with arbitrary source/destination managers, which can be used to implement buffered I/O, so the API is really designed for transferring a chunk of the image at a time, compressing/decompressing that chunk, transferring another chunk, etc.  AMD's developers tried some creative ways of getting around that, such as buffering the entire image whenever a single scanline was read/written, but this is an abuse of the libjpeg architecture.  At the end of the day, libjpeg is a 25-year-old API.  It was originally designed to work on 640k machines, so there are major limitations to how that API can be accelerated.  SIMD instructions just happen to be a good fit, because they have basically no overhead and can thus provide significant acceleration despite the fine-grained nature of the API.

libjpeg-turbo 1.6 will have AVX2 support, which should accelerate it by about 25% relative to libjpeg-turbo 1.5.  That project is funded.  I'm just trying to clear my plate enough to finish the development of it.  Other than that, the likelihood that other parallel computing technologies will make it into libjpeg-turbo is slim.  This project was originally intended as a high-speed drop-in replacement for the industry-standard libjpeg v6b, meant to make it easy for performance-critical JPEG applications to take advantage of SIMD acceleration without changing their source code.  After seven years, libjpeg-turbo has itself become a de facto industry standard and is under consideration to become an official ISO reference implementation.  I think we've neared the limit of what can be done in terms of acceleration.  Even AVX2 requires some architectural changes that make the libjpeg API slightly less fine-grained.  Because of Amdahl's Law, the incremental speedup from AVX512 vs. AVX2 will probably only be about 10-15%, which is likely not worth pursuing.  I'm certainly interested in any functional improvements, SIMD extensions for platforms that we don't currently support, optimizations to the existing SIMD extensions, etc., but I think the paradigm of libjpeg-turbo as a SIMD-accelerated JPEG library is well-established and unlikely to change at this point.  GPGPU JPEG acceleration would best be implemented using some other library.  TurboJPEG would be a good architectural fit, although it's questionable whether there are enough applications using that API to bother releasing another implementation of it.  Really and truly, the industry needs to sit down and come up with a new standard API to replace the libjpeg API, because that API is needlessly complicated and fine-grained.  A more coarse-grained API could achieve better performance simply by pipelining the existing subroutines or using thread parallelism (something else that is too coarse-grained to work with the libjpeg API.)
