### ISSUE TITLE
decode this JPEG failed on windows platform

### ISSUE THREAD

**Issue by chengfang0911** [libjpeg-turbo/libjpeg-turbo#192]
The JPEG only decode 301 lines,decode error at 302 line.
The belowed is the JPEG picture.
![154897](https://user-images.githubusercontent.com/12134859/33366474-595adcbc-d526-11e7-8ec3-78cf9cb37311.jpg)

The below JPEG effect result is which I decode on windows.

![1](https://user-images.githubusercontent.com/12134859/33366894-a5228e64-d527-11e7-90b8-c00fd9484b23.jpg)

**Comment by dcommander** [comment]
There is something wrong with the image.  When I try to decode it using djpeg, I get a warning ("Corrupt JPEG data: premature end of data segment.")  djpeg continues to decode the image and produce valid data, but that's because it is ignoring the warning.  You can make your code do likewise, which should allow the image to decode properly.  The bug is in the image, not in our code, so therefore it's your responsibility to work around it.

**Comment by chengfang0911** [comment]
@dcommander Thanks for your replay. I use the same function "jpeg_read_scanlines" with the demo.But my program didn't decode to the end until the function return 0. Is there some  other operate when you use the function decode fail?

**Comment by dcommander** [comment]
The best advice I can give you is to examine the [source code for djpeg.c](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/djpeg.c), since it is obviously able to fully decode this image.  Also look at the [tjDecompress2() function in the dev (evolving 1.6) branch](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/dev/turbojpeg.c#L1189-L1267).  The evolving 1.6 version of the TurboJPEG API can ignore warnings or treat them as fatal, so it serves as an example of how to achieve that with the underlying libjpeg API.

In general, I do not provide development support for the libjpeg API.  It is a 25-year-old API, and I did not design it.  I know that it fully works, because it receives intense scrutiny from Google and Mozilla and others.  libjpeg.txt documents that API, and cjpeg.c, djpeg.c, jpegtran.c, and turbojpeg.c provide good examples of its usage.

**Comment by dcommander** [comment]
Also refer to Page 9 of this report:
https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf
which demonstrates how to modify djpeg.c so that warnings are fatal.  You want to do the opposite of that, but this demonstrates how to create your own error manager that can distinguish warnings from errors.  You will need to create such a custom error manager for your own program.

**Comment by chengfang0911** [comment]
@dcommander  Thanks your advice.I use cjpeg.c to decode the picture and find the problem.My function ptr is different from demo.
The cjpeg.c use the evaluation of "jpeg_resync_to_restart" to  "src->pub.resync_to_restart" function ptr.I didn't give the funtion ptr value.
Now I solve the problem.Thanks a lot.
