### ISSUE TITLE
jpeg_skip_scanlines till end of image

### ISSUE THREAD

**Issue by svgpp** [libjpeg-turbo/libjpeg-turbo#194]
When trying to skip lines to the end of the image, `jpeg_skip_scanlines` [exits immediately](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdapistd.c#L389). I'm not sure if it is always correct to skip call to the [finish_input_pass](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdapistd.c#L507). 
I'd expect that call to `jpeg_skip_scanlines` will be indistinguishable from `jpeg_read_scanlines` as to library-controlled state, but looks like `finish_input_pass` makes the difference. But I may easily be wrong.

**Comment by dcommander** [comment]
If you can demonstrate that this creates a tangible, reproducible bug in the library's user-visible behavior, then I'm happy to fix it.  Otherwise, I absolutely don't care.  I only fix real bugs, not theoretical ones.

That feature was implemented by Google as a prerequisite for libjpeg-turbo's inclusion in Android.  I agreed to integrate the feature only because Google paid for my labor to clean up their code and API documentation and to make sure it fit as well as possible within the long-established libjpeg API, without causing any disruption.  However, the developer whose code I integrated no longer even works for Google, and my relationship with them is no longer active.  Thus, I am maintaining that feature purely on a break/fix basis.

**Comment by dcommander** [comment]
You are correct.  The problem this exposes is that, when skipping to the end of the image, a subsequent call to `jpeg_consume_input()` will return `JPEG_SUSPENDED` instead of `JPEG_REACHED_EOI`.  Investigating how best to fix it.

**Comment by dcommander** [comment]
I'm not sure how you encountered this issue to begin with, but obviously you are doing some sort of code review, so I would encourage you to review the commit I just pushed and make sure it does what you think it should.  I am not confident that this eliminates all problems with skipping to the end of the image.  Unless I miss my guess, if `jpeg_skip_scanlines()` is used to skip to the end of the image, any markers at the end of the image will be ignored.  That may not matter in most cases, but I can imagine that there may be some cases in which it does.

Unfortunately, the libjpeg API is unnecessarily complex in this day and age, because its design was originally intended to allow JPEG images to be compressed or decompressed using no more than 640k of memory.  That complexity makes it extremely difficult to extend the API to support new complex features such as partial image decompression, and it is unlikely that I will add any such complex features to the libjpeg API in the future.  That API is essentially legacy at this point, and it needs to be completely refactored or replaced before anything major is added to it again.

**Comment by dcommander** [comment]
Also, if you could evaluate the fix within the next few days, that would be great.  I'd like to release libjpeg-turbo 1.5.3 within the next week or so.

**Comment by svgpp** [comment]
I'm not nearly as familiar with library to review this fix nor have reproducing sample, but change looks close to what I was expecting. Thank you.

**Comment by dcommander** [comment]
How did you uncover the problem?

**Comment by svgpp** [comment]
I was performing some modifications to Chromium-based browser (Blink part) and, when I've used jpeg_skip_scanlines at the end of the image, JPEGImageDecoder stopped handling correctly end-of-image decode status. For a number of reasons, I didn't proceed with jpeg_skip_scanlines.

**Comment by dcommander** [comment]
OK, well then can you test JPEGImageDecoder with the new modification?  And next time, please include that information in the bug description.  You made it sound like this bug was purely theoretical.

**Comment by svgpp** [comment]
I've changed code to the state when I observed this bug and your change really fixed the issue.
