### ISSUE TITLE
Thread safety issues

### ISSUE THREAD

**Issue by SoLaRGit** [libjpeg-turbo/libjpeg-turbo#201]
I wanted to replace old Intel IJL library that was capable of loading down sampled decompressed images ultra fast. And libjpeg-turbo had promising small thumb size as IJL, and as fast as IJL. Took jpegturboCLI as .Net wrapper, upgraded libjpeg-turbo to 1.5.3. And made some performance test, and it seamed OK (fixed stride bug in wrapper lib). But I have discovered issues with Thread safety, and other random errors in decoding (please notice other libraries decode this images correctly in multi threaded environment). 

Now I have two questions:

1. There must be some better .Net (C++/C#) wrapper for libjpeg-turbo, could you please suggest some?

2. Also noticed there are other decompress functions (unlike one used in turbojpegCLI), that are thread safe. Is there any guide on libjpeg-turbo thread safety, and what function are more preferred in multi threading decompression environment, or must we make guard to decompress functions?

thank you
and best regards.

**Comment by dcommander** [comment]
I know very little about .Net programming.  The two .Net libjpeg-turbo wrappers of which I am aware are linked here:
https://libjpeg-turbo.org/About/Software
If you have questions about the thread safety of those wrappers, then that needs to be taken up with the developers of the wrappers.  Those are both downstream projects and are not supported by this project.

The underlying C libraries are thread-safe as long as you use one compressor or decompressor instance per thread, which generally means you can only use one thread to compress or decompress a particular JPEG image.  If you are in control of both compression and decompression, then you can implement multithreading by compressing a large uncompressed image in parallel (thus producing multiple smaller JPEG images), transmitting those images, then decompressing them in parallel to reconstruct the large uncompressed image.  Otherwise, however, there is generally no way to compress or decompress the same JPEG image using multiple threads.  Doing so would require an in-tree wrapper that calls the internal libjpeg functions (refer to jpegint.h), and even then, it would not be possible to perform entropy decoding in parallel unless the JPEG image was encoded with at least as many restart markers as the desired number of decompression threads.

In general, implementing this kind of thread parallelism within libjpeg-turbo would be difficult, because of the fine-grained and sequential nature of the libjpeg API.  That API was designed originally for 640k MS-DOS machines, so it is really meant for compressing or decompressing a JPEG image in chunks rather than all at once.  That data flow is not very conducive to thread-level parallelism, which is why this project has focused on the use of more fine-grained parallelism (SIMD instructions, specifically.)
