### ISSUE TITLE
Error when including as subproject

### ISSUE THREAD

**Issue by redagito** [libjpeg-turbo/libjpeg-turbo#202]
I want to build the library as part of a bigger project and use 
>add_subdirectory(libjpeg-turbo)

to include the project in my build
Unfortunatly this fails, because the CMakeLists.txt in the project uses 
>CMAKE_SOURCE_DIR 

instead of 
>CMAKE_CURRENT_SOURCE_DIR

Changing this should not affect the current build process but will make it usable as a subproject

**Comment by dcommander** [comment]
In general, it is unrealistic to expect upstream library maintainers to avoid using `CMAKE_SOURCE_DIR` and other CMake variables that are available to us.  I could fix this once, but it would likely break again in the future, since we don't test other project's build systems as a matter of course.  The CMake [`ExternalProject_Add()`](https://cmake.org/cmake/help/v3.0/module/ExternalProject.html) function is designed precisely to avoid this problem.  Please use it.

**Comment by cstamatopoulos** [comment]
Have seen a couple of issues talking about this.
PROJECT_SOURCE_DIR might be an option.

**Comment by dcommander** [comment]
No, because again, that would require us to change our build system to accommodate downstream projects.  There is a high likelihood of breakage under that scenario, since we don't test subproject builds of libjpeg-turbo as a matter of course (and I am unwilling to do so unless someone pays for that labor), and I guarantee you that libjpeg-turbo developers (including myself) aren't going to be mindful of avoiding  `CMAKE_SOURCE_DIR` in any of our CMakeLists.txt files.  Thus, it's best for downstream projects to use `ExternalProject_Add()`.  That's what it is designed for.
