### ISSUE TITLE
sample_range_limit table may be too small

### ISSUE THREAD

**Issue by glyphandcog** [libjpeg-turbo/libjpeg-turbo#207]
Decompressing the attached JPEG image appears to incorrectly clip the samples in ycc_rgb_convert().  I suspect that the sample_range_limit table is too small.  It looks like libjpeg uses a larger table (maybe this was changed after libjpeg-turbo was forked?).

I tested with libjpeg 9c and 6b (couldn't find anything older), as well as my own JPEG decoder (in Xpdf), and those produce similar output.  Libjpeg-turbo 1.5.3 produces incorrect output -- the RGB values aren't being clipped correctly.

(The attached image is a single MCU, pulled out of a larger image using "jpegtran -crop".)

![im1](https://user-images.githubusercontent.com/35048595/35457966-921e9f46-02d2-11e8-997d-46cf1530c774.jpg)

**Comment by dcommander** [comment]
Please attach the original, uncompressed and uncropped, image that you used to generate the JPEG.  I need to figure out whether this is reproducible using a full encode/decode, as well as see the error in context.  Whatever the cause, the issue goes away if you set `JSIMD_FORCENONE=1`, thus disabling the SIMD extensions, so it has nothing to do with when we forked (our code is indirectly based on libjpeg v6b, and libjpeg v6b has been unmodified for 20 years.)  It has something to do with our SIMD extensions.

**Comment by glyphandcog** [comment]
Interesting -- so maybe nothing to do with sample_range_limit at all.

I'm attaching the full image.  I've confirmed that setting JSIMD_FORCENONE=1 changes the output, for both the single MCU image and the full image.

Note that the full image is damaged, so you may be right about it being an odd case.  Though I'd be a little surprised if it caused nondeterministic behavior.

![im0-orig](https://user-images.githubusercontent.com/35048595/35461695-d0fa69c6-02e0-11e8-9e1b-2f1a67ccaf99.jpg)

**Comment by dcommander** [comment]
"Deterministic" was perhaps the wrong choice of words on my part.  What I meant was that, if the source image is damaged or is otherwise not an image that can be produced by a valid JPEG compressor, then you can't expect the output image to be correct.  I would agree that the decompressed image generated by libjpeg is closer to the intended image than the decompressed image generated by libjpeg-turbo, but still, the root cause of the problem is that the image is damaged, not that our implementation is incorrect.  The differing behavior seems to be due to our SIMD IDCT implementation, which uses 16-bit math, whereas the C IDCT implementation uses 32-bit math.  For all valid images, 16-bit math is sufficient, but if an image has missing data, then the DCT coefficients decoded by the Huffman decoder will likely be incorrect, and it's possible that some of them are out of bounds.  There are scenarios in which out-of-bounds DCT coefficients will wrap around in the SIMD implementation but not the C implementation.

Unless this be reproduced with an undamaged image, there isn't really anything we can do about it.  Damaged input produces damaged output, and there can't really be any expectation as to how correct the damaged output will be.  The fact that libjpeg produces a more correct image is only because it's using a very slow algorithm that employs more accuracy than is actually needed.
