### ISSUE TITLE
565 dithering behavior depends on client memory alignment

### ISSUE THREAD

**Issue by mattsarett** [libjpeg-turbo/libjpeg-turbo#22]
This isn't a fix/feature request.  I want to document a strange behavior that I was unaware of (and maybe others will be interested to know as well).

Looking at ycc_rgb565D_convert_internal() in jdcol565.c (or any of the 565 conversion functions with dithering), you'll notice that it dithers two pixels at a time in the main loop, with an if statement before the loop to handle a single, non 32-bit aligned pixel before the loop, if necessary.

What is interesting is that, depending on whether the input memory is aligned to 32-bits, the result of the dithering will be different (because DITHER_ROTATE() will be called at different intervals).  This is not really a bug, given that, regardless of the input memory alignment, the output image looks fine (and differences are indistinguishable to my eye).

But it is strange to me that the outputs are not identical, especially because of the lengths libjpeg-turbo goes to in order to ensure pixel compliance with 6b in its more traditional modes.

Just to be clear, I'm not advocating any action here.  This is an FYI.  We're not currently planning to use dithering with 565, I'm not aware if there are other users of turbo that may be using this functionality (or care that the output is not always identical).

**Comment by dcommander** [comment]
There's an old tracker item for known RGB565 issues:

https://sourceforge.net/p/libjpeg-turbo/bugs/74/

The RGB565 stuff was submitted by Linaro, and I had to do quite a bit of cleanup on it (and bug fixing-- the submitted code did not work properly on big endian architectures.)  Another (non-Linaro) developer identified some issues with the dithering code that are related to the above, but I never bothered to fix them, because (as you point out) the images look OK.  However, I definitely do think that the output should be deterministic based on a given input image, so it seems like this specific issue is worth fixing.

**Comment by dcommander** [comment]
(Note also:  RGB565 wasn't part of jpeg-6b or any other IJG release, so that's why our normal modus regarding pixel compliance diverges in this case.)

**Comment by dcommander** [comment]
After re-pondering this, it seems to me that the reason why the dithering constant is chosen based on the starting address of the output-- and why it should be-- is that it allows dithering to work properly when decompressing a sub-image.  For instance, let's assume that your output image is W x H and you have already decoded the full image into that buffer.  Now you want to decode a couple of sub-images of size W0 x H0 and W1 x H1, where W0 & W1 <= W AND H0 AND H1 <= H.  Regardless of the values of W0, W1, H0, and H1, the dithering will still work properly, because the dithering constant for a particular pixel will always be determined by the address of that particular pixel, so the pixel will appear the same regardless of whether it is the first (or only) pixel being decompressed or whether it is deep within a larger sequence of pixels being decompressed.

Please let me know if my understanding is flawed in some way, and I'll reconsider.

**Comment by dcommander** [comment]
NOTE:  This issue also seems to be unrelated to those described in the previous bug report (https://sourceforge.net/p/libjpeg-turbo/bugs/74/).  I am not 100% sure that the remaining issues identified in that report are really issues, since they don't seem to cause any real visual errors.
