### ISSUE TITLE
Opimization 

### ISSUE THREAD

**Issue by jdm7dv** [libjpeg-turbo/libjpeg-turbo#225]
could we pass the ../configure the -O3 (for performs maximal speed optimization) and 
-Os (so that it  tries to make the executable as small as possible)

**Comment by dcommander** [comment]
Several comments:
- Using configure is now a legacy feature, with the impending release of libjpeg-turbo 2.0.x.  libjpeg-turbo 2.0.x uses only CMake.
- The legacy autotools-based build system in libjpeg-turbo 1.5.x and prior already overrides `CFLAGS` to add `-O3`: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/1.5.x/configure.ac#L89-L91
- CMake uses `-O3` when `CMAKE_BUILD_TYPE` is set to `Release` (which is the default when building libjpeg-turbo) and `-Os` when `CMAKE_BUILD_TYPE` is set to `MinSizeRel`.
- `-O3` and `-Os` are mutually exclusive, because maximum performance and minimum code size are mutually exclusive goals.  You cannot use both.
