### ISSUE TITLE
jpegtran: better perfect transformations

### ISSUE THREAD

**Issue by ConradHughes** [libjpeg-turbo/libjpeg-turbo#233]
A range of perfect transformations are currently precluded because of jpegtran's treatment of the command line, where `-rotate` is always performed before `-crop`.  A relatively straightforward assist for this would be for jpegtran to process `-rotate`/`-crop` operations in the order in which they were specified.  For example, with a block size of 8×8, it is currently possible to perfectly extract a 90° clockwise rotated 15×15 rectangle at +16+17 from a 63×63 image as follows (final crop co-ordinates appear different because of the rotation):
```
jpegtran -perfect -crop 48x48+0+0 < 63x63.jpg | \  # Select a perfectly-rotatable area
    jpegtran -perfect -rotate 90 | \               # Rotate it
    jpegtran -perfect -crop 15x15+16+16 > out.jpg  # Crop as desired
```
I think you can achieve the same thing in a single command as follows:
```
jpegtran -rotate 90 -crop 15x15+24+16 < 63x63.jpg > out.jpg
```
.. but this fails with `-perfect`.  I'm sympathetic to the fail since even though the transformation is lossless, the imperfect rotation has broken the co-ordinate system (forcing the "+24" to select the correct location).

Ideally, ordered operations would in fact recognise perfection when it occurred - this (aiming for the same end result) isn't perfect because the intermediate JPEG cannot be perfectly constructed:
```
jpegtran -crop 15x15+16+17 < 63x63.jpg | jpegtran -rotate 90 > out.jpg
```
.. but this would be perfect (assuming operations are executed in switch order), since the final top-left corner of the crop is at an iMCU corner before the rotation:
```
jpegtran -crop 15x15+16+17 -rotate 90 < 63x63.jpg > out.jpg
```

**Comment by dcommander** [comment]
Also, it might be worthwhile to look at how the TurboJPEG API accomplishes this.  It allows you to specify an array of transformations, each with its own operation and options.  Thus, using that API, you can attach the "perfect" option only to particular transforms in a sequence, and you can control the order of those transforms.

**Comment by ConradHughes** [comment]
If I were to do something on this, what do you think would be an acceptable approach?  Enforcing order on command line transformations could break anything which expected the rotate-before-crop behaviour but didn't express it...

**Comment by dcommander** [comment]
The underlying transupp API isn't actually performing cropping after rotation.  It's performing both transforms within the same loop (refer to https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/transupp.c).  It's just that the cropping coordinates are interpreted relative to the destination (geometrically transformed) set of DCT coefficient blocks, not the source coefficient blocks.  Conceptually, if all you need to do is perform one flip/rotate/transpose/transverse operation at a time, with a single cropping spec applied to the source rather than the destination coordinates, then the most straightforward hack would be to implement an `s` specifier in the crop spec.  For instance, currently you can add `f` to the crop spec to disable automatic adjustment of the cropping region.  The `s` specifier could work similarly to specify that you want to crop against the source coordinates.  That way, you wouldn't need to make any deep modifications to jpegtran, and its behavior would remain backward compatible.

If, however, you're interested in performing multiple simultaneous transforms or multiple cropping operations within the same command invocation, then you're really better off writing a new utility (`tjtran` perhaps) that wraps the `tjTransform()` function.  For performance, you'd still probably want to modify the transupp API to handle cropping against source rather than destination coordinates, since that would eliminate some unnecessary memory copies.  It might even be possible to modify the existing tjexample program to do this, since it already handles lossless transforms.

Since the `-flip`, `-rotate`, `-transpose`, and `-transverse` arguments (in tjexample, these are `-hflip`, `-vflip`, `-transpose`, `-transverse`, `-rot90`, `-rot180`, `-rot270`) are currently mutually exclusive, the basic strategy of a command-line utility that supports multiple simultaneous lossless transforms should be to create a new transform spec whenever one of those arguments is specified, then allow the other arguments (`-perfect`, `-trim`, `-grayscale`, and `-crop`) to modify the transform immediately to the left of them.  You'd also need a new argument (`-none`) to create a new transform spec with no geometric modification (i.e. to do only cropping.)  Thus, you could specify multiple transforms on the same command line by doing something like:

```
tjtran -rotate 90 -crop 48x48+0+0 -perfect -none -crop 15x15+16+16 -perfect < 63x63.jpg`
```

It's certainly possible to make those modifications to jpegtran as well, but given that that program is inherited from libjpeg, a lot of people expect it to behave a certain way, and I'm loathe to change it in backward-incompatible ways.

**Comment by ConradHughes** [comment]
Sorry for the long delay replying; I'm also a little reluctant to take on anything big, but have had another idea which I might be able to practically contribute.  That would be to add a **-untrim** switch to jpegtran: when rotating odd-sized images **-untrim** would work contrarily to **-trim** — rather than dumping an odd-sized edge if it interfered with rotation, -untrim would expose the hidden pixels, i.e. rather than round the image size down it would round it up to the next block size.  What you'd get in the newly exposed pixels would of course be dependent on the creator of the original image, but the net result would be no loss of visible pixels from the original image.  AFAICS this feature doesn't seem to currently exist in the codebase, but a tentative proof-of-concept hasn't yet exploded in my face.  Its relationship to my original comment may appear a little tenuous, but it would somewhat ease the pipeline approach I describe above as a workaround to -perfect's limitations.

I also like your "s" specifier idea and will look into that.

**Comment by ConradHughes** [comment]
Just as a very late note on this, I finally realised that you'd provided me with a solution in the form of the 'f' suffixes to cropped image dimensions: this allows me to rotate and crop to desired size in a single action without the bottom right corner being unnecessarily rounded out to the ICMU boundary, which gets me what I wanted.

I think there is still a bug here, in that if I compare the output file from '-rotate R -crop WfxHf+x+y' (which fails if I apply '-perfect') with the equivalent file generated from a series of '-perfect' commands (first, perfectly crop image dimensions to ICMU boundary, then perfectly rotate it, then perfectly crop it so top left corner of output image is on ICMU boundary but bottom right is arbitrary), the two files are identical.  So it would appear that '-perfect' is rejecting a range of perfect transformations unnecessarily.

That all said, for my own purposes I'm happy enough with the workaround provided: just append 'f' to the crop width and height.  Thanks very much for your help in this regard!

**Comment by dcommander** [comment]
All of the lossless crop stuff was inherited from libjpeg.  If the behavior is different in libjpeg-turbo vs. libjpeg, then I would consider that to be a bug in libjpeg-turbo.  If the behavior is identical, then it's intended behavior.  You are welcome to petition [Guido](http://ijg.org/) to change the behavior upstream.  Despite what it says [here](https://libjpeg-turbo.org/About/Jpeg-9), I do still treat jpeg-9 as an upstream source for the lossless cropping features, and the libjpeg-turbo 2.1 (soon to be beta) code base has integrated the latest lossless crop features from jpeg-9d.
