### ISSUE TITLE
jpeg_read_scanlines hangs after calling jpeg_skip_scanlines

### ISSUE THREAD

**Issue by LeonScroggins** [libjpeg-turbo/libjpeg-turbo#237]
Not always, but a particular file (attached below) using a particular order of calls. Basically, we want an image that is 1/19th the size of the original file, so we do something like the following:

`  jpeg_skip_scanlines(&cinfo, 9);`
`  while (cinfo.output_scanline < cinfo.output_height) {`
`    (void) jpeg_read_scanlines(&cinfo, buffer, 1);`
`    jpeg_skip_scanlines(&cinfo, 18);`
`  }`

(This is actually a modified block of code from example.c, to make sure it wasn't a problem in our code.) Without the calls to jpeg_skip_scanlines, this works as expected. With them, we successfully decode line 732 of the image (which is 760 tall) and then skip 18 lines. The next call to jpeg_read_scanlines hangs. It enters an infinite while loop here:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/7c3b9e80a6c6bad90705a92755e5633b6610e18a/jdcoefct.c#L275

(*cinfo->inputctl->consume_input)(cinfo) returns JPEG_REACHED_EOI without changing any of the loop variables. Did jpeg_skip_scanlines skip too far?

![img-20160813-wa0008](https://user-images.githubusercontent.com/13983895/39596620-f0383ff6-4ee0-11e8-930f-c726807b6357.jpg)

**Comment by dcommander** [comment]
Ignore my previous comment.  I guess I can't add 732 and 18 in my head anymore.  :|  Investigating.

**Comment by LeonScroggins** [comment]
> the purpose of incrementing `main_ptr->iMCU_row_ctr`

`jpeg_read_scanlines` increments this (in `process_data_context_main`), and it is used to detect when we've reached the second iMCU row and when we've reached the last one. `jpeg_skip_scanlines` needs to increment it for the same reason.

> why it is being incremented differently for multi-scan vs. single-scan images.

This looks to be the bug to me. Your simple patch makes it so they are incremented the same [(see single-scan)](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/2401e4d10c2749c5c260a711c3bde52163829505/jdapistd.c#L518).

**Comment by dcommander** [comment]
I agree. It looks like a bug, but it would be nice to get confirmation from the author, since he knows what he was thinking when he wrote that code. Barring that, I will probably have to spend some hours prior to the final 2.0 release comparing a bunch of different partial image decompression scenarios and thus convincing myself that the patch above doesn’t introduce any new problems.

**Comment by walisser** [comment]
I don't know if this is related, but today with git master I found that using jpeg_skip_scanlines() in conjunction with do_fancy_upsampling=FALSE resulted in a segfault.

**Comment by dcommander** [comment]
It would be very easy for you to confirm whether or not it's related by applying the patch I listed above.

If it's an unrelated bug, then I'm to the point of just disabling any libjpeg features that don't work properly with partial image decompression.  I'm also to the point of saying that I will never again accept any disruptive modifications to the libjpeg API code.  I've already had to donate thousands of dollars of labor to fix Google's feature, because their employee who developed it is nowhere to be found.
