### ISSUE TITLE
Change integral types in the C-API to the platform-independent

### ISSUE THREAD

**Issue by Sergey-Terekhin** [libjpeg-turbo/libjpeg-turbo#24]
Hello!
I try to make .Net wrapper for libjpeg-turbo using C API defined in the turbojpeg.h
I've found issue with `unsigned long` parameters in the jtDecompressHeader3, jtDecompress2, jtTransform functions. The size of `unsigned long` is platform-dependent (4 bytes for x86 and 8 bytes for x64), but `ulong` in the .Net world is always 8 bytes. 
That mismatch makes writing some ugly code like this:

``` C#
static int tjDecompress(IntPtr handle, IntPtr jpegBuf, ulong jpegSize, IntPtr dstBuf, int width,
            int pitch, int height, int pixelFormat, int flags)
{
    switch (IntPtr.Size)
    {
        case 4:
            return tjDecompress2_x86(handle, jpegBuf, (uint)jpegSize, dstBuf, width, pitch, height, pixelFormat, flags);
        case 8:
            return tjDecompress2_x64(handle, jpegBuf, jpegSize, dstBuf, width, pitch, height, pixelFormat, flags);

        default:
            throw new InvalidOperationException("Invalid platform. Can not find proper function");
    }
}

[DllImport("turbojpeg.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "tjDecompress2")]
private static extern int tjDecompress2_x86(IntPtr handle, IntPtr jpegBuf, uint jpegSize, IntPtr dstBuf, int width, int pitch, int height, int pixelFormat, int flags);
[DllImport("turbojpeg.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "tjDecompress2")]
private static extern int tjDecompress2_x64(IntPtr handle, IntPtr jpegBuf, ulong jpegSize, IntPtr dstBuf, int width, int pitch, int height, int pixelFormat, int flags);
```

I think it was much more better to use platform independent types (like `int64_t` defined in the `<inttypes.h>`) for public API

**Comment by dcommander** [comment]
I agree, and others have requested the same thing:

https://sourceforge.net/p/libjpeg-turbo/mailman/libjpeg-turbo-devel/thread/5342E998.6050902@users.sourceforge.net/

But changing the datatypes requires changing the function signatures, and that's painful enough that I don't want to do it unless there are other changes to the TurboJPEG API that necessitate it (for instance, implementing a new feature such as https://github.com/libjpeg-turbo/libjpeg-turbo/issues/1.)  So yes, this is on my radar, and I intend for it to happen eventually, but I can't say exactly when.

**Comment by Sergey-Terekhin** [comment]
Thanks for your answer. I'll wait for update

My implementation of .net wrapper is here:
https://bitbucket.org/autonomicsystems/as.turbojpegwrapper
It's published under MIT license and it's also available as NuGet package.

I think it would be useful if you add links to the related projects

**Comment by dcommander** [comment]
Links added here: http://www.libjpeg-turbo.org/About/Software

**Comment by Sergey-Terekhin** [comment]
Thanks

**Comment by dcommander** [comment]
Please do not close issues until they are resolved.

**Comment by smasherprog** [comment]
Sergey, I have came across this as well. You can overcome this by using the IntPtr and it will all just work since it is always the size of a pointer, which is what you are looking for.  Net will serialize the numbers correctly as well.

**Comment by Sergey-Terekhin** [comment]
Thanks, I'll check

**Comment by dcommander** [comment]
@Sergey-Terekhin Please let me know if you are able to work around this using the method that smasherprog demonstrated above.

Here's the basic problem with respect to the TurboJPEG API:  unsigned long variables are used to represent buffer sizes in quite a few places:  `tjCompress2()`, `tjCompressFromYUV()`, `tjCompressFromYUVPlanes()`, `tjBufSize()`, `tjBufSizeYUV2()`, `tjPlaneSizeYUV()`, `tjDecompressHeader3()`, `tjDecompress2()`, `tjDecompressToYUV2()`, `tjDecompressToYUVPlanes()`, and `tjTransform()`.  There will be an opportunity to change some of those function signatures in libjpeg-turbo 1.6, in order to implement #1, but not all of them.  And it doesn't make sense to change all of them just for the purpose of changing the C type used to represent buffer sizes-- particularly given that the underlying libjpeg API uses unsigned long or size_t for buffer sizes as well.

Incidentally, our own Java wrapper does basically what smasherprog suggests doing above.  I think that is ultimately the best solution to this.

**Comment by dcommander** [comment]
Closing as WNF, since it seems that it would be easier overall to work around this at the .Net level than to change the C API.  If further information comes to light, please share it.

**Comment by dcommander** [comment]
The TurboJPEG 3 API now uses `size_t` instead of `unsigned long`.  That at least eliminates the O/S dependency, although the size parameters still depend on whether 32-bit or 64-bit code is being used.  `size_t` made the most sense, because that makes it possible to pass the return value of the TurboJPEG buffer size functions to `malloc()`.

Because Java is limited to 32-bit buffer sizes, I have to deal with differing C word sizes in the TurboJPEG JNI wrapper by checking for int overflow and then clamping the `size_t` value to 32 bits, because it is possible for the C functions to return values larger than `INT_MAX`.  Similar accommodations would have to be made with C#.
