### ISSUE TITLE
Debug works but Release crashes

### ISSUE THREAD

**Issue by MaeThird** [libjpeg-turbo/libjpeg-turbo#240]
I just want to compress bgr byte stream into jpeg file it works in Debug compile but crashes in Release compile of newest source code of libjpeg-turbo. too Strange to debug.
```
int tjwritejpeg(const char* jpegfile,const unsigned char*imgBuf,int w,int h,int pix_fmt){
  FILE * jpeg =NULL;
  tjhandle  tjInstance =NULL;
  unsigned char* jpegBuf;
  int jpegSize =w*h*4;
  if(!(jpeg =fopen(jpegfile,"wb"))){
    return -1;
  }
  tjInstance = tjInitCompress();
  jpegBuf = (uint8_t*)tjAlloc(jpegSize);
  int  res = 0;
  if(tjCompress2(tjInstance,imgBuf,w,0,h,pix_fmt == 0 ? TJPF_BGR:TJPF_BGRX,
		 &jpegBuf,&jpegSize,TJSAMP_444,95,/*TJFLAG_FASTUPSAMPLE*/TJFLAG_FASTDCT) != 0){
    res = -2;
    goto Exit;
  }
  if(fwrite(jpegBuf,1,jpegSize,jpeg) != jpegSize){
    res = -3;
  }
 Exit:
  tjDestroy(tjInstance);
  fclose(jpeg);
  tjFree(jpegBuf);
  return res;
}

```
I tried to let tjCompress2 allocate memory for jpegBuf but still crashed.

**Comment by dcommander** [comment]
Your code looks correct on the surface, but since you don’t show how imgBuf is allocated, I am immediately suspicious that you are somehow overrunning that buffer. I would suggest running your program through valgrind to attempt to diagnose that failure. You can also look at tjexample.c, which is known to work, and compare your program with that one. This is almost certainly not a libjpeg-turbo bug, but if you can produce evidence that it is, I’m happy to look into it.

**Comment by MaeThird** [comment]
Hi @dcommander  Yes,it's least likely a libjpeg-turbo bug.But this piece of code still crashed:
```
int tjwritejpeg_test(const char* jpegfile){
  FILE * jpeg =NULL;
  tjhandle  tjInstance =NULL;
  unsigned char* jpegBuf;
  unsigned char imgBuf[320*320*3];
  for(int i = 0;i < 320*320;++i){
    imgBuf[3*i] = imgBuf[3*i+1] = imgBuf[3*i+2] = 189;
  }
  if(!(jpeg =fopen(jpegfile,"wb"))){
    return -1;
  }
  tjInstance = tjInitCompress();
  int jpegSize =320*320*10;
  jpegBuf = (uint8_t*)tjAlloc(jpegSize);
  int  res = 0;
  if(tjCompress2(tjInstance,imgBuf,320,0,320,TJPF_BGR,
		 &jpegBuf,&jpegSize,TJSAMP_444,95,TJFLAG_FASTUPSAMPLE /*TJFLAG_FASTDCT*/) != 0){
    res = -2;
    goto Exit;
  }
  printf(":%d\n",jpegSize);
  res = fwrite(jpegBuf,1,jpegSize,jpeg);
  if(res != jpegSize){
    res = -3;
  }
 Exit:
  tjDestroy(tjInstance);
  fclose(jpeg);
  tjFree(jpegBuf);
  return res;
} 
```
![a](https://user-images.githubusercontent.com/14851411/40952654-9f604976-686b-11e8-9863-d032c622f2d9.png)
after days I will find it my hand but now I use example.txt's code  to continue.

**Comment by dcommander** [comment]
Try swapping the second and third arguments to fwrite() (you will also need to compare res against 1, not jpegSize.) If that doesn’t work, then you’ll have to wait until I have a chance to reproduce it, which may be a few days.

**Comment by dcommander** [comment]
Unable to reproduce the segfault, but one problem I noticed in your code is that `jpegSize` should be unsigned long, not int.  It's not hard for me to imagine a scenario in which that could cause a segfault on certain platforms with certain compilers.  Otherwise, I have no clue.  The segfault is clearly occurring outside of our code.

**Comment by MaeThird** [comment]
@dcommander Yes, change `int jpegSize =320*320*10;` into `unsigned long int  jpegSize =320*320*10;` is OK. Thank you.
