### ISSUE TITLE
jpeg's CVE-2018-11813

### ISSUE THREAD

**Issue by pgajdos** [libjpeg-turbo/libjpeg-turbo#242]
See https://nvd.nist.gov/vuln/detail/CVE-2018-11813 for details.

The testcase exhibits the bug for me with libjpeg-turbo 1.5.3.

**Comment by dcommander** [comment]
Upon further inspection, the issue whereby no data was written to the output only occurred when compressing a bottom-up TGA file, because such files are preloaded into memory by the reader.  When compressing a top-down TGA file, replacing `getc()` with `read_byte()` causes the Targa reader to behave like the PPM reader.  Fix pushed to both master (2.0) and 1.5.x branches.

**Comment by pgajdos** [comment]
Thank you.
