### ISSUE TITLE
Massive Memory use due to 258 byte JPEG file

### ISSUE THREAD

**Issue by bobfriesenhahn** [libjpeg-turbo/libjpeg-turbo#249]
This issue was discovered via Google's oss-fuzz while testing GraphicsMagick (oss-fuzz issue 9031)
![oss-fuzz-9031](https://user-images.githubusercontent.com/40547492/41822968-7c4e6f92-77bd-11e8-8ffa-5a1f886432de.jpg)
.  A very large amount of memory is allocated prior to any error being reported.  The IJG JPEG project's version does not suffer from this issue.

scooby:bugs/open/oss-fuzz-9031% which memusage
memusage: aliased to LD_PRELOAD=/lib/x86_64-linux-gnu/libmemusage.so
scooby:bugs/open/oss-fuzz-9031% memusage djpeg -pnm oss-fuzz-9031.jpg > oss-fuzz-9031.pnm
Corrupt JPEG data: 18 extraneous bytes before marker 0xd5
Quantization table 0x20 was not defined

Memory usage summary: heap total: 2425672615, heap peak: 2425672615, stack peak: 1632
         total calls   total memory   failed calls
 malloc|         20     2425672615              0
realloc|          0              0              0  (nomove:0, dec:0, free:0)
 calloc|          0              0              0
   free|         18     2424623487
Histogram for block sizes:
  160-175             1   5% ===
  544-559             1   5% ===
 1904-1919            1   5% ===
 4128-4143            1   5% ===
13248-13263           1   5% ===
16416-16431           1   5% ===
   large             14  70% ==================================================

**Comment by dcommander** [comment]
Reproduced.  Investigating.

**Comment by dcommander** [comment]
The behavior of libjpeg-turbo in this regard is the same as the behavior of jpeg-6b and jpeg-7.  The reason why jpeg-8 and later behave differently on this specific test case is because of this piece of code:

https://github.com/libjpeg-turbo/ijg/blob/jpeg-8/jdinput.c#L243-L334

which was introduced to support Guido's SmartScale extension.  The underlying issue is the one labeled "LJT-01-004" in this report:

https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf

Basically, because the libjpeg API library pre-allocates memory for progressive scans, a specially-crafted malformed input file can fool the library into thinking that it needs to allocate a great deal of memory to decode a very large JPEG file.  This specific test case includes a header indicating that the image is 65312 x 8224 pixels, so the library attempts to allocate 65312 x 8224 x 4 bytes ~= 2 gigabytes.  The aforementioned code that Guido introduced for SmartScale causes the library to detect the corrupt scan header prior to the memory being allocated, but it is very easy to modify the test case so that this check passes.  Simply change the 100th byte in the file from 0x20 to 0x3F, and jpeg-8 and later will also allocate 2 gigabytes.  As the aforementioned report demonstrates, it is entirely possible to craft a completely valid JPEG file that exhibits the same issue.  Thus, there is little that the decoder itself can do to guard against this, since valid JPEG images can contain as many as 4 billion pixels.  Applications wishing to guard against this issue should set cinfo->mem->max_memory_to_use, which libjpeg-turbo's memory manager now honors (as of version 1.5.2.)  For instance, passing `-maxmemory 100m` to libjpeg-turbo's implementation of djpeg works around the issue.

It would be easy enough to introduce a similar check for cinfo->Se into libjpeg-turbo (I would assume that any value other than 63 is invalid for our purposes, since we don't support SmartScale.)  I am open to that idea.  However, it should also be understood that such a check would just hide the real problem.  Whereas it would "fix" this particular test case, there are many other test cases that would still cause the library to allocate a great deal of memory.

**Comment by bobfriesenhahn** [comment]
Thanks.  Setting a memory limit for libjpeg "solves" the problem.  The only issue I notice is that libjpeg gave an error other than that it had hit its memory limit.

**Comment by dcommander** [comment]
libjpeg doesn't handle cinfo->mem->max_memory_to_use.  Only libjpeg-turbo does.  More specifically, in Tom Lane's code, that field was only honored by jmemansi.c, jmemdos.c, jmemmac.c, and jmemname.c, all of which are obsolete.  The POSIX memory manager (jmemnobs.c) used on all modern systems never had support for max_memory_to_use.  In the 1990s, Tom assumed that there was no real need to limit memory consumption in libjpeg on Un*x systems, but more recently, mobile platforms changed that assumption, so I had to add support for max_memory_to_use to jmemnobs.c.

The specific commit is here:
https://github.com/libjpeg-turbo/libjpeg-turbo/commit/da2a27ef056a0179cbd80f9146e58b89403d9933
