### ISSUE TITLE
Decoding issue with libjpeg-turbo 1.4.2 on ARM64 Android

### ISSUE THREAD

**Issue by marty-emmanuel** [libjpeg-turbo/libjpeg-turbo#26]
libjpeg-turbo 1.4.2 does not correctly decode the attached image (original_image) at least on Android when built for arm64-v8a. A section of a screenshot of the wrongly decoded image is also attached (jpegturbo1_4_2_issue).

The issue was observed on a Nexus 9. The lib was built with Android ndk-r10e using Clang. It does use the arm assembly code.

libjpeg-turbo 1.4.0 decodes the same image correctly on the same hardware.

v1.4.2 on windows, mac, iOS does not seem to exhibit this issue either.

Android uses unsigned char rather than signed, maybe that can be a factor.

I tried commenting out a change that looked suspicious in jddctmgr.c but it didn't change the result. The change was a block braced by if (divisor == 1) { .... } in compute_reciprocal(). None of the arm-specific assembler code was changed from 1.4.0 to 1.4.2

I am happy to help bisect this issue on that hardware.

![jpegturbo_1_4_2_issue](https://cloud.githubusercontent.com/assets/8497162/10450339/fdb52c1a-7199-11e5-9349-21c1d277146a.png)
![original_image](https://cloud.githubusercontent.com/assets/8497162/10450361/25ade11c-719a-11e5-9103-b3cc2a3960a9.jpg)

**Comment by dcommander** [comment]
Can you try a different build without the SIMD extensions (`configure --without-simd`) and see if it still breaks?

**Comment by dcommander** [comment]
Wait a second-- the output image is a different size than the input image.  Are you trying to use scaling?  Perhaps that's why I can't reproduce the issue.  Can you please supply me with the complete set of parameters that you are using to decode the image?

**Comment by dcommander** [comment]
Looking at the code differences between 1.4.0 and 1.4.2, I see some possibilities.  I would definitely try building with each of the following changes in isolation to see if you can nail down which one caused the error:

1. Revert a series of patches that caused the Huffman decoder to properly use a 64-bit holding register on non-Linux and non-Windows 64-bit platforms:

        git checkout 1.4.0 jdhuff.h

2. Revert some changes that removed negative left shifts and other undefined behavior:

        git checkout 8e9cef2e6f5156c4b055a04a8f979b7291fc6b7a~

3. Revert another negative shift bug fix:

        git revert  944aa8e3c4ea827c57d7bb9125f39611eb67ede1

**Comment by marty-emmanuel** [comment]
The image isn't actually rescaled by libjpeg-turbo; the buggy jpeg is a screenshot from the device, where the image is rescaled to the screen size by mapping it to a GLES quad. (outside of libjpeg-turbo scope)

#1 (reverting jdhuff.h) didn't change anything but.. YOU HAVE A WINNER. #2 solves the issue (reverting commit 8e9cef2e6f5156c4b055a04a8f979b7291fc6b7a in isolation)

I will try to reapply this patch in small steps and see which change(s) create the issue

![flower_ok1](https://cloud.githubusercontent.com/assets/8497162/10481108/d9ced5aa-726e-11e5-8f80-92b01558809a.png)

**Comment by marty-emmanuel** [comment]
I tracked the issue down to the change below. To be sure, I also verified that taking 1.4.2 and reversing this single change does make the bug disappear. 

diff --git a/jidctint.c b/jidctint.c
index 688fd22..3429795 100644
--- a/jidctint.c
+++ b/jidctint.c
@@ -235,8 +238,8 @@ jpeg_idct_islow (j_decompress_ptr cinfo, jpeg_component_info * compptr,
     z2 = DEQUANTIZE(inptr[DCTSIZE*0], quantptr[DCTSIZE*0]);
     z3 = DEQUANTIZE(inptr[DCTSIZE*4], quantptr[DCTSIZE*4]);
 
-    tmp0 = (z2 + z3) << CONST_BITS;
-    tmp1 = (z2 - z3) << CONST_BITS;
+    tmp0 = LEFT_SHIFT(z2 + z3, CONST_BITS);
+    tmp1 = LEFT_SHIFT(z2 - z3, CONST_BITS);
 
     tmp10 = tmp0 + tmp3;
     tmp13 = tmp0 - tmp3;

**Comment by dcommander** [comment]
Can you please ascertain whether the bug also exists when building with `--without simd`?  That would tell me whether this bug is purely in the C code or whether it is triggered by some interaction with the assembly code.

**Comment by dcommander** [comment]
What's confusing me is the fact that the ARM64 NEON SIMD extensions have coverage for the ISLOW IDCT, so the code that you discovered to be the culprit is code that shouldn't actually be executed.

**Comment by marty-emmanuel** [comment]
It looks like I am not actually using the SIMD code on ARM64, contrary to what I thought. I had a ifeq for arm64-v8a buried in the jni/Android.mk script that I forgot to remove. That could also explain why it works fine on ARM32 (which does build with SIMD).

**Comment by dcommander** [comment]
Aha.  OK, if you are able to reproduce the issue with ARM32 with `--without-simd`, then that is actually something I can test.

**Comment by marty-emmanuel** [comment]
Sadly no, I built for armeabi-v7a with jsimd_none and the image decodes fine

**Comment by dcommander** [comment]
OK, so can you verify that ARM64 with SIMD also works?  If so, then it does appear that we're dealing with some sort of compiler issue, and I will refer the matter to the Linaro developers.

**Comment by marty-emmanuel** [comment]
I confirm that when building on ARM64 with SIMD (jsimd_arm64.c and jsimd_arm64_neon.S), the image is decoded correctly -- unsurprisingly

**Comment by marty-emmanuel** [comment]
Could it be an issue with __INT32_IS_ACTUALLY_LONG on ARM64 somehow?

**Comment by marty-emmanuel** [comment]
Ah yep, that's it. Somehow the #define __INT32_IS_ACTUALLY_LONG isn't in my jmorecfg.h. Probably an issue when I patched to 1.4.2. With it the image decodes correctly on ARM64

Wow, that #define has scary consequences!

**Comment by dcommander** [comment]
OK, cool.  Yeah, the whole __INT32_IS_ACTUALLY_LONG thing is admittedly a hack, and there's a long story behind it.  This is as good a place as any to tell that story.

The INT32 typedef in jmorecfg.h dates back to libjpeg v5 in 1994.  Back then, at least to the best of my recollection, it wasn't common for other APIs to define INT32 as a datatype, or at least it wasn't as common as it is today.  The Win32 API headers started defining INT32 at some point, and other APIs such as Qt started defining INT32 as well, so this created a bit of a conflict.  Technically the definition of INT32 is part of the libjpeg API-- any program that includes jpeglib.h from libjpeg v5 or later is well within its rights to expect that INT32 will be a valid type.  However, the libjpeg header files define INT32 to long.  This is another legacy thing-- because int used to be 16-bit on MS-DOS and Win16, it was necessary to define INT32 to long to ensure that the holding registers for the DCT algorithms were at least 32 bits wide.  Ideally, libjpeg should have either used a different typedef (such as "JINT32", for instance) or defined INT32 to int instead of long on 64-bit platforms, a la Xmd.h:

    # ifdef LONG64
    typedef long INT64;
    typedef int INT32;
    # else
    typedef long INT32;
    # endif

Sadly, though, neither one of these things happened, so our current hackish approach continues to be:

- Check whether Xmd.h, QtGlobal.h, or basetsd.h (Win32) is already included, and don't attempt to define INT32 in that case (since the headers in question will have already defined it.)  If this happens, then INT32 will always be a 32-bit signed datatype.

- If one of the afore-mentioned headers isn't included, then define INT32 to long.  This makes it a 64-bit type on 64-bit Un*x platforms but a 32-bit type on all other platforms (note that Win64 is LLP64, so long is always 32-bit on Windows.)

https://github.com/libjpeg-turbo/libjpeg-turbo/commit/8e9cef2e6f5156c4b055a04a8f979b7291fc6b7a introduced code to make the undefined behavior sanitizers in modern compilers happy, and that means eliminating left shifts in which either of the operands was a negative number.  But that means typecasting the negative operand to either (unsigned int) or (unsigned long), depending on whether INT32 is 32-bit or 64-bit, so the compiler understands that we're intentionally treating the negative operand as a raw 2's-complement binary number instead of as a negative integer.  But as you point out, this introduces a macro that has scary consequences, because making the wrong assumption about whether INT32 is 64-bit or 32-bit will now cause the results of all of the left shift operations in the C code to be incorrect.

I think I need to bite the bullet and use an internal datatype, such as JINT32, instead.  INT32 will remain defined in jmorecfg.h, for backward compatibility, but it won't be used internally.

**Comment by marty-emmanuel** [comment]
Thanks for the detailed explanation! That makes perfect sense. I guess you could also assert that sizeof(INT32) is what you expect for now, but using JINT32, etc is definitely the safest route.
