### ISSUE TITLE
How to compile individual file

### ISSUE THREAD

**Issue by xu932** [libjpeg-turbo/libjpeg-turbo#268]
I tried to understand the `Makefile` but for the most part I don't know what file or dependencies it is compiling exactly. If I were to call functions in `tjexample.c` from another program, how do I compile?

**Comment by dcommander** [comment]
The Makefiles are generated automatically by CMake.  You should not ever use those directly.  You should instead install the libjpeg-turbo SDK, either from your own build of libjpeg-turbo or from one of our [pre-built binaries](https://sourceforge.net/projects/libjpeg-turbo/files).  Then, on Un*x systems, you can do something similar to this:

```
cc -O3 -o tjexample -I/opt/libjpeg-turbo/include /opt/libjpeg-turbo/lib64/libturbojpeg.a
```
 
On Windows systems, you can do something similar to this:

```
cl /O2 /Ic:\libjpeg-turbo\include ..\tjexample.c /link c:\libjpeg-turbo64\lib\turbojpeg-static.lib
```

libjpeg-turbo works similarly to other open source libraries in that regard.

I've spent many hundreds, if not thousands, of unpaid hours over the last 8 years making this library as easy to use as possible.  It's considerably easier to use than libjpeg.  If there are specific suggestions for how to make libjpeg-turbo even more intuitive, then I'm happy to consider those specific suggestions, but I cannot provide individual instruction.

**Comment by xu932** [comment]
Thank you for your answer. But I have a follow up question.

If I'm building on remote server which I don't have sudo access, and the SDK is not installed there. Is there anything I can do?

**Comment by dcommander** [comment]
Install it into your home directory.  You haven't provided any information about what type of server (CPU, O/S, distribution, etc.) you are using, so I have no idea how to be more specific, but you can certainly build libjpeg-turbo from source and install it into any directory you choose (by setting the `CMAKE_INSTALL_PREFIX` variable.)  If your server is Debian-based or Red Hat-based, then there are ways to install the .deb or .rpm packages into a non-root directory.  Google it.

Again, libjpeg-turbo works similarly to other open source libraries in that regard.  What I mean by that is:  you would have to do the same thing in order to install and use virtually any other open source library, and it isn't my job to impart basic knowledge regarding the use of open source libraries.  There are numerous online resources for that.  If you are using Linux, then there's a good chance that your distro provides libjpeg-turbo already  (although most don't provide the TurboJPEG API portion of it.)
