### ISSUE TITLE
Is reshape the image one of the functionality

### ISSUE THREAD

**Issue by xu932** [libjpeg-turbo/libjpeg-turbo#270]
Is there a reshape function to shape a large image to a smaller one (not scale by a factor)?

For example, given a 800x600 image and I would like an 400x400 output. The image will be distorted (and lossy reshape is fine) but not cropped.

**Comment by dcommander** [comment]
No, libjpeg-turbo does not do this.  The decompression scaling feature in libjpeg-turbo works in frequency space by scaling the 8x8 DCT coefficient blocks into smaller blocks in the process of performing the inverse DCT algorithm.  That's why it only supports specific scaling factors that are multiples of 1/8 and does not support changing the aspect ratio.  What you're referring to is scaling in image space, which is out-of-scope for a JPEG library.  There are numerous open source image libraries that already do this, including GraphicsMagick and Imlib2 and OpenCV and DevIL, as well as commercial solutions such as Intel Integrated Performance Primitives.
