### ISSUE TITLE
Debian jpeglib62-turbo, but no jpeglib8-turbo

### ISSUE THREAD

**Issue by Armannas** [libjpeg-turbo/libjpeg-turbo#28]
Might be better to ask to Debian community, but found this repo to be more accessible.
Is it true that there is no Debian package for libjpeg8-turbo? I'd like to accelerate Pillow, but I couldn't find it in the packages.

**Comment by dcommander** [comment]
I know that Debian 8.0 "Jessie" and later provide libjpeg-turbo, but I am not usually privy to the details of how distros package the libraries.  A quick search

https://packages.debian.org/search?keywords=libjpeg&searchon=names&suite=stable&section=all

shows that they appear to be doing the same thing Fedora/Red Hat is doing, which is building libjpeg-turbo with "extended" libjpeg v6.2 API/ABI support.  That is, they are using the default build options in libjpeg-turbo, which include the libjpeg v6.2 API/ABI (for backward compatibility) but also include the `jpeg_mem_src()`/`jpeg_mem_dest()` functions from libjpeg v8.  There are no known open source applications that take advantage of libjpeg v8 features other than the memory source/destination manager, so it isn't actually necessary to use the full libjpeg v8 API/ABI.  A lot of projects upgraded to libjpeg v7 or v8 before libjpeg-turbo really took off.  Some project maintainers were just sourcing the latest & greatest IJG code without really realizing that the "new" IJG had become more of a science fair for DCT research and had moved away from Tom Lane's original goals of encouraging the widest possible adoption of the JPEG standard. libjpeg v8 does some clever things with the DCT algorithm, but in doing so, it introduces a new extension to the JPEG file format that is not approved by standards committees, and despite being a clever trick, without standards approval, there is little chance that that new JPEG extension will ever be widely adopted.  There is also doubt as to whether the extension really accomplishes anything that can't already be accomplished in other ways:

http://www.libjpeg-turbo.org/About/SmartScale

And when you disregard SmartScale, there is really nothing else in libjpeg v8 other than the memory source/destination manager, which libjpeg-turbo supports as an extension to the libjpeg v6.2 API/ABI.

So as far as I know, JPEG is accelerated under Jessie and later, but I have never actually used Debian, so I don't know the specifics.  I will say that you can always take our "official" binary packages and install them on RPM-compatible or Debian-compatible platforms that don't include libjpeg-turbo.  They install under /opt/libjpeg-turbo, and you can then manipulate LD_LIBRARY_PATH to use those libraries instead of the ones under /usr.

**Comment by Armannas** [comment]
Thanks for the very elaborate answer! Googling your story results in old Debian mailing lists where people have [discussed] (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717076#5) the exact matter that you have stated.
