### ISSUE TITLE
Extremely slow JPEG

### ISSUE THREAD

**Issue by bobfriesenhahn** [libjpeg-turbo/libjpeg-turbo#284]
This JPEG test case was produced by oss-fuzz. It spends about a minute in jpeg_start_decompress() although it is only 38kB in size.  I don't want to do hacky things in GraphicsMagick to work around this issue.

Is it possible for libjpeg-turbo to do better with this file?

![oss-fuzz-10258](https://user-images.githubusercontent.com/40547492/45601532-f1287a80-b9d3-11e8-8ac6-52b7e56aebd8.jpg)

**Comment by dcommander** [comment]
libjpeg-turbo performs similarly to libjpeg on this file.  This is another example of the LJT-01-003 issue described [here](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf).  The file contains over 1000 14-megapixel progressive arithmetic scans, and the size of the file strongly indicates that it's taking advantage of the same EOB run loophole described in the aforementioned report.  As the report demonstrates, the issue in question can occur with a completely valid progressive JPEG file, and given that the feature being exploited is part of the JPEG standard, there isn't really a way to work around it other than to abort after decoding a specific number of scans.  Basically, the exploit is taking advantage of a file format feature that was meant to save space/bandwidth.  Other codecs besides libjpeg and libjpeg-turbo experience the same issue (Photoshop, for instance, is also vulnerable to it-- albeit not with this specific image, since Photoshop doesn't support arithmetic entropy coding.)  In this case, limiting the number of scans to 100 causes this image to decode in 3 seconds rather than 30 on my particular machine.

I spent a great deal of time researching this issue in the context of co-authoring the aforementioned report, and if there is another way to work around the issue other than setting a limit on the number of progressive scans, I am unaware of it.  But I also fail to see the usefulness of a valid progressive JPEG image with > 100 scans, so I don't see why you couldn't set that as a default limit in GraphicsMagick and allow the limit to be overridden at run time with an environment variable or other advanced setting.  I unfortunately can't set such a default limit in libjpeg-turbo because, technically speaking, the progressive JPEG format has no such limit.  So being compatible with the strict letter of the JPEG standard causes us to be vulnerable to this particular exploit.

**Comment by dcommander** [comment]
That being said, I would be open to a feature in libjpeg-turbo that allows a limit on the number of progressive scans to be set using an environment variable.  That would at least make it easier for applications to work around the issue, if they so choose, and it would allow the issue to be worked around in the TurboJPEG API.

**Comment by bobfriesenhahn** [comment]
Today I added fixes in GraphicsMagick based in part on your document.  The fixes provide a default limit of 100 scans and allow the user to adjust the limit.
