### ISSUE TITLE
Tag 1.5.4 release?

### ISSUE THREAD

**Issue by ncopa** [libjpeg-turbo/libjpeg-turbo#285]
There seem to be various important fixes, including at least 2 security fixes (CVE-2018-1152, CVE-2018-11813).

It would be very helpful if 1.5.4 was tagged and released.

**Comment by dcommander** [comment]
All of the above are in 2.0.0, which is a stable release.  There will not be a 1.5.4.  Use 2.0.0.

**Comment by dcommander** [comment]
To elaborate:

- The master branch always contains the latest stable release, plus any bug fixes that have been applied since the release.
- The next-gen release (including any new features relative to the latest stable release) is developed in the dev branch.
- When the dev branch is ready for beta, it is merged into the master branch, and a stable branch is created for the previous (last-gen) stable release + bug fixes.  You can see that we have one of these branches for every major release of libjpeg-turbo back to 1.0.x.
- The version number is always incremented when new commits are pushed relative to a release, but an incremented version number does not mean that that code will be officially released.
- With rare exceptions, releases are only made from the master branch, so once the next-gen release has stabilized and is in master, no further releases will be made from the last-gen stable branch.
- Any bug fixes from the master branch (current stable release) will be cherry picked into the last-gen stable branch, to allow those who wish to use the previous version of the code to continue to do so while they transition to the current version.
- All stable branches will receive critical security patches, if applicable.
- Travis and AppVeyor build pre-release binaries and source tarballs from the next-gen (dev), current (master), and last-gen (1.5.x at the moment) branches, thus allowing those who wish to use the last-gen version of the code to continue to do so while they transition to the current version.
- If you want a specific commit cherry picked into the last-gen branch, all you have to do is ask.

Given all of that, I do not see any compelling reason to put out a 1.5.4 release.  Those wishing to continue using the legacy Autotools build system can easily do so by checking out the 1.5.x branch, or getting GitHub to automatically generate a [tarball](https://github.com/libjpeg-turbo/libjpeg-turbo/archive/1.5.x.tar.gz) from it, or using the [pre-release binaries and tarball](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) built from that branch.  I am always more than happy to push bug fixes to that branch, even if they are specific to the last-gen version of the code and don't apply to the current version.

Specific to 1.5.x, at the time 2.0 beta1 was released, there were only three bug fixes relative to 1.5.3, which was not enough to justify a 1.5.4 release.  Had there been more bug fixes at the time, I would have likely put out a 1.5.4 release just prior to the 2.0 beta1 release.  I generally want at least 4-5 significant changes before putting out a new release.  So basically there isn't a 1.5.4 because of timing.  Also, if you'll look at our version history, none of the other major releases ever made it to .4.  1.5.3 was the first .3 release, and it exists only because 2.0 took so long to develop.

**Comment by dcommander** [comment]
As far as tagging the release, I don't tag a release unless I'm going to build it and put the binaries/tarball out on SourceForge, which takes a significant amount time, since the official builds are all done offline.  Also, SourceForge unfortunately will show the latest release as being the most recent, so if I put out a 1.5.4 release now, it would be the default release shown to people on SourceForge until 2.0.1 was released.  That's one of the logistical problems that necessitates the policy described above.
