### ISSUE TITLE
set(CMAKE_DEBUG_POSTFIX "d") ?

### ISSUE THREAD

**Issue by woopsoop382n** [libjpeg-turbo/libjpeg-turbo#293]
libpng and zlib seem to use this, so why not add this to libjpeg? On windows + visual studio, debug and release libraries are uncompatible, they use different versions of runtime library. With this postfix, I can compile both and easily switch between them, they can be in the same folder.

Also I have so much trouble with just organising all my libraries on windows, how should I do this? To debug a library, I need to make sure that .pdb file is in the same directory as the .lib file. So I think I'm not supposed to actually "install" libraries into the C:/install like I do right now, but instead show my main program where to get those libraries from, one project at the time. I placed sources for all libraries I use in C:/src, but how can I show each library where to look for each other library? For example, libpng depends on zlib, so I guess I have to add a few lines in the CMakeLists.txt to tell it where it's placed.

Here is my thread on that https://board.flatassembler.net/topic.php?t=20521

**Comment by dcommander** [comment]
If you are using the Visual Studio IDE, then such a postfix is unnecessary, as is specifying `CMAKE_BUILD_TYPE`.  The IDE already creates unique subdirectories for each build type, and when using the IDE, you control the build type from within the IDE, not from the CMake command line.  I personally don't want to add a debug postfix, because it would interfere with my development workflow.  I don't use IDEs, so I almost always work from a command-line (NMake) Release build of libjpeg-turbo when developing new features, then if I find something that needs to be debugged with the debugger, I'll switch the build type to RelWithDebInfo and rebuild in the same directory, then switch back to Release once the bug is fixed.

Telling you how to organize libraries on Windows is out of scope for the support I provide, but generally if one library depends on another, you can use CMake variables to specify where to find the dependency.  In the case of Zlib, for instance, the FindZlib CMake module uses the variables `ZLIB_INCLUDE_DIR` and `ZLIB_LIBRARY`.  You can override those variables to tell it where to find the Zlib headers and the Zlib link library.  Any further questions regarding how to use CMake with external dependencies are best asked within the CMake community.

**Comment by zchrissirhcz** [comment]
Adding postfix `d` for debug library on windows is a good practice for most people.
Using nmake instead of Visual Studio is really realy wired. IDEs are for boosting debugging effiency.

What's more, switching debug and release library can be automatically done in Visual Studio if the `FindXXX.cmake` is well organized.

**Comment by zchrissirhcz** [comment]
Just make it simple: when people are on windows and would like a postfix d for debug library, then when invoking cmake, add this:

```
-DCMAKE_DEBUG_POSTFIX=d
```

**Comment by dcommander** [comment]
@zchrissirhcz You are not in a position to say what is a good practice for “most people.” You only speak for yourself. I have already explained why this feature is not a good fit for libjpeg-turbo. You have not convinced me otherwise.
