### ISSUE TITLE
pc files not installed with Visual Studio packages

### ISSUE THREAD

**Issue by nacho** [libjpeg-turbo/libjpeg-turbo#296]
I just built the last version with cmake and as far as I checked right after the pc files are not installed for win32 nor osx. Note that meson can be used on windows and depends on the pc files for proper dependency support.

**Comment by dcommander** [comment]
**OS X:**

The .pc files are available under /opt/libjpeg-turbo/lib/pkgconfig in our official packages, and under ${CMAKE_INSTALL_LIBDIR}/pkgconfig when doing `make install`.

**Windows:**

The .pc files are available under c:\libjpeg-turbo-gcc\lib\pkgconfig and c:\libjpeg-turbo-gcc64\lib\pkgconfig in our official MinGW packages (libjpeg-turbo-gcc*.exe) and under ${CMAKE_INSTALL_LIBDIR}/pkgconfig when doing `make install`.  It doesn't make much sense to have .pc files in the Visual C++ packages.

**Comment by nacho** [comment]
Note what I pointed out about meson which we use with gvsbuild to build with visual studio

**Comment by dcommander** [comment]
OK, but your original post claimed that .pc files do not exist on OS X or Windows.  That is not true.  They are only missing in the Visual Studio packages for libjpeg-turbo, because Visual Studio is not traditionally something that could be used with pkg-config.

It seems that the crux of your request is to add .pc files to the Visual Studio package, but before I am willing to do that, I need a reproducible workflow that:

1. demonstrates the need for those files when used with Visual Studio
2. allows me to test the correctness of those files, once introduced into the Visual Studio packages

Given that I have never used Meson or gvsbuild, please provide further instructions.  Suffice it to say that those are esoteric workflows not used by most Visual Studio users.

**Comment by nacho** [comment]
About 1. pkgconfig is properly supported on windows these days, either by using the upstream pkg-config software or the new lighter pkgconf one.
On Windows it will redefine the prefix of the pc in relation to the pkgconf binary, so even if you built libjpeg in dir foo and you copied it to dir bar, the relocation will work properly even if foo is hardcoded in the pc file.
About an use case you can fine one here: https://github.com/wingtk/gvsbuild/blob/master/gvsbuild/projects.py#L971 . Currently for libgxps we have a hardcoded pc file for jpeg and we use it instead of having upstream to install its own one.

In relation to correctness, I think that doing the same as what you do for mingw or linux will just work fine with visual studio.

**Comment by nacho** [comment]
And here our custom pc files: https://github.com/wingtk/gvsbuild/tree/master/patches/libjpeg-turbo/pc-files

**Comment by dcommander** [comment]
This is what I don't understand, though-- those .pc files have GCC syntax, but you're linking with Visual C++ libraries.  How does that even work?

Also, please do not confuse the names "libjpeg-turbo" and "TurboJPEG."  libjpeg-turbo is the name of our project.  TurboJPEG and libjpeg are both APIs that our project supports.  Refer to https://libjpeg-turbo.org/About/TurboJPEG.

**Comment by nacho** [comment]
Adding @nirbheek and @jpakkane developers of meson which can answer that question

**Comment by nirbheek** [comment]
pkg-config has a flag `--msvc-syntax` that converts `-lfoo` to `foo.lib` and `-Lbar` to `/LIBPATH:bar`. Meson also does a more comprehensive translation internally for all arguments when building with the visual studio compiler.

**Comment by nacho** [comment]
I will give it a try next week with gvsbuild. Thanks.
