### ISSUE TITLE
HAVE_STDDEF_H and HAVE_STDLIB_H should not be in public header file

### ISSUE THREAD

**Issue by farindk** [libjpeg-turbo/libjpeg-turbo#298]
When including `jpeglib.h` in application code, there is a possible conflict of double macro definitions.
`jpeglib.h` includes `jconfig.h`, which defines autoconf variables like `HAVE_STDDEF_H` or `HAVE_STDLIB_H`.
When the application using libjpeg-turbo is also using autoconf, it will probably also define such variables, leading to double macro definition errors.

We have such an issue here
https://github.com/strukturag/libheif/issues/70
and the current workaround is to `#undef` these variables after including `jpeglib.h`, which is not nice.

The preferred way to handle this is to never include autoconf configuration variables in public header files. These should only be included in private, compiled code.

I understand that you also have configuration variables like `BITS_IN_JSAMPLE` in that config file that should be public. However, maybe the configuration then should be split into a public part and a private part.

**Comment by dcommander** [comment]
Refer to https://github.com/libjpeg-turbo/libjpeg-turbo/issues/280.  I have fixed the regression that caused those macro definitions to be incompatible with autotools, and you can find that fix in the 2.0.x stable pre-release builds (https://libjpeg-turbo.org/DeveloperInfo/PreReleases), but since those macros have existed in the libjpeg public header files for decades, I am not going to remove them.
