### ISSUE TITLE
difference between simd and non-simd when using -dct float

### ISSUE THREAD

**Issue by yunzhehi** [libjpeg-turbo/libjpeg-turbo#302]
when using -dct float, the simd and non-simd version give diffrent result. How can I get equivalent C version of asm code?

**Comment by dcommander** [comment]
This is expected, and documented:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/README.md#mathematical-compatibility

The floating point DCT/IDCT is non-deterministic if you're using C code, because it depends on the compiler settings and the CPU.  Also, the floating point DCT/IDCT is largely a legacy feature.   The ISLOW ("slow integer") DCT/IDCT (NOTE: the name is a relic of libjpeg-- it isn't actually slow in libjpeg-turbo) produces results that are very close to the floating point DCT/IDCT in terms of accuracy, and it's much faster.
