### ISSUE TITLE
'make test' failed if choose DCT precision to JDCT_FLOAT

### ISSUE THREAD

**Issue by huaqiangwang** [libjpeg-turbo/libjpeg-turbo#31]
Tested with latest release 1.4.2, select the DCT precision with type JDCT_FLOAT, like this:
 249
 250 #ifndef JDCT_DEFAULT            /* may be overridden in jconfig.h */
 251 #define JDCT_DEFAULT  JDCT_FLOAT
 252 #endif
 253 #ifndef JDCT_FASTEST            /* may be overridden in jconfig.h */
 254 #define JDCT_FASTEST  JDCT_FLOAT
 255 #endif

The  test failed.

**Comment by dcommander** [comment]
Yes, of course it does.  Please be aware that floating point DCT is a legacy feature.  It doesn't generally provide any more precision than can be provided by ISLOW, so it is supported only for backward compatibility with prior releases of libjpeg.  Please do not waste your time supporting that feature in new code.  Focus on ISLOW and IFAST.  libjpeg-turbo does not support changing JDCT_DEFAULT or JDCT_FASTEST.  Those are also legacy features from the 1990's.  In more recent years, software that uses the libjpeg API has come to expect that JDCT_FASTEST will always be set to JDCT_IFAST and JDCT_DEFAULT will always be set to JDCT_ISLOW, and software has come to expect to the bitwise output of those DCT algorithms will equal that of jpeg-6b.  We maintain those requirements in libjpeg-turbo to maintain compatibility with jpeg-6b.

There is very little point to accelerating the floating point DCT, because literally no one uses that feature anymore.
