### ISSUE TITLE
A new industry-standard JPEG compression/decompression API

### ISSUE THREAD

**Issue by kornelski** [libjpeg-turbo/libjpeg-turbo#313]
I have use-cases for getting data at almost every stage of JPEG decoding:

### Quantized coefficients access

* Lossless block-based transformation, e.g. application of EXIF rotation flag.

### Dequantized coefficients access

* Quick requantization to lower image quality on the fly, without full decode & re-encode. 
   Image optimization services have an option to serve lower-quality images to users on slow networks.
   The tricky part is that it's also desirable to subsample chroma if it wasn't subsampled already, and AFAIK that's not feasible to do purely in the DCT space, so it may be needed to get Y in DCT, Cb & Cr as pixels.

### Raw YCbCr pixels, with padding

* Full re-encoding at lower quality, without need to pad blocks again. 

### YCbCr pixels

* Conversion to other image formats using the same color space. Avoids lossy roundtrip through RGB.

### RGB pixels

* As usual

### Mixed raw DCT & pixels access

* To edit fragment of an image, e.g. to add a watermark or signature at the bottom, without introducing loss in areas that haven't changed.

----

Currently the old API combines and manages all these decoding stages itself. There is `jpeg_read_raw_data`, but not much beyond that.

But the decoding, at least conceptually, is effectively a pipeline with stages that filter the data:

`entropy to quantized DCT` &rarr; `DCT dequantization` &rarr; `IDCT` &rarr; `blocks to channels` &rarr; `YCbCr channels to RGB`

So it seems to me that at the lowest level, it'd make sense to make the library API a pipeline with stages you can add or remove.

This could enable new uses. For example, currently application of color profiles to JPEGs is problematic, because on 8-bit RGB it's low quality, but to get 12/16-bit RGB output you need a whole separate copy of the entire library.

With a pipeline solution, you would only need to expose a 12/16-bit version of a few stages. The user could even customize it further, e.g. `IDCT to 16-bit blocks` &rarr; `YCbCr to 16-bit RGB` &rarr; `apply color profile` &rarr; `16-bit blocks to 8-bit bitmap`. This would have great cache locality by applying color profiles per block, and still be able to have 8-bit output for overall low mem usage.

**Comment by dcommander** [comment]
Thank you for this.  I agree that access to every stage of the pipeline would be a nice feature to have.  However, I also question whether that is possible without changes to the underlying architecture, which are probably not in the cards.  Basically, my litmus test for a new API is:  can it be implemented without requiring any modifications to the SIMD extensions?  We already know that accessing the DCT coefficients is possible (currently accomplished with `jpeg_read_coefficients()`/`jpeg_write_coefficients()`), and accessing planar YCbCr data is possible (currently accomplished with `jpeg_read_raw_data()`/`jpeg_write_raw_data()`.)  My gut says that trying to support both 16-bit and 8-bit pixels with the same API isn't going to be possible without fundamentally restructuring the innards of the libjpeg code, which will be exceedingly difficult to do while maintaining backward API compatibility.  Also, I have some limited experience with a design similar to the one you propose, in the context of the TurboJPEG API.  As demonstrated in TJBench, you can use `tjDecompressToYUV2()` and `tjDecodeYUV()` in place of `tjDecompress2()`, and `tjCompressFromYUV()` and `tjEncodeYUV3()` in place of `tjCompress2()`.  However, there is a performance penalty for hijacking the pipeline in this manner.  The internal behavior of the libjpeg API is to fully process an MCU row through all pipeline stages before processing the next MCU row.  As you implied above, processing the full image through each stage of the pipeline is going to wreck cache locality, so the API would need to somehow allow block-based processing for each stage.  That would probably also be necessary in order to avoid architectural changes, since presumably (for performance reasons) we would want to provide access to the existing internal buffers rather than copying the data into other buffers, in case the calling program intends to modify the data and let processing continue.

**Comment by kornelski** [comment]
What are your goals for the new API?

Would you get rid of the main large multi-purpose `jpeg_(de)compress_struct` not just from the API, but also from the implementation?

**Comment by dcommander** [comment]
@kornelski I talked about this with Tom Lane back in 2013, and one of the things he always wanted to do with the libjpeg API was to eliminate the exposed structures, as was done with libpng.  Doing that would require introducing a handful of get/set functions-- basically what we did with mozjpeg, but the functions would also need to allow getting/setting existing structure members.  The idea is that, after a suitable deprecation period during which both the exposed structures and the get/set functions were provided, the structures could be made opaque.  Flash forward to 2019, and I no longer have much interest in a wholesale refactoring of the libjpeg API.  I think the footprint of that API within the open source community is just too large to support refactoring it.  There is too much legacy code out there that people would be loathe to change, so the reality is that a lot of people would do nothing during the deprecation period, and when the exposed structures were removed, they would keep using the old version of libjpeg-turbo as long as they could.  It could even (gulp) trigger a fork, which is the last thing I want (I've learned to never underestimate the resistance to change among software developers-- particularly enterprise software developers.)  As such, I think the more viable approach is to maintain the libjpeg API-- extend it using get/set functions if that becomes necessary, introduce new API functions for non-unwinding error handling, but don't fundamentally change the API.  So what we're really discussing here is a new API that non-legacy applications could use instead of the libjpeg API.  That new API would wrap the libjpeg API in much the same way that the TurboJPEG API does, but it need not be specific to libjpeg-turbo.  (It's worth noting that, prior to libjpeg-turbo, the TurboJPEG API wrapped the Intel Performance Primitives and Sun mediaLib and Pegasus PicTools and QuickTime.)

For me personally, the TurboJPEG API does everything I need it to do, and it already has the basic design that I'd like to see for a new API.  However, here is an incomplete list of things that I think it would need in order to become a viable general-purpose replacement for the libjpeg API:
1. The ability to do buffered I/O, i.e. the ability for users to allocate a fixed JPEG buffer for the compression/decompression pipeline and instruct the library to use no more memory than that.
2. The ability to compress or decompress only a subset of image rows at a time (also to save memory.)
3. Partial image decompression, i.e. the ability to decompress only a specific image region.
4. A general function for setting internal codec parameters, such as specifying the JPEG colorspace, enabling optimized Huffman coding, using arithmetic entropy coding, adding restart markers, etc.  This function could also be used to set the JPEG quality and subsampling, thus eliminating the need to specify those parameters in arguments.
6. A new API name.  "TurboJPEG" is too easily confused with "libjpeg-turbo", particularly for people whose native language uses a different adjective/noun order than English.  It's particularly problematic given that the TurboJPEG API library is called "libturbojpeg" on Un*x systems, which looks a lot like libjpeg-turbo.

I honestly think this new API could just be an extension of the existing TurboJPEG API, and given the TurboJPEG API's relatively low adoption rate compared to the libjpeg API, it would be a lot less painful to eliminate the TurboJPEG API in favor of the new API than to eliminate the libjpeg API.  I don't claim to be an API design expert, though, so that's why I really would like community buy-in-- particularly from those who might be more aware of best practices in this regard.

**Comment by dcommander** [comment]
I also echo your goals regarding getting access to the major stages in the pipeline.  It would be really nice if the compress/decompress functions were just convenience functions and it were possible to manually invoke every stage of the pipeline without significant performance penalty.  As stated above, in order to achieve this, the API would have to allow processing individual blocks or MCU rows rather than only the full image.

**Comment by lilith** [comment]
What level of funding are we talking about? My project [imageflow](https://github.com/imazen/imageflow) has been blocked on https://github.com/libjpeg-turbo/libjpeg-turbo/issues/311 for several years now and I'm rather desperate for a workaround. I can't abort a server process when a jpeg is invalid.

**Comment by dcommander** [comment]
This issue is describing a much broader long-term effort.  I think there are much easier ways of addressing #311 in one of the existing APIs.  I just need to understand your specific needs.  Please contact me offline to discuss:
https://libjpeg-turbo.org/About/Contact

**Comment by dcommander** [comment]
For posterity, I'm adding a note that the imageflow problem was resolved in https://github.com/imazen/imageflow/commit/d9cddf7617e39d77a7fc3fb62914a8d8a39f446e, so it is no longer blocking on this.

**Comment by dcommander** [comment]
As far as general API design, I would propose to take cues from the TurboJPEG Java API and make the new API more object-oriented.  Ideally, the flow could be something like:

```
cinstance = jpegInit(JPEG_COMPRESS);
if (loadSourceImageFromFile) {
  /* The image is not actually loaded until jpegCompress() or jpegLoad() is
   * called.
   */
  if (jpegSetSourceFile(cinstance, file) < 0) {
    printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
  }
  /* This optionally forces the file, or a subset thereof, to be loaded into
   * an intermediate buffer.  region and pixelFormat are optional.  If
   * unspecified, the intermediate buffer uses the most optimal pixel
   * configuration for the source file, to avoid pixel format conversion.
   * region = a struct specifying width, height, x, y, and pitch
   */
  if (jpegLoad(cinstance, region, pixelFormat) < 0) {
    printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
  }
} else {
  if (jpegSetSourceBuffer(cinstance, sourceBuf, region, pixelFormat) < 0) {
    printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
  }
}
printf("Source image: %d x %d, pitch %d, pixel format %d\n",
       jpegGet(cinstance, JPEG_WIDTH), jpegGet(cinstance, JPEG_HEIGHT),
       jpegGet(cinstance, JPEG_PITCH), jpegGet(cinstance, JPEG_PIXELFORMAT));
jpegSet(cinstance, JPEG_QUALITY, 95);
jpegSet(cinstance, JPEG_H_SAMP, 2);
jpegSet(cinstance, JPEG_V_SAMP, 1);
jpegSet(cinstance, JPEG_COLORSPACE, JPEG_YCbCr);
jpegSet(cinstance, JPEG_DCT, JPEG_ACCURATE);
if (saveJPEGImage) {
  if (jpegSetJPEGFile(cinstance, file) < 0) {
    printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
  }
} else if (!automaticBufferAllocation) {
  jpegBuf = malloc(jpegGet(cinstance, JPEG_MAX_BUFSIZE));
  jpegSetJPEGBuffer(cinstance, jpegBuf);
} /* else the JPEG buffer is automatically allocated and grows to the necessary
     size. */

/* region can optionally be used here to further restrict compression to a
 * subset of the image, even if the image is already a subset.  That allows
 * applications to easily load a source image into memory and compress multiple
 * JPEG images from different regions of the same source.
 */
if (jpegCompress(cinstance, region) < 0) {
  printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
}
jpegBuf = jpegGetJPEGBuffer(cinstance);
if (jpegBuf) {
  /* If saveJPEGImage is true, jpegBuf will be NULL. */
  doSomething(jpegBuf);
  if (!automaticBufferAllocation)
    free(jpegBuf);
}
```

```
dinstance = jpegInit(JPEG_DECOMPRESS);
if (loadJPEGImageFromFile) {
  /* The image is not actually loaded until jpegDecompress() is called. */
  if (jpegSetJPEGFile(dinstance, file) < 0) {
    printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
  }
} else {
  if (jpegSetJPEGBuffer(dinstance, jpegBuf) < 0) {
    printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
  }
}
if (jpegDecompressHeader(dinstance) < 0) {
  printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
}
printf("JPEG image: %d x %d, colorspace %d subsampling %d:%d\n",
       jpegGet(dinstance, JPEG_WIDTH), jpegGet(dinstance, JPEG_HEIGHT),
       jpegGet(dinstance, JPEG_COLORSPACE), jpegGet(dinstance, JPEG_H_SAMP),
       jpegGet(dinstance, JPEG_V_SAMP));
jpegSet(dinstance, JPEG_SCALE_NUM, 1);
jpegSet(dinstance, JPEG_SCALE_DENOM, 2);
if (saveOutputImage) {
  if (jpegSetOutputFile(dinstance, file, JPEG_BMP) < 0) {
    printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
  }
} else if (!automaticBufferAllocation) {
  outBuf = malloc(jpegGet(dinstance, JPEG_WIDTH) *
                  jpegGet(dinstance, JPEG_HEIGHT) * 3);
  if (jpegSetOutputBuffer(dinstance, outBuf, region, pixelFormat) < 0) {
    printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
  }
} /* else the output buffer is automatically allocated. */

if (jpegDecompress(dinstance, region) < 0) {
  printf("%s (type %d)\n", jpegGetErrorStr(), jpegGetErrorType());  exit(1);
}
outBuf = jpegGetOutputBuffer(dinstance);
if (outBuf) {
  /* If saveOutputImage is true, outBuf will be NULL. */
  doSomething(outBuf);
  if (!automaticBufferAllocation)
    free(outBuf);
}
```

Shortcutting the pipeline to avoid color conversion could be accomplished by providing additional `jpegSetSourceBufferYUV()` and `jpegSetOutputBufferYUV()` functions.  Additional `jpegEncode()` and `jpegDecode()` functions could also be provided, in order to perform only color conversion.

**Comment by dcommander** [comment]
I am about to push a wholesale refactoring of the TurboJPEG API (#517), which is an incremental step toward this goal.  It has taken its toll on me, however.  I had about 80 hours of funding to work with, but even though I severely scaled back my ambitions with regard to the TurboJPEG 3 overhaul, it took me more than 160 hours to finish that project.  Borrowing that much labor against future funding has left me with little room to perform any other significant libjpeg-turbo enhancements any time soon.  (Irrespective of funding, I need to get back to my other OSS projects and de-focus from libjpeg-turbo for a while.)  Historically, it is usually the case that the amount of cost I have to eat on a libjpeg-turbo enhancement is proportional to the size of the enhancement.  Because libjpeg-turbo is the world's most popular JPEG library, it's an ISO reference implementation, and it's built upon a 30-year-old somewhat fragile API and architecture, it's very difficult to make deep modifications to the code base without breaking a lot of applications.  That makes deep modifications hard to fund and even harder to estimate.

I have to be honest with myself and admit that this proposed new API is probably too big of a project for my business model as an independent OSS developer.  No one is going to pay me hourly to do it, and even if they did, I could see it taking the better part of a year of full-time labor to get it right.  It would be impossible to estimate the labor up front.  I no longer have the appetite for that kind of massive undertaking with respect to libjpeg-turbo.  I am open to a variety of long-term paths for libjpeg-turbo, including corporate acquisition, and a project such as this probably wouldn't be feasible absent such an acquisition.  It needs more than just one guy working on it part-time in his spare bedroom on a shoestring budget.

That being said, I am certainly open to straightforward enhancements to the TurboJPEG API that would get us closer to the overall goal.  TurboJPEG 3 should be a lot more extensible than prior versions of that API.

**Comment by dcommander** [comment]
Created #646 to discuss potential future improvements to the TurboJPEG API, which should be able to subsume most of the features mentioned above.
