### ISSUE TITLE
Use of maven central

### ISSUE THREAD

**Issue by rleigh-codelibre** [libjpeg-turbo/libjpeg-turbo#315]
A bit related to your comments in https://github.com/libjpeg-turbo/libjpeg-turbo/issues/160.

Have you considered uploading the jar to https://search.maven.org/ so that it's easily consumable by java projects which want to make use of it.  This is, for better or worse, the standard way of doing this in Java nowadays, and works with all build systems be it ant, ivy, maven, gradle or others.  Not being on maven central makes it difficult, if not impossible, for many projects to be able to use a third-party dependency or not.  You mentioned not supporting it in the above issue; what have been the historical reasons for not supporting it?  I can't see any licensing barriers to doing so.

I've recently found it necessary to start doing this myself, and had to go through the process of registering and getting upload rights, which turned out to be pretty easy.  I also had to get to grips with a [gradle build](https://gitlab.com/codelibre/ome-model/blob/master/ome-xml/build.gradle) to automate the upload.  But now making a new release is as simple as tagging and typing in my GPG passphrase.

If this was of interest, I'd be happy to contribute a gradle build for the Java part of turbojpeg.

Regards,
Roger

**Comment by dcommander** [comment]
"All build systems" except, well, the one I actually use.  The libjpeg-turbo JAR is consumed by another project I maintain (TurboVNC), and that project uses CMake and treats the JAR, from a build point of view, similarly to any other framework against which an application might link.  As such, I have no personal need for Maven, and since I have no personal need for it, I have no personal time to devote to it.  Even if you contributed a patch, it would still take time and effort for me to integrate and test it, as well as time and effort to maintain the additional distribution platform (I don't check any code into libjpeg-turbo unless I can personally vouch for it.)  I have no interest in learning Gradle or other technologies I don't personally need, unless there is a strong business case for doing so or unless someone is paying for me to do so.  This falls under the category of "libjpeg-turbo really needs a general sponsor", i.e. a company who will pay for general-interest projects like this.  Otherwise, barring any direct funded development or general sponsorship, the only way that I can monetize my labor on libjpeg-turbo is by justifying it in the context of my downstream projects, which pay most of the bills.  I estimate that I've spent the equivalent of US$150,000-$200,000 in pro bono labor on libjpeg-turbo since founding it in 2010.  I just can't afford to do that anymore.  Barring the emergence of a "General Fund" for this project, any new features that I can't justify in the context of my downstream projects will need to be funded.

Barring any of that, your best approach is probably to upload the JAR to Maven yourself.

**Comment by dcommander** [comment]
I accept your technological argument, but please allow me to elaborate on my business argument (sorry for the tome-- I take every opportunity I can to publicly explain this, in case some benevolent corporation stumbles upon it and is thus encouraged to become a sponsor):

I am an independent software developer, and the bulk of my income comes from patronage and funded development on this project, VirtualGL, and TurboVNC.  As such, if I spend a week on something and don't get paid for it, that's a week in which I don't have money for rent or other basic necessities.  I factor some pro bono labor into the rates I charge for open source development, but if a significant amount of time has passed without any funded development, then I have no more overhead left in order to pursue pro bono projects.  Furthermore, I have to be extremely strategic about how and when I devote my time to pro bono projects.  In addition to ensuring that I only do so when I have sufficient cash reserves (which is unfortunately not the case right now), I also have to ensure that I'm devoting that time toward projects that will be of long-term strategic benefit-- i.e. that will drive more business my way.  That means focusing on features that might attract future funded development, and ensuring that I don't give away so much free milk that no one wants to buy the cow.

I've done things this way for nearly 10 years because it's the most effective way to develop these projects.  It frees me from having to waste time on corporate administrivia and pet projects that are of no benefit to the community.  (During my four years at Sun Microsystems, prior to my stint as an independent developer, I did way too much of both.  Probably half of my time was spent making things work on their obsolete SPARC graphics workstations and Solaris 8-9 releases.)  As such, I can spend almost all of my time putting hand to code in a meaningful way.  Since these projects are free of any one organization's agenda, I can work on anything that anyone cares enough to pay me for.  (That is, BTW, the only reason why libjpeg-turbo supports SIMD acceleration on so many platforms.)  It is, to quote Louis Winthorpe III from "Trading Places", the "last bastion of pure capitalism left on Earth."  That business model ensures that my open source projects remain free of cruft, because ultimately there is someone out there with a vested financial interest in every single major feature that I've implemented in the past 10 years.  (That includes, BTW, the TurboJPEG Java interface, which was funded both directly by a startup and indirectly via corporate sponsors of the TurboVNC Viewer.)

If an organization wants a feature badly enough, then they have to pay for that feature to be developed or integrated in a manner that maintains the existing high quality standards (including performance) of the libjpeg-turbo code base.  As such, high quality standards are baked into the business model, since the projects are effectively treated like products, even though they're provided free of charge.  Ultimately, all open source projects that are worth anything are paid for by someone.  In this case, I'm just making that process 100% transparent.  (It is sort of like a co-op model, whereby the users are also the investors.)  By acting as gatekeeper, I can ensure that the needs of my (largely corporate) sponsors and the needs of the community are balanced.  For the sponsors, they benefit from being able to pay a few hundred or thousand dollars here and there to make the product do what they need, rather than investing millions in the development of a new product.  They also benefit from the security of being able to freely use and modify the code themselves for perpetuity, should anything happen to me.  They also benefit from others in the community continuously testing libjpeg-turbo and rooting out security issues and other bugs.  For the community, they benefit from being able to freely use product features that someone else paid for, and they benefit from the fact that every new feature is developed to high quality standards and thoroughly tested.  For me, I benefit from remaining self-employed and not chained to a desk, and since I have retained copyright on all of the open source IP I've generated over the past 10 years, I can freely move that code between differently-licensed projects if I need to (including licensing the code for proprietary projects.)  It's a win-win-win, but the downside is two-fold:

1. The business model absolutely relies on a minimum amount of funded development every year.  Otherwise, development stagnates.  Unfortunately, funded development on my projects has decreased in the past two years, in part because of the less favorable exchange rate of the U.S. dollar compared to the Euro and Australian dollar (U.S. companies unfortunately tend to be paranoid of open source projects, in part because of 20-year-old Microsoft FUD, although I do see that trend slowly reversing.)  I was only able to keep libjpeg-turbo going through 2017 because of a grant from Mozilla, which funded the work needed to complete the 2.0 release.  Unfortunately, there has been zero additional funded development on libjpeg-turbo this year, and as such, I have had to divert my focus to other projects that are receiving more corporate interest at the moment.

2. The "bazaar" model of development is a poor fit for my business model.  Ultimately, it takes me less time to develop new features than it would take anyone else, since I have the most experience with the code.  So ultimately corporations spend less money paying me to do the work than they would spend paying their own staff.  However, since they have to pay their own staff anyhow, there's always a temptation for them to do the work themselves, thus depriving me of the revenue (and often depriving the community of high-quality code.)  The worst-case scenario (which unfortunately often happens) is that a corporation pays some offshore developer to hack something together, that offshore developer submits the code as a PR, and I can't integrate it because it would take 50 hours of pro bono labor to clean it up.  It's really hard to make corporations understand that they sometimes have to pay me to integrate code that they're already paid someone else to develop, but that's unfortunately the way this works, and it's the only way I can maintain the high quality standards of libjpeg-turbo.  That's another reason why I have to act as gatekeeper-- to ensure that I don't get undercut.  Basically, if you want to get anything done with the world's most popular JPEG codec (which is also being considered for adoption as an ISO standard), you have to go through me.

    As such, the argument that uploading to Maven would increase the number of contributors doesn't really resonate.  Historically, that kind of exposure for this project has resulted in more people asking me to do something for nothing.  That's why I really need a general sponsor.  Unfortunately, this Maven project will likely not happen without one, because it is too mundane for anyone to be willing to pay for it, and it is not the sort of project that will drive more paying work than pro bono work my way.
