### ISSUE TITLE
How can we compile it with GPU support

### ISSUE THREAD

**Issue by qli-aa** [libjpeg-turbo/libjpeg-turbo#32]
I saw there is nvcc in configure file, does that mean we can use CUDA to compile it, then it will support GPU ?

I try, but failed, is there any guide ?

**Comment by dcommander** [comment]
The reference to nvcc in configure is apparently something that autoconf adds automatically.  libjpeg-turbo does not support CUDA or OpenCL or any other GPU-based SIMD technology, and it is doubtful that it ever will.  Significant research has been done into how to make that happen, and a prominent CPU company was even sponsoring the project for a time.  In addition to a general clash of project management styles between The libjpeg-turbo Project and the developers that the company hired to write the OpenCL extension code (in short, they took years to produce results, they would go dark for months at a time, I was never able to reproduce their results, and it finally came to light that they weren't using the correct benchmarking methodology to begin with), the project also failed for some fundamental technological reasons (refer to https://sourceforge.net/p/libjpeg-turbo/patches/40 for the gorey details):

Summary of technological issues:

- Huffman encoding/decoding is not easily parallelizable, and since that accounts for 40-50% of execution time, it is necessary to pipeline Huffman coding with the rest of the compression/decompression algorithms.  That necessitates encoding/decoding the entire image ahead of time, even if the application ultimately doesn't request it.  This is not just an awkward fit for the libjpeg API, but it also breaks the custom source/destination manager architecture of said API.

- Furthermore, shipping the data down to the GPU and reading it back has a lot of overhead associated with it, which meant that it was necessary to use an integrated CPU/GPU in order to get a decent speedup.  Even with that stipulation, it was still necessary to compress or decompress the entire image all at once to hide the overhead.  Also not a good fit for the fine-grained libjpeg API.

Even when all of those limitations were taken into account, I was still unable to reproduce any significant speedup, and on discrete GPUs (which didn't support the afore-mentioned pipelining trick), the performance slowed down by 3X.  Nope.

I think that GPU-based compression/decompression is really more of something that needs to be the province of a full-frame API, such as a video codec.  The libjpeg API is just too fine-grained to support it in any sane manner.
