### ISSUE TITLE
Slow to decode a corrupted jpeg file

### ISSUE THREAD

**Issue by HongxuChen** [libjpeg-turbo/libjpeg-turbo#328]
This was originally observed from [a cwebp issue](https://bugs.chromium.org/p/webp/issues/detail?id=416).

For a corrupted jpeg file with incorrect pixel information, the decoding can be extremely slow. For example, 
![h01.jpeg](https://user-images.githubusercontent.com/843267/52468066-86661e80-2bc2-11e9-8d0f-1b0e6677e1d2.jpeg)
h01.jpeg only has 118 bytes, however the claimed pixel is 62994x65284. Although libjpeg seems to have a validation for the upper bound, it's not enough. As of e2442e0, the release version of djpeg may still take a long time to process deconding.
```
time ./libjpeg-turbo/BUILD/djpeg-static -gif -outfile /tmp/test.gif h01.jpeg
Corrupt JPEG data: 4 extraneous bytes before marker 0xda
                                                    
real    21.68s                                               
user    18.84s                                              
sys     2.74s

# generated gif file is around 4.4G
```
IMO, it's better to have a check for the file size when it determines the image has been corrupted, and refuses to decode in such a case.

**Comment by dcommander** [comment]
This seems to be closely related to LJT-01-004 described in https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf.  That class of problem is a by-product of a useful feature in the JPEG standard-- allowing only a few bytes in the compressed image to represent long runs of zeroes in the uncompressed image.  As such, I don't really know how to work around the issue, other than to suggest that applications wishing to avoid it should either (a) treat libjpeg warnings as fatal or (b) set a reasonable limit on the image width and height.  As described in the aforementioned report, even treating libjpeg warnings as fatal doesn't always work around the issue, since it is possible to create a valid JPEG image (albeit much larger than 100 bytes-- more like 2 MB) that will exhibit the issue and produce no warnings.  libjpeg v6b and v9c exhibit the issue as well, if a113506d175d03ae0e40965c3d3d21a5d561e119 is applied to them.  In this case, setting `cinfo->mem->max_memory_to_use` doesn't guard against the issue (max_memory_to_use isn't effective unless virtual arrays are needed in order to decompress the image.)

Refer also to #249.
