### ISSUE TITLE
NASM/YASM dependency for libjpeg-turbo

### ISSUE THREAD

**Issue by mattsarett** [libjpeg-turbo/libjpeg-turbo#35]
DRC, can you a little provide a little background libjpeg-turbo's NASM/YASM dependency?

I know the basics - this tool is required to compile the x86 and x86-64 assembly code in libjpeg-turbo.  I'm guessing because the assembly code uses a NASM specific syntax?

Within Android, there is pretty strong opposition to adding yet another assembler/compiler tool.  So much so, that we'd rather rewrite the assembly to be compliant with gcc/clang.

Do you know if there is any reason why the code couldn't be rewritten to be compiled by standard tools?  If we could provide some manpower from Intel to rewrite the code, would you be interested in accepting these contributions?

**Comment by dcommander** [comment]
Why would you need to use NASM for Android?  NASM is only required for the MMX, SSE2, and (soon) AVX2 SIMD extensions, but the ARM NEON stuff is all written in GCC assembly.

The reasons why NASM is used are both historical and technical.

Historical:  libjpeg-turbo's x86 SIMD extensions were inherited from Miyasaka-san, the developer of libjpeg/SIMD, and the 32-bit versions of those have only a few changes relative to his code (the 64-bit versions were developed by Pierre Ossman and myself, as part of the TigerVNC project, and those are a more-or-less direct port of the 32-bit SIMD code.)

Technical:  when dealing with those instruction sets, efficient register allocation is critical to performance, since there are only 8 or 16 registers available.  This is why using intrinsics wouldn't be a good idea, and using GCC assembly wouldn't be a good idea because it would make the solution difficult (perhaps impossible) to build in Visual Studio on Windows.

That's the issue with using terms like "standard tools."  What is standard for you might not be standard for others.  Windows developers aren't going to want to much with installing a MinGW environment just so they can build some assembly code for libjpeg-turbo.

**Comment by mattsarett** [comment]
*Why would you need to use NASM for Android? NASM is only required for the MMX, SSE2, and (soon) AVX2 SIMD extensions, but the ARM NEON stuff is all written in GCC assembly.*

While many Android devices are ARM, Android runs on ARM, mips, and x86/x86-64.

*The reasons why NASM is used are both historical and technical.*

Thanks for sharing your reasoning though.  That should help inform us on how to move forward.

**Comment by dcommander** [comment]
I am always receptive to new ideas, but in this case, I don't see a way forward with anything other than NASM on x86.  That may change in the future, however.
