### ISSUE TITLE
Question: Naming of language bindings and static linking

### ISSUE THREAD

**Issue by jfolz** [libjpeg-turbo/libjpeg-turbo#358]
Newer versions of libturbojpeg are significantly faster on modern hardware than whatever many Linux distributions offer. Obtaining turbojpeg separately and compiling Pillow, OpenCV etc. from source is too cumbersome, and they are slower than they need to be anyways. So I made this thin and fast Python binding: https://gitlab.com/jfolz/turbojpeg

It seems to to its jobs well enough so I would like to put it on [PyPI](https://pypi.org/).
Two questions then:
1. I want to ask permission to use the "turbojpeg" name for my library. It's not creative at all and doesn't even have "py" in it, but it does describe very well what it does and [PyTurboJPEG](https://pypi.org/project/PyTurboJPEG/) is already taken.
1. Is it OK if my library statically links against libturbojpeg? It's available under MIT license and it was just easier to set up this way.

**Comment by dcommander** [comment]
Just to clarify:

* libjpeg-turbo is the name of our project.
* TurboJPEG is one of two APIs that we provide (the other being the industry-standard libjpeg API, which is compatible with older releases of the IJG's software.  The IJG's software is commonly referred to as "libjpeg", but that is not its official name.)
* The performance of the two APIs is similar, as long as they are used to perform similar operations.

"libturbojpeg" is too easily confused with "libjpeg-turbo", so I generally refer to the libraries as the "libjpeg API library" and the "TurboJPEG API library", both of which are provided by libjpeg-turbo (our project.)

I don't understand your statement that the TurboJPEG API library is faster than what many Linux distros offer.  Most Linux distros are shipping libjpeg-turbo these days, although few of them ship the TurboJPEG API.  The TurboJPEG API is just a wrapper for the libjpeg API, so if OpenCV and other packages are not achieving peak performance with the libjpeg API, then it's probably because they aren't taking advantage of our colorspace extensions or because they are otherwise using the API sub-optimally.  I vaguely recall that OpenCV specifically was doing its own RGB conversion, which was necessary when using libjpeg, but that kills a lot of the speedup that would otherwise be realized from using libjpeg-turbo.

I don't care if you link statically with the TurboJPEG API library, but I cannot grant you permission to use the "TurboJPEG" name in its pure form.  PyTurboJPEG is OK, because it's clear from the name that that is a Python implementation of the TurboJPEG API.  But calling your wrapper "TurboJPEG" would be nonsensical and confusing-- TurboJPEG wraps TurboJPEG?  That would only further confuse an already confusing naming convention.  Please at least prefix it with something.

**Comment by jfolz** [comment]
Thanks for the reply, I'll think of a more appropriate name.

For posterity: At least Debian (and its derivatives like Ubuntu) ships with some version of libjpeg-turbo on release that is never updated during the support period. Even if that version was current at some point, it will be outdated after some time.

**Comment by dcommander** [comment]
That is typical of most Linux distributions, but other than adding AVX2 support in libjpeg-turbo 2.0, there haven't been a lot of changes to the x86 performance of libjpeg-turbo since the earlier releases.  You would probably get about the same performance with libjpeg-turbo 1.2 and 2.0 on an x86 machine that didn't support AVX2.

**Comment by dcommander** [comment]
(assuming baseline compression/decompression.  One thing that did change in 2.0 was the addition of SSE2-accelerated progressive JPEG compression.)
