### ISSUE TITLE
Is there anyway to make install without having root access?

### ISSUE THREAD

**Issue by phcao101** [libjpeg-turbo/libjpeg-turbo#362]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes, although this is more of an unorthodox problem unique to my situation; not quite a bug.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
Hi, I was wondering if there is anyway to make install the software without having root access. Basically, I'm currently using a server remotely with PuTTY, and I don't have root access, and "sudo" is disabled. 

When I run:

./configure && make install 

I get this error at the end:

 /bin/mkdir -p '/opt/libjpeg-turbo/lib64'
/bin/mkdir: cannot create directory ‘/opt/libjpeg-turbo’: Permission denied
make[2]: *** [install-libLTLIBRARIES] Error 1
make[2]: Leaving directory `/home/knight/cmerrick/Desktop/paul/libjpeg-turbo-1.4.2'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/knight/cmerrick/Desktop/paul/libjpeg-turbo-1.4.2'
make: *** [install-recursive] Error 1

I think the issue is that I need to make a directory within /opt. However, to make a directory within /opt I need root access. Is there anyway for me to perhaps make the necessary directory elsewhere? Or is there any work around here? 

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Currently using linux

**I'm very new to coding. If there's any additional information I can provide that would be helpful, please let me know. Thanks so much in advance!!

**Comment by dcommander** [comment]
The fact that you are using a configure script tells me that you are building libjpeg-turbo 1.5.x, which is obsolete.  I strongly recommend upgrading to the latest libjpeg-turbo release.  That being said, this answer applies to both 1.5.x and 2.0.x.  GNU Make has a feature whereby you can override the installation path without re-configuring or rebuilding the code.  Simply pass `DESTDIR={dir}` to `make` when installing.  Example:

```
make DESTDIR=~ install
```

will install libjpeg-turbo under **~/opt/libjpeg-turbo** rather than under **/opt/libjpeg-turbo**.  Such is true of most Un*x open source projects, BTW.  This isn't specific to ours (refer to https://www.gnu.org/software/make/manual/html_node/DESTDIR.html).

Also, this isn't a bug.  In the future, please do not file such questions as bug reports.  Click on "Open a regular issue" instead.  Thanks.
