### ISSUE TITLE
Trouble building package

### ISSUE THREAD

**Issue by phcao101** [libjpeg-turbo/libjpeg-turbo#363]
Hi,

I've been trying to build libjpeg-turbo 2.0.2

I'm currently using a server remotely with PuTTY, and I don't have root access, and "sudo" is disabled. 

I was advised to pass DESTDIR={dir} to make when installing but when I ran:

make DESTDIR=~ install

I got this error:

make: *** No rule to make target `install'.  Stop.

Can someone please help? 

**I'm very new to coding. If there's any additional information I can provide that would be helpful, please let me know. Thanks so much in advance!!

**Comment by dcommander** [comment]
A brief pointer on GitHub etiquette:  to continue a conversation, i.e. to report whether advice I gave you worked, please post a new comment under the old issue (#362) rather than filing a new issue.

I have no idea why the "install" target isn't available in your build, but I can only imagine that it's due to the build not being configured correctly.  Please read BUILDING.md in the source tree for instructions.

**Comment by phcao101** [comment]
Sorry about that, and thanks. I'll read up on that right now!
