### ISSUE TITLE
cannot find file io.h only with cmake

### ISSUE THREAD

**Issue by rashadkm** [libjpeg-turbo/libjpeg-turbo#37]
I am getting error cannot find include io.h when only using cmake build in any liunx system.

If this is a windows only stuff shouldn't it be wrapped around and ifdef WIN32 ?

sorry for not attaching the exact error message now. It was only my other system.
steps to reproduce are:
download libjpeg-turbo-1.4.1.tar.gz from sourceforge
mkdir build && cd build
cmake /path/to/libjpeg-turbo

**Comment by dcommander** [comment]
CMake is not a supported build system on platforms other than Windows.  Refer to https://github.com/libjpeg-turbo/libjpeg-turbo/pull/29

**Comment by rashadkm** [comment]
Okay. Thanks for the information. 

So cmake will not be maintained for *nixes by you in near future unless the funding situation changes. Also that any PR related to cmake or any volunteer effort to maintain cmake support will be rejected.

**Comment by dcommander** [comment]
Yes, that is correct.  I won't maintain two build systems for the same platform.  I don't have any objections to supporting CMake on Un\*x.  I much prefer CMake over autotools.  It's just that it would require a lot of work to make sure all of the existing autotools functionality is covered, and to make sure that the major O/S vendors are OK with that change (autotools is the standard for system libraries on Linux, so using CMake would be slightly unorthodox.)  This is work that probably isn't going to be done correctly unless I do it myself, because it will rely on a lot of the knowledge I have gained (both technical as well as political) from 5 years of working with this code base and its consumers.

**Comment by rashadkm** [comment]
I understand you are the most expert in libjpeg. And you know every corner of the code in this library. fine.. This is good for the project. 

Now cmake is not supported.
if someone provides a support that will only affect cmake. 
They will not fix something inside autotools. so co-existence is fine. 
package maintainers continue to use autotools and there won't be no harm. 

My only point is it is better for any other thirdparty project using libjpeg-turbo to use the upstream rather than keeping a fork with cmake lists.txt and syncing their fork now and then. IMHO, you don't have to be learn each and every function of what libjpeg is about just to write cmakelists.txt. 

if there is problem in cmake and you are providing support because of funding that is fine. No complaints. If someone is willing to give away their time to fix cmake why is it a big no always?

you can  argue make changes break autoconf, windows, or maybe even mess up the whole library. I don't know. I am not that experience to deal with libjpeg politically as you have done.

**Comment by dcommander** [comment]
I have addressed all of those arguments in https://github.com/libjpeg-turbo/libjpeg-turbo/pull/29.  You are arguing the same points that others have already argued, and I have already explained fully why I disagree with those arguments.  My decision is final.

**Comment by rashadkm** [comment]
you won't add support and also won't accept anyone else's work no matter the code quality. Wel, Good to know.

**Comment by dcommander** [comment]
Please do not interpret my comment as arrogance.  It's just that there are a lot of things I have to think about as the maintainer of this project that downstream users don't have to think about.  Every time someone has submitted a CMake build system patch, it has been constructed in such a way that it works for them on a narrowly-defined set of platforms, but in order for me to adopt it, I would have to contribute a great deal of my own time and energy to making it work properly on all platforms.  I'm not willing to do that work for free, nor should anyone expect me to.  Not many people are going to have access to all of the platforms that would need to be tested.  Not many people are going to have the unique knowledge of all of those build tools.  If someone did magically contribute a patch that was carefully developed and well tested on *all* supported platforms, then yes, I would accept it, although it would still take time to work through the political ramifications.  But history suggests that such a patch will never materialize.  Even the most carefully developed patches usually still require some work on my part to integrate and tweak.  It's the nature of the game.  No one can be expected to know as much as the guy who's been maintaining the product for 5 years and similar products for a decade before that.

**Comment by rashadkm** [comment]
Sorry if I sounds rude in my last comment. I am okay, I can use autotools with linux and I respect the work you do for the libjpeg-turbo. I completely agree that once you start maintaining or put out a sincere  effort on development a lot of unpaid work happens. I mean a lot lot. And worst part is if funding is stopped for some time you get frustrated. This is natural. I was bit reluctant to fork it for the cmake fixes when I opened this issue. And the idea of keeping the fork forever to use cmake is a sad for the users and in one way or other for libjpeg-turbo( too many forks which various cmake fixes).

This is my last comment on this issue.

**Comment by dcommander** [comment]
OK, no problem.  I do understand that this can be an issue for projects that choose to include libjpeg-turbo in-tree, but that isn't really the common case.  However, some prominent projects like Firefox include libjpeg-turbo in-tree, so you aren't alone here.  The basic objection I have to multiple build systems on the same platform is:  where do I draw the line?  What if someone wants me to support qmake or Ant or whatnot?  Yeah, they may be willing to do the work up front to add support for that system, but ultimately I'm going to be the one who maintains it going forward, and that means I have to make an effort to test both systems each time I change something, even if that something only affects one platform.  After many years of doing this, I have a good sense of how to design stability into the product, such that-- to the greatest extent possible-- breakages in both the build system and the library itself will be detected automatically.  Having multiple build systems undercuts that.  It may work for one person, but if it doesn't at least attempt to work for everyone, then I'm going to get a lot of support requests from people saying "why doesn't CMake work on ARM" or "why doesn't CMake work on MIPS" or "why doesn't CMake work on Solaris 10."  It's better to just say, unambiguously, that CMake isn't supported on any Un\*x platform at all.  If it helps, just pretend as if we don't have a CMakeLists.txt file in our source tree, because this answer would be the same answer I would give to someone who offered to add Ant or QMake support to the product.

**Comment by dcommander** [comment]
Cross-platform CMake build system is now available in dev.  Please test.
