### ISSUE TITLE
jpegtran.1: mention which corner X and Y are measured from

### ISSUE THREAD

**Issue by jidanni** [libjpeg-turbo/libjpeg-turbo#371]
jpegtran.1 says
```
crop WxH+X+Y
Crop the image to a rectangular region of width W and height H, starting at
point X,Y. 
```
but neglects mentioning which corner X and Y are measured from.

**Comment by dcommander** [comment]
That documentation is straight from libjpeg.  I didn't write it.  By convention, JPEG files are written in top-down scanline order and have been for nearly 30 years, so since jpegtran is performing cropping in frequency space, 0, 0 must be the top left.

I'll reiterate what I said in response to your other issue, which is that libjpeg-turbo isn't a comprehensive image processing package.  It's a codec library intended for developers.  If you want more user-friendly and powerful image processing tools, then those are available in ImageMagick or commercial solutions.

**Comment by jidanni** [comment]
Fine but where do I tell them to fix their man page?
https://jpegclub.org/reference/contact/ ?
I guessed that it referred to the same coordinates as GIMP, but had to reverse-engineer it by trial and error to find out.

**Comment by dcommander** [comment]
I can think of only a few cases in computer graphics in which the coordinate system is bottom-up rather than top-down (OpenGL and Windows BMP are the first two that come to mind.)  Thus, if an origin isn't specified, it's usually safe to assume that it's at the top left, because televisions and CRTs historically scanned left-to-right and top-to-bottom.  That is also the convention for digital video.  Since JPEG is a top-down image format (libjpeg.txt says as much), it makes sense that a lossless cropping feature for JPEG images would adhere to the top-down scanning order that is standard for those images.

It's impossible to develop a software package (particularly a low-level software package like this one) whose usage is obvious to everyone.  jpegtran is more or less a proof of concept for lossless cropping of JPEG images in frequency space.

As far as contacting the IJG, try jpeg-info@jpegclub.org.  If Guido decides to fix the man page in libjpeg, I can adopt his fix, but since he wrote that feature, I'm not particularly interested in re-documenting it.
