### ISSUE TITLE
[Help Wanted] build project with djava=1 failed 

### ISSUE THREAD

**Issue by fabricezhang** [libjpeg-turbo/libjpeg-turbo#375]
hi, i've build android project with ndk successfully, but when I try to build with java enable, I got the error messages below, I've tried use java8 or set PATH manually, but still face the same error. Does anybody met this error before ?  Please give some tip, thanks a lot!

CMake Error at /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY
  JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)

cmake version 3.14.3
java version 12

**Comment by dcommander** [comment]
I assume you're using macOS and CMake from HomeBrew, because of the **/usr/local/Cellar** path.  The **FindJNI.cmake** script sometimes has difficulty finding the JNI headers on macOS.  The easiest workaround is: prior to invoking CMake, set the `JAVA_HOME` environment variable to the directory containing **include/jni.h**.

**Comment by fabricezhang** [comment]
> I assume you're using macOS and CMake from HomeBrew, because of the **/usr/local/Cellar** path. The **FindJNI.cmake** script sometimes has difficulty finding the JNI headers on macOS. The easiest workaround is: prior to invoking CMake, set the `JAVA_HOME` environment variable to the directory containing **include/jni.h**.

It works , thank you!
