### ISSUE TITLE
possible infinite loop when using djpeg

### ISSUE THREAD

**Issue by houjingyi233** [libjpeg-turbo/libjpeg-turbo#393]
I think I might encountered an infinite loop problem.
git clone https://github.com/libjpeg-turbo/libjpeg-turbo
cd libjpeg-turbo
cmake -G"Unix Makefiles"
make
./djpeg -grayscale sample
The program do the output and never stop.
[sample.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/3958811/sample.zip)

**Comment by dcommander** [comment]
This is a variation of the same sort of issue described in this report:
https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf

If you generate a bogus JPEG image with a valid header (in this case, indicating that the image contains > 4 billion pixels) but with junk image data, then libjpeg and libjpeg-turbo will dutifully try to decompress that image until they find a problem.  In this case, the problem is reported as a libjpeg API warning:

```
Corrupt JPEG data: found marker 0xd9 instead of RST6
```

and the default libjpeg API behavior is to treat warnings as non-fatal.  Refer to the aforementioned report for an example of how to change that behavior in the libjpeg API (the TurboJPEG API provides a flag for doing so.)  Generally, if the program is not mission-critical-- i.e. if it is something like an interactive offline image viewer/editor, which will never be exposed to arbitrary data attacks-- then treating libjpeg warnings as non-fatal is a good idea, because it will allow the maximum number of pixels from a partially-corrupted JPEG image to be displayed.  However, if the program is mission-critical-- if it is something like a web browser or other infrastructure that is exposed to arbitrary data attacks-- then the program should take steps to avoid this type of format exploit.  Those steps are:

1. Make libjpeg API warnings fatal.
2. Limit the maximum number of progressive scans to a reasonable number.
3. Limit the maximum libjpeg API memory usage to a reasonable percentage of available memory.

(1) avoids the problem caused by this specific dataset.  Note that it isn't an infinite loop.  libjpeg-turbo is simply trying to write a 16 GB output file, which takes some time.  Since libjpeg API warnings are being ignored, it's a case of garbage in, garbage out.  The 16 GB output file will contain junk data because the input file contains junk data.  Treating libjpeg API warnings as fatal simply catches that problem before the output file can be written.
