### ISSUE TITLE
possible bug report

### ISSUE THREAD

**Issue by luca2125** [libjpeg-turbo/libjpeg-turbo#397]
[jpeg.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/4023843/jpeg.zip)

Deat libjpeg turbo,

First of all happy new year !!

I notify you a strange situation (I don’t known if is a bug).

I have download from github the project “darkplaces” writed in “quake c” and I open it in Visual Studio 2012.

This project need the library libjpeg.dll loaded dynamically at runtime.

Without this library the project don’t load the texture in jpeg.

I have copied the files:

jpeg62.dll (that I have rename in libjpeg.dll)
turbojpeg.dll

in the main folder where there is “darkplaces-sdl.exe”.

If I compile in 32 bit, the library load and work perfectly, but If I compile in 64 bit the library don’t load.

I have checked in the project source code and I have find where there is the problem:

//
dllhandle = LoadLibrary (dllnames[i]);
//

LoadLibrary is a macro of windows API “LoadLibraryA”

dllnames[i]) in some iteration is = “libjpeg.dll” because is inside a for loop.

So if I compile in 64 bit the handle is null, but if I compile in 32 the handle is non zero and work.

I have tried to copy your library in both architecture 32 and 64 bit with some result.

Attached the original c file.

I don’t know if this is a bug of your library or depend by this project.

For your opinion is possible extend the compatibility to 64 bit architecture ?

Best Regards

**Comment by dcommander** [comment]
Please use the DLL from the 64-bit libjpeg-turbo SDK for Visual C++ (**libjpeg-turbo-{version}-vc64.exe**.)  Also, you only need **jpeg62.dll**, not **turbojpeg.dll**.  **turbojpeg.dll** implements an entirely different API, not the traditional libjpeg API that your application is using.

**Comment by dcommander** [comment]
It's difficult to parse your exact meaning above, but if you have already tried to use the DLL from the 64-bit libjpeg-turbo SDK for Visual C++, then the failure may be due to a mismatch in calling conventions (the pre-compiled libjpeg-turbo DLLs use cdecl, not stdcall.)  You may ultimately have better luck building the darkplaces code with `-DLINK_TO_LIBJPEG` and linking directly with the libjpeg-turbo SDK, rather than trying to load the DLL dynamically at run time.

**Comment by luca2125** [comment]
Dear dcommander,

I have tried different times to add normally the reference with linker to turbojpeg and libjpeg without success.

The project need the reference to SDL also but I never found difficoult to link this dependence , 

If I open the exe with dependence walker my exe don't have the libjpeg (the original darkplaces exe have this depencence inside the exe) as showed in the next screenshot.

![confronto](https://user-images.githubusercontent.com/55355625/71842268-89fb7180-30c1-11ea-90cc-1334c3939cd8.png)

I like to follow your suggest and add this reference using linking, can you please send me step by step how I can do it ?

**Comment by dcommander** [comment]
Install the libjpeg-turbo SDK for Visual C++, add either **c:\libjpeg-turbo64\include** (64-bit) or **c:\libjpeg-turbo\include** (32-bit) to your project's include directories, and link against either **c:\libjpeg-turbo64\lib\jpeg.lib** (64-bit) or **c:\libjpeg-turbo\lib\jpeg.lib** (32-bit).  That is true when building any Windows application with Visual C++ and libjpeg-turbo.

**Comment by luca2125** [comment]
Dear dcommander,

Attached the screenshot of my setting for include the dependence:

![setting1](https://user-images.githubusercontent.com/55355625/71920547-4d924900-3187-11ea-9299-efb5a7e7f419.png)
![dir1](https://user-images.githubusercontent.com/55355625/71920588-600c8280-3187-11ea-8fe0-285c64714848.png)
![setting2](https://user-images.githubusercontent.com/55355625/71920599-6438a000-3187-11ea-9703-87cfebbd87ff.png)
![setting3](https://user-images.githubusercontent.com/55355625/71920601-669afa00-3187-11ea-9255-209ba7bb4499.png)
[log.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/files/4032016/log.txt)

As you can see in the verbose Log visual studio skip this dependence for some reason that I don't know.

There is some setting wrong ?

**Comment by dcommander** [comment]
I do not have time to offer personal one-on-one programming assistance.  I can assure you that many people are successfully using libjpeg-turbo in Visual C++ projects.  Our own build system demonstrates how to do that, because it builds executables that link with libjpeg-turbo.  I figured out all of this stuff for myself from first principles.  I don't think it's too much to ask for you to figure out a few things using the platform of information I have provided you-- information that did not exist when I was trying to figure those things out.
