### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [libjpeg-turbo/libjpeg-turbo#400]
Would you like to add more error handling for return values from functions like the following?
- [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close stream.") ⇒ [tjSaveImage](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6367924ac62e72fc97e3105c43eb6bd1ec8eead3/turbojpeg.c#L2150)
- [putc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/putc.html "Put a byte on a stream.") ⇒ [process_COM](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6399d0a699b1756337cd0589bf3de0b4fad48b20/rdjpgcom.c#L213)

**Comment by dcommander** [comment]
Regarding `fclose()`:

It makes no sense to check errors within an error handler.  If `fclose()` fails, then there's nothing we can do about it at that point.  We've already reported another error to the calling program, and it's the calling program's decision as to how to handle that error.  The initial error may very well have been due to some underlying problem, such as lack of disk space, that would also cause `fclose()` to fail.

Regarding `putc()`:

`putc()` will never return an error if passed stdout.  Calling that function with stdout is semantically similar to `printf()`, so it is neither necessary nor appropriate to check the return value.

In the future, please do not use bug reports to discuss such trivialities as this.  Bug reports are for actual, user-visible and user-reproducible bugs.  If you submit an issue in the future that bears the "bug" label but bypasses our bug report questionnaire, then your issue will be summarily closed without comment.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by dcommander** [comment]
Please make a specific proposal rather than asking open-ended questions.

**Comment by elfring** [comment]
Would you trust [any advices](https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors "Detect and handle standard library errors") (from source code analysis tools) more than known suggestions (from me)?

**Comment by dcommander** [comment]
It’s not a matter of trust. It’s a matter of time. You are asking for a lot of my time. This project has limited resources, and I have to be judicious with how I use them. These issues are not user-visible, so I don’t care about them that much. The benefit of fixing them does not outweigh the cost, so you need to help me reduce that cost if you want me to fix them. That means providing a specific compiler flag or exact steps to use some other tool to detect all of the issues.

**Comment by elfring** [comment]
>These issues are not user-visible, …

Do software users occasionally care for file output failures?

**Comment by dcommander** [comment]
Seriously?  I've already answered that question.  At this point, your comments are bordering on trolling.  So let me be 100% clear about this:

1. I am willing to fix actual (not hypothetical) issues that can be demonstrated with a real use case.
2. I am willing to fix code style issues that can be detected with a pre-existing automated tool.
3. I am willing to fix the issues described in (2) only if you provide exact instructions regarding the use of the pre-existing automated tool to detect such issues.
