### ISSUE TITLE
Just one of my regression images won't load with libjpeg-turbo

### ISSUE THREAD

**Issue by MikeCowlishaw** [libjpeg-turbo/libjpeg-turbo#401]
Hi, and happy New Year/Decade!

This isn't urgent (because fallback to GDI load works around nicely), but I got a surprise the other day when I added a new image to my regression tests.   The attached file fails with messages: 
  Backing store not supported
  JPG decode failed

(even though it loaded without errors with libjpeg), on both 32-bit and 64-bit Windows versions.   I tried with and without a 'cinfo.mem->max_memory_to_use' setting (3MB, it seems from my notes of a couple of years ago, was/is optimal for libjpeg).

Any ideas?   Mike

![Waikiki-8000](https://user-images.githubusercontent.com/56477819/72010262-6cf4a900-324f-11ea-84b9-e5c2458f617a.jpg)

(Provenance: this is a 50% version of a much larger file [which loads fine in 64-bit with libjpeg-turbo], created by FastStone Image viewer; it does load as expected with GDI and I am sure it loaded OK with libjpeg - though will admit I haven't tried that recently -- but will do f you want.)

**Comment by dcommander** [comment]
This image requires > 96 MB in order to decompress.  I can reproduce the failure when the library's memory usage is limited to 96 MB or less:

```
# ./djpeg -maxmem 96M 72010262-6cf4a900-324f-11ea-84b9-e5c2458f617a.jpg >out.ppm
Backing store not supported
```

I cannot reproduce the failure when the library's memory usage is limited to more than 96 MB or when the library's memory usage is unlimited:

```
# ./djpeg -maxmem 97M 72010262-6cf4a900-324f-11ea-84b9-e5c2458f617a.jpg >out.ppm
# ./djpeg 72010262-6cf4a900-324f-11ea-84b9-e5c2458f617a.jpg >out.ppm
```

I tried on both Windows and Mac with both 32-bit and 64-bit builds of libjpeg-turbo.

**Comment by MikeCowlishaw** [comment]
OK, thanks for the quick response!   I did try not setting cinfo.mem->max_memory_to_use -- and this failed for me; is there different way to specify unlimited?

(I'd also like to not make special cases for libjpeg-turbo; my code (written a year or so ago) reads as below .. this implies that 97MB would be very slow with original libjpeg?)

The other concern I have is it's only this one image that fails in this way -- far bigger ones are fine, including the 16000x8000 version of the same image (though that one needs 64-bit build).   Any idea what the underlying cause is?   It sounds as though I need the 'unlimited' option, with a switch for when I'm building with turbo.

Thanks -- Mike

  // reduce memory use; without this jpeg_start_decompress
  // will malloc 6 bytes for every output image pel
  cinfo.mem->max_memory_to_use=3*1000*1000;

  // larger sizes were slower, e.g., for 16000x8000 image:
  //   3MB 4.1s, 5MB 4.5s, 7MB 7s, 70MB 27s, 170MB 32s, 370MB 42s

**Comment by dcommander** [comment]
The default value of `max_memory_to_use` is `0`, which means unlimited.  As to why that setting only affects certain images, it's probably because some images you're decompressing are progressive JPEGs and some aren't.  If you're using a buffered source manager (which is what cjpeg and djpeg do) and writing the decompressed image directly to disk (also what cjpeg and djpeg do), then a baseline (non-progressive) JPEG may only require a few kilobytes of memory (the size of the buffer) in order to decompress.  However, for progressive JPEG images, the library must create a holding buffer the size of the full decompressed image.  That is because each successive scan in a progressive JPEG image "refines" the previous scan, so the pixels generated by Scan N are supposed to overwrite the pixels generated by Scan N-1.  (Progressive JPEG images were intended for web browsing on slow connections, which is why they behave this way.  The idea is to show a lower-quality representation as a place holder while a higher-quality representation is being downloaded and decompressed computed.)

**Comment by dcommander** [comment]
Original libjpeg completely ignored the `max_memory_to_use` setting unless you were using one of the exotic memory managers (MS-DOS, 1990s MacOS, named temp files), all of which are obsolete and were thus never used by libjpeg-turbo.  In most cases, the `malloc()`/`free()` memory manager was used in libjpeg, so setting `max_memory_to_use` had no effect.  Thus, in order to make libjpeg-turbo behave the same way as libjpeg for your code, simply don't set `max_memory_to_use`.

**Comment by MikeCowlishaw** [comment]
Very many thanks!

Looking at my notes, I spent some some time getting libjpeg to heed max_memory_to_use -- I see I built it with jmemansi; this (setting max_memory_to_use to 3E+6) then made a big difference to speed, and also allows/allowed loading bigger images in the 32-bit version of PanGazer.

Setting max_memory_to_use to 0 does indeed allow loading my 'rogue' image using libjpeg_turbo (I just tried it, and without the fallback to GDI it's delightfully fast).   I am now setting a #define to indicate that I'm using turbo and should set that 0, which leads to one last (I hope!) question: is there some function call I can make to detect whether I'm linked with plain-old-libjpeg or turbo?   It would be nice to have the set-to-0 be automatic.

Thanks again for all your help ... acknowledged, of course, at: http://speleotrove.com/pangazer/thanks.html

Mike

**Comment by dcommander** [comment]
The most reliable way to detect OG libjpeg vs. libjpeg-turbo at run time, and the only way that is guaranteed to work with all versions of libjpeg-turbo, is to attempt using the libjpeg-turbo colorspace extensions.  Those will fail on OG libjpeg.  Refer to **jcstest.c** in the libjpeg-turbo source for an example.

**Comment by MikeCowlishaw** [comment]
Hmm, just been looking at  jcstest.c ... seems that to use that code one has to include the turbo .h files, which sort of defeats the object of being able to switch fully between the two for testing/backup/timing.

I think I'm probably better off with a static define -- On thinking about it, I can modify my 'switch' Rexx script to modify that in the appropriate source .h file.

But thanks for the pointer, anyway!

**Comment by MikeCowlishaw** [comment]
Ah silly me .. of course I can/must do this at compile time, so just testing whether JCS_EXT_RGBA is defined is sufficient.

**Comment by dcommander** [comment]
No, jcstest should work with libjpeg as well. It performs both compile-time and run-time detection.

**Comment by dcommander** [comment]
Note that it’s entirely possible to compile against libjpeg and use libjpeg-turbo at run time, or vice versa. But an easier method of compile-time detection these days is to just #ifdef based on one of the version macros that only libjpeg-turbo provides (look at jconfig.h.)

**Comment by MikeCowlishaw** [comment]
Understood (jcstest) ... but will look at your jconfig.h -- that should be absolutely fine.  Thanks!

Mike
