### ISSUE TITLE
add support JPEG-XL

### ISSUE THREAD

**Issue by KonoromiHimaries** [libjpeg-turbo/libjpeg-turbo#405]
https://google.github.io/brunsli/#demo

**Comment by dcommander** [comment]
My understanding of JPEG XL is limited, but whereas I'm interested in supporting lossless encoding (refer to #402), it would only be possible to do so if a significant number of existing libjpeg-turbo algorithms could be reused for that purpose.  Otherwise, there isn't much point to back-porting a new image format into software whose primary purpose is to accelerate compression/decompression of a 30-year-old image format with a 30-year-old API.  It would be more straightforward to just create a new project and API for JPEG XL.  The only open source implementation of JPEG XL I could locate is Apache-licensed, meaning that its license is incompatible with ours and I could not re-use any of that code as-is.  If I'm mistaken about any of the above, please correct me, but as far as I can determine at the moment, this would be out-of-scope for libjpeg-turbo.
