### ISSUE TITLE
What's up with my_upsampler being defined twice in a header and source file?

### ISSUE THREAD

**Issue by MarcusJohnson91** [libjpeg-turbo/libjpeg-turbo#409]
Is changing this even possible? it's giving Xcode tons of issues, but Cmake manages to compile just fine somehow

**Comment by dcommander** [comment]
It shouldn't be causing any issues.  Are you using CMake to create the Xcode project?  If so, then please describe the steps necessary to reproduce the problem.  `my_upsampler` is always a local definition, not a global one.  In the original libjpeg code, both **jdmerge.c** and **jdsample.c** created a private sub-object called `my_upsampler` that extended `jpeg_upsampler` in different ways.  In the context of implementing partial image decompression in libjpeg-turbo, it was necessary to move the private sub-object from **jdsample.c** into a private header (**jdsample.h**), which is now included by both **jdsample.c** and **jdapistd.c**.  But `my_upsampler` is still a local definition, since it is defined only in the local scope of those two files.

**Comment by MarcusJohnson91** [comment]
Oh no honestly I lowkey forgot about that, I just made the project myself.

I'll try generating it with Cmake.

**Comment by MarcusJohnson91** [comment]
It appears to work when I generate it with Xcode, but now there's some really strange bugs cropping up

1: dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
  Expected in: /Users/Marcus/Source/External/libJPEG-Turbo-MyLossless/BUILD/Debug/libjpeg.62.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib

2: memmove has a weird overflow? not exactly sure since it only shows source code but it looks like that

**Comment by dcommander** [comment]
I assure you that those are not libjpeg-turbo issues.

(1) Figure out why LibTIFF is being included in your build.  That does not come from libjpeg-turbo.  libjpeg-turbo provides `jpeg_resync_to_restart()` rather than `__cg_jpeg_resync_to_restart()`, and it does not use or include LibTIFF.

(2) `memmove()` is a C library function that is out of our control, and libjpeg-turbo does not use that function.

**Comment by MarcusJohnson91** [comment]
> I assure you that those are not libjpeg-turbo issues.
> 
> (1) Figure out why LibTIFF is being included in your build. That does not come from libjpeg-turbo. libjpeg-turbo provides `jpeg_resync_to_restart()` rather than `__cg_jpeg_resync_to_restart()`, and it does not use or include LibTIFF.
> 
> (2) `memmove()` is a C library function that is out of our control, and libjpeg-turbo does not use that function.

Yeah, I think the __gq__ is a linker prefix, for like name mangling but idk why it would be doing name mangling in the first place.

**Comment by dcommander** [comment]
The more relevant question is:  why is LibTIFF being included in a build of libjpeg-turbo, and why is `memmove()` being called?

**Comment by MarcusJohnson91** [comment]
Yeah, I'm looking into that, I jut uninstall libjped9d with Homebrew, hopefully it was a symbol clash with Homebrew?

**Comment by dcommander** [comment]
Building libjpeg-turbo itself should not require any outside libraries except for the C library.  If it is somehow conflicting with libjpeg in Homebrew, then there is something wrong with the build.

**Comment by MarcusJohnson91** [comment]
I'm thinking it's a dynamic linking issue.

libjpeg being built is not in `PATH`, but Homebrew installs things into `PATH` so hopefully that's it.

**Comment by MarcusJohnson91** [comment]
Ok, not that I've rebuilt libjpeg-turbo after uninstall libjpeg it fails at `Invalid SOS parameters for sequential JPEG` for both djpeg and djpeg-static with a test image.

so it looks like that fixed it.
