### ISSUE TITLE
Problem with non-ASCII file name

### ISSUE THREAD

**Issue by dehghani-mehdi** [libjpeg-turbo/libjpeg-turbo#414]
File with English name compressed without problem, but if I rename same file and use non-ASCII name, e.g: `تست.jpg`, the following error shows up:

> jpegtran: can't open ???.jpeg for reading

What should I do to fix this problem?

__Update__: the problem is not limited to the file name, the whole file path (include directory names) are matter and it makes it even harder to handle.

**Comment by dcommander** [comment]
I have no idea.  cjpeg, djpeg, and jpegtran all use `fopen()` to open files, so if `fopen()` cannot handle non-ASCII filenames, then those programs will not handle them either.  Those programs are limited to using stdio functions, since the use of stdio FILE handles is part of the libjpeg API (`jpeg_stdio_src()` and `jpeg_stdio_dest()`.)  If there is a way to make `fopen()` handle non-ASCII filenames (such as a flag I'm not aware of), then I am open to modifying the programs thusly, but the modification would have to be non-disruptive and backward-compatible.

**Comment by dehghani-mehdi** [comment]
I'm not good at this area, I got this answer from kornelski tho, is it helpful?

> This is because Visual Studio's standard library for C doesn't support non-ASCII filenames (without Windows-only workarounds in programs). You can recompile these utilities with GCC/MinGW instead. Or use stdin/stdout. Or submit patches to libjpeg-turbo adding workaround for MSVC.

**Comment by dcommander** [comment]
That makes sense, because I was able to successfully use the non-ASCII filename with libjpeg-turbo on Mac and Linux.  It seems like it might be necessary to use `_wfopen()` with Visual Studio in order to support non-ASCII filenames:
https://stackoverflow.com/questions/396567/is-there-a-standard-way-to-do-an-fopen-with-a-unicode-string-file-path
If you or someone else wants to formulate a patch for that (re-emphasizing that the patch must be backward compatible, i.e. it must also work with ASCII filenames, and it must use only C library functions), then I'll evaluate it for inclusion in libjpeg-turbo.  However, I have no time to look into the matter personally.  As Kornel pointed out, you can pass the file to jpegtran using stdin as a workaround, i.e.

```
cat تست.jpg | jpegtran {options} >{transformed_image}.jpg
```

**Comment by dehghani-mehdi** [comment]
Using `cat  تست.jpg | .\jpegtran.exe > b.jpg` I got this error:

> Not a JPEG file: starts with 0x3f 0x3f

But it's okay if I rename the file to `a.jpg` and run `jpegtran.exe a.jpg > b.jpg`

**Comment by dcommander** [comment]
libjpeg-turbo is a low-level library meant primarily for programmers and power users.  A basic level of command-line knowledge (including understanding what "stdin" means) is necessary in order to use libjpeg-turbo.  If you don't understand what something is, then please google it.  I can only provide support regarding the specific usage of libjpeg-turbo and any problems that might arise with that.  If you require a more high-level/user-friendly solution, then please use one of the many image viewers/editors that are built with libjpeg-turbo (IrfanView is my personal favorite for Windows.)

**Comment by dehghani-mehdi** [comment]
You are right, actually I did use google, that's why I deleted my comment.

I'm programmer and I planed to use libjpeg-turbo in my app. _I mean I'm not looking for free GUI program to optimize my images with_

Anyway thank you for the help, and I'll _and should_ work on my knowledge about command-line.

**Comment by dehghani-mehdi** [comment]
@dcommander  I have a problem with the output, I want to overwrite the optimized image.

Using:
```
type تست.jpg | jpegtran -optimize -progressive -copy none -outfile تست.jpg
```

Shows `can't open ?.jpg for writing` error and using:
```
type تست.jpg | jpegtran -optimize -progressive -copy none > تست.jpg
```
Shows `Empty input file` error and overwrite the original image with 0 size one.

The second situation happens with following command too:
```
jpegtran -optimize -progressive -copy none test.jpg > test.jpg
```

The only working solution is 
```
jpegtran -optimize -progressive -copy none -outfile test.jpg test.jpg
```
Which doesn't work with non-ASCII filenames.

Why this syntax: `test.jpg > test.jpg` doesn't work?

**Comment by dcommander** [comment]
libjpeg is a nearly 30-year-old codec, and libjpeg-turbo is a much-faster-but-still-backward-compatible implementation of it.  Back in 1991, when libjpeg was first released, there were still a lot of MS-DOS systems around that were limited to 640 kB of directly addressable memory.  Thus, the libjpeg API and its supporting utilities (cjpeg, djpeg, jpegtran) are designed to buffer data from/to disk and operate on only a chunk of the input/output image at a time.  Thus, you can't redirect the output to the same file as the input.  Most command-line utilities have similar limitations, and this is part of that "basic level of command-line knowledge" I referred to above.

**Comment by dehghani-mehdi** [comment]
>  and this is part of that "basic level of command-line knowledge" I referred to above.

If this information are basic, what is the advanced level of command-line knowledge? could you give me one or two example please?
