### ISSUE TITLE
Odd output sizes in raw mode.

### ISSUE THREAD

**Issue by milkylainen** [libjpeg-turbo/libjpeg-turbo#427]
I'm using an older 1.5.3 release, but could not see any changes related to this.
Im trying to use jpeg_write_raw_data.
YUV 4:2:0 so comp_info[0].h_samp_factor, v_samp_factor = 2.
in_color_space = JCS_YCbCr,
dct_method = JDCT_IFAST, ARM Neon.
raw_data_in = TRUE.
Quality ~85.

I feed raw_data with 16x rows upwards rounded to nearest 16x but let cinfo width and height stay the same.
Ie. I feed 1920x1088 and 960x544 (Quarter size) lines but cinfo height is 1080 and 540 respectively.

The picture gets encoded as 1920x1080 with 1088 input lines.
But for 544 lines the output is 544 height even though cinfo is 540 in height.
I was surprised to see a difference between the sizes, as both are divisible by 16.

**Comment by dcommander** [comment]
I barely understand what you're saying, so let me repeat what I think I understand.

* You are attempting to use `jpeg_write_raw_data()` to compress a 1920x1080 JPEG image from planar YCbCr source data.
* You are padding the input planes up to the nearest iMCU boundary (which should be 16x16 for luminance and 8x8 for chrominance, since you are using 4:2:0 subsampling.)
* You are setting cinfo.width to 1920 and cinfo.height to 1080.

Things I definitely do not understand:
* I do not understand what you mean by "cinfo height is 1080 and 540 respectively."  cinfo.height should always be 1080.
* I do not understand what you mean by "But for 544 lines the output is 544 height even though cinfo is 540 in height."  What do you mean by "output"?  And, again, why is cinfo.height set to 540?  cinfo.height should be the height of the overall image, not of the plane.

**Comment by milkylainen** [comment]
My bad. Sorry for being so confusing. I hope I can clarify things.

So what I am trying to do is the following:
1. Create a JPEG out of a 1920x1080 planar source YCbCr data.
2. Create a JPEG out of a 960x540 planar source YCbCr data. This image is a quarter size of the original one. height/2, width/2.

I have absolutely no trouble getting an image, only that I am a little confused by the height number in the output.

I try to feed the encoder with 16 lines at a time, padded to the nearest 16 over height.
Ie.
1. I feed 1920x1088 total lines (nearest 16 above, + 8 padded lines). Leaving cinfo.height at 1080. From this I get an image of 1920x1080 out.
2. I feed 960x544 total lines (nearest 16 above + 4 padded lines). Leaving cinfo.height at 540. From this I get an image of 960x544 out.

I can verify that cinfo.height is 1080 in the first case and 540 in the second case. But images are 1080 and 544 respectively. I am confused why this happens.
Maybe I am feeding it wrong? What would be the correct method of getting 1080 and 540 lines out with <code>jpeg_write_raw_data()</code> if they are not evenly divisible by 16?

**Comment by dcommander** [comment]
I'm not sure, but the TurboJPEG API function `tjCompressFromYUVPlanes()` produces the expected behavior, so I'm guessing that the issue is in your code.  I'm happy to look at your code if you post it, but otherwise, my best advice is to refer to the implementation of `tjCompressFromYUVPlanes()` for an example of how to use `jpeg_write_raw_data()` with a source image whose width and height are not evenly divisible by the iMCU size.  Based on your description, you're doing the right thing (padding the source data up to the nearest iMCU boundary), but there may be other details that you're getting wrong.

**Comment by milkylainen** [comment]
I can't find anything really obvious in my code, the interface seems simple enough to me.

Init part. cinfo is static and reused. Maybe that is wrong? Encoder called directly from here.
Raw data planar has space and is already padded before entering the encoder part.
There is a lot of fixed numbers, but the use case is fixed so I don't bother much right now.
```
    static struct jpeg_error_mgr jerr;
    static struct jpeg_compress_struct cinfo;
    if (!cinfo.err) {
        cinfo.err = jpeg_std_error(&jerr);
        jpeg_create_compress(&cinfo);
    }
    cinfo.image_width = scale ? width / 2 : width;
    cinfo.image_height = scale ? height / 2 : height;
```
Runtime part:
Set some parameters, figure out nearest 16-block unit above height. Go.
```
static gsize
jpeg_thread_enc(struct jpeg_compress_struct *cinfo, const yuvp *yuv,
                     guint8 *jpeg, const jpegdefs *def)
{
    guchar *p;
    guint y, i, rndup_height;
    JSAMPROW xy[16], xcr[16], xcb[16];
    JSAMPARRAY blks[3] = { xy, xcr, xcb };

    struct jpeg_destination_mgr memd = {
        .next_output_byte = jpeg,
        .free_in_buffer = 1024 * 1024,
        .init_destination = jpeg_enc_init,
        .empty_output_buffer = jpeg_enc_empty,
        .term_destination = jpeg_enc_term,
    };
    if (cinfo->image_height & 0xf) {
        rndup_height = ((cinfo->image_height + 15) >> 4) << 4;
    } else {
        rndup_height = cinfo->image_height;
    }
    cinfo->dest = &memd;
    cinfo->input_components = 3;
    cinfo->in_color_space = JCS_YCbCr;
    jpeg_set_defaults(cinfo);
    cinfo->raw_data_in = TRUE;
    cinfo->comp_info[0].h_samp_factor = 2;
    cinfo->comp_info[0].v_samp_factor = 2;
    cinfo->comp_info[1].h_samp_factor = 1;
    cinfo->comp_info[1].v_samp_factor = 1;
    cinfo->comp_info[2].h_samp_factor = 1;
    cinfo->comp_info[2].v_samp_factor = 1;
    if (def->quality > 90) {
        cinfo->dct_method = JDCT_ISLOW;
    } else {
        cinfo->dct_method = JDCT_IFAST;
    }
    jpeg_set_quality(cinfo, def->quality, TRUE);
    jpeg_start_compress(cinfo, TRUE);
    for (y = 0; y < rndup_height; y += 16) {
        for (i = 0; i < 16; i++) {
            xy[i] = (guchar *)yuv->Y + (y + i) * cinfo->image_width;
            if (i < 8) {
                xcr[i] = (guchar *)yuv->U + (y / 2 + i) * (cinfo->image_width / 2);
                xcb[i] = (guchar *)yuv->V + (y / 2 + i) * (cinfo->image_width / 2);
            }
        }
        jpeg_write_raw_data(cinfo, blks, 16);
    }
    jpeg_finish_compress(cinfo);
    return 1024 * 1024 - memd.free_in_buffer;
}
```

**Comment by milkylainen** [comment]
I think I might have found a issue. Not 100% sure yet.

I was using the rtp payloader in gstreamer.
But it has stupid restrictions and RFC is being rather obtuse.
https://tools.ietf.org/html/rfc2435
https://github.com/GStreamer/gst-plugins-good/blob/master/gst/rtp/gstrtpjpegpay.c
(ROUND_UP_8)
It requires RTP payload to be 8x pixel sizes "because of JPEG".
But it makes a stupid assumption that encoding size == display size == transportation declaration size, which could not be further from the truth.
So the rtp payloader adds 4 pixels to 540 to get upwards divisible by 8.
(1080 is divisible by 8, that is why I don't notice it there.)
Technically, the RTP JPEG RFC should not bother this much what JPEG it is transporting.
Classical example of code knowing to much and screwing it up.

**Comment by milkylainen** [comment]
Well. Turns out I cannot do anything to fix this.
RTP JPEG RFC is actually not real width in the header. But 8-pix wide units.
So I physically cannot give the data real width or real height.
That probably saved 4 bytes back in 1999...
