### ISSUE TITLE
Preserve frame pointers

### ISSUE THREAD

**Issue by phraktle** [libjpeg-turbo/libjpeg-turbo#43]
Please provide the binary distribution compiled with preserving frame pointers (gcc -fno-omit-frame-pointer). Due to the larger number of registers on newer architectures, this should pose minimal overhead, however it would aid in providing coherent stack traces in profiling tools (such as linux perf). These are very useful in production systems as well.

**Comment by dcommander** [comment]
OK, I'm about to do a complete run of performance tests, so I'll add this and make sure it doesn't cause any regression.

**Comment by dcommander** [comment]
Follow-up question:  How would compiling our official binaries with -fno-omit-frame-pointer give you coherent stack traces?  Our official binaries aren't compiled with debugging symbols.

**Comment by phraktle** [comment]
Hi,

The use case is that I'm trying to get production profiling with Linux perf working. The `perf report` shows the entry points for libturbojpeg.so fine (even without additional debug symbols), but it can't connect these to the caller due to the lack of frame pointer. If there was a frame pointer, the turbojpeg calls could be attributed to the appropriate call-site and visualized using a tool such as https://github.com/brendangregg/FlameGraph.

Regards,
  Viktor

**Comment by dcommander** [comment]
Unfortunately, this creates a consistent slow-down across the board.  The slow-down is small (about 2-3%) when SIMD is active, but decompression can slow down by as much as 20% when SIMD is inactive (more typically around 10%.)  The latter is a concern because some platforms still use the C routines for certain algorithms, so without doing a thorough performance review, I don't have confidence that the addition of the `-fno-omit-frame-pointer` switch won't cause significant slow-downs in other places.

**Comment by phraktle** [comment]
Thanks for evaluating this though :)
