### ISSUE TITLE
Question: Save quantized DCT tensors as a jpeg file

### ISSUE THREAD

**Issue by Nithanaroy** [libjpeg-turbo/libjpeg-turbo#437]
How can I use libjpeg-turbo to save quantized DCT arrays as a jpeg file? I couldn't find any direct API for this in the documentation. So thought I would ask here.

![image](https://user-images.githubusercontent.com/670556/85831333-fe46d180-b742-11ea-9a5d-0c9da036169c.png)
**Image credits:** https://eng.uber.com/neural-networks-jpeg/

**Comment by dcommander** [comment]
`jpeg_read_coefficients()`?

**Comment by Nithanaroy** [comment]
Thanks @dcommander. This is a pretty good lead, which I have been looking for several days now.  I have read on stackoverflow that `jpeg_write_coefficients` expects the quantization tables as the first argument, which I don't have. As shown in the above picture, I only have quantized DCT Python `numpy` arrays for `Y`, `Cb` and `Cr` of shapes `[(181, 161, 64), (91, 81, 64), (91, 81, 64)]` respectively. Could you please share an example showing the usage of this function when DCT components are already quantized by an external program?

**Comment by dcommander** [comment]
Refer to the function documentation in libjpeg.txt.  It says, "Each block in the block arrays contains quantized coefficient values in normal array order (not JPEG zigzag order)."  It doesn't say anything about supplying the quantization table.  The jpegtran program uses `jpeg_write_coefficients()` in order to copy the DCT coefficients from one JPEG container into another, so it is a good example of how to use the function.
