### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [libjpeg-turbo/libjpeg-turbo#442]
Story time:

I was fuzzing the turbojpeg.h library in an attempt to find a vulnerablility with afl++. I found a DOS (Denial of service). While I was attempting to get RCE (Remote code execution) I noticed that the library uses ASAN (lib asan). So this exploit in the end just crashes the program, because of ASAN's memory curroption detection throwing SIGILL (Illegal instruction). To be more specific lib asan throws the assembly instruction ud2 (undefined), which crashes the program. Sorry if there are any spelling mistakes. I'm doing all of this on an old laptop with a broken backlight. So one of the corners are dimmed out so it would be hard to see.

Originaly I was planning on selling the exploit to the developers. However, if it isn't RCE most don't care.

If you wan't to know more. Then let me know

**Comment by dcommander** [comment]
If the issue goes away when you set `JSIMD_FORCENONE=1` in the environment, then it’s a known issue with ASan and valgrind and other tools of that nature. (They either do not handle or do not properly handle SIMD assembly instructions.)

If it is a different issue, then please post instructions and (if applicable) a test image that can be used to reproduce the issue. I am happy to fix such issues in our code, but I of course have no ability to pay you for the fix. My general maintenance, support, and bug-fix work on this project is funded almost entirely through patronage and donations, and our budget is already used up through October.

**Comment by KittyTechnoProgrammer** [comment]
![Screenshot at 2020-07-19 15-24-36](https://user-images.githubusercontent.com/45339160/87884477-eee33d00-c9fd-11ea-82ad-b4004d32d133.png)

The issue still persists. I believe its a malformed bmp header causing the issue. I do have an exploit script in python that writes out the bmp header in binary to a file (exploit.txt) which you can test. I can give you details on how this exploit works (or at least how my debugging experience went with gdb-pwndbg), and which function causes the crash. Let me know if you would like to know more information on how it works.



P.S. Sorry for the wait. There was some bad weather, and I understand the money situation.
Meme: Understandable, have a nice day.

**Comment by KittyTechnoProgrammer** [comment]
Heres the python file.
[ezip.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/4944597/ezip.zip)

**Comment by dcommander** [comment]
I tried to reproduce the issue but unfortunately could not.  I compiled libjpeg-turbo with ASan and UBSan enabled, and UBSan does detect an issue with exploit.txt:

```
rdbmp.c:595:38: runtime error: signed integer overflow: 1073741952 * 3 cannot be represented in type 'int'
```

As far as I can tell, however, that is a false positive, since the destination variable is `JDIMENSION`, which is an unsigned int.  ASan does not detect any issues.  Any additional information you can provide that might help me reproduce the issue is appreciated.

**Comment by KittyTechnoProgrammer** [comment]
can you inform me on the commands to enable ASan and UBSan for the library. I compiled it with make.

**Comment by dcommander** [comment]
```
cd {libjpeg-turbo_source_directory}
mkdir build
cd build
cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS_RELWITHDEBINFO="-O1 -fsanitize=address,undefined -fPIE" -DCMAKE_C_COMPILER=clang ..
make test
```

**Comment by dcommander** [comment]
@KittyTechnoProgrammer Do you have any further information that may help me reproduce this issue?

**Comment by dcommander** [comment]
Still cannot reproduce.  The BMP header specifies a width of 1,073,741,952, a height of 271,843,328, and a BPP of 24.  Thus, libjpeg-turbo fails to allocate memory [here](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/rdbmp.c#L620) because `row_width` is 3,221,225,856 and `alloc_small()` cannot handle more than 1,000,000,000 bytes.  This produces an error ("Insufficient memory (case 7)"), but ASan does not catch any other issues.  I've tried various versions of ASan in both Clang and GCC.
