### ISSUE TITLE
Provide ARM build for Raspberry Pi

### ISSUE THREAD

**Issue by apandada1** [libjpeg-turbo/libjpeg-turbo#449]
It would be great if `armhf` and `arm64` builds of Debian installer are made available at the sourceforge page, so that it can be easily installed in Raspberry Pi.

**Comment by apandada1** [comment]
I saw that libjpeg-turbo used to be available at [Launchpad](https://code.launchpad.net/~tom-gall/linaro/libjpeg-turbo), but not updated since 2011. I am unsure if both are the same projects. However, Launchpad can be configured to automatically import code from github and build the package into PPA for multiple architectures.

Also, is the package [libjpeg-turbo-progs](https://packages.debian.org/bullseye/libjpeg-turbo-progs) in Debian the same package from this GitHub repository, or is it something different altogether?

**Comment by dcommander** [comment]
The only packages we maintain are the ones on SourceForge.  Any other packages are maintained by downstream developers and O/S distributors.  Debian splits the libjpeg-turbo run-time programs (**cjpeg**, **djpeg**, **jpegtran**, etc.) into a separate package (**libjpeg-turbo-progs**.)  The header files and link libraries are in the **libjpeg-dev** package.

I would be open to creating unofficial builds on a site such as LaunchPad, but at the moment, I don't have the infrastructure to enable official ARM builds.

When libjpeg-turbo was first released ten years ago, all of the major Linux distributions were still using libjpeg.  Our official packages served two purposes at the time:
1. They facilitated building my downstream software (VirtualGL and TurboVNC) that relies on libjpeg-turbo.  (The VirtualGL and TurboVNC build systems look for libjpeg-turbo in **/opt/libjpeg-turbo** by default, which allows me to control which version of libjpeg-turbo is used to build them.)
2. They provided a drop-in replacement for libjpeg, allowing applications that were dynamically linked with libjpeg to use libjpeg-turbo at run time.

(2) is no longer a concern, since libjpeg-turbo is available in almost all Linux distributions these days.  However, the official packages are still useful in the following x86 development situations:
- A downstream application needs the libjpeg-turbo Java interface, but the O/S distribution of libjpeg-turbo doesn't include the Java interface (this is often the case.)
- A downstream application needs to link statically with libjpeg-turbo (for instance, in order to provide cross-distribution binaries), but the O/S distribution of libjpeg-turbo doesn't include the static libraries (this is sometimes the case.)
- A downstream application needs the TurboJPEG API, but the O/S distribution of libjpeg-turbo doesn't include the TurboJPEG API (this is sometimes the case.)
- A downstream application needs some of the features/fixes in the latest libjpeg-turbo release, but the O/S distribution of libjpeg-turbo is out-of-date (this is often the case.)

Otherwise, there isn't really any advantage to the official packages.

Specific to Debian, the latest stable release (10.5 "buster") is still stuck on libjpeg-turbo 1.5.2 for some reason.  The testing release ("bullseye") has libjpeg-turbo 2.0.5.

**Comment by dcommander** [comment]
Marking as "revisit", since it will likely become easier at some point in the future to cross-compile ARM packages once other factors necessitate upgrading our official build infrastructure.  Also, ARM is increasing in popularity, so the demand for official ARM packages is likely to increase over time.

**Comment by apandada1** [comment]
I would like to add that Launchpad provides free building service for Debian packages, for all major architectures, including ARM. Also, it has the feature to automatically import git code from GitHub, and automatically build it if the code is updated (in GitHub).
