### ISSUE TITLE
Add documentation about using libjpeg-turbo as an external library

### ISSUE THREAD

**Issue by Sph00b** [libjpeg-turbo/libjpeg-turbo#450]
First of all I've been working with CMake for only a couple of months so I'm not so knowledgeable about best practices.

I'm having an hard time trying to add the libjpeg-turbo as an external library in my project, long story short I'm using vcpkg now but handling the CI is a nightmare.

In referring to #353, #202 and #339 I've seen that there are restriction  and best practice reccomanded to solve the problem but no official documentation.

It is something reasonable to ask for or it is something undoable for reason I don't understand?

**Comment by dcommander** [comment]
It's not unreasonable from a technical point of view, but from a project management point of view, it's tricky at best.  As an independent open source developer, I have very limited resources with which to work on this project.  Cendio AB provides a general fund for my work on libjpeg-turbo, but that amounts to about 8 hours of funding per month, which is currently used up through October.  I have a pending funded development project to integrate ARM NEON SIMD enhancements into libjpeg-turbo 2.1, but the rest of the features on tap for libjpeg-turbo 2.1 are currently unfunded, so it will likely be necessary to use up the general fund well into next year in order to get libjpeg-turbo 2.1 out the door.  That release is already months behind schedule because my other open source projects (VirtualGL and TurboVNC, which are remote display/remote desktop solutions) became suddenly more popular in the wake of COVID-19, thus necessitating a spate of bug fixes.

Most major features that have been developed for libjpeg-turbo since its inception 10 years ago have been funded by outside organizations.  I also receive a bit of funding from user contributions, but even so, I have personally donated as much or more of my pro bono labor than has been funded.  My pro bono labor on this project over the past ten years would have a value of hundreds of thousands of U.S. dollars if a corporation were paying me a salary for that labor.  Since 2009, I have managed to barely pay my bills through my work on VirtualGL and TurboVNC, but libjpeg-turbo is basically a loss leader.

libjpeg-turbo's CMake build system was implemented using pro bono labor-- thousands of dollars worth of it.  I personally prefer CMake over autotools, but ultimately, I overhauled the build system because downstream project maintainers who used CMake complained bitterly about the difficulties in integrating libjpeg-turbo into their projects.  Even though I donated a significant chunk of my free time toward making those downstream project maintainers, I still get bitter complaints from other downstream project maintainers about not supporting libjpeg-turbo as a subdirectory build (i.e. about requiring `ExternalProject_Add()`.)

I have spent a great deal of my personal time improving the performance and security of this library, making the standards organizations happy so that libjpeg-turbo can be an official ISO/ITU-T reference implementation, providing easy-to-use binary packages for popular platforms, providing comprehensive automated regression tests, overhauling the build system, providing an easy-to-use and fully-documented/fully-exampled API for first-time users, providing continuous pre-release builds that are equally as easy to use as our official release builds, answering numerous questions from the community about the library's use, etc.  I can't just wave my hand and magically solve every problem.  Solving any problem requires time and effort.  It requires careful and methodical experimentation to determine the best technical solution, as well as exploring the problem from all feasible angles to ensure that that solution truly is the best.  If I document something, then I have to document it on all supported platforms (of which there are many), which means that I have to test it on all supported platforms.  That takes time, and time is money, and I cannot spare either right now.

My approach to this problem would likely be similar to your approach-- googling `ExternalProject_Add()`, trying to integrate libjpeg-turbo into a test project using that CMake function, googling any problems that I might encounter, and continuing to bang on it until a solution is found.  I would reap zero reward for my labor on such a solution, since it only benefits downstream projects.  I have done my best to make this project as straightforward as I can possibly make it, and it is certainly light years ahead of its predecessor in that regard.  I don't expect everyone to spend as much time as I have spent becoming an expert on libjpeg-turbo, but I am just one person, so it's impossible for me to solve every problem or to make every one of the millions of libjpeg-turbo users happy.

If you have more targeted questions, then I'm happy to field those questions individually, but there's a big difference between asking me to provide unofficial support for you as an individual developer (which I am always happy to do) and asking me to officially document and support a use case for potentially thousands (or even millions) of people.

**Comment by dacap** [comment]
I'll leave a comment here just for future users that might find it useful and I think is quite important when we try to replace `add_subdirectory()` with `ExternalProject_Add()`.

There are three possible ways to structure your code:

1) use `ExternalProject_Add()` in a parent `CMakeLists.txt` of your own code:
```
  root/CMakeLists.txt       <- has ExternalProject_Add() for libjpeg-turbo
  root/src/CMakeLists.txt   <- reference the libjpeg-turbo target
```
2) having a special module in `CMAKE_MODULE_PATH` paths to use `find_package()`:
```
  root/cmake/FindJpegTurbo.cmake  <- has ExternalProject_Add() for libjpeg-turbo
  root/src/CMakeLists.txt         <- uses find_package(JpegTurbo) and uses libjpeg-turbo target
```
3) everything in the same `CMakeLists.txt` file.

And example [FindJpegTurbo.cmake](https://github.com/dacap/aseprite/blob/422d74a271e43c6f8846c09bed6a993b1d097ff1/cmake/FindJpegTurbo.cmake#L30) file that creates a `libjpeg-turbo` target.

---

**DO NOT** use this kind of structure:
```
  root/CMakeLists.txt                <- uses add_subdirectory() for each subdir
  root/libjpeg-turbo/CMakeLists.txt  <- with ExternalProject_Add() for libjpeg-turbo
  root/src/CMakeLists.txt            <- libjpeg-turbo target is not visible here (!)
```

Sorry for the noise to libjpeg-turbo authors, you can ignore this comment and leave this here just for people googling or searching some help through the issues.
