### ISSUE TITLE
Random data returned for exiv2 meta data

### ISSUE THREAD

**Issue by emmenlau** [libjpeg-turbo/libjpeg-turbo#467]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes, I could not find anything related to "exiv" or "exiv2".

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

I'm pretty sure it does not.

**Clear and concise description of the bug:**

When I open the following image using libjpeg-turbo and read the exiv meta data field, I get mostly random data there. More concretely it is not completely random but in my tests its usually one of a few random choices of bytes without any predictable pattern. It looks to me like either the file is corrupt or something is broken in reading this specific file.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

I'm using a highly integrated library. So while I can step in the debugger to the origin of reading the exiv data, and I see its in libjpeg-turbo, I do not know the details on how this is implemented. Sorry if this bug report is not so useful.

**Image(s) needed in order to reproduce the bug (if applicable):**

![oi](https://user-images.githubusercontent.com/1098087/97812760-f6b0af80-1c83-11eb-959c-2d4956f58f03.JPG)

The image is originally from the great vigra image processing library at https://github.com/ukoethe/vigra/blob/master/src/images/oi.JPG

**Expected behavior:**

Some reproducible data should be returned for reading the meta data. I'm not sure if the file contains exiv2 data, so maybe returning nothing is also ok. But the returned bytes should not change between invocations.

**Observed behavior:**

A large random string (size roughly 10xxx bytes) is returned that changes between reads.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Ubuntu 20.04 current latest, Ubuntu 18.04 current latest, MSVC Visual Studio 2019 current latest.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

Version 2.0.5 release. I currently can not test against other versions because I do not use libjpeg-turbo directly, I use a high-level wrapper.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
Please clarify your terminology.  Exiv2 is an open source library for accessing EXIF, IPTC, XMP, and ICC metadata, so I don't know what you mean when you say "exiv metadata."  Which type of metadata specifically?  How are you trying to read it?  libjpeg-turbo provides no API or other facility for reading such metadata, other than `jpeg_read_icc_profile()`.  Any access to EXIF/IPTC/XMP metadata is the province of higher-level libraries, many of which use Exiv2 for that task.  It's entirely possible that the memory region that those higher-level libraries are using is provided by libjpeg-turbo, but the code they are using to access the metadata is not provided by us.

I can confirm that the image you posted does indeed contain EXIF metadata (`exiftool` appears to read it properly), but absent further data, this issue does not appear to be our bug.  Please feel free to post further clarifying comments that may convince me otherwise.
