### ISSUE TITLE
internal loop labels are kept as symbols

### ISSUE THREAD

**Issue by sunweaver** [libjpeg-turbo/libjpeg-turbo#486]
A while back, the below issue has been reported against an older version of libjpeg-turbo in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918175

Can the libjpeg-turbo upstream maintainer(s) please check, if to any respect the described issue is still a problem with latest libjpeg-turbo? If not, please close this issue immediately. It it needs to be addressed, still, please see the patch posted in the above Debian bug (although the to-be-patched file nasm_lt.sh has been removed from the upstream sources by now).

Here comes the original bug report:

When profiling any program that uses libjpeg-turbo, there's a proliferation
of “symbols” that are really internal labels, confusing the profiler:

  14,50%  MJPEG_Encode     libjpeg.so.62.2.0              [.] jsimd_fdct_islow_sse2
   8,80%  MJPEG_Encode     nageru                         [.] memcpy_interleaved_fastpath
   8,69%  MJPEG_Encode     libjpeg.so.62.2.0              [.] ..@25..CHECKBUF47_END
   4,51%  MJPEG_Encode     libc-2.28.so                   [.] __memmove_avx_unaligned_erms
   3,81%  MJPEG_Encode     libjpeg.so.62.2.0              [.] jsimd_quantize_sse2.quantloop
   3,24%  MJPEG_Encode     libjpeg.so.62.2.0              [.] encode_mcu_huff
   2,81%  Mixer_Audio      libzita-resampler.so.1.6.0     [.] Resampler::process
   2,54%  MJPEG_Encode     libjpeg.so.62.2.0              [.] jsimd_convsamp_sse2.convloop
   2,44%  nageru           [unknown]                      [k] 0xffffffffa280015f
   2,31%  MHD-connection   [unknown]                      [k] 0xffffffffa280015f
   2,09%  MJPEG_Encode     libjpeg.so.62.2.0              [.] ..@44..CHECKBUF31_END
   2,02%  QS_Encode        [unknown]                      [k] 0xffffffffa280015f
   1,98%  Mixer_Audio      libzita-resampler.so.1.6.0     [.] VResampler::process
   1,89%  MJPEG_Encode     libjpeg.so.62.2.0              [.] compress_data
   1,57%  MJPEG_Encode     libjpeg.so.62.2.0              [.] jsimd_huff_encode_one_block_sse2.BLOOP
   1,39%  MJPEG_Encode     libjpeg.so.62.2.0              [.] forward_DCT
   1,21%  MJPEG_Encode     libjpeg.so.62.2.0              [.] jsimd_huff_encode_one_block_sse2

Note in particular ..@25..CHECKBUF47_END, which is really part of
jsimd_huff_encode_one_block_sse2, and the same with .BLOOP. This is a known
shortcoming of nasm, but can be stripped out fairly easily, e.g., with
something like

**Comment by dcommander** [comment]
The libjpeg-turbo build system makes no effort to strip local symbols, preferring instead to hide those symbols using a link-time version script/mapfile.  This issue would not have been magically fixed in more recent versions of libjpeg-turbo because it's not a libjpeg-turbo bug.  According to [this article](https://stackoverflow.com/questions/39653210/all-asm-labels-becoming-symbols-in-executable-file), it seems to be a NASM issue that doesn't even exist in YASM.  Possible workarounds:

1. Use YASM.
2. Build NASM 2.15 from source, apply [the patch from this forum post](https://forum.nasm.us/index.php?topic=2666.0), and pass `-DCMAKE_ASM_NASM_FLAGS=--discard-labels` to CMake when configuring the libjpeg-turbo build.
3. Create a NASM wrapper script that invokes `strip --discard-locals` for every assembler object created, then pass `-DCMAKE_ASM_NASM_COMPILER={path_to_your_wrapper_script}` to CMake when configuring the libjpeg-turbo build.

These are all things that libjpeg-turbo users can do, irrespective of the involvement of O/S distributors, if they need to work around this problem.  And let's be clear that this is a pretty esoteric problem, because it involves facilitating the profiling of libjpeg-turbo's internals.  Why does anyone other than the libjpeg-turbo developers need to do that?

If there is something straightforward that I could do to the libjpeg-turbo code or build system in order to prevent those symbols from being visible, then I'll consider that, but hard-coding a Un*x-specific dependency (`strip`) into the build system and/or forcing non-global symbols to be stripped by default (which would be too presumptuous on our part) is the wrong approach.  As far as I can tell, our code is doing the right thing by prefixing all of the local labels with a period.  If NASM is making those local labels globally-visible, then that's a bug in NASM, not in libjpeg-turbo.  Again, I'm happy to work around it, but only if doing so does not introduce potential compatibility or maintenance problems.
