### ISSUE TITLE
Is CVE-2020-14152 present in libjpeg-turbo 2.0.5? 

### ISSUE THREAD

**Issue by wangsc0355** [libjpeg-turbo/libjpeg-turbo#500]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

**Clear and concise description of the bug:**

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

**Image(s) needed in order to reproduce the bug (if applicable):**

**Expected behavior:**

**Observed behavior:**

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
Please refer to the change log.  libjpeg-turbo has honored `max_memory_to_use` since v1.5.2, which was released in 2017, so CVE-2020-14152 is not applicable to us.  CVE entries will always specify if the issue applies to libjpeg-turbo, because libjpeg-turbo has a lot broader reach than libjpeg these days.

To be frank, I don't think it was correct to assign a CVE to that issue.  libjpeg traditionally had multiple memory managers, including some system-specific ones (MS-DOS, System 7 Macs) and a couple of different approaches for Un*x systems (`malloc()`/`free()`, temp files.)  The purpose of most of these memory managers was to implement a kind of rudimentary virtual memory on operating systems that didn't have virtual memory (you see, kids, back in the day...)  Thus, `max_memory_to_use` was not traditionally supported on virtual memory systems, for which the `malloc()`/`free()` memory manager was intended to be used.  In the **jmemnobs.c** file, which implements the simple `malloc()`/`free()` memory manager, **nobs** stands for "no backing store", which indicates that the backing store capabilities are expected to be provided by the operating system.  This is documented behavior in libjpeg, so applications cannot expect it to behave otherwise.  If applications wanted to limit the memory used by the libjpeg `malloc()`/`free()` memory manager, they needed to handle that at the application level (such as examining the JPEG header and restricting the size of image that could be decoded) or at the operating system level.

Since libjpeg-turbo has only ever included the `malloc()`/`free()` memory manager, I agreed to re-introduce support for `max_memory_to_use` primarily to make things easier for mobile device developers.  However, that was a feature enhancement, not a bug fix.  I don't think it's correct to call it a "security issue" when an application tries to decompress an NxM JPEG file, knowing full well that it will require NxMxX bytes of memory and that there isn't that much memory available.  I also don't think it's correct to call it a "security issue" when an application tries to use an API feature, that API feature is explicitly not supported on the run-time platform, and the documentation reflects that.

But anyhow, the answer is no, CVE-2020-14152 never affected libjpeg-turbo, because the fix for that issue was in libjpeg-turbo several years prior.
