### ISSUE TITLE
checkasm tool

### ISSUE THREAD

**Issue by ilyakurdyukov** [libjpeg-turbo/libjpeg-turbo#503]
Did you have a tool to test simd functions one by one?
Similar to checkasm from ffmpeg/x264.

tjbench shows overall performance, which is not that useful.

**Comment by dcommander** [comment]
TJBench has been used to develop every existing set of libjpeg-turbo SIMD extensions. In my opinion, measuring the impact of each SIMD algorithm on overall performance with real-world JPEG images is more meaningful than measuring the low-level performance of each algorithm in isolation. It allows you to see areas in which optimization is useful and areas in which optimization is not as useful (Amdahl’s Law.) Benchmarking whole images also reproduces real-world memory caching behavior, whereas testing each algorithm in isolation does not.

The way I approach the problem is to establish a performance baseline with a particular set of images using TJBench, then I add each new SIMD algorithm one-at-a-time and measure the incremental performance difference with TJBench to ensure that every algorithm speeds up overall performance by an amount significant enough to justify its existence. I also disable as many processes as possible on the machine when doing this, and I use either compression or decompression performance (whichever one shouldn’t be affected by the algorithm currently being tested) as a sanity check on the other. Generally, on my machines, I can get to within 1% accuracy this way. When I get back to the office, I will share the spreadsheet template that I use for this.

Incidentally, this process represents a lot of the labor involved with integrating SIMD extensions developed by others, which is why I must always find funding (either directly from the submitter or from a third-party research grant) in order to integrate those. I have not found a benchmarking method that works better for libjpeg-turbo’s purposes than the time-consuming differential performance analysis method described above, but I am also open to suggestions.

**Comment by ilyakurdyukov** [comment]
Measuring the performance of each part separately is useful for regression testing and comparing CPUs of the same arch, but of different generations. This makes it easier to see problems with a specific compiler/CPU. When viewing the results of the tjbench - poor results in specific functions may be overlooked.

I am looking at overall performance, but I also wrote separate tests for several functions to make it easier to experiment with.

**Comment by dcommander** [comment]
If I can successfully stabilize the funding for this project, then such a checkasm utility is perhaps something I can work on in the long term. I agree that it would be beneficial in some cases, particularly if the utility also measures the mathematical correctness of the algorithms against their C counterparts. It would take a lot of work to get it right, though. I would have to spend time designing an appropriate set of input matrices that cover the range of values that each function is expected to handle. Most likely, the Huffman algorithms would have to be excluded, since their performance depends on the input and is thus not deterministic at the low level.

**Comment by ilyakurdyukov** [comment]
I guess that after a while I'll start writing the simple checkasm tool, with the performance benchmark part only. Also excluding the Huffman part. I thought maybe you already have such a tool, but it hasn't been published yet.
