### ISSUE TITLE
libjpeg-turbo doesn't build with CMake for Mac universal binary

### ISSUE THREAD

**Issue by AndySomogyi** [libjpeg-turbo/libjpeg-turbo#512]
We are using libjpeg-turbo as a CMake sub-project. 

We switched our build system over to produce universal binaries, set the options in the top-level CMake to:

```
set (CMAKE_OSX_ARCHITECTURES "arm64;x86_64")
set (CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH NO)
```

But libjpeg-turbo will not allow ```CMAKE_OSX_ARCHITECTURES``` to have more than one value.

**Comment by dcommander** [comment]
libjpeg-turbo contains assembly code, so it cannot support multiple values in `CMAKE_OSX_ARCHITECTURES`.  You must build arm64 and x86_64 versions separately.  Our build system provides a mechanism for automatically combining arm64 and x86_64 builds into a single binary package (refer to **BUILDING.md**).

**Comment by dimitre** [comment]
In fact the way it is structured today it is easy to remove this restriction.
As CMAKE will build everything twice if we use more than one architecture it is only a matter of removing the restriction, and it will build twice and run lipo to combine both.
by removing this lines from CMakeLists.txt
```cmake
# set(COUNT 1)
# foreach(ARCH ${CMAKE_OSX_ARCHITECTURES})
#   if(COUNT GREATER 1)
#     message(FATAL_ERROR "libjpeg-turbo contains assembly code, so it cannot be built with multiple values in CMAKE_OSX_ARCHITECTURES.")
#   endif()
#   math(EXPR COUNT "${COUNT}+1")
# endforeach()
```
it is able to build a universal fat lib direclty, output:
```
libjpeg.a:      Mach-O universal binary with 2 architectures: [x86_64:current ar archive random library] [arm64:current ar archive random library]
libjpeg.a (for architecture x86_64):	current ar archive random library
libjpeg.a (for architecture arm64):	current ar archive random library
libturbojpeg.a: Mach-O universal binary with 2 architectures: [x86_64:current ar archive random library] [arm64]
libturbojpeg.a (for architecture x86_64):	current ar archive random library
libturbojpeg.a (for architecture arm64):	current ar archive random library
```

**Comment by dcommander** [comment]
> In fact the way it is structured today it is easy to remove this restriction. As CMAKE will build everything twice if we use more than one architecture it is only a matter of removing the restriction, and it will build twice and run lipo to combine both. by removing this lines from CMakeLists.txt

It clearly doesn't work for me with the latest CMake release (4.1.1).  `CMAKE_OSX_ARCHITECTURES` causes CMake to pass `-arch arm64 -arch x86_64` to the compiler.  Thus, all of the C code will be built for both architectures.  However, as I said above, and as the build system explains, that does nothing for the assembly code.  `CMAKE_OSX_ARCHITECTURES` does not and cannot magically build both the x86 and Arm SIMD extensions, because those are completely different code bases that are built with different tools (NASM in the case of x86) and options.  The only way you can make `CMAKE_OSX_ARCHITECTURES` work with multiple values is to build libjpeg-turbo without SIMD extensions, which means that it is no longer "turbo."
