### ISSUE TITLE
How to reduce color depth to save space

### ISSUE THREAD

**Issue by AachoLoya** [libjpeg-turbo/libjpeg-turbo#522]
I need to save some space, other than quality setting, color depth reduction is used by converting 32-bit images to 16-bit color when encoding and then decode them back as 32-bit. But afaik, jpeg internally converts RGB to YCbCr colorspace. 

Does that mean that passing 32-bit or 16-bit color depth as no affect on resulting jpeg size? Is there an option to specify chrominance subsampling 444 vs 422 vs 420 in libjpeg api (not Turbo api)?

**Comment by dcommander** [comment]
You are correct that converting RGB888 to RGB565 prior to JPEG compression wouldn’t be useful, because the RGB components would be converted back to 8-bit-per-component YCbCr planes during JPEG compression. The libjpeg API uses 4:2:0 subsampling by default. Refer to this code for an example of how to change that:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/c23672ce52ae53bd846b555439aa0a070b6d2c07/rdswitch.c#L392

Chroma subsampling and quantization (reducing JPEG quality) are better methods of compression than converting to RGB565, because chroma subsampling and quantization take into account the limits of the human visual system. Thus, 4:2:0 will reduce the size just as much as RGB565 but with fewer visual artifacts. Reducing JPEG quality discards the highest frequencies in the image first, since those are the hardest for the human visual system to perceive.

Also note that enabling progressive entropy coding will reduce the final JPEG size by about 5-15% relative to baseline entropy coding, particularly if you reduce the scans to the bare minimum. If compression time isn’t a concern, you could use mozjpeg to get even more compression, at the expense of very slow compression performance.
