### ISSUE TITLE
Grayscale Compression Failing

### ISSUE THREAD

**Issue by yaadhavraajagility** [libjpeg-turbo/libjpeg-turbo#526]
I am wrote a function with Jpeg Turbo to allow it to do compression and it looks something like this:

```
bool JPEGCompress::compress(const uint8_t* data, size_t width, size_t height, ImageFrame::image_type type, std::string& out)
{
  // Prealloc if not
  out.reserve(1 << 24); // Preallocate 16 MB output buffer

  // Allocate memory for compressed output
  int subsamp = TJSAMP_420;
  auto outsize_max = tjBufSize(width, height, subsamp);
  if (size_t(-1) == outsize_max) {
    fmt::print("Size out of bounds: w={} h={} ss={}\n", width, height, subsamp);
    return false;
  }
  out.resize(outsize_max);

  // Select Pixel Format
  int pix_fmt = -1;
  if(type == ImageFrame::image_type::ImageColor)
    pix_fmt = TJPF_RGB;
  else if(type == ImageFrame::image_type::ImageGray) 
    pix_fmt = TJPF_GRAY;
  else{
    fmt::print("Compression doesn't work for this format: {}", ImageFrame::convEnum(type));
    return false;
  }

  // Compress
  auto outptr = (uint8_t*) out.data();
  auto outsize = outsize_max;
  if (-1 == tjCompress2(
        compressor_, data, width, 0, height, pix_fmt,
        &outptr, &outsize, subsamp, quality_, TJFLAG_NOREALLOC)) {
    fmt::print("Error encoding image: {}\n", tjGetErrorStr2(compressor_));
    return false;
  }
  out.resize(outsize);

  return true;
}
```

It works great with RGB images, but fails on greyscale images with 
`Error encoding image: Unsupported color conversion request`

I don't know what I am doing wrong with the library. I've double and triple checked the size of the inputs and the type sent are all correct.

**Comment by dcommander** [comment]
The color conversion request is unsupported because you're asking the codec to convert a grayscale image (which has only luminance information) into a 4:2:0 image (which has both luminance and chrominance information.)  It is legal to compress from an RGB/extended RGB source image into a grayscale JPEG image (doing so discards the chrominance information), but it is not legal to compress from a grayscale source image into a YCbCr JPEG image (because there is no chrominance information to compress.)  Thus, when using `TJPF_GRAY`, you must also use `TJSAMP_GRAY`.
