### ISSUE TITLE
Libjpeg-turbo all version have a stack-based buffer overflow in the "transform" component. A remote attacker can send a malformed jpeg file to the service and cause arbitrary code execution or denial of service of the target service.

### ISSUE THREAD

**Issue by mf1632015** [libjpeg-turbo/libjpeg-turbo#527]
https://vuldb.com/?id.176175
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-17541

Was this bug fixed?When will you fix this bug?

**Comment by dcommander** [comment]
The link you posted above links to #392, which clearly indicates that the bug was fixed and links to the commit that fixed it.  So you could have very easily answered this question yourself.

The issue in question was fixed in libjpeg-turbo 2.0 beta1, which was released over three years ago, so I have no idea why the security community waited until 2020 to assign a CVE ID to it.  By the time they assigned the CVE ID, libjpeg-turbo already had five production releases and one beta release containing the fix.  The fix was also immediately back-ported to the 1.5.x branch so that it could easily be applied to code bases that were still using libjpeg-turbo 1.5.3.  The issue was also likely not exploitable, since the overrun was fully contained within the stack (even valgrind didn't detect it.)

Frankly, in my opinion, this speaks a lot to how useless the CVE system is.  It seems like those ID numbers are assigned based on knee-jerk reactions to some automated tool reporting some potential issue.  Actual risk analysis does not seem to be involved, nor does timeliness in this case.  Fortunately, now that we're fully integrated with OSS-Fuzz, it will catch a lot of this stuff before it makes it into a release, so hopefully I don't have to deal with the bureaucratic nonsense as much.

**Comment by dcommander** [comment]
The link you posted above links to #392, which clearly indicates that the bug was fixed and links to the commit that fixed it.  So you could have very easily answered this question yourself.

The issue in question was fixed in libjpeg-turbo 2.0.4, which was released nearly 18 months ago, and the CVE was assigned more than 8 months after the fix was released.  By the time they assigned the CVE ID, libjpeg-turbo already had two production releases containing the fix.  The fix was also immediately back-ported to the 1.5.x branch so that it could easily be applied to code bases that were still using libjpeg-turbo 1.5.3.  The issue was also likely not exploitable, since the overrun was fully contained within the stack (even valgrind didn't detect it.)

Frankly, in my opinion, this speaks a lot to how useless the CVE system is.  It seems like those ID numbers are assigned based on knee-jerk reactions to some automated tool reporting some potential issue.  Actual risk analysis does not seem to be involved, nor does timeliness in this case.  Fortunately, now that we're fully integrated with OSS-Fuzz, it will catch a lot of this stuff before it makes it into a release, so hopefully I don't have to deal with the bureaucratic nonsense as much.

**Comment by mf1632015** [comment]
Thank you very much for your help!
I find nothing while when I search this and try to find a way to avoid this.
Your answer is very helpful to me！

**Comment by dcommander** [comment]
I modified the change log and GitHub release entry to indicate which bug fix relates to the CVE ID. It’s disappointing that the CVE database links to the relevant GitHub issue but doesn’t link to the commit that fixes it.
