### ISSUE TITLE
jpegtran: Add option to keep ICC profile

### ISSUE THREAD

**Issue by joshuakraemer** [libjpeg-turbo/libjpeg-turbo#533]
Stripping metadata with `-copy comments` (the default) or `-copy none` also removes ICC profiles, which leads to a change of displayed image colors. An option to keep the ICC profile would thus be useful. See also https://github.com/mozilla/mozjpeg/issues/222.

**Comment by dcommander** [comment]
Does `-copy all` copy the ICC profile as you would expect?  If so, then I don't see the problem.  ICC profiles are part of the image's metadata.  The documented behavior of `-copy comments` is to copy only the comments and ignore other metadata (which implicitly includes the ICC profile), and the documented behavior of `-copy none` is to copy no metadata at all.  You can argue that those command-line options aren't particularly useful, and I would agree, but they're a legacy of the 1990s libjpeg interface, which predated the widespread use of ICC profiles.  The ability to read/write ICC profiles was only added to libjpeg-turbo a few years ago.  It never existed in libjpeg.

If `-copy all` does not copy the ICC profile, then I consider that to be a bug, and I will fix it.  Otherwise, if you want to copy only the comments + ICC profile or only the ICC profile, then I think we would need new `jpegtran -copy` options for that purpose.

**Comment by dcommander** [comment]
`-copy all` does appear to copy the ICC profile, so unless you are requesting an option to copy only the comments + ICC profile or only the ICC profile, this is a non-issue.  Please clarify your intent.

**Comment by paperboyo** [comment]
Thank you, @dcommander! 🥳

**Comment by joshuakraemer** [comment]
What I want to request is a `-copy` option to only copy the ICC profile and discard other metadata.

Rationale: I want to strip metadata from certain images to optimize their filesize and avoid privacy issues. ICC profiles should be kept though, because their removal would visually alter the images.

A workaround is to first extract the profile (e.g. with ImageMagick) and then add it again with jpegtran:
```
magick original.jpg profile.icm
jpegtran -copy none -icc profile.icm original.jpg > stripped.jpg
```
