### ISSUE TITLE
unrecognized command line option ‘-m64’ on RPI3 ARM

### ISSUE THREAD

**Issue by burnbabyburn** [libjpeg-turbo/libjpeg-turbo#550]
OS:Octopie (Debian 10.10)

i try to follow build.md and executed

```
cd /opt/libjpeg-turbo
cmake -G"Unix Makefiles" /home/pi/libjpeg-turbo
make
```

But it immediatly breaks
```

`pi@octopi:/opt/libjpeg-turbo $ cat "/home/pi/libjpeg-turbo/CMakeFiles/CMakeError.log"
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc
Build flags: -m64
Id flags:

The output was:
1
cc: error: unrecognized command line option ‘-m64’

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc
Build flags: -m64
Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3

The output was:
1
cc: error: unrecognized command line option ‘-m64’
cc: error: unrecognized command line option ‘--target=arm-arm-none-eabi’`
```

I was not able to figure out the parameters i need to pass to cmake so it gets "arch" and "target" right. Setting LDFLAGS and CFlags didn't work. Also showing not listed parameters (ccmake) breaks with the same error.
Passing -march=armv7 was ignored
I am clueless what i am missing

**Comment by dcommander** [comment]
Nowhere in our documentation does it say to pass `-m64` to the compiler, so I'm not sure why you are filing this as a bug against libjpeg-turbo.  Referring to the GCC documentation, `-m64` is a valid option for certain architectures (x86-64, PowerPC, and SPARC, for instance) but not for Arm.  If you are building on an Arm Linux system, then you shouldn't need to pass any architecture arguments to the compiler, since the default target architecture of the compiler will be the same as the architecture of the system.  If you are trying to cross-compile an Arm executable (for instance, targeting AArch32/Armv7 on an AArch64/Armv8 system or targeting AArch64/Armv8 on an x86-64 system), then the procedure for that depends heavily on your Linux distribution.  I can tell you that, on Ubuntu, it requires a different toolchain (you can't just use `/usr/bin/cc`), so that's probably true of Debian as well.
