### ISSUE TITLE
In GIF image modify two bytes and adjust the size of the allocated memory

### ISSUE THREAD

**Issue by Rusamerr** [libjpeg-turbo/libjpeg-turbo#560]
Hi, i genetate GIF image with SE technicians (size 58 bytes) and used it like:  cjpeg <image>
![gt](https://user-images.githubusercontent.com/91011486/140482589-03c19190-a53e-4110-a8b6-b8756f2883fe.png)
On Windows systems this can easily cause a denial of service system. 
Inside the file, you can modify two bytes and adjust the size of the allocated memory.
![gt1](https://user-images.githubusercontent.com/91011486/140483594-c25823ff-28a6-443d-85ae-36e81aba4d1a.png)
The file is available at the link:
https://drive.google.com/file/d/1EvA25b-Fa1w0SrmtkSVxZjyEQY9gDJfk/view?usp=sharing

**Comment by dcommander** [comment]
Sorry, this apparently got buried in my inbox. I will investigate.

**Comment by dcommander** [comment]
This is a similar issue to LJT-01-004 described in [this report](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf).  As with that issue, it isn't a bug per se.  In some cases, such as when decompressing multi-scan (progressive) JPEG images or LZW-compressed interlaced GIF images, it is necessary for the libjpeg API library and its companion programs to create a whole-image buffer to receive the decompressed image.  Progressive JPEG decoding uses this whole-image buffer to hold each scan before it is overwritten by the next scan, since the libjpeg API allows the calling program to access the decompressed pixels from a scan as soon as it is decoded.  Compressed LZW GIF decoding uses the whole-image buffer to re-order (de-interlace) the scanlines of an interlaced GIF image so that they can be fed into the JPEG compressor in the correct order.  In both cases, the libjpeg API library and its companion programs rely on the width and height reported in the image header to determine the size of the whole-image buffer to create.  This buffer is allocated on demand, so it only grows to its full size as scanlines are added to it.

Since GIF images can be up to 65535x65535 pixels in size, a perfectly valid GIF image may require 4 GB of memory to decompress.  As with LJT-01-004, the root of your complaint is that a trivially small file can also require that much memory to decompress.  Both complaints stem from the fact that the libjpeg API library and its companion programs treat warnings as non-fatal by default, which allows them to decode as much data from a corrupt image as possible.  However, that behavior can also cause issues such as this one and LJT-01-004, which is why djpeg, jpegtran, and the TurboJPEG API can optionally treat warnings as fatal.  I just added the same `-strict` argument to cjpeg, so it can now treat warnings as fatal as well. (In the case of cjpeg, that argument only affects the LZW-compressed GIF reader, because it is the only compression-side code that can throw warnings.)  Treating warnings as fatal improves fault tolerance in the sense that trivially small corrupt images can no longer cause the libraries and companion programs to consume undue amounts of memory.  Treating warnings as fatal makes fault tolerance worse in the sense that the libraries and companion programs will not try to extract as much data as possible from corrupt images.  They will simply abort at the first sign of corruption.

This issue is confined to the cjpeg program, which is intended to be an example of libjpeg API usage rather than a comprehensive image compression/conversion program.  The issue does not exist in the libjpeg-turbo libraries, meaning that it does not affect mission-critical programs that use libjpeg-turbo.  Thus, I posit that the issue is not, as you claim, a DoS issue or a security issue at all.  It is simply a product of cjpeg behaving as it is designed.  If it receives a header from an interlaced GIF file that reports the file to be 4 gigapixels in size, then it has no choice but to pre-allocate a 4 GB whole-image buffer.  If warnings are not treated as fatal, then the LZW-compressed GIF decoder will keep trying to decode past the warning, hoping that it will find a region of valid image data after the corruption.  That is, as we say in the biz, "a feature, not a bug."  The issue can be worked around in much the same way as LJT-01-004 can be worked around-- either by making libjpeg API warnings fatal (facilitated by the new cjpeg` -strict` argument, which functions identically to the same argument in djpeg and jpegtran) or by limiting memory usage with the `-maxmemory` argument.  Making warnings fatal causes the corrupt image to be detected immediately before a significant amount of memory is allocated.
