### ISSUE TITLE
Update deprecated function calls

### ISSUE THREAD

**Issue by Sebuckle** [libjpeg-turbo/libjpeg-turbo#568]
Some function calls used in this library have been deprecated for thread-safety or security reasons (e.g. sscanf, fopen, strcat, strcpy). Warnings for these deprecated functions are ignored using the /wd4996 flag for MSVC. This proposal would:

- Remove the /wd4996 flag from the MSVC compiler options
- Update deprecated functions to their secure/compliant versions when cross-platform options are available
- Use secure/compliant Windows versions of function calls when building Windows code when cross-platform options are not available. This would be in a guard like follows: 
```
#ifdef _WIN32
   _sopen_s(args)
#else
  file = _open(args)
#endif
```

**Comment by dcommander** [comment]
Thread safety is a moot point, since libjpeg-turbo's usage of those functions is confined to single-threaded example programs.

I am aware that `strcat()` and `strcpy()` are potentially unsafe, but their usage is confined to the `wrjpgcom` program, and that program checks for the possibility of buffer overruns before using those functions.

I am not aware of any potential safety issues with `sscanf()` unless it is used to scan a string, which libjpeg-turbo never does.

To the best of my understanding, the only advantage of `fopen_s()` over `fopen()` is that the former checks for NULL pointers, but since we don't ever pass those to `fopen()`, this is also moot.  Anyhow, any issues that existed with our usage of `fopen()` would exist on Un*x as well.

If there is something I missed, then please be more specific regarding the potential risk.

**Comment by Sebuckle** [comment]
Thanks for the additional context (and your quick response!), these are good points.

We're mainly looking to remove the /wd4996 flag and functions MSVC considers deprecated from our production code. This would entail removing the /wd4996 flag from libjpeg-turbo itself and fixing the corresponding issues. But it's perfectly fine for binaries and test code to continue suppressing these warnings. With a bit more digging, we've narrowed down our focus to the following changes:

CMakeLists.txt:
- Remove `/wd4996` from libjpeg-turbo, but continue to apply it to binaries and test code
- Add ` add_definitions(/D_CRT_NONSTDC_NO_WARNINGS) ` to MSVC so it will ignore the deprecated POSIX name warning for `putenv()`

turbojpeg.c:
- Replace `sprintf()` with `sprintf_s()`
- Replace `fopen()` with `fopen_s()`
- Replace `stricmp()` Windows macro with `_stricmp()`
- `strerror()`: We're stumped on this one. MSVC wants us to use `_strerror_s()`, but we're not sure how large of a buffer to allocate because the [Microsoft UCRT doesn't implement `strerrorlen_s()`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/compatibility?view=msvc-170) and there isn't a clear answer on the max size of an errno message. We're currently following up on why this specific function is missing.
- Replace `getenv()` with `getenv_s()`, and use a fixed-sized buffer of, for example, 4 bytes. If getenv_s() returns `ERANGE` because the buffer is too small for the environment variable, then we assume that the environment variable isn't set to "1" nor "B", the only two values we check for.

We believe that the impact of changing functions to their _s versions would be minimal since they're similar in functionality. Is this a reasonable assumption?

**Comment by dcommander** [comment]
If your organization is willing to pay for my labor, then I am willing to dig into this and implement appropriate project-level macros that map to the non-deprecated functions on Windows.  (I have some experience doing that in my other open source projects.)  However, since this amounts to placating MS compilers rather than fixing actual security issues, I am unwilling to spend The libjpeg-turbo Project's limited funding on it.  Contact me [through e-mail](https://libjpeg-turbo.org/About/Contact) if you would like to pursue this as a funded development opportunity.

**Comment by Sebuckle** [comment]
We're willing to put in the labor to implement and test this change. We opened this feature request to ask permission to make this change, for guidance on how to approach it, and for information about testing and validation.

We took a crack at implementing the list of changes we mentioned above: https://github.com/Sebuckle/libjpeg-turbo/tree/remove_wd4996

**Comment by dcommander** [comment]
At first glance, your patch appears as if it will break the Un*x build, so no.  A hacked-together patch that works for your specific platform is a far cry from a patch that would be acceptable for inclusion in an official ISO reference implementation used by millions of people worldwide on a variety of different platforms.  I have 11 years of professional experience with this code base and its 30-year-old predecessor.  It would take me more time to teach you how to implement this feature properly or to fix whatever patch you submitted than it would take for me to do it the right way myself (particularly given that I could partially implement the feature using code that I already own.)  Given the high exposure of the libjpeg-turbo code base, I am not interested in half-assing this.  It needs to be a project-level change that meshes well with the coding standards established for the libjpeg API code.  If I'm going to do this, then I'm going to run low-level tests on each macro to ensure that the truncation behavior and such is the same across all supported platforms, and I'm going to do the appropriate research to ensure that no backward compatibility issues are introduced.  I have dozens of different Linux distributions, several different Windows versions, FreeBSD, and Solaris all available for testing in my lab.  The finished implementation would be a set of project-level macros that I, as the project maintainer, can confidently rely upon for future libjpeg-turbo modifications.

I don't earn a salary for my work on this project, and the amount of funding I have available for 2022 amounts to about 12-13 hours/month of labor.  Doing this the right way could take as much as 8-10 hours, given the need to test for regressions on a variety of platforms.  We are far from the only popular open source project that uses the "insecure" POSIX functions in question, and our usage of those functions is not actually insecure (per above.) Given that there is no demonstrable security issue here, I am unwilling to spend our project's funding on this.  I have contracted with Microsoft before on some of my other open source projects (I may still be in your vendor database), and I think your company can certainly afford to pay for the 8-10 hours of labor (maybe less) that would be required to do this correctly.  Otherwise, I'm perfectly happy continuing to use `/wd4996`.

**Comment by dcommander** [comment]
Unfortunately `fopen_s()` appears to be so broken as to be unusable.  Specifically, it crashes rather than returning `EINVAL` (the documented behavior) when passed a NULL argument, and it returns `ENOENT` when passed a mode of "wb" with other valid arguments.  The idea of replacing the cross-platform function calls with Microsoft "secure" equivalents flies out the window if the "secure" equivalents are more error-prone than the function calls they are replacing.  Literally the only reason `fopen_s()` exists is to check for NULL arguments, which is exactly the situation that causes it to crash.  I am not impressed.

**Comment by dcommander** [comment]
Apparently `_putenv_s()` also crashes when passed a NULL argument.  Yikes.

**Comment by reynoldsbd** [comment]
Hey @dcommander have you seen this doc?

https://docs.microsoft.com/en-us/cpp/c-runtime-library/parameter-validation?view=msvc-170

**Comment by dcommander** [comment]
What an awful design.  :(

I was able to work around the crashes, but `fopen_s()` still returns `ENOENT` when passed `"wb"`.

**Comment by dcommander** [comment]
OK, my panic has subsided somewhat, upon discovering that:

(a) The errno issue was due to the fact that `fopen_s()` does not reset errno to 0 upon successful completion.  (IOW, the `ENOENT` value came from a previous function.)

and

(b) `fopen()` also invokes the invalid parameter handler and, by default, crashes the application on Windows if passed an invalid parameter.  (IOW, `fopen_s()` would not introduce additional risk relative to the existing code.)

However, that still leaves me confused as to the purpose of some of these secure functions, and in order to justify the enhancements to libjpeg-turbo, I need to be able to explain why these functions improve the quality of the code. Specifically:

1. Given that the invalid parameter behavior of `fopen()` and `fopen_s()` is the same on Windows, why is `fopen_s()` "safer" than calling `fopen()` and checking its return value?

2. (Same question as above for `strerror_s()`, `_putenv_s()`, and `getenv_s()`.)

3. Why does Visual Studio complain about using `sscanf()` to read a single character?  Surely that is just as safe as using `sscanf()` to read an integer (about which it does not complain)?

I can certainly justify replacing `sprintf()` and `strcpy()`, but I need to be able to justify the other changes beyond just saying "this silences Visual Studio compiler warnings."
