### ISSUE TITLE
How can I decompress YCCK color space jpeg file

### ISSUE THREAD

**Issue by firstplayer001** [libjpeg-turbo/libjpeg-turbo#569]
I use libjpeg-turbo to decompress some ycck jpeg files, but i get error as follows:

org.libjpegturbo.turbojpeg.TJException: Unsupported color conversion request
        at org.libjpegturbo.turbojpeg.TJDecompressor.decompress(Native Method)
        at org.libjpegturbo.turbojpeg.TJDecompressor.decompress(TJDecompressor.java:803)
        at org.libjpegturbo.turbojpeg.TJDecompressor.decompress(TJDecompressor.java:853)

so I want to know that does libjpeg-turbo support decomress ycck color space jpeg file? and how. thank you!

**Comment by dcommander** [comment]
When decompressing a YCCK JPEG image, you have to specify a pixel format of `TJ.PF_CMYK` for the decompressed image.  YCCK can only be converted to CMYK, because any other conversion would require a color management system and would depend on the display and printer profiles.

**Comment by ValZapod** [comment]
Just FYI, there is no default CMYK color space, not like with sRGB, so ICC profile is mandatary and also neither sRGB, nor CMYK from USA classic are contained in each other, also CMYK is not a triangle, it more like xvYCC, crazy form that is made even more complex by YCCK thag allows out of gamut colors since it has YCbCr and K and YCbCr has a lot of values (1/6) that are leading to negative values.
