### ISSUE TITLE
unity3d + ios64bit

### ISSUE THREAD

**Issue by friuns2** [libjpeg-turbo/libjpeg-turbo#57]
Hi, i trying to integrate plugin with unity3d
on ios 32bit version it works fine but on 64bit i get this error
https://www.dropbox.com/s/win39u7strx4tp3/Screenshot%202016-02-15%2017.51.11.png?dl=0
uint outputsize variable is seems corrupted, how i can fix this?

this how this function implemented on c# side 
`private static extern void tjCompress2(IntPtr jpegCompressor, IntPtr srcImage , int width, int picth , int height, int pixelformat, 
	                                       ref IntPtr compressedimage, ref uint outputsize, int subsamp, int quality, int flags);`

**Comment by dcommander** [comment]
libjpeg-turbo is a low-level C library, so it's quite impossible for me to debug high-level problems unless they can also be reproduced using the low-level tools (or unless the problem is at least relateable to the underlying library.)  I'm a command-line developer who speaks C, C++, Java, and assembly, so I don't have a lot of familiarity with C#, ObjC, or the Xcode IDE.

My best guest is that this is related to #24.  Currently the output size in tjCompress2 is of type long, which means that it's 32-bit on 32-bit platforms and 64-bit on 64-bit platforms (well, except Windows, because Windows is LLP64, not LP64.)  You seem to be casting it to a uint pointer, which is probably why it's failing under 64-bit.

**Comment by friuns2** [comment]
yes changed type to long and its now working, thanks.

**Comment by konsnos** [comment]
Hey @friuns2 ,

Can you explain how you imported the plugin to Unity? So far I've implemented it in Windows and Android, but iOS is a little tricky to me. I'm building with the instructions from [ARMv8 (64-bit)](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/BUILDING.md#armv8-64-bit) and I'm trying by adding the libturbojpeg.a file but it doesn't work and it seems it needs a bridge file or something that I can't understand so far.

**Comment by SebaDudzic** [comment]
Hey @konsnos !

Have you made any progress since the last post with integrating turbojpeg to iOS in Unity?
I'm currently struggling with same problem for 3 days. I managed to use dylib files but I have error while instantiaing tjDecompress. It says I am releasing memory from not allocated pointer.
