### ISSUE TITLE
Android/Java, retuned ByteBuffer of compressed image/ size on disk is large. 

### ISSUE THREAD

**Issue by m-aljammali** [libjpeg-turbo/libjpeg-turbo#575]
I think the problem is either in Jni or java code. Or my use of the library that is why I am not reporting it as a bug.

Compressing the image and then writing the buffer on the disk saved image will be too large (30-40 MB) unless you modify the byte array to the correct size. 

`

        val bmp = getBitmap()
        val startTime = System.currentTimeMillis()

        val size: Int = bmp.rowBytes * bmp.height
        val bytes = ByteArray(size)
        val b: ByteBuffer = ByteBuffer.wrap(bytes)
        bmp.copyPixelsToBuffer(b)
        bmp.recycle()

        tjc.setSourceImage(bytes, 0, 0, bmp.width,0, bmp.height, TJ.PF_RGBX)

        tjc.setSubsamp(TJ.SAMP_420)
        tjc.setJPEGQuality(comp)

        val outputBytes: ByteArray = tjc.compress(0)
        tjc.close()
     
        var outputBytes2 =  outputBytes.dropLast( outputBytes.size - tjc.compressedSize).toByteArray()
        val endTime = System.currentTimeMillis()
        Log.d(TAG, "  duration :" + (endTime - startTime)  + "ms" )

        saveImage(outputBytes2 , "$comp-mozjpeg.jpeg")
`

saving/writing on disk outputBytes directly will cause the saved image to be too large ( even though its quality is low "comp = 1")

dropping bytes from the byte array fix the issue  
var outputBytes2 =  outputBytes.dropLast( outputBytes.size - tjc.compressedSize).toByteArray()

I think it is just that output buffer = input buffer so just deleting extra empty byte in buffer.

**Comment by dcommander** [comment]
Unlike the TurboJPEG C API, the TurboJPEG Java API doesn't have the ability to dynamically reallocate the JPEG buffer to the appropriate size.  (This is due to the historical design of the TurboJPEG Java API, which predated the implementation of dynamic buffer reallocation in the TurboJPEG C API.  The TurboJPEG Java API was funded by a startup company that is no longer in business.  Supporting dynamic buffer reallocation in that API would be possible through the use of NIO buffers, but it would require completely refactoring the API, so it's not something that could happen without significant new funding.  It would make sense to do that as part of #517.)  Thus, when you ask the TurboJPEG Java API to allocate a JPEG buffer for you, it will return a buffer with the maximum size that is possible for any JPEG image with the given width, height, and level of subsampling.  Note that this size is actually larger than the source buffer.  Because DCT coefficients are 16-bit, it is possible to generate a pathological JPEG image that has no quantization and no Huffman compression and thus approaches twice the size of the input image.  Unless the TurboJPEG API can dynamically reallocate the JPEG buffer to the appropriate size, it has no choice but to use the worst-case size, or else it would be vulnerable to buffer overruns.

The problem with using `dropLast()` is that a buffer copy is involved, which is why the TurboJPEG API doesn't do that internally, but if a buffer copy is OK for your application, then that is a valid workaround.
