### ISSUE TITLE
Compatibility of jpeg(XT) 8bit photos with jpeg-turbo

### ISSUE THREAD

**Issue by Jamaika1** [libjpeg-turbo/libjpeg-turbo#581]
Compatibility of jpeg(XT) 8bit photos, i.e. all types of jpeg lossless, progressice, sequetial, baseline (RGB and YCbCr).
Oddly enough, these pictures seem to be reading the jpeg-turbo codec (assembler) these days.
Jpeg(XT) lossless and variations can still be problematic.
Code:
```
Unsupported marker type 0xf7
Unsupported marker type 0xc3
```
I tested aom, libavif, libwebp2 and libjxl.
Code:
```
JPEG XL encoder v0.7.0 0.7.0-4bba562 [Scalar] with JPEG lossy transcode
jpg.cc:202: JXL_FAILURE: arithmetic code JPEGs are not supported

JPEG XL encoder v0.7.0 0.7.0-4bba562 [Scalar] without JPEG lossy transcode
enc_jpeg_data_reader.cc:170: Invalid comps_in_scan: 3
enc_jpeg_data.cc:305: JXL_FAILURE: Error reading JPEG
```
**_Independent JPEG Group's CJPEG, version 9e 16-Jan-2022
Copyright (C) 2022, Thomas G. Lane, Guido Vollbeding_**
cjpeg_08bit.exe -quality 100 -rgb -progressive -arithmetic -bgycc -verbose image_21447_24bit.ppm image_21448_24bit(ps)_RGB.jpg
cjpeg_08bit.exe -quality 100 -progressive -arithmetic -bgycc -verbose image_21447_24bit.ppm image_21448_24bit(ps)_YCbCr.jpg
cjpeg_08bit.exe -quality 100 -rgb -arithmetic -bgycc -verbose image_21447_24bit.ppm image_21448_24bit(ss)_RGB.jpg
cjpeg_08bit.exe -quality 100 -arithmetic -bgycc -verbose image_21447_24bit.ppm image_21448_24bit(ss)_YCbCr.jpg

Failed `progressive` to create temporary file

**_jpegXT Copyright (C) 2012-2022 Thomas Richter, University of Stuttgart
and Accusoft_**
jpegLS.exe -encodepnm image_21447_24bit.ppm image_21448_24bit(l)_YCbCr.jls
jpegXT.exe -q 100 -l -c -a -r -qt 3 -s 1x1,1x1,1x1 image_21447_24bit.ppm image_21448_24bit(l)_RGB.jxt
jpegXT.exe -q 100 -v -c -a -r -qt 3 -s 1x1,1x1,1x1 image_21447_24bit.ppm image_21448_24bit(p)_RGB.jxt
jpegXT.exe -q 100 -v -a -r -qt 3 -s 1x1,1x1,1x1 image_21447_24bit.ppm image_21448_24bit(p)_YCbCr.jxt
jpegXT.exe -q 100 -c -a -r -qt 3 -s 1x1,1x1,1x1 image_21447_24bit.ppm image_21448_24bit(s)_RGB.jxt
jpegXT.exe -q 100 -a -r -qt 3 -s 1x1,1x1,1x1 image_21447_24bit.ppm image_21448_24bit(s)_YCbCr.jxt

av1enc.exe -q 100 -444 -size 1563x1558 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(l)_YCbCr.jls -d image_21447_24bit(1).av1
av1enc.exe -q 100 -444 -size 1563x1558 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(l)_RGB.jxt -d image_21447_24bit(2).av1
av1enc.exe -q 100 -444 -size 1563x1558 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(p)_RGB.jxt -d image_21447_24bit(3).av1
av1enc.exe -q 100 -444 -size 1563x1558 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(p)_YCbCr.jxt -d image_21447_24bit(4).av1
av1enc.exe -q 100 -444 -size 1563x1558 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(s)_RGB.jxt -d image_21447_24bit(5).av1
av1enc.exe -q 100 -444 -size 1563x1558 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(s)_YCbCr.jxt -d image_21447_24bit(6).av1

cjxl.exe image_21448_24bit(l)_RGB.jxt image_21447_24bit(2).jxl -e 5 -m -v -q 100 -s 5 -C 1 --num_threads=4
cjxl.exe image_21448_24bit(p)_RGB.jxt image_21447_24bit(3).jxl -e 5 -p -v -j -q 100 -s 5 -C 1 --num_threads=4
cjxl.exe image_21448_24bit(p)_YCbCr.jxt image_21447_24bit(4).jxl -e 5 -p -v -j -q 100 -s 5 -C 1 --num_threads=4
cjxl.exe image_21448_24bit(s)_RGB.jxt image_21447_24bit(5).jxl -e 5 -v -j -q 100 -s 5 -C 1 --num_threads=4
cjxl.exe image_21448_24bit(s)_YCbCr.jxt image_21447_24bit(6).jxl -e 5 -v -j -q 100 -s 5 -C 1 --num_threads=4

cwp2.exe image_21448_24bit(l)_RGB.jxt -info -q 100 -nometadata -mt -effort 5 -uv_mode 2 -csp 0 -o image_21448_24bit(2).wp2
cwp2.exe image_21448_24bit(p)_RGB.jxt -info -q 100 -nometadata -mt -effort 5 -uv_mode 2 -csp 0 -o image_21448_24bit(3).wp2
cwp2.exe image_21448_24bit(p)_YCbCr.jxt -info -q 100 -nometadata -mt -effort 5 -uv_mode 2 -csp 0 -o image_21448_24bit(4).wp2
cwp2.exe image_21448_24bit(s)_RGB.jxt -info -q 100 -nometadata -mt -effort 5 -uv_mode 2 -csp 0 -o image_21448_24bit(5).wp2
cwp2.exe image_21448_24bit(s)_YCbCr.jxt -info -q 100 -nometadata -mt -effort 5 -uv_mode 2 -csp 0 -o image_21448_24bit(6).wp2

htj2k-cgrok_ojph.exe -v -i image_21448_24bit(l)_RGB.jxt -o image_21447_24bit-grok(2).j2k -H 1 -M 32 -r 1 -mct 1
htj2k-cgrok_ojph.exe -v -i image_21448_24bit(p)_RGB.jxt -o image_21447_24bit-grok(3).j2k -H 1 -M 32 -r 1 -mct 1
htj2k-cgrok_ojph.exe -v -i image_21448_24bit(p)_YCbCr.jxt -o image_21447_24bit-grok(4).j2k -H 1 -M 32 -r 1 -mct 1
htj2k-cgrok_ojph.exe -v -i image_21448_24bit(s)_RGB.jxt -o image_21447_24bit-grok(5).j2k -H 1 -M 32 -r 1 -mct 1
htj2k-cgrok_ojph.exe -v -i image_21448_24bit(s)_YCbCr.jxt -o image_21447_24bit-grok(6).j2k -H 1 -M 32 -r 1 -mct 1
https://www.sendspace.com/file/mjx988

**Comment by dcommander** [comment]
JPEG XT is backward compatible with the original JPEG specification. (In fact, to the best of my understanding, the original JPEG specification is Part 1 of the JPEG XT spec.) But of course an original JPEG codec, particularly one that has 30-year-old roots as libjpeg-turbo does, is not forward compatible with all parts of JPEG XT. Referring to #232, there are some parts of JPEG XT that may be possible and beneficial to support in libjpeg-turbo, but in general, anything that would require new algorithm implementations or would otherwise cause a serious disruption to the code base is not likely to happen. So it’s probably best to speak in terms of which parts of JPEG XT we might be able to support without massively disrupting the libjpeg-turbo code base. For better or worse, our code is now used daily by billions of people worldwide and is an official ISO reference implementation, yet the amount of funding I have been able to secure for it will pay for only a couple of days’ worth of full-time labor per month in 2022. Thus, I’m extremely limited in what I can do to enhance libjpeg-turbo. Even if I could secure funding for this effort in principle, which would require a stakeholder who needs the feature badly enough to pay for it, I would have to somehow estimate the labor required. The larger the project, the more difficult it is to estimate that, and historically, missing that mark has led to me eating a lot of labor cost on libjpeg-turbo. The business model that enables me to work on this project independently of any one company’s agenda also unfortunately doesn’t provide a lot of wiggle room for “blue sky” features. libjpeg-turbo would need a lot more general funding in order for me to be able to speculate on something like this. As it is, most of the funding goes toward security-related stuff and basic project maintenance. If anything is left, it usually goes toward performance, compatibility, or usability improvements. Supporting other types of images unfortunately isn’t a high priority. I see our project priorities as more in line with the historic priorities of Tom Lane’s IJG from the 1990s: encourage adoption of and convergence around the original JPEG format (although convergence is less of a concern these days) by making it as easy, secure, and performant as possible to use that format. (The mere fact that we’re 2-6x faster than libjpeg allows JPEG images to be used for real-time applications for which they would not otherwise be suitable.) Whereas there is some need for transparent JPEG images in my other open source projects (both of which are high-performance remote display tools) that might drive the development of #232, there isn’t much of a “killer app” for most of the other parts of JPEG XT. (Lossless JPEG support would be compelling if it could be made to compress and perform as well as PNG or webp, but my research suggests that that’s a tall order.) So let’s break this down into which specific parts of JPEG XT might be a good fit, based on the requirements I stated above (no new algorithms and no major disruption to libjpeg-turbo) and which parts of JPEG XT aren’t a good fit.

**Comment by Jamaika1** [comment]
I was only surprised by the fact that a year ago I couldn't import jpegxt files via jpeg-turbo. This is now possible through newer versions. For me this is progress and the other charls jpegls should be left aside.

**Comment by dcommander** [comment]
What changed in libjpeg-turbo to make that possible?

**Comment by Jamaika1** [comment]
I will not suggest anything. I gave examples of codecs in sendspace.
https://github.com/libjxl/libjxl/issues/1172
https://github.com/thorfdbg/libjpeg/issues/65
https://github.com/team-charls/charls/commits/master

**Comment by dcommander** [comment]
Well, I'm still confused regarding your statement that you previously could not import JPEG XT files using libjpeg-turbo and now you can.  Can you give me an example of such a file?  As far as I'm aware, nothing has changed in libjpeg-turbo's image format compatibility.

**Comment by Jamaika1** [comment]
Example of file from one year ago
https://www.sendspace.com/file/z891g3
cwp2.exe image_21447_(l)_RGB.jpg -q 100 -nometadata -mt -effort 5 -uv_mode 2 -csp 0 -o image_21448_24bit.wp2
Unsupported JPEG process: SOF type 0xc3
Error! Cannot read input 'image_21447_(l)_RGB.jpg'
Status: WP2_STATUS_BITSTREAM_ERROR

**Comment by dcommander** [comment]
That file still cannot be opened by libjpeg-turbo.  It gives the same SOF error you list above.

**Comment by dcommander** [comment]
I should clarify that 21447 cannot be successfully decompressed by libjpeg-turbo but 21448 can.  I tried an older version of libjpeg-turbo (1.5.3) and got the same result.

**Comment by ValZapod** [comment]
See https://github.com/strukturag/libheif/issues/533 matrix_coefficients=0 will not work.

**Comment by dcommander** [comment]
@ValZapod What does that have to do with libjpeg-turbo?

**Comment by ValZapod** [comment]
> does that have to do with libjpeg-turbo?

That will not be lossless due to a bug and so any comparisons are invalid.

**Comment by ValZapod** [comment]
> @ValZapod I don’t understand what you are saying.

Do you know what HEIC is? iPhones and Galaxy devices... JPEG XL, AVIF? HEIC encoder has a regression bug that makes it not lossless.

**Comment by ValZapod** [comment]
@Jamaika1 was comparing Lossless old JPEG to lossless HEIC, but as I said, there is no way HEIC is lossless.

**Comment by dcommander** [comment]
Great, but this issue is about potentially supporting some aspects of the JPEG XT format in libjpeg-turbo, a codec that currently only supports the original JPEG format.  Referring to https://github.com/libjpeg-turbo/libjpeg-turbo/issues/581#issuecomment-1037317317, in order for any action to result from this discussion, we need to discuss which aspects of the JPEG XT format would specifically be supportable in libjpeg-turbo.  I don't have a very good understanding of JPEG XT.  Lossless support is happening per #402, and per #232, JPEG XT Part 9 is potentially useful as well (but I would need funding to implement it, and it's not a high-priority feature.)  However, is original lossless JPEG compatible with the lossless format specified in JPEG XT Part 8?

**Comment by Jamaika1** [comment]
New 4K test and new questions. Some malicious questions, e.g. from the developer of ffmpeg. I suppose he knows the answer.
Why I don't create SIMD codecs? 
I did previous test for lossless JPEGXT files with x265 and aom codecs which have the lossless function. The JPEG test should be lossy.

Conclusions:
Libheif only uses optimize the Huffman tables. RGB (lossless) files can't be added.
Why libjpeg in SIMD AVX for 8bit not compatible with the aom codec?
```
jpegLS.exe -encodepnm image_21447_24bit.ppm image_21448_24bit(l)_YCbCr.jls
jpegXT.exe -q 100 -l -c -a -r -qt 3 -s 1x1,1x1,1x1 image_21447_24bit.ppm image_21448_24bit(l)_RGB.jxt
jpegXT.exe -q 100 -v -c -a -r -qt 3 -s 1x1,1x1,1x1 image_21447_24bit.ppm image_21448_24bit(p)_RGB.jxt
jpegXT.exe -q 100 -v -a -r -qt 3 -s 1x1,1x1,1x1 image_21447_24bit.ppm image_21448_24bit(p)_YCbCr.jxt
jpegXT.exe -q 100 -c -a -r -qt 3 -s 1x1,1x1,1x1 image_21447_24bit.ppm image_21448_24bit(s)_RGB.jxt
jpegXT.exe -q 100 -a -r -qt 3 -s 1x1,1x1,1x1 image_21447_24bit.ppm image_21448_24bit(s)_YCbCr.jxt

av1enc_avx.exe -q 90 -420 -size 4000x3000 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(l)_YCbCr.jls -d image_21447_24bit_q90(1)_avx.av1
av1enc_avx.exe -q 90 -420 -size 4000x3000 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(l)_RGB.jxt -d image_21447_24bit_q90(2)_avx.av1
av1enc_avx.exe -q 90 -420 -size 4000x3000 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(p)_RGB.jxt -d image_21447_24bit_q90(3)_avx.av1
av1enc_avx.exe -q 90 -420 -size 4000x3000 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(p)_YCbCr.jxt -d image_21447_24bit_q90(4)_avx.av1
av1enc_avx.exe -q 90 -420 -size 4000x3000 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(s)_RGB.jxt -d image_21447_24bit_q90(5)_avx.av1
av1enc_avx.exe -q 90 -420 -size 4000x3000 -effort 5 -tune butteraugli -thread 4 image_21448_24bit(s)_YCbCr.jxt -d image_21447_24bit_q90(6)_avx.av1

avifenc_avx.exe -c aom -d 8 -y 420 -r full -s 5 -j 4 image_21448_24bit(l)_YCbCr.jls image_21447_24bita_q90(1)_avx.avif
avifenc_avx.exe -c aom -d 8 -y 420 -r full -s 5 -j 4 image_21448_24bit(l)_RGB.jxt image_21447_24bita_q90(2)_avx.avif
avifenc_avx.exe -c aom -d 8 -y 420 -r full -s 5 -j 4 image_21448_24bit(p)_RGB.jxt image_21447_24bita_q90(3)_avx.avif
avifenc_avx.exe -c aom -d 8 -y 420 -r full -s 5 -j 4 image_21448_24bit(p)_YCbCr.jxt image_21447_24bita_q90(4)_avx.avif
avifenc_avx.exe -c aom -d 8 -y 420 -r full -s 5 -j 4 image_21448_24bit(s)_RGB.jxt image_21447_24bita_q90(5)_avx.avif
avifenc_avx.exe -c aom -d 8 -y 420 -r full -s 5 -j 4 image_21448_24bit(s)_YCbCr.jxt image_21447_24bita_q90(6)_avx.avif

heifenc_avx.exe image_21448_24bit(l)_YCbCr.jls -v --avif -q 90 --no-alpha -p speed=5 -p chroma=420 -p threads=4 -p tune=ssim --matrix_coefficients=6 --full_range_flag=1 -o image_21447_24bith_q90(1)_avx.avif
heifenc_avx.exe image_21448_24bit(l)_RGB.jxt -v --avif -q 90 --no-alpha -p speed=5 -p chroma=420 -p threads=4 -p tune=ssim --matrix_coefficients=6 --full_range_flag=1 -o image_21447_24bith_q90(2)_avx.avif
heifenc_avx.exe image_21448_24bit(p)_RGB.jxt -v --avif -q 90 --no-alpha -p speed=5 -p chroma=420 -p threads=4 -p tune=ssim --matrix_coefficients=6 --full_range_flag=1 -o image_21447_24bith_q90(3)_avx.avif
heifenc_avx.exe image_21448_24bit(p)_YCbCr.jxt -v --avif -q 90 --no-alpha -p speed=5 -p chroma=420 -p threads=4 -p tune=ssim --matrix_coefficients=6 --full_range_flag=1 -o image_21447_24bith_q90(4)_avx.avif
heifenc_avx.exe image_21448_24bit(s)_RGB.jxt -v --avif -q 90 --no-alpha -p speed=5 -p chroma=420 -p threads=4 -p tune=ssim --matrix_coefficients=6 --full_range_flag=1 -o image_21447_24bith_q90(5)_avx.avif
heifenc_avx.exe image_21448_24bit(s)_YCbCr.jxt -v --avif -q 90 --no-alpha -p speed=5 -p chroma=420 -p threads=4 -p tune=ssim --matrix_coefficients=6 --full_range_flag=1 -o image_21447_24bith_q90(6)_avx.avif

heifenc_avx.exe image_21448_24bit(l)_YCbCr.jls -v -q 90 --no-alpha -p preset=placebo -p chroma=420 -p x265:thread=4 -p tune=butteraugli --matrix_coefficients=6 --full_range_flag=0 -o image_21447_24bit_q90(1)_avx.heif
heifenc_avx.exe image_21448_24bit(l)_RGB.jxt -v -q 90 --no-alpha -p preset=placebo -p chroma=420 -p x265:thread=4 -p tune=butteraugli --matrix_coefficients=6 --full_range_flag=0 -o image_21447_24bit_q90(2)_avx.heif
heifenc_avx.exe image_21448_24bit(p)_RGB.jxt -v -q 90 --no-alpha -p preset=placebo -p chroma=420 -p x265:thread=4 -p tune=butteraugli --matrix_coefficients=6 --full_range_flag=0 -o image_21447_24bit_q90(3)_avx.heif
heifenc_avx.exe image_21448_24bit(p)_YCbCr.jxt -v -q 90 --no-alpha -p preset=placebo -p chroma=420 -p x265:thread=4 -p tune=butteraugli --matrix_coefficients=6 --full_range_flag=0 -o image_21447_24bit_q90(4)_avx.heif
heifenc_avx.exe image_21448_24bit(s)_RGB.jxt -v -q 90 --no-alpha -p preset=placebo -p chroma=420 -p x265:thread=4 -p tune=butteraugli --matrix_coefficients=6 --full_range_flag=0 -o image_21447_24bit_q90(5)_avx.heif
heifenc_avx.exe image_21448_24bit(s)_YCbCr.jxt -v -q 90 --no-alpha -p preset=placebo -p chroma=420 -p x265:thread=4 -p tune=butteraugli --matrix_coefficients=6 --full_range_flag=0 -o image_21447_24bit_q90(6)_avx.heif
```

**Comment by dcommander** [comment]
@Jamaika1 I don't know.  This entire thread seems to be you brain dumping information onto me without providing any context for that information.  What *specifically* do you want me to do, as the maintainer of libjpeg-turbo?  What is the action item from this issue?  Do you want libjpeg-turbo to add JPEG XT extensions?  If so, which ones?  As I said above, our codec currently supports the original JPEG standard, which means that it only supports JPEG XT files that are backward compatible with the original JPEG standard.  It does not currently support any of the JPEG XT extensions.  If you expect an intelligent answer from me, then you need to first answer some of the questions I posed above and provide adequate context for your questions.  These questions in particular are *very* unclear, and I cannot parse your meaning:

Why libjpeg in SIMD AVX for 8bit not compatible with the aom codec?
Is libjpeg SIMD recommended?

I assume you mean libjpeg-turbo rather than libjpeg.  (They are not the same thing.)  I don't even know what the aom codec is, much less why the AVX2 SIMD extensions in libjpeg-turbo would be incompatible with it.  (Those extensions, like all of our SIMD extensions, are bitwise-compatible with the C algorithms from jpeg-6b.)  I also don't know the source for any of the executables you cite above.  Are you trying to report a compatibility problem with libjpeg-turbo?  If so, then please provide specific examples of images that are incompatible and a proposal for how to support those images.  Assume that I know *nothing* about the inner workings of FFMPEG, aom, libavif, libwebp2, or libjxl.

**Comment by ValZapod** [comment]
>the aom codec is

AV1 and AVIF.

**Comment by dcommander** [comment]
@ValZapod Again, why is that relevant to libjpeg-turbo?  The original issue seems to be asking me about compatibility of JPEG XT photos with libjpeg-turbo.  Why is any software that doesn't use libjpeg-turbo relevant to this discussion at all?

**Comment by ValZapod** [comment]
You said you do not know what AOM is. I clarified.

**Comment by dcommander** [comment]
Now clarify why it is relevant to libjpeg-turbo.

**Comment by ValZapod** [comment]
It is not.

**Comment by Jamaika1** [comment]
I don't require anything from free software. As I said before, I am glad that libjpeg supports JPEGXT.
As an amateur I use gcc 11.3.0 on Windows. I assume gcc is buggy. They may be AOM errors.

When I use noSIMD codec. Almost all options work with libjpeg turbo. The versions are given in the rar file.
An interesting fact for me is the correct operation of codecs and additions for SIMD in gcc.
https://github.com/jbeich/aom/commit/f4c53bd1eebc2ad1820a33113dfefc1a44639f31
https://github.com/AOMediaCodec/libavif/commit/cd03eef10a7cc6081ee98e3911e21d977a2bf17b
https://github.com/libjpeg-turbo/libjpeg-turbo/commit/4f7a8afbb7839a82dd357b5128cfb04dac6a5986
https://github.com/glennrp/libpng/commit/04c016d79f97eb072c601787a4bc1b039a500025
https://github.com/strukturag/libheif/commit/57b5889a240d6cf93a2c494b52d42a32226d2a57
https://chromium.googlesource.com/codecs/libwebp2/+/af96e37a715c512636eea589045ab20f32efe796
https://github.com/thorfdbg/libjpeg/commit/54ec64374a4991c7eadf05107389692267a459e1
https://github.com/team-charls/charls/commit/17c747296d9355c5be787590df4b1af64f36e132

**Comment by dcommander** [comment]
@Jamaika1 I only support libjpeg-turbo.  I don't have any stake in or deep knowledge of downstream software.  If you can find examples of images that decompress properly in libjpeg-turbo with the SIMD extensions disabled but fail to decompress with the SIMD extensions enabled, then please post those examples.  Otherwise, there is nothing further I can do to help you.

**Comment by Jamaika1** [comment]
No problem. Image can be displayed in standard JPEG.

**Comment by dcommander** [comment]
What do you mean by "standard JPEG"?

**Comment by dcommander** [comment]
I just tried the image, and it decodes fine with libjpeg-turbo with the SIMD extensions enabled.  I have no idea why it isn't working for you.

**Comment by Jamaika1** [comment]
I use ffmpeg.
ffmpeg -i image.ppm image.jpg
it isn't jpegXT. The effect was the same
Stream #0:0: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 4000x3000, 25 fps, 25 tbr, 25 tbn

**Comment by Jamaika1** [comment]
Try the gcc codecs listed above. Maybe I'm doing something wrong.

**Comment by dcommander** [comment]
Yeah, I don't know.  I don't have time to bring up a reproduction environment on Windows.  I would suggest installing the official libjpeg-turbo Windows package:
https://sourceforge.net/projects/libjpeg-turbo/files
and trying to decompress the file using **c:\libjpeg-turbo\bin\djpeg.exe**.  If it still fails, then post the error.  If it works, then the bug is downstream and out of our control.

**Comment by Jamaika1** [comment]
I thought so. Thanks for the answer.

**Comment by ValZapod** [comment]
>I use ffmpeg.
>ffmpeg -i image.ppm image.jpg
>it isn't jpegXT

We do not support XT in ffmpeg. 🤣

**Comment by Jamaika1** [comment]
https://forum.doom9.org/showthread.php?p=1978264#post1978264
