### ISSUE TITLE
"Progressive mode" is always "optimized" (Huffman)

### ISSUE THREAD

**Issue by fireattack** [libjpeg-turbo/libjpeg-turbo#59]
Long in short, when using `cjpeg` or `jpegtran`, I found that when `-progressive ` switch is enabled, `-optimize` (Huffman) will always be applied too even when we don't use that parameter, i.e. using `-progressive` and `-progressive -optimize` will give out identical results (bit-accurate).

After a quick search, I believe it's doing so because of https://github.com/libjpeg-turbo/libjpeg-turbo/blob/d4be42360c6c8a89309ffb0cc32041d799deb392/jcmaster.c#L606

Now I was just curious (not questioning), what's the reason to do so? 

I found [this ](https://sourceforge.net/p/libjpeg-turbo/mailman/message/34534764/)relavant dicussion in the maillist but it didn't explain too much.

Cheers.

**Comment by dcommander** [comment]
Referring to https://www.w3.org/Graphics/JPEG/itu-t81.pdf, p. 150, Section K.3, the "default" Huffman tables that libjpeg (and most other JPEG codecs) use are "developed from the average statistics of a large set of video images with 8-bit precision."  In other words, those default tables are, to a certain extent, a "one-size-fits-all" solution for the most common case (baseline JPEG.)  For other cases, including 12-bit samples and progressive JPEG, the codec has to generate Huffman tables "on the fly" based on the actual image content, because there are no default Huffman tables defined for those cases.  Specifying `-optimize` causes the codec to generate Huffman tables for the baseline case as well, which can improve compression a few percent at the cost of about a 2X performance drop (in the case of libjpeg-turbo, at least.)

Back when JPEG was invented (I'm actually old enough to have witnessed this first-hand), computers were so slow that doing a full statistics gathering ("optimization") pass to generate custom Huffman tables for an image could have meant the difference between the image taking a minute to compress vs. several minutes to compress.

As to why default Huffman tables were never generated for progressive JPEG, I'm guessing it's because the progressive format can have multiple scans with arbitrary degrees of quality, so it wouldn't have been feasible to develop a "one-size-fits-all" solution for that case.  As to why default Huffman tables were never generated for 12-bit JPEG, I have no idea-- probably it just wasn't a common enough case "back then" to worry that much about (perhaps there were insufficient test images available to develop a one-size-fits-all solution.)

**Comment by fireattack** [comment]
That answered my question. Thanks!
