### ISSUE TITLE
Integer Truncation at jdarith.c:474

### ISSUE THREAD

**Issue by kobrineli** [libjpeg-turbo/libjpeg-turbo#592]
Hi, libjpeg-turbo team! I recently fuzzed your repository and found Integer Truncation bug in your code in df3c3dcb9b0b24d78f9e58e28c8b509a49967ba8 version. The bug is in `jdarith.c:474`, in that string:

        *thiscoef += (JCOEF)m1;

So, addition of integer promoted *thiscoef and (JCOEF)m1 leads to the value, that cannot be represented in type JCOEF (short), and error occurs.
This is output of sanitizer verification:

        /libjpeg-turbo/jdarith.c:474:23: runtime error: implicit conversion from type 'int' of value -32896 (32-bit, signed) to type 'JCOEF' (aka 'short') changed the value to 32640 (16-bit, signed)
        SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /libjpeg-turbo/jdarith.c:474:23 in

Maybe, that is normal truncation for algorithm represented in corresponding function

To reproduce the bug, build Docker container from here: https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/libjpeg-turbo

        $ sudo docker build -t oss-sydr-fuzz-libjpeg-turbo .
        $ sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-libjpeg-turbo /bin/bash

After running Docker container execute built with sanitizers binary `/transform_fuzzer` with input 
[sydr_e6af6a67219e54fe28eec2293f2b2fde62515b05_int_overflow_10_signed_0.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/files/8495684/sydr_e6af6a67219e54fe28eec2293f2b2fde62515b05_int_overflow_10_signed_0.txt)

        $ /transform_fuzzer sydr_e6af6a67219e54fe28eec2293f2b2fde62515b05_int_overflow_10_signed_0.txt

**Comment by dcommander** [comment]
This is not a bug but rather a false positive.  As you can see, UBSan doesn't just complain about **jdarith.c**.  It also complains about **jcphuff.c**, and the line it complains about in **jcphuff.c** is a line that was introduced because of a prior complaint from a different version of UBSan.  In **jdarith.c**, UBSan complains about "implicit conversions", but in fact those conversions are not implicit.  They are explicitly type-cast, which should give Clang a clue that the conversion is intentional.  Referring to [the UBSan documentation](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html), the extra sanitizers that `-fsanitize-integer` enables relative to `-fsanitize=undefined` are: `unsigned-integer-overflow`,`implicit-unsigned-integer-truncation`,`implicit-signed-integer-truncation`, and `implicit-integer-sign-change`.  These sanitizers do not actually report undefined behavior.  They just report suspicious behavior that "is often unintentional."  In other words, they are pedantic, which is why libjpeg-turbo is not tested with `-fsanitizer=integer`.  Specifically, `implicit-integer-sign-change` and `implicit-signed-integer-truncation` are the two sanitizers that produce the errors above.  You can disable those by adding `-fno-sanitize=implicit-integer-sign-change,implicit-signed-integer-truncation` to the C/C++ flags, but I would suggest removing `integer` from the `-fsanitize` argument instead.  Since upstream fuzz testing (OSS-Fuzz) never uses `-fsanitize=integer`, I cannot guarantee that there won't be future breakage with the `unsigned-integer-overflow` and `implicit-unsigned-integer-truncation` sanitizers, even though those appear to pass at the moment.  We simply don't support any of the pedantic sanitizers enabled by `-fsanitize=integer`, and in my opinion, there is not a compelling reason for us to do so.

**Comment by dcommander** [comment]
Regardless, it is not undefined behavior, nor is it unintentional.  Therefore, it is not a bug.

**Comment by dcommander** [comment]
To clarify, when the error is triggered by the pedantic integer sanitizers, `*thiscoef` is -32768 and `m1` is -128.  The sum of the two is -32896, which won't fit in a 16-bit signed integer and thus wraps around to 32640.  That is expected, because the input file is an invalid JPEG file with out-of-range DCT coefficients.  In order for this to be a bug, one of the following would have to be true:
1. The issue would cause an otherwise valid JPEG image to fail to decode.
2. The issue would cause an invalid JPEG image to trigger truly undefined behavior.  (Integer underflow is not undefined.)
3. The issue would cause an invalid JPEG image to be treated as valid by the decoder.

None of those are true.
