### ISSUE TITLE
How can i read MCU of JPEG without header?

### ISSUE THREAD

**Issue by HanalogInstruments** [libjpeg-turbo/libjpeg-turbo#606]
Hi,

How can i read MCU of raw data after SOS without header to get height and width from MCU only?

**Comment by dcommander** [comment]
To the best of my knowledge, you can't.  The width and height are provided in the SOF (Start Of Frame) marker.  Without that information, the JPEG decoder has no idea where the decoded MCUs should be placed in the output image.  You can, for instance, use a hex editor to modify the width and height fields in an existing JPEG image.  If the new width and height add up the same number of MCUs as the old width and height, then the image will decode without errors, but the MCUs will be in the wrong place.  Without the header information, a 1000 x 8 image and a 100 x 80 image and a 10 x 800 image look the same to the decoder.  All the decoder knows is that there are 125 MCUs in each image.  It needs to know the width and height in order to know how many MCUs are in a row.  Certain motion-JPEG video formats can get away with discarding the width and height information in each JPEG frame, but only because the frame width and height are implied by the format or are supplied by a header at the start of the video file.

**Comment by HanalogInstruments** [comment]
Hi,

I already have the sample header with same chroma sampling 4:2:2 with raw data, but the sample header came with wrong demension  because mcu from raw data not match to this header, how can i auto define the demension from mcu to fix for sample header of SOF?

**Comment by dcommander** [comment]
As I said, to the best of my knowledge, you can't.
