### ISSUE TITLE
12bit compile failure with WARNMS

### ISSUE THREAD

**Issue by kjurka** [libjpeg-turbo/libjpeg-turbo#607]
When using the latest git master that supports simultaneous usage of 8 and 12 bit libraries, I get a compile error with the 12 bit variant trying to use WARNMS that works under an 8 bit build.

```c
#include <stdio.h>
#include <jerror.h>

#ifdef J12
#include <jpeg12lib.h>
#define DECOMPRESS_PTR j12_decompress_ptr
#else
#include <jpeglib.h>
#define DECOMPRESS_PTR j_decompress_ptr
#endif

void show_error() {
	DECOMPRESS_PTR cinfo;
	WARNMS(cinfo, JWRN_JPEG_EOF);
}

```

8 bit build works, but 12 bit errors:
```
gcc -c -I install22b/include -DJ12 12bitwarn.c
In file included from 12bitwarn.c:2:0:
12bitwarn.c: In function ‘show_error’:
install22b/include/jerror.h:279:36: error: ‘j_common_ptr’ undeclared (first use in this function); did you mean ‘j12_common_ptr’?
    (*(cinfo)->err->emit_message) ((j_common_ptr)(cinfo), -1))
                                    ^
12bitwarn.c:14:2: note: in expansion of macro ‘WARNMS’
  WARNMS(cinfo, JWRN_JPEG_EOF);
  ^~~~~~
install22b/include/jerror.h:279:36: note: each undeclared identifier is reported only once for each function it appears in
    (*(cinfo)->err->emit_message) ((j_common_ptr)(cinfo), -1))
                                    ^
12bitwarn.c:14:2: note: in expansion of macro ‘WARNMS’
  WARNMS(cinfo, JWRN_JPEG_EOF);
  ^~~~~~
```

**Comment by dcommander** [comment]
Ugh. I didn't anticipate the need to use those macros from user code, but in fact, they are a documented part of the libjpeg API. Since you aren't including **jpeglib.h** and **jpeg12lib.h** simultaneously, you can get away with the following temporary hack:
```
--- 12bitwarn-old.c
+++ 12bitwarn.c
@@ -3,5 +3,4 @@
 
 #ifdef J12
-#define j_common_ptr j12_common_ptr
 #include <jpeg12lib.h>
 #define DECOMPRESS_PTR j12_decompress_ptr
```
However, the intent is that user code should be able to include **jpeglib.h** and **jpeg12lib.h** simultaneously.  Probably the best solution would be to create a **j12error.h** header with 12-bit-specific macros.  I am open to suggestions for what to name them.  My initial thought is to prefix `ERREXIT*()`, `TRACEMS*()`, and `WARNMS*()` with `J12`.

**Comment by dcommander** [comment]
Referring to https://github.com/libjpeg-turbo/libjpeg-turbo/issues/199#issuecomment-1303932860, the 12-bit implementation has been completely refactored, so both 8-bit and 12-bit data precisions now share the same libjpeg API structures and all but a handful of libjpeg API functions.  It is no longer necessary to use 12-bit-specific error/warn/trace macros.
