### ISSUE TITLE
jpeg_finish_decompress without jpeg_abort, to keep markers

### ISSUE THREAD

**Issue by henrik-lindqvist** [libjpeg-turbo/libjpeg-turbo#608]
I'm writing thin a JNI wrapper. It holds a pointer to the `jpeg_decompress_struct` through the decoding stages, so the Java side can access its properties after `jpeg_read_header`, then again after `jpeg_finish_decompress`, until the Java object is "closed" which call `jpeg_destroy_decompress`. The problem is that [jpeg_finish_decompress](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/2.1.3/jdapimin.c#L382) ends with a call to [jpeg_abort](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/2.1.3/jcomapi.c#L32) that frees everything, including any markers it just read.

Is there no way to do a complete and orderly "decompress", i.e. from `jpeg_start_decompress` through `jpeg_read_scanlines` then finally `jpeg_finish_decompress`, without freeing markers and other properties?

I understand that `jpeg_finish_decompress` can't change, but there should be an alternative that doesn't call `jpeg_abort` "resetting" the `jpeg_decompress_struct`.

**Comment by dcommander** [comment]
Why do you need to access the markers after the image has finished decompressing?

**Comment by henrik-lindqvist** [comment]
@dcommander So the Java side can get them from the `jpeg_decompress_struct` pointer it holds. As it works now i'll have to duplicate the `marker_list` before the `jpeg_finish_decompress` call, even if the Java side choose not to access it.

JNI or not, it's strange API design that the final part of reading will reset/dispose of the information it just read.

**Comment by dcommander** [comment]
But you haven't explained why you need to get the markers after the image has finished decompressing.  To me, it doesn't seem strange at all that the library assumes you won't need that information after decompression has finished.  It seems much more strange that you need that information after decompression has finished.  Please justify your need.

**Comment by henrik-lindqvist** [comment]
As said, to access them, e.g. APP1/Exif, after the whole image (file) has been read successfully, which `jpeg_finish_decompress` seems to verify/ensure.

As a user of the API, without any knowledge of its internals or JPEG, how would i know `jpeg_finish_decompress` doesn't read any trailing markers, i.e. after the scanlines until EOF, that's strange. In contrast to libpng, with a similar `png_read_end` which doesn't reset everything therefore letting `png_get_unknown_chunks` be used any time thereafter.

Here's pseudo code of how my/a JNI wrapper could work:

    d = new JpegDecoder("test.jpg");        // jpeg_create_decompress
    d.readHeaders();                        // jpeg_read_header
    byte[] b = d.readBitmap(d.getFormat()); // jpeg_start_decompress, jpeg_read_scanlines, jpeg_finish_decompress
    List<Marker> m = d.getMarkers();        // marker_list
    d.close();                              // jpeg_destroy_decompress

So it needs to retain the `marker_list` after it has `readBitmap`, or make an unnecessary duplicate while doing so.

**Comment by dcommander** [comment]
The libjpeg API is 30 years old, it predates both libpng and Exif, and I had no part in its design.  You are the first person who has complained about this since I founded The libjpeg-turbo Project in 2010, so I have had no reason to look into the issue until now.  A cursory reading of **libjpeg.txt** (specifically [this section](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/59337a67b1cf47a74cf1415c7445fed4275a5d5e/libjpeg.txt#L2554-L2642)) suggests that there are ways of accomplishing what you want to accomplish, but like most things in the libjpeg API, they aren't straightforward or intuitive.  Note that the aforementioned section in **libjpeg.txt** also documents the behavior you observed, i.e. that markers are freed in the body of `jpeg_finish_decompress()`.  Please refer to the `jpeg_read_icc_profile()` function for an example of a function that copies markers into memory in order to preserve them.  If you have a suggestion for a more generic version of that function that will handle non-ICC markers, then I will consider it.

**Comment by dcommander** [comment]
I understand that you are not suggesting a change in the behavior of `jpeg_finish_decompress()`.  That was never on the table anyway.  However, a separate version of `jpeg_finish_decompress()` that doesn't call `jpeg_abort()` is also not on the table.  The design of the libjpeg API, and its documented behavior, is that it frees all library-allocated memory when `jpeg_finish_decompress()` is called.  Creating a separate version of `jpeg_finish_decompress()` that doesn't free any memory would create a maintenance/support/documentation burden for me and potential confusion for other users.  It is, to be blunt, an error-prone hack, and hacks aren't acceptable in a library that has such a large reach as libjpeg-turbo, not to mention such a large potential for security exploits.  The purpose of such a function is not well justified, since there are already other ways to accomplish what you want to accomplish.  If you aren't interested in writing a marker parser, which is how Tom Lane intended for the problem to be solved, then I offered to extend the API so that you can easily save markers in the same manner that `jpeg_read_icc_profile()` does.  (In fact, `jpeg_read_icc_profile()` could probably be re-implemented by calling the new API function, which would make the feature maintenance-neutral.)  If neither of those solutions is acceptable to you, then you're on your own.
