### ISSUE TITLE
Can this package come to Kali Linux as soon as possible please?

### ISSUE THREAD

**Issue by thecowmilk** [libjpeg-turbo/libjpeg-turbo#616]
Hi guys, I know I'm kinda rushing with `as soon as possible` knowing very well this a project through **contribution**. But I really wanna know if this project will be ported to Kali Linux.
There are some packages like `libturbojpeg0` but another package which depends on `libjpeg-turbo8` cannot be installed with the former on my system.

I hope I will get an answer. Thank you guys!

**Comment by dcommander** [comment]
Since Kali is Debian-based, you can use the .deb packages from our official releases. We do not have the resources to maintain distribution-specific packages. We only provide generic packages for Debian-based and RPM-based distributions. Those packages should work with any distribution that has glibc 2.12 or later.
