### ISSUE TITLE
Add support for OSX Universal Binary building

### ISSUE THREAD

**Issue by clusty** [libjpeg-turbo/libjpeg-turbo#617]
On OS-X you can build binaries that work on both x86_64 and Arm64 by passing: -arch x86_64 -arch arm64 to the clang compiler

For some reason jpeg-turbo explicitly forbids this:
`CFLAGS="${CFLAGS} -arch x86_64 -arch arm64" cmake ../ -DCMAKE_INSTALL_PREFIX="../../build" -DCMAKE_PREFIX_PATH="../../build"             `                                                                                  

yields:

```
-- CMAKE_BUILD_TYPE = Release
-- VERSION = 2.1.4, BUILD = 20220914
CMake Error at CMakeLists.txt:64 (message):
  The libjpeg-turbo build system does not support multiple values in
  CMAKE_OSX_ARCHITECTURES.
```

**Comment by dcommander** [comment]
There is no way we can support this, because the two architectures require different libjpeg-turbo SIMD extensions, and the SIMD extensions for x86-64 and AArch64 are built with different tools. You can use our build system to combine a separate x86-86 and AArch64 build into one package, as we do with the official libjpeg-turbo Mac package.

**Comment by clusty** [comment]
Great. Would you please be so kind to share the path towards the jpeg-turbo universal binary ? (I've been using home-brew till not that does not build universal-ly)

**Comment by dcommander** [comment]
You can always use our official package, which already does that work for you:
https://sourceforge.net/projects/libjpeg-turbo/files/
The procedure is documented in **BUILDING.md**.

**Comment by alex-tee** [comment]
The excuse for not allowing multiple architectures (same in #512 ) seems to be that libjpeg-turbo contains assembly code, however that is not the case when `WITH_SIMD` is false. So the check in CMakeLists that does `if(COUNT GREATER 1)` could be changed to `if(WITH_SIMD AND COUNT GREATER 1)`. This works in my universal builds since I don't care about SIMD for this library.

Unless my logic is wrong, please fix the if-condition in CMakeLists. I tried making a pull request but it won't allow me. I can't reopen this issue either.
