### ISSUE TITLE
Clarify scan script specification

### ISSUE THREAD

**Issue by NoraH2004** [libjpeg-turbo/libjpeg-turbo#624]
Hi there,

I have a question regarding custom scan scripts.
I would like to send an image within three scans. 

The first scan should contain all DC coefficients.
The second should contain the 6 most significant bits of all channels' AC coefficients.
The final scan should contain the remaining 2 bits of all channels' AC coefficients.

I was not able to 
1. transfer AC coefficients of all channels within one scan, and 
2. transfer the last 2 bits within one scan (also not individually per channel).

Here is the scan script I would like to use, but did not work:

```
# All DC with all bits for all channels
0,1,2: 0-0, 0,0;

# 6 most significant bits of all channels' AC coefficients
0,1,2: 1-63, 0,2;

# All remaining bits of all channels' AC coefficients
0,1,2: 1-63, 2,0;
```

I was able to compress the image only by sending the channels individually and splitting the last 2 bits into two separate scans.

```
# All DC with all bits for all channels
0,1,2: 0-0, 0,0;

# 6 most significant bits of all channel's AC coefficients
1: 1-63, 0,2;
2: 1-63, 0,2;
0: 1-63, 0,2;

# Next-to-least significant bit of all channel's AC coefficients
1: 1-63, 2,1;
2: 1-63, 2,1;
0: 1-63, 2,1;

# All remaining bits of all channel's AC coeffs
1: 1-63, 1,0;
2: 1-63, 1,0;
0: 1-63, 1,0;
```

The  [wizard.txt](https://github.com/libjpeg-turbo/ijg/blob/main/wizard.txt) explains how custom scan scripts are built, but apparently, there are further constraints. Is there a detailed specification of custom scan scripts available?

Thanks and best,
Nora

**Comment by dcommander** [comment]
I'm afraid that **wizard.txt** and the source code itself are the only references.  I am no expert on scan scripts, and as far as I can tell, your scan script is consistent with the documentation.  Thus, I have no idea what's wrong.

**Comment by dcommander** [comment]
The initial script is failing because apparently AC scans must contain only one component.  Then your second attempt failed because apparently only the first AC scan can contain more than 1 bit.  I agree that the documentation is vague on those points.  **wizard.txt** just refers the reader to the JPEG spec.  Even the [Wallace paper](https://www.ijg.org/files/Wallace.JPEG.pdf) is a bit vague:

"Upon a coefficient’s first encoding, the N most significant bits can be encoded first, where N is specifiable. In subsequent scans, the less significant bits can then be encoded."

This doesn't specify that the subsequent scans must contain only one bit each.  :|
