### ISSUE TITLE
-dev branch breaks libtiff (and other packages) builds due to missing BITS_IN_JSAMPLE define

### ISSUE THREAD

**Issue by rouault** [libjpeg-turbo/libjpeg-turbo#632]
**Clear and concise description of the bug:**

The removal of ``#define BITS_IN_JSAMPLE`` in jmorecfg.h breaks libjpeg users, such as libtiff:
```
/home/even/libtiff/libtiff/tif_jpeg.c: In function ‘JPEGSetupEncode’:
/home/even/libtiff/libtiff/tif_jpeg.c:1812:31: error: ‘BITS_IN_JSAMPLE’ undeclared (first use in this function)
 1812 |   if (td->td_bitspersample != BITS_IN_JSAMPLE)
      |                               ^~~~~~~~~~~~~~~
```

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Download http://download.osgeo.org/libtiff/tiff-4.4.0.tar.gz and build it against libjpeg-turbo current -dev branch
Note that I'm working to add support for libjpeg-turbo -dev branch in libtiff master, so the issue is only for currently released versions.
I see it will also break GDAL that tests BITS_IN_JSAMPLE in a number of places

Searching in all sources of Debian (https://codesearch.debian.net/search?q=BITS_IN_JSAMPLE ), I see that other software like FFMPEG will be affected: https://sources.debian.org/src/ffmpeg/7:5.1.2-1/libavcodec/jfdctint_template.c/?hl=122#L122

Not sure if the #define should be re-installed and set to 8, or if it should be documented as a breaking change somewhere.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

All

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

commit 140a1ea315b1b1cabe931072643877793b877386 (HEAD -> dev, origin/dev)

**Comment by dcommander** [comment]
Thinking out loud, I guess we could define `BITS_IN_JSAMPLE` to `8` externally, in order to preserve backward compatibility with prior versions.  That is more or less truthful, because we now use a different data type (`J12SAMPLE`) for 12-bit precision (so `JSAMPLE` still is, literally, an 8-bit data type.)  Also, 12-bit precision is an opt-in feature, so existing programs will only be able to access 8-bit precision unless they explicitly call the new `jpeg12_*` functions.  (IOW, software that worked properly with 8-bit builds of libjpeg-turbo 2.1.x and prior should still work the same way with libjpeg-turbo 2.2.x, so that supports the argument that we should continue defining `BITS_IN_JSAMPLE` to `8`.)

However, if downstream software still expects to be able to redefine `BITS_IN_JSAMPLE` to `12` and thus build a 12-bit-only version of libjpeg-turbo, that certainly will no longer work.  Such software will need to be modified to use the new 12-bit API functions, as demonstrated in **example.c**.  Also, I may need to change `BITS_IN_JSAMPLE` to something else internally, since I currently use that macro to build both 8-bit and 12-bit versions of relevant modules for inclusion in the same library.  (IOW, if I reintroduce `#define BITS_IN_JSAMPLE` into **jconfig.h**, I would have to either guard it with `#ifndef BITS_IN_JSAMPLE`, or I would get macro redefinition warnings when building the 12-bit modules.)  Why do I fear that, if I change that macro internally, someone else is going to complain?

BTW, libjpeg-turbo has traditionally defined `BITS_IN_JSAMPLE` in **jconfig.h**, not in **jmorecfg.h**.  That has been the case since libjpeg-turbo 1.4, when we added the ability to specify 12-bit precision in the build system (whereas libjpeg required one to modify **jmorecfg.h** in order to build with 12-bit precision.)

**Comment by rouault** [comment]
> Thinking out loud, I guess we could define BITS_IN_JSAMPLE to 8 externally

+1

> However, if downstream software still expects to be able to redefine BITS_IN_JSAMPLE to 12

Regarding libtiff, traditional support for 12-bit jpeg involved building the TIFF JPEG twice, once against includes of libjpeg "traditional" (IJG >= 6b series or libjpeg-turbo) with BITS_IN_JSAMPLE = 8, and another time against a modified copy of libjpeg 6b where jmorecfg.h was replaced to have BITS_IN_JSAMPLE = 12 and different #define renaming hacks so that symbol names of libjpeg 6b 12-bit don't conflict with the ones of libjpeg(-turbo) 8-bit.  So all in all, the fact that libjpeg(-turbo sets  BITS_IN_JSAMPLE = 8 doesn't affect the hacky old way of supporting 12-bit. Not sure if that's clear...

Anyway in https://gitlab.com/libtiff/libtiff/-/merge_requests/422 I've the changes to support libjpeg-turbo 2.2dev. In https://gitlab.com/libtiff/libtiff/-/merge_requests/422/diffs#b608e95caaafb8d17dc9d74cffe80a1b68ce08e0_127_139, I provisioned to #undef BITS_IN_JSAMPLE to redefine it to 8 for tif_jpeg.c built for 8-bit support and to 12 for tif_jpeg12.c built for 12-bit support.

> BTW, libjpeg-turbo has traditionally defined `BITS_IN_JSAMPLE` in **jconfig.h**, not in **jmorecfg.h**

sorry, yes that's what I meant. I guess I was confused with the legacy of use of the modified-for-12-bit-support-libjpeg-6b that uses jmorecfg.h for that
