### ISSUE TITLE
memory requirement of decoding jpegs

### ISSUE THREAD

**Issue by ChinaTizenRT** [libjpeg-turbo/libjpeg-turbo#639]
which factors will mainly influence the memory requirement of decoding jpegs?

if the resolution is more bigger,  the memory get mucher?
of the internal structure (such as compress ratio) influence the memory consuption, thanks

**Comment by dcommander** [comment]
If you are using the libjpeg API, which supports buffered I/O, then you can mostly control the memory consumption by way of the source/destination manager that you choose or implement.  (For instance, the in-memory source and destination managers-- `jpeg_mem_src()` and `jpeg_mem_dest()`-- use a 4k buffer by default.)  There are some exceptions, such as compressing/decompressing a progressive/multi-scan JPEG file or performing Huffman optimization, both of which require buffering the full image to memory.  Otherwise, libjpeg was originally designed to run on 640k MS-DOS machines, so it is possible to configure it to use very little memory.  Note that the API includes a structure field (`max_memory_to_use`) that can be used to place a limit on total memory consumption.  Refer to **libjpeg.txt** and **structure.txt** for further details.
