### ISSUE TITLE
Scaling during decompression - fractional edge pixels

### ISSUE THREAD

**Issue by nathanaeljones** [libjpeg-turbo/libjpeg-turbo#64]
Is there a way to know what fraction of a pixel the right/bottom edge pixels represent?

Say you take a 65x65 pixel image and scale it 1/4, you would get a 17x17 pixel result (possibly 18x18 uncropped, if the original was 72x72 in terms of whole blocks).   The 17th pixels would only represent 1/4th of a pixel, however. (I'm assuming here that edge pixels are duplicated to fill the remaining part of a given block prior to averaging). 

This could be calculated after the fact with sufficient knowledge of libjpeg-turbo internals, but perhaps it is already exposed somewhere?

This value is useful if one is later performing true image resampling, where the pixel weight can be plugged into the contribution calculations and subsequently be compensated for - perfectly.

**Comment by dcommander** [comment]
DCT scaling occurs in frequency space, not in image space, so when you scale by 1/4 (for instance), you're using a special DCT algorithm that takes an 8x8 block from frequency space and outputs a 2x2 block in image space.  I don't profess to be a signal processing expert-- I only had to take one course on that when I was getting my engineering degree-- but my understanding is that the scaled DCTs basically reduce the high frequencies in the image but then project the resulting lower-frequency image onto a smaller number of pixels.  I don't know what that means in terms of edge pixels.  I'd have to spend a lot of time examining the code, which you could do just as easily.

**Comment by nathanaeljones** [comment]
I don't understand the codebase well, but [comments imply that edge pixels are duplicated outwards](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jcsample.c#L20), which would imply data is spatially relative?  Or is this happening in YCbCr space? I truthfully don't understand the call graph here, but I'll spend more time digging into it.

**Comment by dcommander** [comment]
The edge pixels are duplicated outward during compression, yes, because JPEG images have to consist of full 8x8 MCU blocks.  This is done after RGB-->YCbCr color conversion but prior to chroma upsampling.  As to how that affects the scaling algorithm during decompression, I'm not entirely sure, but I can say that the scaled IDCT algorithms basically ignore some of the frequency-space coefficients.  4x4 (1/2 scaling) ignores row/column 4;  2x2 (1/4 scaling) ignores rows/columns 2, 4, & 6;  1x1 (1/8 scaling) ignores everything but the DC coefficient.  But my understanding is that these are cheats that you can only get away with if you are scaling down by a power of 2.  Otherwise, the algorithms have to be more complex.  Good luck.

**Comment by nathanaeljones** [comment]
Yeah, I'm primarily interested in power-of-two anyhow.
