### ISSUE TITLE
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library

### ISSUE THREAD

**Issue by LordOfDragons** [libjpeg-turbo/libjpeg-turbo#644]
Steps to reproduce:
- Create a new DLL project
- Download the prebuilt jpeg-static.lib
- Compile
- Build shows warning: LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library

The static libraries should be compiled without linking to a specific runtime. This way the runtime of the DLL/EXE linking against the static library is used.

Build System:
- Windows 10, 64-Bit
- Visual Studio 2022

Used precompiled library: libjpeg-turbo-2.0.3-vc64

**Comment by dcommander** [comment]
Either pass `/NODEFAULTLIB:libcmt` to the linker or build libjpeg-turbo from source with the `WITH_CRT_DLL` CMake variable enabled.  Unfortunately it isn't possible for us to support all permutations of Windows CRT linkage.  I chose libcmt because I prefer that my applications not depend on the CRT DLLs.  Fortunately it is easy to override my preference by using the aforementioned linker flag.

Suffice it to say that I am fully aware of all of the ramifications of this issue, I have heard a variety of arguments from a variety of people, and I have considered them multiple times over the past 12 years.  I have no intention of changing my position on this at the moment.
