### ISSUE TITLE
Update or remove GNUInstallDirs.cmake

### ISSUE THREAD

**Issue by atsampson** [libjpeg-turbo/libjpeg-turbo#648]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No.

**Clear and concise description of the bug:**

libjpeg-turbo bundles a 4-year-old version of `GNUInstallDirs.cmake`, which handles `CMAKE_INSTALL_LIBDIR` incorrectly when using cmake 3.25.2.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

The problem occurs if you set `CMAKE_INSTALL_LIBDIR` to a relative path - it's treated as being relative to the source directory, rather than the destination directory. (There are other applications that **only** support this being a relative path, so distributions will do this if they're trying to override the `lib64` behaviour or similar.)

```
cd
tar xzvf libjpeg-turbo-2.1.5.tar.gz
cd libjpeg-turbo-2.1.5
cmake -DCMAKE_INSTALL_PREFIX=/tmp/dest -DCMAKE_INSTALL_LIBDIR=lib .
make -j8
make install
```

**Image(s) needed in order to reproduce the bug (if applicable):**

N/A

**Expected behavior:**

Libraries are installed to  `/tmp/dest/lib`.

**Observed behavior:**

Libraries are installed to `~/libjpeg-turbo-2.1.5/lib`.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

cmake 3.25.2 (I think 3.24 was OK), GCC 12.2, GNU/Linux, amd64.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

Found in the 2.1.5 tarball; confirmed with `master` at fd93d98a959ac3700e2da07310a44867c9c46f03.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

N/A

**Additional information:**

Removing the bundled file and just saying `include(GNUInstallDirs)` in `CMakeLists.txt` fixes the problem - it's been shipped with CMake since 2011 so that's probably the easiest fix.

**Comment by dcommander** [comment]
Our version of GNUInstallDirs contains customizations not present in the upstream version, so using the upstream version isn't an option.  It would be nice if CMake didn't break things, but I guess that's too much to expect.  I'll investigate.

**Comment by dcommander** [comment]
Does it work if you add `PATH:` to the variable, as **BUILDING.md** instructs?  If so, then this is a non-issue.  Our implementation of **GNUInstallDirs** is specific to our project, and its behavior is specific to our project as well.  That behavior is documented in **BUILDING.md** and shouldn't be expected to mirror the behavior of the upstream version, so unless the behavior differs from the documented behavior, it isn't a bug.

**Comment by dcommander** [comment]
Since the build system behaves as documented, this isn't a bug.  It's a feature request, and because our project accrued a large funding deficit in the context of finishing the 3.0 beta1 release, I can't work on any feature requests using the libjpeg-turbo General Fund until that deficit is covered.  (Refer to https://groups.google.com/g/libjpeg-turbo-announce/c/1tjx8XZN3EE/m/jZfp4_tkAgAJ.)  More specifically, I have to cover about 77 hours, and the General Fund only refreshes at the rate of about 8-10 hours/month.

Even if you submitted a PR, it would take some time for me to test it and verify that it doesn't break any of our customizations, and unless someone specifically pays for that time, I won't have the funding to cover it until 2024.  If I'm going to dig into GNUInstallDirs, I want to spend the time to dig into it thoroughly and see if it is possible to implement our customizations without duplicating the functionality of the whole file.  That's going to require a lot of testing (preferably via an automated test that iterates through the permutations of the various directory variables.)  Since I use the same customized GNUinstallDirs in my other projects, I'm interested in improving it in all of those projects, but not right now.

**Comment by arrowd** [comment]
I just bumped into this because CMake documentation says the default directory for manpages is `${PREFIX}/share/man`, while libjpeg-turbo insisted on `${PREFIX}/man`. After digging it a bit I found that it ships its own `GNUInstallDirs.cmake` with old defaults.

If using CMake's module is not an option, would you like a PR fixing this specific case?

**Comment by dcommander** [comment]
No, libjpeg-turbo's default install paths are based on its specific packaging needs. Bear in mind that libjpeg-turbo was originally a drop-in replacement for libjpeg v6b that applications could use at run time by manipulating `LD_LIBRARY_PATH`. Thus, it historically installed under **/opt/libjpeg-turbo** so as not to interfere with the operating system's libjpeg installation. Even though practically every Linux distribution ships libjpeg-turbo now, few of them ship the latest version or the complete set of APIs. (The Java API, in particular, is hardly ever packaged by O/S distributors.) Thus, we still install under **/opt/libjpeg/turbo** by default, so as not to interfere with the operating system's libjpeg-turbo installation. Most people who need to build libjpeg-turbo from source need to do so because the system’s libjpeg-turbo installation is insufficient. Thus, the default paths in our build system are geared for libjpeg-turbo user/developers, not for downstream packagers. The defaults are easy enough to override, for those who want to package libjpeg-turbo in different ways, but it isn’t incumbent upon us to conform to another project’s defaults unless those defaults make sense for us.

All of that aside, the build system should be using a default man path of **/usr/share/man** if the prefix is **/usr**. I thought that I had made that modification to libjpeg-turbo, but maybe I was thinking of another of the projects I maintain. I will look into that specific issue next week.

I am still also planning to look into reusing CMake’s **GNUInstallDirs.cmake**, but I am not sure if it will even be possible to make it do what we need it to do. (See above. It obviously didn’t in the past, which is why I had to modify it and use an in-tree copy.) This project was on the back burner due to lack of project funding, but thanks to some sponsorships that landed this month, I should be able to look into it soon.

**Comment by dcommander** [comment]
Referring to the [commit log](https://github.com/libjpeg-turbo/libjpeg-turbo/commits/main/cmakescripts/GNUInstallDirs.cmake) for our in-tree version of **GNUInstallDirs.cmake**, there are some enhancements to it (such as the ability to override the default directories) that don't exist in the upstream version and couldn't be bolted onto it.  Also, I prefer not to have to re-test our build system every time CMake changes something.  Thus, I think it would be best to address the specific issues that have been raised with our in-tree version of **GNUInstallDirs.cmake** rather than attempting a wholesale replacement of it.

1. Our in-tree version of **GNUInstallDirs.cmake** already uses a default man page directory of `<CMAKE_INSTALL_PREFIX>/share/man` if you override `CMAKE_INSTALL_PREFIX`.  I just verified that it works as expected if `CMAKE_INSTALL_PREFIX` is set to `/usr`, so I don't understand the complaint in https://github.com/libjpeg-turbo/libjpeg-turbo/issues/648#issuecomment-1890437285.  @arrowd Can you clarify how you are attempting to configure the build?
2. The need to prefix relative paths with `PATH:` is, although a documented requirement of the build system, admittedly awkward and prone to user confusion.  I will look into the possibility of fixing that.

**Comment by arrowd** [comment]
I believe this part is what sets it to just `man/` instead of `share/man` https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/cmakescripts/GNUInstallDirs.cmake#L314

**Comment by dcommander** [comment]
@arrowd Ah, OK, you didn't mention you were using FreeBSD.  The core issue is that we need to integrate https://github.com/Kitware/CMake/commit/f835f189aeb38a791ad09ba5c2d89300a3fd16f1 and https://github.com/Kitware/CMake/commit/c07bba27302960fc2f35b6a9e00eab8b32ca9a49.  That's easy enough.

**Comment by dcommander** [comment]
5a2353c2dad951af3f823ca4f9bdee293876cea1 should address the two aforementioned issues.  Please test.
