### ISSUE TITLE
multiple threads

### ISSUE THREAD

**Issue by DavidBrenner3** [libjpeg-turbo/libjpeg-turbo#65]
Hi,

And thank you for this wonderful code.

Right now I'm trying to use jpeg62.dll (1.4.9 version) in a Delphi application for decoding many (almost identical) jpeg files into TBitmaps as fast as possible.
The decoder is very fast (< 1 ms on a 768x768 24 bit image) but moving the data into the bitmap is slow (30..40 ms).
I'm using this code:

//variables
   jpeg: jpeg_decompress_struct;
   jpeg_err: jpeg_error_mgr;
   prow: Prgbarray;
   RowD: Prgbarray;

   ...........

   // reading image
   jpeg_start_decompress(@jpeg);

   // allocate row
   GetMem(prow, jpeg.output_width * 3);

   //here becomes very slow
   inherited SetSize(jpeg.output_width, jpeg.output_height);
   inherited PixelFormat := pf24bit;
   for y := 0 to jpeg.output_height - 1 do
   begin
      // reading row
      jpeg_read_scanlines(@jpeg, @prow, 1);
      rowD := scanline[y];
      for x := 0 to jpeg.output_width - 1 do
      begin
         rowD[x].RgbtRed := prow[x].Rgbtblue;
         rowD[x].Rgbtgreen := prow[x].Rgbtgreen;
         rowD[x].Rgbtblue := prow[x].RgbtRed;
      end;
   end;

Is there any way to speed it up?

I thought about using multiple threads.
I already tried decoding separate jpegs into separate bitmaps (each in its own thread), but I got access memory violation.

---------------------------
Debugger Exception Notification
---------------------------
Project Test.exe raised exception class $C0000005 with message 'access violation at 0xfeeefeee: read of address 0xfeeefeee'.
---------------------------
Break   Continue   Help   
---------------------------

I get the exactly same error from all threads.
It's like the decoder is using the same memory range in all threads. Which is weird because the threads are using separate memory.

Any advice?

Thank you in advance.

Best regards,
David

**Comment by dcommander** [comment]
This code is what's slowing you down:

    for x := 0 to jpeg.output_width - 1 do
    begin
    rowD[x].RgbtRed := prow[x].Rgbtblue;
    rowD[x].Rgbtgreen := prow[x].Rgbtgreen;
    rowD[x].Rgbtblue := prow[x].RgbtRed;
    end;

Single-byte pixel transfers are literally the slowest image processing algorithm in the world.  You seem to be doing this because you need BGR instead of RGB output, but you can tell libjpeg-turbo to output BGR directly by setting the output colorspace to `JCS_EXT_BGR` (not sure how exactly that's implemented in Delphi, but in C we would do `cinfo.out_color_space = JCS_EXT_BGR` prior to calling `jpeg_start_decompress()`.)

Also, with regards to multithreading, you would need to use a separate jpeg_decompress_struct for each thread.  Multithreading works well if your image is already broken up into different JPEG tiles and you can decode each tile separately.  It doesn't work well for decoding a single image, however.
