### ISSUE TITLE
Question : best way of referencing library when adding as external project

### ISSUE THREAD

**Issue by boxerab** [libjpeg-turbo/libjpeg-turbo#654]
I am adding libjpeg-turbo to my project as follows :

```
  ExternalProject_Add(libjpeg-turbo
                      CMAKE_ARGS
                        -DENABLE_SHARED=OFF
                        -DENABLE_STATIC=ON
                        -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/libjpeg-turbo
                        -DCMAKE_INSTALL_LIBDIR=${CMAKE_BINARY_DIR}/bin
                        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  				      GIT_REPOSITORY https://github.com/libjpeg-turbo/libjpeg-turbo.git
  					  GIT_TAG        2.1.5.1)
if(WIN32)
  set(JPEG_LIBNAME ${CMAKE_BINARY_DIR}/bin/jpeg-static.lib PARENT_SCOPE)
else(WIN32)
  set(JPEG_LIBNAME ${CMAKE_BINARY_DIR}/bin/libjpeg.a PARENT_SCOPE)
endif(WIN32)
```

and then I use `${JPEG_LIBNAME}` in `target_link_libraries`

Is there a less ugly way of determining the name of the static library, on both Windows and Linux\MacOS ?

**Comment by dcommander** [comment]
You could have CMake install libjpeg-turbo into a directory under your build directory and then include the libjpeg-turbo CMake config file, but honestly, I would just do what you are doing. Five lines of code isn't that ugly, and the libjpeg-turbo library names aren't going to change. You can also pass `WITH_TURBOJPEG=0` to our build system to disable the TurboJPEG API library, since you aren't using it.

**Comment by boxerab** [comment]
Thanks!
