### ISSUE TITLE
On using semver compatible prereleases

### ISSUE THREAD

**Issue by dvzrv** [libjpeg-turbo/libjpeg-turbo#655]
Hi! I package libjpeg-turbo for Arch Linux.
Downstreams usually use tooling such as nvchecker to track upstream development and releases.

For upstreams using git it is very easy to track the releases via (some form of) `git ls-remote -t <link>` and ignore version strings that e.g. contain prerelease identifiers (such as -alpha, -beta1.1, etc.).

This workflow is unfortunately not possible with libjpeg-turbo, as an arbitrary number is chosen to serve as prerelease version (i.e. a patch level number above 90 serves as beta for the next major version release), which shadows new releases (e.g. 2.1.5.1).

Can the versioning scheme for prereleases be switched to something [semver](https://semver.org) compatible? That way it would be very clear what is a stable version and what is not and it would not lead to shadowing of stable releases.

**Comment by dcommander** [comment]
There is nothing arbitrary about it.  Our versioning scheme is [documented](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) and matches that of other open source projects.  (In fact, I adopted our scheme based on TigerVNC's, because libjpeg-turbo originated in that project.)  This scheme is basically a form of [Numeric 90+ Versioning](https://en.wikipedia.org/wiki/Software_versioning#:~:text=Numeric%2090%2B%20is%20another%20scheme,open-source%20projects%20like%20Fontconfig).  X.X.80-.89 are alpha pre-releases, which are only ever available on https://libjpeg-turbo.org/DeveloperInfo/PreReleases.  They are never posted to SourceForge or given Git tags.  X.X.90-.94 are beta releases.  X.X.95-.99 are release candidates.  Anything else is a final or bug-fix release.  Alpha, beta, and RC versions have the same major and minor version as the previous release series.

The primary justification for this scheme-- and the reason why using identifiers such as "alpha", "beta", etc. isn't viable-- is to ensure proper behavior with various package managers.  Package managers don't typically know how to deal with non-numeric identifiers in version numbers.  In fact, one of my other projects-- VirtualGL-- used to use a scheme more similar to SemVer, but I got numerous complaints about package managers not being able to handle the `beta1` identifier in beta versions.  Thus, all of my projects, including libjpeg-turbo, have been using the same Numeric 90+-style versioning scheme since 2010.  When a beta version is released, the version number will automatically cause package managers to replace the current stable release.  That is by design, to encourage people to test the beta release during the 3-month beta period, rather than report bugs the day after the beta goes final.  If people don't want to test beta releases, then they can ignore any version ending in `\.9[0-9]`, as demonstrated [here](https://libjpeg-turbo.org/Downloads/YUM) for our YUM repository.

If you want to determine the set of non-beta public releases from our Git tags, then simply ignore any tags beginning with `jpeg-`, ending in `-esr`, or ending in `\.9[0-9]`.  That doesn't seem any more difficult than looking for identifiers such as `-alpha`, `-beta1`, `-rc1`, etc.
