### ISSUE TITLE
Heap Buffer Overflow in /libjpeg-turbo/jquant2.c:224 at prescan_quantize() (SIGSEGV)

### ISSUE THREAD

**Issue by chameleon10712** [libjpeg-turbo/libjpeg-turbo#668]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No

**Clear and concise description of the bug:**

I found a poc which can cause djpeg crash when fuzz testing. 

> AddressSanitizer report it a heap buffer overflow in /libjpeg-turbo/jquant2.c:224 at prescan_quantize()

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Normal run:
```
$ ../build_norm/djpeg -colors 10 -rgb565 ./poc1min.jpg
fish: “../build_norm/djpeg -colors 10…” terminated by signal SIGSEGV (Address boundary error)
```

Asan report:
```
$ ../build_asan_g/djpeg -colors 10 -rgb565 ./poc1min.jpg
=================================================================
==2390006==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62900000939a at pc 0x7f0438ef479b bp 0x7ffeb86ef390 sp 0x7ffeb86ef380
READ of size 2 at 0x62900000939a thread T0
    #0 0x7f0438ef479a in prescan_quantize /home/oceane/fuzz_test/new_djpeg/libjpeg-turbo/jquant2.c:224
    #1 0x7f0438eda642 in post_process_prepass /home/oceane/fuzz_test/new_djpeg/libjpeg-turbo/jdpostct.c:192
    #2 0x7f0438eca918 in process_data_context_main /home/oceane/fuzz_test/new_djpeg/libjpeg-turbo/jdmainct.c:381
    #3 0x7f0438e074a4 in output_pass_setup /home/oceane/fuzz_test/new_djpeg/libjpeg-turbo/jdapistd.c:139
    #4 0x560835de2f8f in main /home/oceane/fuzz_test/new_djpeg/libjpeg-turbo/djpeg.c:708
    #5 0x7f0438baa0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #6 0x560835de4b3d in _start (/home/oceane/fuzz_test/new_djpeg/libjpeg-turbo/build_asan_g/djpeg+0x8b3d)

Address 0x62900000939a is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow /home/oceane/fuzz_test/new_djpeg/libjpeg-turbo/jquant2.c:224 in prescan_quantize
Shadow bytes around the buggy address:
  0x0c527fff9220: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff9230: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff9240: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff9250: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff9260: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c527fff9270: fa fa fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff9280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff9290: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff92a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff92b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fff92c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2390006==ABORTING
```

**Image(s) needed in order to reproduce the bug (if applicable):**

![poc1min.jpg](https://user-images.githubusercontent.com/25949382/227706134-e3f5c229-ca3a-403c-b9ff-36058ce61ab8.jpg)

**Expected behavior:**

Without crash.

**Observed behavior:**

djpeg crashes with SIGSEGV.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Ubuntu 20.04.4 LTS
Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
```

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

```
$ git log --oneline -1
cc8c6d36 (HEAD -> main, origin/main, origin/HEAD) tjbenchtest: Test all subsampling types

$ ../build_norm/djpeg -version
libjpeg-turbo version 2.1.92 (build 20230325)
```

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
Please test whether the bug is reproducible with the 2.1.x branch. That will tell me whether it is a regression.

**Comment by chameleon10712** [comment]
This bug is not reproducible with the 2.1.x branch.

**Comment by dcommander** [comment]
This issue and #669 actually are reproducible with libjpeg-turbo 2.1.x and prior if you enable 12-bit data precision (set the `WITH_12BIT` CMake variable to `1`.)  The rest of the issues (#670, #671, #672, #673, #674, #675, #676, #677, #678, #679, #680, and #681) have reproducers with SOF markers of 0xffc3 (lossless JPEG w/ Huffman coding) and thus cannot be reproduced with libjpeg-turbo 2.1.x and prior, but the issues themselves are not specific to lossless JPEG.  It should be possible to craft reproducers that expose the issues in libjpeg-turbo 2.1.x and prior.  None of the issues are reproducible in libjpeg v6b because the issues or their reproducers require features (RGB565, lossless JPEG, decompression of motion JPEG frames) that are not present in libjpeg v6b.  Again, however, it should be possible to craft reproducers that expose the issues in libjpeg.

The underlying cause of the issues is the same.  The libjpeg API library uses a signed `short` datatype to store 12-bit sample values, so 12-bit is the only data precision for which the datatype range (-32768-32767) exceeds the valid sample range (0-4095).  The libjpeg code did not adequately guard against out-of-range 12-bit sample values when those values were used as array indices.  These issues were exposed in the default build of libjpeg-turbo 3.0.x because libjpeg-turbo 3.0.x now handles 12-bit data precision by default, whereas previous versions of libjpeg-turbo (and libjpeg) required recompiling the code in order to handle 12-bit data precision.  libjpeg uses a `GETJSAMPLE()` macro to optionally load 8-bit samples into a signed `char` datatype if the (broken and obsolete) compiler lacks support for `unsigned char`.  I used the instances of that macro in libjpeg v6b as hints for where 12-bit samples are unchecked and may exceed the valid sample range.  In all of those places where the sample values are subsequently used as array indices, a new macro (`_GETJSAMPLE()`) is now used to load the samples.  That macro is a no-op for 8-bit and 16-bit precision and maps to `GETJSAMPLE() & 4095` for 12-bit data precision.  This covers all of the aforementioned issues as well as a few additional issues that were not covered.

This issue, #671, and #680 have an ancillary cause, which is an oversight that occurred when adding the `JCS_RGB565` colorspace in libjpeg-turbo 1.4.x.  The libjpeg code traditionally enabled 2-pass quantization for colorspaces with 3 components, but really 2-pass quantization only works with colorspaces that have 3-sample pixels.  RGB565 is a special case, since it has 3 components but 2-sample pixels, so libjpeg-turbo now explicitly disables 2-pass quantization if the output colorspace is RGB565.  djpeg will ultimately fail if both `-rgb565` and `-colors` are specified, because none of its destination managers (image writers) support color quantization with RGB565.  However, the aforementioned out-of-range sample values triggered failures when initializing 2-pass quantization, which occurred before the destination manager had a chance to fail.

Fixes will be pushed shortly.

**Comment by dcommander** [comment]
Scratch that.  Unfortunately masking the samples to 4095 causes a severe performance regression with 32-bit code.  :(

**Comment by dcommander** [comment]
I am unfortunately at a loss for how to fix this without performance regression.  Our project funding was completely exhausted until next January, and because of the time I have spent on these issues, the funding is now exhausted until next March.  I'm not sure what to do except to beg the community once again for funding, with the understanding that libjpeg-turbo 3.0 is at risk of not being released until next year unless such funding can be secured in a timely manner.  I cannot continue to eat thousands of dollars of cost on every major new release, particularly when the cost is due to oversights in 30-year-old code that I didn't write.

**Comment by chameleon10712** [comment]
I'm sorry to hear that. Hope you can get enough funding for fixing these bugs.
Please let me know if I can be of any help.

**Comment by dcommander** [comment]
Corrections to my comment above:

- The underlying cause of this issue is not an out-of-range sample but rather an uninitialized value, the result of `prescan_quantize()` assuming a 3-sample pixel format.  Thus, avoiding 2-pass quantization if the output colorspace is RGB565 is the correct fix.

- #670 through #681 are in fact lossless-specific, the result of failing to range-limit the output of the predictor.

- I am still trying to figure out #669, since the fix for it is what caused the aforementioned performance degradation.  It appears to be specific to partial image decompression.
