### ISSUE TITLE
2.1.91 (3.0 beta2): compression fails with "Improper call to JPEG library in state 101" when done threaded and in parallel

### ISSUE THREAD

**Issue by YorVeX** [libjpeg-turbo/libjpeg-turbo#691]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
I use libjpeg-turbo to compress a live video feed, which means calling it for example 60 times per second for 60 fps feeds. When I call tjCompress2() synchronously there is no issue and it works very stable. When calling it several times in parallel the call will fail with error 1: "Improper call to JPEG library in state 101". I also tried to use the new model with calling tj3Init() first and then for each frame call tj3Compress8() but the result remains the same, I get the error in async mode and synchronous is fine. For tj3Compress8 I also tried with both lossy and the new lossless mode, same issue.

When I use the exact same code with tjCompress2() but use the stable 2.1.5.1 version it never fails on parallel calls.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Call tjCompress2() or tj3Compress8() multiple times in parallel.

**Image(s) needed in order to reproduce the bug (if applicable):**
Image doesn't seem to matter, happens at arbitrary frames in the test video feed.

**Expected behavior:**
Library is thread-safe, multiple parallel calls to the compression methods don't fail in 2.1.91 just as in 2.1.5.1.

**Observed behavior:**
Library is not thread-safe, multiple parallel calls to the compression methods fail.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Official turbojpeg.dll binary build for 2.1.91 (3.0 beta2), Windows 10 64 bit.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
2.1.91 (3.0 beta2)

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**
I am using TJFLAG_NOREALLOC, compression quality 90, TJPF_RGB + TJCS_RGB, TJSAMP_444.

**Comment by YorVeX** [comment]
Someone just pointed out to me that the problem might be that I am using the same handle for all of the (parallel) calls. So far I was thinking that this would be fine, especially since this doesn't seem to pose an issue with the current stable version. But given that the message indicates the state is tracked somewhere I guess this "somewhere" is the handle and the state gets confused when it's used by multiple compression processes?

Unfortunately the documentation for the init or compression functions don't mention whether a handle can be used multiple times in parallel.

Did the stable version use a locking mechanism when accessing the handle that the beta version doesn't have anymore?

**Comment by YorVeX** [comment]
I already did find my answer in #584 - although I had seen this issue earlier, I missed the passage that says that indeed multiple init calls are necessary for multi-threaded use and only found it now on a second read. Sorry for bothering.

Feel free to close it then, I'd still be curious about possible explanations as to why I don't run into any issues with the stable version though.

It's quite annoying for me, since this is called from a managed task pool (the .NET TPL) where the code that calls the compression method doesn't know anything about other threads (that I don't have to care about this being the whole idea of the TPL). For simplicity I could now surround every tj3compress8() call with tj3Init() and tj3Destroy() calls. Ironically the v3 API that was initially making things simpler for me (less parameters to had over for each compress call) suddenly looks a lot worse, because I also need to make 5 tj3Set() calls every single time. Or I a thread safe pool of pre-initialized handles, which adds a lot of complexity to the code.

**Comment by dcommander** [comment]
The underlying libjpeg API is not thread-safe, and it never has been throughout its 32-year history, unless you use one API instance per thread. (This is documented in libjpeg.txt, if I recall.) Thus, the TurboJPEG API is limited by the underlying libjpeg API. The fact that the TurboJPEG 2.x compress function allowed multiple threads to share the same handle was purely accidental. I doubt that that would have been true in all use cases, nor would it have been true for other TurboJPEG functions.

The TurboJPEG 2.x API is still emulated, so if you don't like `tj3Set()`, you can continue to use the old functions. I had an open issue posted for years in order to solicit ideas for the TurboJPEG 3 API. No one responded to it. I chose the approach that I chose because it makes the API much more extensible. Using stateless arguments for configuration parameters is poor design, because (a) eventually the function signature would become ridiculously long if I continued to add parameters and (b) each time I added a parameter, it would have been necessary to implement a new version of the function. I could potentially add a `tj3Clone()` function that creates a new instance and copies parameters from an existing instance. Would that solve the problem?

**Comment by YorVeX** [comment]
Thanks for taking the time to write this response. Guess that not having issues with v2 is just a coincidental side-effect of something else then.

Don't get me wrong, I totally get why tj3Set() was implemented and my first thought when I saw this compared to v2 was that it definitely is an improvement, and only now with the threaded situation I realized that it's suddenly becoming a bit of a hassle there. Code wise (my other compression functions for QOI and LZ4 are one-liners as opposed to this being surrounded by 7 extra calls (tj3Init, tj3Destroy and 5x tj3Set) and maybe also from performance perspective, although even with this being executed 60 times per second it probably doesn't really matter too much.

The one thing I could think of is having tj3Set() applied not to a handle to the compression object, but to an internal settings object. Then this settings object could be reused for every compress call by either being passed to the compression function directly (that already solves your problem with the function signature with an increasing number of parameters in the future), to the tj3Init() function as additional parameter or to a separate new tj3ApplySettings() function that can apply any settings object to any compression handle.

(compression here being interchangeable with decompression or transform)

**Comment by dcommander** [comment]
Anything global, such as a global settings object, would need to have some sort of mutex, and libjpeg-turbo cannot depend on a threading library. The idea behind `tj3Clone()` is that the calling application could maintain its own global settings object and clone it into sub-objects that are actually used for compression/decompression. I posit that you could achieve the same result with that one function that you could achieve with the various API modifications you describe above. Given that `tj3Clone()` would return an initialized object, you could initialize the settings object in the main thread and set its parameters, then you could call `tj3Clone()` in the secondary threads to clone the settings and initialize a thread-specific object to pass to `tj3Compress8()`. 

Or you could just use the API as-is and stop worrying about a handful of additional function calls. More function calls doesn't necessarily mean that the API is more difficult to use, as you implied above. The TurboJPEG 2.x API was difficult because you had to remember all of the function arguments and their order. I personally find it a lot easier to work with the TurboJPEG v3 API, although it is admittedly a bit more like a reduced instruction set paradigm (fewer instructions to remember but more of them needed to accomplish the same task)
and less like a complex instruction set paradigm.

**Comment by YorVeX** [comment]
I like the tj3Clone() idea but I also agree that if it's all becoming that complicated it's probably not worth the effort just to save a few function calls. Thanks again for taking the time to discuss this and of course for your work on this library in general, I am really impressed by its performance and outside of the issue discussed here (that I already solved with said extra calls) I didn't have a crash with the v3 beta 2 so far, despite pumping 60 frames per second through it for prolonged testing sessions.
