### ISSUE TITLE
Does libjpeg-turbo support CHW format? 

### ISSUE THREAD

**Issue by tachikoma777** [libjpeg-turbo/libjpeg-turbo#693]
which data is storaged as RRRRR GGGGG BBBBB

**Comment by dcommander** [comment]
The most common use case for libjpeg-turbo is to compress a JPEG image from or decompress a JPEG image to an HWC (which we call "packed-pixel") buffer. Using the "raw" functions in the libjpeg API or the YUV functions in the TurboJPEG API, you can also compress from/decompress to a CHW (which we call "planar") buffer. However, this data is not usually RGB. The JPEG algorithms are designed to work most efficiently with YCbCr component planes, so RGB data is typically converted to/from YCbCr (and converted from HWC to CHW simultaneously.) You can create a JPEG image that internally uses RGB component planes rather than YCbCr, but the compression ratio will be significantly worse.
