### ISSUE TITLE
Refactor jpegtran as a re-usable module

### ISSUE THREAD

**Issue by malaterre** [libjpeg-turbo/libjpeg-turbo#696]
I would make sense to provide the `jpegtran` functionalities through a module with a clean API.

Right now users have to copy portion of the JPEG internals in particular the famous `jpegint.h` private header to compile most of the jpegtran/transupp code.

This would expose functionalities of lossless editing of JPEG in a clean way (rotate, crop ...).

Thanks

**Comment by dcommander** [comment]
It sounds simple, but the ramifications of it would be more complicated. It would mean supporting the jpegtran functions as a new external API (an extension of the libjpeg API), even though they were never designed as such. That would require paying more attention to the transform API design, with a specific eye toward user-friendliness, user-proofness, extensibility, and security. Whereas libjpeg-turbo stopped tracking libjpeg API/ABI changes introduced in libjpeg v9+, we still do borrow jpegtran features from libjpeg v9+ from time to time (since those are among the few IJG innovations in the post-Tom Lane era that didn't rely on extending the JPEG format in incompatible and non-standard/unsanctioned ways.) What you ask is possible, but it would require a lot of funding for the implementation and ongoing maintenance/support of the feature. Given that our project's budget is exhausted for the next year, that funding would have to be specifically provided by an organization that is willing to sponsor this feature.

Note that the TurboJPEG API already exposes some of the transform functionality. It would be a much easier task to extend that API to cover the transform features you need than it would be to add transform functionality to the libjpeg API.

**Comment by dcommander** [comment]
@malaterre Would you be open to using the TurboJPEG API to satisfy this feature requirement?  That would be much more likely to happen in the near term.

**Comment by dcommander** [comment]
What implementation would you switch to? libjpeg-turbo is backward API/ABI compatible with jpeg-6b through jpeg-8x (although it doesn't support all of the features in jpeg-8x), but it isn't compatible with jpeg-9x. The only other available implementation, AFAIK, is mozjpeg, which makes extreme performance sacrifices in the name of 10-15% better compression. And it goes without saying that, if I exposed the transformation functions, that would make us less compatible with the other implementations, and you would be even less able to switch.

I am trying my best to evolve the TurboJPEG API into a much more modern interface for JPEG compression/decompression/transformation than the libjpeg API, which is beholden to a 32-year legacy. I also proposed in #313 that the industry come together around completely rethinking the libjpeg API from the ground up, but IIRC only one person cared enough about that to even chime in. Absent that kind of overhaul, I am doing what I can with the limited funding I have, which is to keep incrementally improving TurboJPEG until it covers all but the most esoteric and legacy libjpeg use cases. Strategically, it makes more sense to invest in that than to invest in hacking a 32-year-old API. The libjpeg API is fundamentally fragile because it is so fine-grained and has so many different usage scenarios. It is essentially the API equivalent of CISC, and I would prefer to see the API equivalent of RISC. :) It seems like every time we extend the libjpeg API (for instance, to implement partial image decompression or lossless JPEG), it becomes a security albatross because we weren't able to test some of the millions of permutations of esoteric libjpeg features, and one or more of them inevitably exposes a security flaw in the new API feature. (Inevitably, this happens months or years after the funded development engagement has ended.) It is difficult to fuzz test the libjpeg API because it is so fine-grained, so most of our fuzzers are written against TurboJPEG.

All of that is not to say that what you propose is impossible, but all of that is to say that what you propose is expensive.

**Comment by dcommander** [comment]
After much consideration, I have decided to reject this proposal for multiple reasons:

1. The libjpeg API is 33 years old, unnecessarily fine-grained and complex for modern hardware, and fragile.  Every time I make major changes to it, something breaks, and I have to deal with security reports and bug fixes for months or even years down the road.  I also usually have to eat the cost of those fixes, even if the development of the feature was originally funded.  (As an example, I still occasionally find bugs in the partial image decompression feature, which was submitted and funded by Google in 2015-2016 and introduced in libjpeg-turbo 1.5.x.)  If it is necessary to extend the libjpeg API in order to expand our coverage of the JPEG-1 format (as was the case in libjpeg-turbo 3.0.x) or to add compelling compression/decompression features, then I am willing to do it.  However, exposing an internal lossless transformation API that was never intended to be exposed by its developers is a potential minefield.  (jpegtran was only ever intended to be an example of how to use the `jpeg_read_coefficients()` and `jpeg_write_coefficients()` functions in the public libjpeg API.)
2. It doesn't appear likely that funding will emerge to work on this project.  I would have to estimate the project very conservatively in order to cover the likely possibility of unforeseen bugs and security issues caused by exposing the API, as well as the possibility that the API would have to be refactored in order to make it work properly and safely as a public API.
3. While we [no longer consider libjpeg to be an upstream source](https://libjpeg-turbo.org/About/Jpeg-9), Guido still occasionally introduces new jpegtran features that are worth integrating.  If we made the transupp API public, then it would effectively freeze our lossless transformation implementation (because the transupp API, like the libjpeg API, uses exposed structures), perhaps preventing us from adopting new lossless transformation features in jpegtran or in the TurboJPEG API.
4. The TurboJPEG API is better able to expose the lossless transformation features, because the TurboJPEG API is much less fragile and because it is designed for backward API/ABI compatibility.  The proposed `tj4Transform()` function in the [TurboJPEG 4 API](#646) would use stateful TurboJPEG compressor instances to store the relevant parameters for each transform, which is much more extensible than even the current `tj3Transform()` function in TurboJPEG 3 (which is itself much more extensible than the transupp API would be if it were made public.)

I have discussed and proposed a [new legacy-free industry-standard JPEG API](#313) that would be much easier to extend and maintain, but no one has expressed any interest in that.  (It would be a massive and expensive effort.)  Thus, I have been evolving the TurboJPEG API, as funding and time allows, to make it cover as many of the non-legacy libjpeg API features as possible.  Its coverage is not yet complete, but it is good enough to emulate almost all of the non-legacy functionality of cjpeg, djpeg, and jpegtran from libjpeg v6b.

To address the arguments you made above:
1. You are obviously not OK with the current libjpeg API, because this issue proposes that I extend that API to suit your purposes.
2. If I implemented the suggested extensions, then your program would be just as incompatible with libjpeg or Guetzli or other implementations of the libjpeg API, because those implementations do not support any of our extensions to the libjpeg API, nor would they support the extensions proposed here.

You can, of course, include **transupp.c** in your program if you want to continue using the libjpeg API.  That highlights the difference between making something work for a single application and making it work for all applications.  Making it work for all applications would require a lot of testing and documentation, and probably some re-design as well.

I'm sorry I couldn't bring better news, but funded development for this project (and my other projects as well) is steadily drying up, and I am forced to carefully consider how best to spend our limited resources going forward.  It would be much easier and less disruptive, in the long term, to implement post-jpeg-6b transform features (e.g. `-wipe` and `-drop`) or other missing features (buffered I/O, etc.) in the TurboJPEG API rather than expose the transupp API.
