### ISSUE TITLE
Chroma subsampling in DCT domain

### ISSUE THREAD

**Issue by kplieven** [libjpeg-turbo/libjpeg-turbo#699]
I am trying to chroma subsample in the DCT domain. If the input is a 4:4:4 encoded jpeg, I'm trying to convert it to a 4:2:0 image by just going back to the DCT coefficients.
I calculate the new coefficients and tried to overwrite the existing ones (in the top left quarter of the existing DCT coefficients), then changing the h_samp_factor and v_samp_factor for the chroma components as well as changing the width and height in blocks.
However, doing this yields strange results. Do I need to change any other fields? Any pointers on how I should approach this?

**Comment by dcommander** [comment]
I could be wrong, but to the best of my understanding, you can't.  The problem is that subsampling occurs in the spatial domain.  JPEG files always use 8x8 coefficient blocks.  In a 4:4:4 JPEG file, the 8x8 coefficient blocks for the chroma components correspond to 8x8 pixel blocks.  In a 4:2:0 JPEG file, however, the 8x8 coefficient blocks for the chroma components correspond to 16x16 pixel blocks.  In order to produce those subsampled 8x8 coefficient blocks, the original 16x16 pixel blocks are averaged into 8x8 pixel blocks and then fed through the quantization and forward DCT algorithms.  In the frequency domain, you essentially have no direct and absolute correlation between individual coefficients and pixels.  (The only correlation you can make is at the block level, which is why jpegtran can only losslessly transform JPEG images on a block-by-block basis.)  The coefficients are more like a way of describing the properties of an 8x8 pixel block in terms of how those pixels relate to each other.  AFAIK, there is no way to deterministically translate the frequencies produced by an unsampled 8x8 block into the frequencies that would have been produced by performing 2x2 subsampling on that block and its neighbors.  (Also remember that 2x2 subsampling crosses block boundaries in the spatial domain, and you cannot do that in the frequency domain.)  Things you *can* do in the frequency domain include: changing the block order; spatially transposing, rotating, or flipping a block (this works because the relationships between the pixels are unchanged-- you're just changing the order of those relationships, which changes the pixel order in the spatial domain); reducing the JPEG quality (increasing quantization, i.e discarding some of the high-frequency data), although jpegtran does not currently implement this; and eliminating components (e.g. converting color to grayscale.)  I strongly suspect that, even if there were a way to do what you propose, the computations would take more CPU time than simply running the IDCT on a group of blocks, subsampling them in the spatial domain, and feeding them back through the quantization and FDCT algorithms.

**Comment by kplieven** [comment]
Yes, you can! The math checks out, I have a working POC in Python. I was surprised this worked too :)

It works by subsampling each basis pattern and then applying the DCT, which then works as a translation from the DCT coefficient (corresponding to the basis pattern) to the subsampled DCT coefficients.
Using these matrices it is then possible to combine two DCT blocks into one.
These translation matrices are just static arrays, and the computation consists of going over each DCT coefficient, multiplying them by the corresponding subsampled DCT coefficients and accumulating them in a single 8x8 matrix.

I have the math to go from 4 (2x2) 8x8 DCT blocks to a single one and filling them in in the top left quarter of the image, but I'm having difficulty letting the library know about this change and making it decompress it as a 4:2:0 image.

**Comment by dcommander** [comment]
OK, but what's the point of that?  If you have to generate metadata in the spatial domain that enables you to combine the blocks in the frequency domain, and if that metadata is image-specific, then why wouldn't you just apply subsampling in the spatial domain?  I thought that your intent was to subsample an arbitrary 4:4:4 JPEG input image without knowing anything about the pixels that generated it, and I still posit that that is impossible.

**Comment by kplieven** [comment]
No, you only need the DCT coefficients, no pixel data.
The conversion matrices I'm talking about are only dependent on the size of the DCT, which is why they are constant.

**Comment by dcommander** [comment]
Interesting.  But you would definitely need to rewrite the frame header, and AFAICT that never happens in the libjpeg lossless translation code.

**Comment by kplieven** [comment]
Ahh, the frame header... I forgot about that, I will try some things out tomorrow! Thanks for the help :)
