### ISSUE TITLE
Image rotation from metadata

### ISSUE THREAD

**Issue by gregorni** [libjpeg-turbo/libjpeg-turbo#703]
Pictures shot in portrait mode on a phone are usually rotated by 90°. The fact that the image is rotated is then saved to the EXIF metadata.

<details><summary>Example Image</summary>

![IMG_20230616_100202_HDR](https://github.com/libjpeg-turbo/libjpeg-turbo/assets/119804311/18af6cdf-c27f-4853-8d76-da9eae722791)

</details>

I believe libjpeg-turbo (and the original libjpeg, for that matter) don't read that rotation and therefore open these images 90° rotated (from the user's perspective). Could this be implemented in a good way?

On most image viewers, these images still open right way up. I don't know how they do it, though.

This problem first came up in https://github.com/Talinx/jp2a/issues/13#issuecomment-1611109498

**Comment by gregorni** [comment]
image-rs also have an issue for this at https://github.com/image-rs/image/issues/1045, but there doesn't seem to be a lot of work on that front lately

**Comment by dcommander** [comment]
Partly because of its libjpeg legacy (the libjpeg code base predates EXIF by about four years), libjpeg-turbo has very little inherent support for EXIF.  What little support it does have is limited to twiddling the EXIF width/height tags when transforming a JPEG image using jpegtran or `tj3Transform()`.  Because of the fine-grained nature of the libjpeg API, automatically rotating an image during decompression would be a very difficult problem requiring a lot of deep modifications to 30-year-old code.  (That's assuming that we had full EXIF support and could read EXIF rotation tags during decompression, which we currently can't.)  It would be somewhat less onerous, but still difficult, to implement such functionality at the level of the more coarse-grained TurboJPEG API.

In general, it's best to think of libjpeg-turbo as a toolkit for application developers, not as a complete image processing suite.  cjpeg, djpeg, and jpegtran are basically examples of what can be accomplished with the underlying library.  They aren't meant to take the place of ImageMagick or even exiftran.  (exiftran is jpegtran with EXIF support, so it can automatically and losslessly rotate a JPEG image based on the EXIF tags.  I suspect that the applications to which you refer borrow that code in order to accomplish the same thing-- rotating the input image losslessly before using libjpeg-turbo to decompress it.)
