### ISSUE TITLE
Prominently display donation options

### ISSUE THREAD

**Issue by user8446** [libjpeg-turbo/libjpeg-turbo#706]
Hi,

I just read [this on Reddit](https://www.reddit.com/r/opensource/comments/14q1b0z/libjpegturbo_300_has_been_released_and_why_there/) regarding your post on needed donations for the project.

I think it would be a good idea to put your post on the [readme](https://github.com/libjpeg-turbo/libjpeg-turbo#readme) as well as on the [webpage](https://libjpeg-turbo.org/) for the project to help get the word out to the users and the community.

Thank you for the development!

**Comment by dcommander** [comment]
As if to add insult to injury, none of my hosted domains are working right now (seems to be a DNS issue), so I can't even get to the libjpeg-turbo web site to edit it.  I will add a link to the post on the libjpeg-turbo home page once I am able to.  The post describes a specific funding problem that is hopefully temporary, but I think that adding a more general funding blurb with a GitHub Sponsors button to the README is a good idea.

**Comment by user8446** [comment]
That would be great as the generic "Sponsor this project" on the GitHub page might just be overlooked

**Comment by user8446** [comment]
Just my opinion but I think stronger language or a link to your post would be a good idea.

You deserve to be rewarded for your development and you are at a crossroads where you have to make choices where your time is better spent elsewhere.

**Comment by dcommander** [comment]
I can only hope that the current funding situation is temporary.  I am comfortable providing a link to the email on libjpeg-turbo.org, which is a wiki, but the libjpeg-turbo code base is absorbed by numerous other projects (including the ISO/IEC and ITU-T JPEG reference software.)  Thus, I want to make sure that anything contained in that code base describes a general truism of libjpeg-turbo funding rather than a specific funding problem that may or may not be relevant in the future.
