### ISSUE TITLE
Test failure on macOS 13 arm64 with Xcode 14.3

### ISSUE THREAD

**Issue by carlocab** [libjpeg-turbo/libjpeg-turbo#709]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No.

**Clear and concise description of the bug:**

Running `ctest -V` after building fails with the following error:
```
The following tests FAILED:
        246 - djpeg12-shared-3x2-float-prog-cmp (Failed)
        541 - djpeg12-static-3x2-float-prog-cmp (Failed)
Errors while running CTest
Output from these tests are in: /var/folders/g6/mm_qhlw97px7wmm_kds34bfc0000gn/T/tmp.1vARGXytqS/libjpeg-turbo-3.0.0/build/Testing/Temporary/LastTest.l
og
```
This occurs on macOS 13 on arm64 with Xcode 14.3. Notably, this does not occur on the same version of macOS/Xcode on x86_64, or on macOS 11 or 12 (with the latest possible version of Xcode installed).

See also (somewhat confusing) discussion at #705. (Apologies for that.)

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Run:
```
curl -L https://downloads.sourceforge.net/project/libjpeg-turbo/3.0.0/libjpeg-turbo-3.0.0.tar.gz | tar x
cmake -S libjpeg-turbo-3.0.0 -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --parallel 10
ctest --extra-verbose --test-dir build
```

**Image(s) needed in order to reproduce the bug (if applicable):**

N/A

**Expected behavior:**

No failures.

**Observed behavior:**

Failing tests.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

macOS 13 on arm64 with Xcode 14.3. Clang reports:
```
❯ clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

These failures were encountered in the 3.0.0 release. The tip of the main branch (e429e379b01dde9d1d92b5bbabd2a18ee75d7eaa) also fails with the same error.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

See `git bisect` attempt [below](https://github.com/libjpeg-turbo/libjpeg-turbo/issues/709#issuecomment-1645130770).

**Additional information:**

Logs from `ctest`:
[ctest.log](https://github.com/libjpeg-turbo/libjpeg-turbo/files/12117431/ctest.log)
[LastTest.log](https://github.com/libjpeg-turbo/libjpeg-turbo/files/12117432/LastTest.log)

Passing `-DFLOATTEST12=fp-contract` to `cmake` while configuring as suggested in #705 does not make the failure go away. I tried this from e429e379b01dde9d1d92b5bbabd2a18ee75d7eaa:
```
❯ ctest --test-dir build --parallel 10 --rerun-failed --output-on-failure
Internal ctest changing into directory: /var/folders/g6/mm_qhlw97px7wmm_kds34bfc0000gn/T/tmp.1vARGXytqS/build
Test project /var/folders/g6/mm_qhlw97px7wmm_kds34bfc0000gn/T/tmp.1vARGXytqS/build
    Start 246: djpeg12-shared-3x2-float-prog-cmp
    Start 541: djpeg12-static-3x2-float-prog-cmp
1/2 Test #246: djpeg12-shared-3x2-float-prog-cmp ...***Failed    0.00 sec
testout12_3x2_float.ppm: FAILED.  Checksum is 2da9de6ae869e88b8372de815d366b03

2/2 Test #541: djpeg12-static-3x2-float-prog-cmp ...***Failed    0.00 sec
testout12-static_3x2_float.ppm: FAILED.  Checksum is 2da9de6ae869e88b8372de815d366b03


0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.03 sec

The following tests FAILED:
        246 - djpeg12-shared-3x2-float-prog-cmp (Failed)
        541 - djpeg12-static-3x2-float-prog-cmp (Failed)
Errors while running CTest
```

**Comment by carlocab** [comment]
From `git bisect`:
```
b5a9ef64ea299423b7fb46c47f4a70697a442dd4 is the first bad commit
commit b5a9ef64ea299423b7fb46c47f4a70697a442dd4
Author: DRC <information@libjpeg-turbo.org>
Date:   Sun Nov 13 13:00:26 2022 -0600

    Don't allow 12-bit JPEG support to be disabled
```
I'm not 100% confident about this, though. `git bisect` asked me to test commits where there was no `CMakeLists.txt` (they only had a `configure` script), and I skipped those.

The failing test numbers also changed across commits, but I did check that the descriptions (i.e. `djpeg12-shared-3x2-float-prog-cmp`) were the same before marking a commit as bad. (No other failures appeared for the commits I tested.)

I did _not_ check if the checksum produced by the failing tests was the same each time. I can try this if this is important.

**Comment by dcommander** [comment]
This is already being discussed under #705. I am still trying to get someone to send me the verbose test output so I can determine the proper course of action.

**Comment by dcommander** [comment]
I see that you attached the logs. I cannot open them on my phone, and I am out of the office today. Will look at them in more detail on Monday.

**Comment by carlocab** [comment]
> I see that you attached the logs. I cannot open them on my phone, and I am out of the office today. Will look at them in more detail on Monday.

That's fine. Please enjoy your weekend. Thank you!

**Comment by dcommander** [comment]
I was able to look at the log and figure out that the MD5 sums of the failing tests don't match any MD5 sums generated by known compiler configurations. Thus, there is really no way to validate the 12-bit floating point IDCT with Xcode 14.3/AArch64 except to visually confirm that the images look correct and to measure the perceptual loss (e.g. using DSSIM) relative to the results of the integer IDCT. As I mentioned in #705, the floating point IDCT is a legacy feature, and its results depend heavily on the compiler's floating point implementation. Thus, the test system needs a hint as to the expected floating point results, and that hint is communicated through the `FLOATTEST*` CMake variables. I thought that a reasonable default could be set for `FLOATTEST12`, but I guess not. For now, you should unset that variable by passing `-UFLOATTEST12` to CMake in the failing configuration. I will likely change `FLOATTEST12` to be opt-in rather than opt-out, since it appears to be no longer possible to intelligently predict a correct value for it. Our CI system will manually set that variable to provide a regression check on the floating point IDCT, but it doesn't make sense for all builds to attempt that regression check by default unless the build system can intelligently determine a default value for `FLOATTEST12`. Apparently it no longer can with Xcode 14.3, and that may be a harbinger of similar problems as Linux distributions upgrade to newer Clang releases.

**Comment by negge** [comment]
Why are the floating point values being tested with an MD5 instead of just measuring the MSE with the expected floating point values? I would expect them to be very close and testing with some expected value epsilon sufficiently small should be good enough for correctness.

**Comment by dcommander** [comment]
> Why are the floating point values being tested with an MD5 instead of just measuring the MSE with "known good" floating point values? I would expect them to be very close and testing with some expected value epsilon sufficiently small should be good enough for correctness.

Because there is no test framework for testing the floating point DCT/IDCT using MSE, and since the floating point DCT/IDCT is a legacy feature, I have no interest in using our limited budget to develop such a framework.  I'm just going to unset `FLOATTEST12` by default and set it to an appropriate value within our own builds.

**Comment by dcommander** [comment]
The build system no longer sets `FLOATTEST12` by default for non-x86-64 builds, so this issue should now be worked around.

**Comment by dcommander** [comment]
Because of https://github.com/libjpeg-turbo/libjpeg-turbo/commit/47656a082091f9c9efda054674522513f4768c6c, the floating point DCT/IDCT regression tests should now pass when using Clang 14/AArch64 if you set `FLOATTEST8=fp-contract` and `FLOATTEST12=fp-contract` (assuming you have not modified the default value of the `-ffp-contract` compiler argument.)  With Clang 13/AArch64 and prior, you should set `FLOATTEST8=no-fp-contract` and `FLOATTEST12=no-fp-contract` (assuming you have not modified the default value of the `-ffp-contract` compiler argument.)
