### ISSUE TITLE
jpegtran -drop and larger than expected resulting file size

### ISSUE THREAD

**Issue by cquest** [libjpeg-turbo/libjpeg-turbo#711]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No

**Clear and concise description of the bug:**

I'm using crop/drop to replace parts of 360° pictures to locally decrease the quality (on top/bottom parts) and reduce overall file size while maintaining original quality around the horizon.

The expected gain in file size does not match what is expected:
- original file: 3.7MB
- crop # 1 original 472MB, recompressed 55KB
- first drop: 3.5MB, 200KB gain
- crop # 2 original 1.5MB, recompressed 266KB
- second drop of recompressed crops: 2.5MB

I was expecting a total gain around 1.6MB, but only get 1.2MB.

crop + recompress is done with jpegtran + djpeg + cjpeg

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

```
wget -N https://panoramax.openstreetmap.fr/images/88/75/40/df/8c38-4ca5-9cc0-1a8afe03962e.jpg

IMG=8c38-4ca5-9cc0-1a8afe03962e.jpg

JPG="-dct float -optimize -quality 30 -sample 2x1"

jpegtran -crop 5760x960+0+0    $IMG > crop1.jpg
jpegtran -crop 5760x960+0+1920 $IMG > crop2.jpg

djpeg crop1.jpg | cjpeg $JPG > crop1_recomp.jpg
djpeg crop2.jpg | cjpeg $JPG > crop2_recomp.jpg

jpegtran -optimize -progressive -copy all -drop +0+0 crop1_recomp.jpg $IMG > after_drop1.jpg
jpegtran -optimize -progressive -copy all -drop +0+1920 crop2_recomp.jpg  after_drop1.jpg > after_drop2.jpg

```

**Image(s) needed in order to reproduce the bug (if applicable):**

https://panoramax.openstreetmap.fr/images/88/75/40/df/8c38-4ca5-9cc0-1a8afe03962e.jpg

**Expected behavior:**

**Observed behavior:**

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Ubuntu 22.04

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

v2.1.2, tested with 3.0 with same results

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by cquest** [comment]
I've investigated libjpeg code more in depth, and I suspect this is caused by the requantization taking place when dropping as variable quantization is not supported.

**Comment by dcommander** [comment]
> I've investigated libjpeg code more in depth, and I suspect this is caused by the requantization taking place when dropping as variable quantization is not supported.

To put numbers on this, the original image and the losslessly cropped images use 4:2:2 subsampling with Quality 99.  The recompressed images use 4:2:2 subsampling with Quality 30.  As you surmised, **crop1_recomp.jpg** is re-quantized to Quality 99 when it is dropped into the original image, and **crop2_recomp.jpg** is re-quantized to Quality 99 when it is dropped into **after_drop1.jpg**.   Since the recompressed images were recompressed with Quality 30, a lot of the original data was lost.  However, Quality 30 also has rather extreme compression artifacts, so the recompressed images are much less smooth in the spatial domain than the original image.  (In other words, the recompressed images have a lot of high-frequency transients.) Thus, when the Quality 30 images are recompressed or re-quantized to Quality 99, the compression is worse than that of the original image.  In fact, **after_drop1.jpg** would actually be larger than the original image had you not specified `-progressive`.

The decompression/recompression cycle is the problem.  In order to achieve what you want to achieve, you would need a tool that can selectively re-quantize a specified image region in the frequency domain.  However, I'm not 100% sure if that is possible, because JPEG images can only have one quantization table per component.  The `-drop` feature re-quantizes the dropped image to the quality level of the target image, but selective re-quantization would instead need to re-quantize a region of the target image such that it behaves like Quality 30 but still uses the Quality 99 quantization tables.  Maybe that's a simpler problem than I'm making it out to be, but it's been too long since I dug into those algorithms.

**Comment by dcommander** [comment]
NOTE: I am available for [funded development/professional consulting](https://libjpeg-turbo.org/About/ProfessionalServices) regarding this.  Other users have requested a re-quantization feature in jpegtran, and it might be possible to extend such a feature to handle region-specific re-quantization as well.  [Contact me through e-mail](https://libjpeg-turbo.org/About/Contact) if you are interested in pursuing that as a funded development project.

**Comment by cquest** [comment]
Thanks a lot for the detailed explanations.
