### ISSUE TITLE
Differences caused by upgrading from version 1.5.3 to version 2.1.1

### ISSUE THREAD

**Issue by SWPUhwq** [libjpeg-turbo/libjpeg-turbo#718]
Hello，I used the libejpeg-turbo library to decode image files after the version upgrade, but there were many small differences in the decoding results. May I ask what could be the reason for this。

![bug](https://github.com/libjpeg-turbo/libjpeg-turbo/assets/52646997/25e3c13c-6a81-4d27-a6c5-0b352fb470a9)

**Comment by dcommander** [comment]
Impossible to say unless you provide me with the exact JPEG image you are decompressing and the exact procedure you use to decompress it.

**Comment by SWPUhwq** [comment]
this is the source JPEG image：
![878605](https://github.com/libjpeg-turbo/libjpeg-turbo/assets/52646997/128b4fdf-5e86-41e2-8aa4-dc79040cb743)
And use jpeg_start_decompress to decompress image，then use jpeg_read_scanlines to get scanline buffer。There are some differences in the buffers obtained from versions 1.5.3 and 2.1.1

**Comment by dcommander** [comment]
The image in question uses 4:4:0 (rotated 4:2:2) subsampling, i.e. the chroma components are subsampled 2x in the vertical direction only.  The libjpeg API uses smooth ("fancy") upsampling by default if a smooth upsampling algorithm is implemented for the JPEG image's subsampling type.  Historically, smooth 4:4:0 upsampling was not implemented until libjpeg-turbo 1.5.1.  However, the bias pattern that the feature initially used always rounded down the upsampled pixels, as opposed to rounding alternate pixels up or down as the smooth 4:2:2 upsampling algorithm does.  This was fixed in libjpeg-turbo 2.0.3.  The output of the smooth 4:4:0 upsampler in libjpeg-turbo 1.5.1-2.0.2 wasn't "incorrect" per se.  It just had a rounding bias toward zero, which was inconsistent with the behavior of the other smooth upsampling algorithms.

**Comment by SWPUhwq** [comment]
Is there any way we can still use 4:4:0 subsampling like 1.5.3 in version 2.1.1?

**Comment by dcommander** [comment]
> Is there any way we can still use 4:4:0 subsampling like 1.5.3 in version 2.1.1?

Why would you want to? The only difference in the two implementations is a round-off error, and the newer implementation is more accurate and more like the 4:2:2 implementation. You seem to be using libjpeg-turbo 1.5.3 as an arbitrary standard for mathematical correctness, but in this case, it isn't correct. So your question is like asking me if I can re-enable old libjpeg-turbo bugs in the latest version. 4:4:0 fancy upsampling historically did not exist in libjpeg, so there is no legacy here. The feature was introduced in libjpeg-turbo. I try to maintain mathematical backward compatibility and cross-compatibility where possible. (In other words, it is usually reasonable to assume that algorithms in libjpeg-turbo will produce the same bitwise results from version to version and on different platforms.) However, if an algorithm is implemented incorrectly, then it doesn't make sense to maintain backward mathematical compatibility with the incorrect version.

Maybe if you tell me what you are trying to accomplish, I can better assist you.

**Comment by SWPUhwq** [comment]
Thank you for your reply
