### ISSUE TITLE
GCC compilation warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]

### ISSUE THREAD

**Issue by pszemus** [libjpeg-turbo/libjpeg-turbo#722]
**Clear and concise description of the bug:**

While building jpeg-turbo from main there are compilation warnings:

```
/home/user/libjpeg-turbo/jchuff.c: In function ‘jpeg_gen_optimal_table’:
/home/user/libjpeg-turbo/jchuff.c:1060:22: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
 1060 |     bits[codesize[i]]++;
      |     ~~~~~~~~~~~~~~~~~^~
/home/user/libjpeg-turbo/jchuff.c:963:9: note: at offset 33 into destination object ‘bits’ of size 33
  963 |   UINT8 bits[MAX_CLEN + 1];     /* bits[k] = # of symbols with code length k */
      |
```

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

```
cmake -S . -B build
cmake --build build
```

**Expected behavior:**

no warnings

**Observed behavior:**

compilation warnings:

```
/home/user/libjpeg-turbo/jchuff.c: In function ‘jpeg_gen_optimal_table’:
/home/user/libjpeg-turbo/jchuff.c:1060:22: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
 1060 |     bits[codesize[i]]++;
      |     ~~~~~~~~~~~~~~~~~^~
/home/user/libjpeg-turbo/jchuff.c:963:9: note: at offset 33 into destination object ‘bits’ of size 33
  963 |   UINT8 bits[MAX_CLEN + 1];     /* bits[k] = # of symbols with code length k */
      |
```

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

```
$ cat /etc/fedora-release 
Fedora release 38 (Thirty Eight)

$ gcc --version
gcc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)

$ cmake --version
cmake version 3.27.3
```

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

main branch

**Comment by dcommander** [comment]
Very obvious false positive, since the preceding code ensures that there will never be an overflow.  Our CI system tests the following warnings with GCC 11.4.x, including the strictest setting for `-Wstringop-overflow`:

`--std=gnu90 -Wall -Werror -Wextra -Wpedantic -pedantic-errors -Wdouble-promotion -Wformat-overflow=2 -Wformat-security -Wformat-signedness -Wformat-truncation=2 -Wformat-y2k -Wmissing-include-dirs -Wshift-overflow=2 -Wswitch-bool -Wno-unused-parameter -Wuninitialized -Wstrict-overflow=2 -Wstringop-overflow=4 -Wstringop-truncation -Wduplicated-branches -Wduplicated-cond -Wdeclaration-after-statement -Wshadow -Wunsafe-loop-optimizations -Wundef -Wcast-align -Wno-clobbered -Wjump-misses-init -Wno-sign-compare -Wlogical-op -Waggregate-return -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-declarations -Wpacked -Wredundant-decls -Wnested-externs -Winline -Wno-long-long -Wdisabled-optimization -Wno-overlength-strings`

Thus, this seems to be a regression with GCC, not an issue with libjpeg-turbo.
