### ISSUE TITLE
libjpeg has a different default chrominance quantization table since version 9e

### ISSUE THREAD

**Issue by matmat** [libjpeg-turbo/libjpeg-turbo#727]
The motivation for their change was lossless support, but as far as I know, this affects all encoded images. From libjpeg changelog:

```jcparam.c: change default chrominance DC quantization factor for lossless support. ```

The new table in jcparam.c of libjpeg version 9e (2022-01-16) onwards:

```/* These are the sample quantization tables given in JPEG spec section K.1.
 * NOTE: chrominance DC value is changed from 17 to 16 for lossless support.
 * The spec says that the values given produce "good" quality,
 * and when divided by 2, "very good" quality.
 */
static const unsigned int std_luminance_quant_tbl[DCTSIZE2] = {
  16,  11,  10,  16,  24,  40,  51,  61,
  12,  12,  14,  19,  26,  58,  60,  55,
  14,  13,  16,  24,  40,  57,  69,  56,
  14,  17,  22,  29,  51,  87,  80,  62,
  18,  22,  37,  56,  68, 109, 103,  77,
  24,  35,  55,  64,  81, 104, 113,  92,
  49,  64,  78,  87, 103, 121, 120, 101,
  72,  92,  95,  98, 112, 100, 103,  99
};
```

Would it be worthwhile to change libjpeg-turbo to align with libjpeg on this?

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/c0412b56d66b287817009afca7c105feb674cd7c/jcparam.c#L86

**Comment by dcommander** [comment]
libjpeg-turbo is an ISO/ITU-T reference implementation these days,
so whereas libjpeg under Tom Lane was a de facto standard, libjpeg-turbo is now the de facto standard. We stopped tracking libjpeg because most of the innovations since libjpeg v7 have violated the JPEG-1 spec and were rejected by the relevant standards bodies. To the best of my recollection, the JPEG-1 spec does not specify quantization tables, but the tables used by libjpeg v6b are somewhat canonical at this point, and a lot of software expects them. If there were a compelling reason to support alternative quantization tables, I would consider that as an optional mode, but I doubt that such a reason exists outside of the non-standard features in jpeg-8 and jpeg-9. (The lossless implementation in jpeg-9 is such a feature. libjpeg-turbo supports lossless coding in the standard manner, using differential coding rather than DCT.)
