### ISSUE TITLE
Lost data at the end of a compressed file without WITH_SIMD defined

### ISSUE THREAD

**Issue by Alyosha-Karamazov** [libjpeg-turbo/libjpeg-turbo#728]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
Because the value of `entropy->simd` is only initialized when `WITH_SIMD` is defined, the value is garbage (sometimes 0, sometimes not). (see jchuff.c, line 190). The `flush_bits` method reads this value even if `WITH_SIMD` is not defined. For platforms where `__aarch64__` is defined and `NEON_INTRINSICS` is not, the `flush_bits` method does not seem to work correctly, resulting in lost data (see jchuff.c, line 542). 

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Compile the library without `WITH_SIMD` defined and compress an image. Because the value of `simd` is uninitialized, it will sometimes work correctly, but it varies.

**Image(s) needed in order to reproduce the bug (if applicable):**
Any image works.

**Expected behavior:**
A proper JPEG should be produced

**Observed behavior:**
Utilities like `jpeginfo` will note "Corrupt JPEG data: premature end of data segment" when reading the file.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
MacOS, Clang latest, M1

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
Present on 3.0.0

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
Likely introduced here:
https://github.com/libjpeg-turbo/libjpeg-turbo/commit/bf01ed2fbc02c15e86f414ff4946b66b4e5a00f1

**Additional information:**

**Comment by Alyosha-Karamazov** [comment]
I should note that I was using the library indirectly through the Qt framework, but I don't think that was the root problem. The call to `flush_bits` happens via `finish_pass_huff` via `finish_pass_master` via `jpeg_finish_compress` called here:
https://github.com/qt/qtbase/blob/dev/src/plugins/imageformats/jpeg/qjpeghandler.cpp#L674C9-L674C29
But

**Comment by dcommander** [comment]
It seems to be a legitimate issue, but apparently it doesn't affect x86-64 builds or AArch64 intrinsics builds, since effectively `BIT_BUF_SIZE` and `SIMD_BIT_BUF_SIZE` are the same for those builds, and it isn't necessary to reverse the order of the bit buffer in order to support the legacy Arm GAS SIMD extensions.  Still, though, I wonder why MSan doesn't flag the uninitialized variable, given that our MSan CI tests are performed with the SIMD extensions disabled at build time:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/3d1d68cf967aec4aba34cd51e89a13fc2f0f3d9b/.github/workflows/build.yml#L161-L176

Perhaps the compiler optimizes out the branch because the two paths effectively execute the same code?

I will attempt to reproduce the issue on my AArch64 test machine as well as determine whether the issue also affects 32-bit builds (which I suspect it does.)

**Comment by dcommander** [comment]
MSan does in fact catch the error with x86-64 builds if compiler optimization is disabled, so in the process of fixing the bug, I will also make sure that our MSan CI test uses `-O0`.

**Comment by dcommander** [comment]
Upon closer examination, the scope of the issue does not extend to 32-bit builds with `WITH_SIMD=0`, because both `simd_bit_buf_type` and `bit_buf_type` are `size_t` in that case, and the compiler optimizes out the branch just like it does with x86-64.  The scope is limited to Neon platforms with `WITH_SIMD=0` and `NEON_INTRINSICS=0`, although I have thus far been unable to reproduce the issue on Ubuntu/AArch64.  I am upgrading my test platform to see if a newer Clang release triggers the failure.  (I need this information in order to properly document the issue.) But I should also point out that frameworks such as Qt should enable the SIMD extensions.  There is no good reason not to.
