### ISSUE TITLE
FASTDCT scalar and SIMD do not match

### ISSUE THREAD

**Issue by Zelex** [libjpeg-turbo/libjpeg-turbo#731]
If you input a coef array which is [0, -2048, 0, 0 ... 0] (array size of 64), it overflows when calculating z5 in pass 2 of the idct in the SIMD code. Specifically the addition of z10 and z12 is > SHRT_MAX so it wraps around and produces bad results. The results should be a gradient between 0 and 255, what you get is 0, 255, 0, 255, 0, 255, 0, 255 etc...

**Comment by dcommander** [comment]
If this issue causes a user-visible bug, then please indicate how to reproduce the bug.  Otherwise, unless I miss my guess, this is a known issue that has existed all along with libjpeg-turbo.  Since 6ca69537f1e2ee17dd8e24ea67ad5a6b639926d6 (introduced in libjpeg-turbo 1.1.0), libjpeg-turbo works around the issue by automatically disabling SIMD quantization when using the IFAST ("fast" integer) FDCT with quality levels above 98.  At those quality levels, the SIMD implementation of the quantization algorithm, when used with the IFAST FDCT, overflows a 16-bit datatype.  Even when using the C implementations of the algorithms, which do not overflow, the quality can actually degrade rather than improve for quality levels above 98.  (That has always been the case with libjpeg as well.)  Thus, our documentation goes out of the way to advise against using the IFAST FDCT with quality levels above 98.  (Prior to TurboJPEG 3, the TurboJPEG API wouldn't even let you do that.)

The IFAST FDCT is a legacy feature that was intended to speed up compression on 386 and 486SX CPUs without FPUs, because those CPUs often took minutes to process a 1-megapixel JPEG image.  (The floating point FDCT is, similarly, a legacy feature that was intended to speed up compression on 386 and 486 CPUs with FPUs.)  These days, the IFAST FDCT is not significantly faster than the ISLOW FDCT on x86-64 CPUs, mainly because the ISLOW FDCT uses AVX2 instructions (if available) whereas the IFAST FDCT only uses SSE2 instructions.  (The DCT algorithms have inter-row and inter-column dependencies, so it isn't generally possible to compute more than eight coefficients simultaneously.  Because the ISLOW FDCT uses 32-bit intermediates, it was possible to use dual-lane 256-bit AVX2 instructions to process eight 32-bit intermediates in parallel, thus accelerating the algorithm relative to the SSE2 implementation.  Because the IFAST FDCT uses 16-bit intermediates, there was no advantage to using AVX2 instead of SSE2 for that algorithm.)  On non-x86 CPUs, the IFAST FDCT is generally about 5-15% faster than the ISLOW FDCT.  However, that isn't a very compelling advantage when you consider how fast the ISLOW FDCT already is.  In general, the IFAST FDCT is not recommended for new applications.  It is provided solely for backward compatibility with libjpeg.

**Comment by Zelex** [comment]
This is for the IDCT, not the FDCT.

**Comment by dcommander** [comment]
In that case, refer to https://ssvb.github.io/2011/08/22/simd-idct-libjpeg-turbo-bitexactness.html.  Yes, it is possible to make the SIMD IDCT algorithm overflow, but not when decompressing a real JPEG image.

**Comment by dcommander** [comment]
Basically, the tradeoff is:  a lot more performance in exchange for the inability to properly decode malformed images that would never be generated by a real JPEG encoder.
