### ISSUE TITLE
libjpeg-turbo for opencl

### ISSUE THREAD

**Issue by B-JackMao** [libjpeg-turbo/libjpeg-turbo#742]
Does libjpeg turbo have an API that supports opencl？

**Comment by dcommander** [comment]
No. I collaborated with AMD on that about 10 years ago, but the project was unsuccessful. The basic problem was that OpenCL had too much overhead for the fine-grained libjpeg API. The libjpeg API has to be able to execute each algorithm on a single block in isolation, but the startup and shutdown cost of that was too high with OpenCL. OpenCL would be a much better fit for a more coarse-grained whole-image API such as the TurboJPEG API.

**Comment by B-JackMao** [comment]
Thank you for the reply! Has the development of OpenCL helped to reduce the overhead of initialization and termination when using GPUs to accelerate libjpeg? I saw some papers that were able to accelerate Libjpeg using GPUs.

**Comment by dcommander** [comment]
The GPU implementations actually had the most overhead, because they had to download the code and data to the GPU, execute it, and upload the result back to main memory. Perhaps the existing libjpeg/OpenCL implementation performs better than libjpeg, but that's also a low performance bar. I haven’t looked into how or if the situation has changed in the last 10 years, but in 2013, OpenCL could only meet or exceed the performance of libjpeg-turbo's existing SIMD code if we speculatively prefetched and cached MCU blocks in linear order. A linear access pattern was a reasonable assumption to make in most (not all) use cases, but the prefetching/caching mechanism would have required deep modifications to the libjpeg architecture. The libjpeg API is more than 30 years old at this point, and its design was based on the limitations of late 1980s/early 1990s PC hardware. It is a fine-grained API with a lot of touch points, so there are already a lot of control paths that have to be tested. Any deep modifications to the libjpeg architecture will inevitably increase the number of control paths and thus make the library harder to support and maintain (and it's already really hard.) As an example, the addition of partial image decompression continued to produce bugs, some of them exploitable, many years later (because the feature implementation did not take all control paths into account.) That's the beauty of libjpeg-turbo's SIMD extensions. They plug into the existing libjpeg architecture, with zero overhead, at exactly the granularity that it demands. However, the libjpeg architecture is starting to limit our ability to adopt new SIMD instruction sets as well. Specifically, because the DCT/IDCT algorithms can only work on one 8x8 block of 16-bit coefficients at a time, and because those algorithms have interdependencies that require each row and column to be processed serially, the algorithms can only really take advantage of 128-bit vector widths. We could only take advantage of 256-bit AVX2 instructions because the accurate integer DCT/IDCT algorithms use 32-bit intermediates. The "fast" DCT/IDCT algorithms (which are a relic of the aforementioned 1980s/1990s PCs) do not use 32-bit intermediates, so those algorithms are stuck with 128-bit instructions.

In order to take full advantage of modern technologies, including vector instructions wider than 128 bits, GPGPU, etc., we need an API that can accommodate those modern technologies rather than an API that was designed around the limitations of MS-DOS machines. The API doesn't necessarily need to be a whole-image API, but it does need to be structured such that the calling program can tell the library in advance how many blocks will need to be compressed/decompressed. I have been slowly but surely evolving the TurboJPEG API over the years, as funding has allowed, and TurboJPEG v3 (#517) now covers all of the most common use cases. However, there is a lot more to be done (#646) before it can functionally replace the libjpeg API. Referring to #313, I’m not even sure if the TurboJPEG API is the right API to replace the libjpeg API and become a new de facto industry standard. It’s just the path of least resistance. Also, functionally replacing the libjpeg API is only Step 1. Then comes the more difficult step of encouraging people to migrate to the new API. (That's why I mention in #313 the strong desire for industry buy-in.) Most people just don't care, however. They're happy that libjpeg-turbo gives them 2-7x better performance for free, but they would not be willing to change their application code in order to get more performance. JPEG is an old image format. I got into the high-speed open source JPEG business because I maintain two downstream projects (VirtualGL and TurboVNC) that need a high-speed JPEG codec. Prior to libjpeg-turbo, those projects had to use a mishmash of codec libraries across various platforms. (Incidentally, that's where the TurboJPEG API originated-- as a wrapper for the mishmash of codec libraries.) In 2004, the few high-speed JPEG codecs that existed were the only mechanisms by which I could get sufficient performance and compression ratio to stream 30 Megapixels/second over 100 Mbps Ethernet with perceptually lossless quality. However, there are more advanced codecs out there these days. In the streaming world, people are primarily using interframe video codecs like H.264 or HEVC. And there aren't a lot of other use cases that would necessitate improving JPEG codec performance beyond what libjpeg-turbo already provides. (If you have such a use case, I would be very interested to hear about it.)
