### ISSUE TITLE
Separate license files for project

### ISSUE THREAD

**Issue by dvzrv** [libjpeg-turbo/libjpeg-turbo#744]
**Clear and concise description of the bug:**
Hi! :wave: 
For packaging purposes on Arch Linux I have to package license files for the BSD-3-Clause, IJG and Zlib licenses used in this project. All three licenses are considered "uncommon" by the distribution (we are able to package some license files centrally as "common", because they do not contain personally identifying information such as author and date - "uncommon" licenses have to be packaged with the respective packages).

There is a license file for [IJG](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/289df647c0f208dad7db63f24830361257812b1b/README.ijg) and [the license text for BSD-3-Clause is contained in LICENSE.md](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/289df647c0f208dad7db63f24830361257812b1b/LICENSE.md).
However, there is no separate license file for Zlib and there is only a link to a template:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/289df647c0f208dad7db63f24830361257812b1b/LICENSE.md?plain=1#L17

**Steps to reproduce the bug (using *only* libjpeg-turbo):** n/a

**Image(s) needed in order to reproduce the bug (if applicable):** n/a

**Expected behavior:**

There are separate license files for all applicable licenses.

**Observed behavior:**

The license file for Zlib is missing.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:** n/a

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):** all

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):** n/a

**Additional information:**

For other projects I have been using [reuse](https://reuse.software/), which is a super useful tool to check all files in a repository for license attribution and generically provide license files in a common directory (`LICENSES`). Maybe it can be useful to libjpeg-turbo as well.

**Comment by dcommander** [comment]
As **LICENSE.md** states, the zlib License is effectively a subset of the other two.  As it also states, the libjpeg API library and associated programs fall under the IJG License, and the TurboJPEG API library and associated programs fall under the 3-clause BSD License.  Most distributions package those components separately, so the IJG License would apply to the libjpeg components, and the 3-clause BSD License would apply to the TurboJPEG components.  Since the zlib License is a subset, it doesn't need to be considered separately, as its provisions are covered by the other licenses.

**Comment by dvzrv** [comment]
> As LICENSE.md states, the zlib License is effectively a subset of the other two.

I'm aware of the file. However, stating that the Zlib license is effectively a subset of the other two is just not correct.

[IJG](https://spdx.org/licenses/IJG.html), [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html) and [Zlib](https://spdx.org/licenses/Zlib.html) are distinctively separate licenses, with differing license texts.

> Since the zlib License is a subset, it doesn't need to be considered separately, as its provisions are covered by the other licenses.

Maybe this is where the confusion about the text in LICENSE.md is: For me either there are three licenses that apply to files in this repository or there are not.
Are you trying to convey, that Zlib in fact does not apply to any of the current files in this repository? If so, then it would be great if this could be more clearly stated (e.g. "Some parts of the code has previously been licensed under the Zlib license").

**Comment by dcommander** [comment]
> I'm aware of the file. However, stating that the Zlib license is effectively a subset of the other two is just not correct.
> 
> [IJG](https://spdx.org/licenses/IJG.html), [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html) and [Zlib](https://spdx.org/licenses/Zlib.html) are distinctively separate licenses, with differing license texts.
>
> Maybe this is where the confusion about the text in LICENSE.md is: For me either there are three licenses that apply to files in this repository or there are not. Are you trying to convey, that Zlib in fact does not apply to any of the current files in this repository? If so, then it would be great if this could be more clearly stated (e.g. "Some parts of the code has previously been licensed under the Zlib license").

Why isn't it correct?  As an example, if a piece of software contains some GPL-licensed source code, then effectively any GPL-compatible license that may be applied to other source code in that software is subsumed by the GPL when you consider the license of the overall software.  That is what is happening here.  The individual source files have different licenses, but the overall package doesn't need to consider the zlib License, because it is effectively subsumed.  The terminology for this is "inbound" vs. "outbound" licenses.  The inbound license in this case is the zlib License, and the outbound license is either the IJG or 3-clause BSD License.  An inbound zlib License is compatible with an outbound 3-clause BSD License:

https://joinup.ec.europa.eu/licence/compatibility-check/Zlib/BSD-3-Clause

The same license checker doesn't have the IJG License, but inbound zlib is compatible with outbound IJG for the same reasons.

It isn't common practice for packagers to list every single license that applies to every single file in the source.  It is common practice to list the license that applies to the overall package.  Since you're packaging this for a Linux distribution that presumably makes the source available along with the binaries, the only clauses that actually apply to your packages are the liability disclaimers and the clauses preventing you from using the name of the IJG or The libjpeg-turbo Project in advertising, publicity, etc.  The other clauses either come into play when someone modifies the source code, or they come into play when someone distributes binaries without the source code.  Since every piece of source code contains a license header, it is quite obvious which license applies to that piece of source code.  All you need to be concerned with is which license applies to your overall packages.

**Comment by dvzrv** [comment]
Thanks for your explanation!

>  That is what is happening here. The individual source files have different licenses, but the overall package doesn't need to consider the zlib License, because it is effectively subsumed. The terminology for this is "inbound" vs. "outbound" licenses. 

IANAL, but I trust you verified your license changes :)

> It isn't common practice for packagers to list every single license that applies to every single file in the source.

Frankly, I'd rather err on the side of caution than to under-represent licensing terms. Since the LICENSE.md evidently gave me the wrong impression about the licensing realities of this repository, I opened this ticket :)

> It is common practice to list the license that applies to the overall package.

I would like to do that, but a complex document such as LICENSE.md does not make it easy to understand, that in fact only two (and not three) licenses apply.
Therefore it would be great to make wording such as `"libjpeg-turbo is covered by three compatible BSD-style open source licenses"` more specific when it comes to the distribution of code and binaries.
While the text elaborates at lengths why a certain license was chosen, it does not state what this means effectively for someone distributing this project.

**Comment by dcommander** [comment]
But none of the licensing terms even applies to distribution unless you modify the source or distribute a binary without the source, neither of which you're planning to do.  So I don't understand why it matters from the point of view of the packages.  No other distributors have ever complained about it, at least.  Just label the TurboJPEG packages with 3-clause BSD and the libjpeg packages with IJG.  I don't see how anyone could complain about it except me, and I'm not going to complain about it.

The basic problem is that the IJG License predates the 3-clause BSD License, so Tom Lane had to craft his own license.  The IJG License basically achieves the same result as 3-clause BSD, so maybe Tom would've switched to 3-clause BSD had he continued to maintain the project, but libjpeg v6b was abandoned before the 3-clause BSD License existed. Given that I couldn't change the license of the libjpeg components, my choices were limited:

1. Use a more modern license for the TurboJPEG components, which were my original work.
2. Use the IJG License, which was a poor fit because it specifically refers to the Independent JPEG Group and doesn't extend the attribution and endorsement protections to other entities.
3. Use the zlib License and forego attribution and endorsement protections for The libjpeg-turbo Project.  This would effectively be the same, from our project's point of view, as Option 2.

None of those choices were ideal.  I chose to use a more modern license for my work, because I knew that libjpeg-turbo would be used in a lot of commercial software, and I wanted attribution and endorsement protection.  It isn't really as awkward as it seems, because the BSD License is confined to the TurboJPEG components and the IJG License is confined to the libjpeg components.

I will consider unmentioning the zlib License in **LICENSE.md** in order to avoid confusion, with a well-crafted legal justification in the commit log.  That's probably the best I can do at the moment.

**Comment by dcommander** [comment]
Please review the changes to **LICENSE.md** in https://github.com/libjpeg-turbo/libjpeg-turbo/commit/9ef0d03e1e5f0140636215afe627954b81602c38, as well as the commit log justifying them.  The original author of the libjpeg SIMD extensions was clear that he understood the IJG License to subsume the zlib License in the context of the overall distribution, and that is my understanding as well.  This is very common in open source, and I included a link to RMS's discussion of license compatibility and subsumption as it applies to the GPL.

**Comment by dvzrv** [comment]
Thank you very much! :bow:
