### ISSUE TITLE
Add support for  JPEG MPF (Multi-Picture Format) file

### ISSUE THREAD

**Issue by carlcai** [libjpeg-turbo/libjpeg-turbo#746]
Hello，I want to support HDR gain maps,
A new "gain map" standard (https://helpx.adobe.com/camera-raw/using/gain-map.html) offers this.
There are some gain map examples under the Adobe link (direct download is https://www.adobe.com/go/gainmap_sample_photos).
And the supplied sample JPEG files with gainmaps are stored in JPEG MPF (Multi-Picture Format) files. 
Relevant CIPA document on Multi-Picture Format: https://www.cipa.jp/std/documents/e/DC-X007_E.pdf

I found I can't extract the multiple images by libjpeg-turbo, Do libjpeg plan to support the MPF?

**Comment by dcommander** [comment]
libjpeg-turbo is an ISO/ITU-T reference implementation of JPEG-1 and JFIF. I am open to supporting sanctioned format extensions, such as JPEG XT, that extend JPEG-1 in a backward-compatible way, but this is not that. It appears to be something that Adobe controls and has patented, so we could not legally include support for it under the current libjpeg-turbo licenses. Correct me if I've misunderstood something.

**Comment by dcommander** [comment]
Sorry, I see now that you're asking whether we could support MPF, not whether we could support Adobe's gain map (which would have to be handled by higher-level software.)

**Comment by carlcai** [comment]
Yes，I am asking for whether libjpeg-turbo could support MPF，Do libjpeg-turbo have plan to support MPF，or  the latest version of libjpeg-turbo is supported  MPF Now?

**Comment by dcommander** [comment]
libjpeg-turbo does not currently support MPF. I need to look into the potential legal/standards issues that might be involved. We are an ISO/ITU-T reference codec, so there is a limited amount we can do to support format extensions that are not sanctioned by those standards bodies. However, I want to understand what the necessary changes would be at the codec level. It may be possible to do something straightforward that allows higher-level codecs to use libjpeg-turbo with MPF images without providing explicit support ourselves. Please be patient, as it will take time to research this.

**Comment by jreck** [comment]
> It may be possible to do something straightforward that allows higher-level codecs to use libjpeg-turbo with MPF images without providing explicit support ourselves.

The jpeg_save_marker API allows layering MPF handling on top of libjpeg-turbo. This is the approach used by Skia for Android & Chromium without modifications to libjpeg-turbo. The higher-level codec then parses the MPF payload to resolve offsets to feed back into libjpeg-turbo for secondary image decodes.

**Comment by dcommander** [comment]
Given that it is already possible to handle MPF without modifications to libjpeg-turbo, I would prefer not to add specific support for MPF to libjpeg-turbo, since it is technically out of scope for our project.  CIPA standards, including EXIF and MPF, are best handled at a higher level.  I am open to extending libjpeg-turbo to make it easier to handle those standards, but that would require more specific technical suggestions from the user community.

**Comment by DichenZhang1** [comment]
Hi carlcai,

Technically Ultra HDR is not JPEG, it happens to be using JPEG for encoding base image and gainmap. Gainmap formats require different APIs / more flexibility, therefore Google developed [libultrahdr](https://github.com/google/libultrahdr) which uses libjpeg-turbo, and abstracts the users as such. We also road mapped the libavif and libheif dependencies so that in the future it will support transcoding formats such as converting the JPEG based gainmap version to AVIF-10-bit-HLG version without gainmap etc. There are quite a few applications using libultrahdr in their backends as of today successfully.

Thank you!

**Comment by carlcai** [comment]
ok，Thanks for the reply
