### ISSUE TITLE
libjepg-turbo is support HarmonyNext platform?

### ISSUE THREAD

**Issue by stevenXS** [libjpeg-turbo/libjpeg-turbo#762]

**Comment by dcommander** [comment]
Theoretically, it should be possible to compile libjpeg-turbo for HarmonyOS, as long as the platform supports standard compilers and C library functions. I do not know whether anyone has specifically tested it. In general, platforms that have the broadest reach get the most attention in the open source community. Niche platforms get the least attention. I frankly do not have a lot of sympathy for platforms and CPUs that needlessly reinvent the wheel, although I would accept minor patches to support such platforms, as long as the patches were straightforwardly reviewable (in other words, as long as I didn't need access to the platform in order to review them.) libjpeg-turbo is an open standard, so in general, I prefer to work with other open standards.
