### ISSUE TITLE
The image rotation information is not handled correctly

### ISSUE THREAD

**Issue by zhengqiangwang** [libjpeg-turbo/libjpeg-turbo#774]
I set the rotation information when decoding the image and then decoded it, but some of the decoded images were not rotated correctly

**Comment by dcommander** [comment]
libjpeg-turbo is a JPEG-1 codec.  It is not a comprehensive image processing toolkit.  libjpeg-turbo provides an example application (jpegtran) that demonstrates how to losslessly rotate a JPEG image by rearranging the image's DCT coefficients.  However, libjpeg-turbo does not automatically rotate images when decompressing them, nor does it claim to.  libjpeg-turbo also does not handle Exif tags.  That is partly historical, given that libjpeg was introduced years before Exif was introduced.  It is also partly philosophical, given that Exif derives from an industry group rather than from a standards body, and properly handling Exif tags would require staying abreast of numerous device-specific maker notes.  It is also partly architectural.  Because Exif applies to multiple image formats, it is best handled at a higher level on the software stack.  Because libjpeg-turbo is at the lowest level of the software stack, it cannot easily depend on other libraries.  That is why image processing toolkits typically use both libjpeg-turbo and libexif if they want to properly handle JPEG rotation.

Refer also to #703.
