### ISSUE TITLE
Change of destination manager has no guards against memory corruption if misused

### ISSUE THREAD

**Issue by pornel** [libjpeg-turbo/libjpeg-turbo#78]
Setting destination to a file, and then changing it to mem dest leads to memory corruption, because previously allocated dest struct size will be too small. 

There is [a comment](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/2e480fa2a3285d9ff83a780ab3417badeb3f2d37/jdatadst.c#L213-L216) that says it's dangerous, but it doesn't try to detect or prevent this.

Initializer function pointer can be used as a magic identifier for the type of the struct, so incorrect use can be easily detected and prevented.

**Comment by dcommander** [comment]
I'll look at this in more detail next week.  I assume that this issue will occur if you call jpeg_stdio_dest() followed by jpeg_mem_dest() on the same jpeg_decompress_struct instance?  Does the same issue exist with jpeg_stdio_src() and jpeg_mem_src()?  I haven't looked closely at it, but it seems like the correct behavior would be for any call to jpeg_mem_dest() or jpeg_stdio_dest() to override any previous call to jpeg_mem_dest() or jpeg_stdio_dest().  If that is not possible, then it seems like the function should throw a fatal error.

**Comment by pornel** [comment]
Yes, `jpeg_stdio_src`/`jpeg_mem_src` make the same assumption.

I've figured out it's possible to safely and reliably check what type of structure has been already set by checking function pointers. I believe that's the best approach, since it's compatible with existing programs and preserves the memory-recycling behavior when used correctly.

If you're happy with #79 I'll make a similar change for `*_src()` functions.

**Comment by dcommander** [comment]
Doesn't #79 create a memory leak if you call jpeg_stdio_dest() followed by jpeg_mem_dest() or vice versa?  It seems like cinfo->dest should be freed if it has already been allocated.  Maybe I'm missing something.

**Comment by pornel** [comment]
The object is placed in a memory pool, which despite being called "permanent", is freed when you destroy the `cinfo` object. 

So it's not a leak in a classic sense, but it does allocate more memory in pathological situations. Change of destination manager used to be forbidden and could cause memory corruption, so hopefully there aren't many clients that do it excessively.

**Comment by dcommander** [comment]
Is there any reason why switching source/destination managers "on the fly" would be useful to an application?  If so, then I think it would be good to allow that behavior, but I also think that if we're going to allow it, we should *really* allow it-- and that means ensuring that the old source/destination managers are cleaned up before the new ones are created.

Otherwise, if this new behavior isn't particularly useful, then I think we should just throw an error if an application tries to do that.

**Comment by pornel** [comment]
I don't know enough how people use the API to judge how useful/common this is.

Are you OK with a potential compatibility break? Old implementation without error handling didn't always crash, so adding check would change behavior from "works if you're lucky" to "doesn't work"

**Comment by dcommander** [comment]
Let's just allow the behavior and make sure that the resources are properly freed.

**Comment by pornel** [comment]
I don't know how to improve anything about freeing here. The API promises the object will live as long as `cinfo`, and freeing these objects in `jpeg_destroy` is already implemented by the memory pool.

**Comment by pornel** [comment]
A compromise could be to print a warning message when destination manager is changed. Developers would be reminded that this wasn't a safe operation in libjpeg, but apps depending on that behavior would continue to work.

**Comment by dcommander** [comment]
If it wasn't a safe operation before, then why would there be any apps that depend on that behavior?

**Comment by pornel** [comment]
Because it could work without crashing if first struct allocated for destination manager was large enough, or memory right after that struct wasn't important enough to cause immediate crash.

**Comment by dcommander** [comment]
Here's my current thinking:

The memory source/destination managers didn't exist before 2010 (they were a feature of jpeg-8), and prior to libjpeg-turbo 1.3, those source/destination managers could only be used in libjpeg-turbo if it was built with jpeg-8 API/ABI emulation.  Thus, the number of applications that use those source/destination managers is very small.  For instance, in Fedora, there were only two applications that necessitated the inclusion of the memory source/destination managers.  So we're already dealing with a very small subset of applications, and the number of those applications that mistakenly call jpeg_stdio_\*() and jpeg_mem_\*() on the same object probably approaches zero.  So I don't really think that there are any practical arguments to be made here-- only theoretical ones.  And the theoretical argument boils down to:  this behavior has never been technically allowed by the libjpeg API, and currently, if you call jpeg_stdio_dest() followed by jpeg_mem_dest(), you're going to stomp on memory.  So the options become:

1. Formalize the fact that the behavior isn't allowed, by throwing an error.  Problem:  because jerror.h is part of the libjpeg API, adding a new error string technically requires extending the API, which is a pain in the butt.  Thus, my preferred approach here would be to throw JERR_BUFFER_SIZE only if the application calls jpeg_mem_dest() followed by jpeg_stdio_dest(), or jpeg_stdio_src() followed by jpeg_mem_src()-- that is, if the previously-allocated source/destination manager struct isn't big enough for the current source/destination manager.
2. Allow the behavior, using your patch, with the caveat that it leaks memory.  Problem: most developers won't be aware of that, and there is no straightforward way to make them aware of it (just like there is no straightforward way to make them aware of the current pitfalls with the behavior.)  I personally think that this approach has a high potential of creating problems down the road.
3. Allow the behavior, but display a warning about the memory leakage.  Problem:  same as in (1).  Warning messages are technically extensions to the API, and in this case, there is no reasonable way to reuse an existing warning message.
4. Allow the behavior by merging my_destination_mgr and my_mem_destination_mgr into a single structure, thus ensuring that the memory created by one source/destination manager can be reused by the other.

My favorite approaches at the moment are (1) and (4).  Thoughts?

**Comment by pornel** [comment]
[The bug is there in v6b too](https://github.com/libjpeg-turbo/libjpeg-turbo/blame/5c064de10dc544ceeecfc63f6a781b9f71576f57/jdatadst.c#L208-L216
) — if you set `cinfo->dest` to your own struct, and then call  `jpeg_stdio_dest()` it'll blindly reuse that memory. libjpeg-8 just made a convenience method with bigger struct that made it a bigger problem.

But if you're not worried about applications using that bug, then I think (1) is a fine solution.

**Comment by dcommander** [comment]
OK, so would it be possible for us to just check the size of the memory allocated at cinfo->dest?  I'm sorry if this is a stupid question-- I'm juggling 1000 things right now and have zero time to dig into this.

**Comment by pornel** [comment]
No, size isn't stored anywhere.

I can check whether `dest->init_destination` is a known pointer to libjpeg built-in functions. If it is, I can assume it's been allocated by libjpeg, so it has known size. But if the pointer wasn't allocated by libjpeg, it's unknown. Then I can leak it or crash.

**Comment by dcommander** [comment]
Given that this is reproducible independently of the presence of the memory source/destination manager feature, then Option 4 above isn't really an option (since, as you point out, a user-allocated source/destination manager could still cause the problem.)  And it seems wrong to expose internal behavior externally, which would be the case if we allowed certain sequences of jpeg_stdio_\*() and jpeg_mem_\*() but not others (the user doesn't know what size the opaque structures are that those functions allocate.)  So I think it's probably best if we take Option 1 and modify the code such that JERR_BUFFER_SIZE is always thrown whenever jpeg_stdio_\*() or jpeg_mem_\*() is called and there is already a source/destination manager allocated elsewhere.  I do not think it was ever the intent of the API developers to allow the source/destination managers to be switched on the fly, but this may be a case of "change it and see who complains."
