### ISSUE TITLE
Potential Memory Reallocation and Security Risks in jpeg_mem_dest_tj Function

### ISSUE THREAD

**Issue by YancyLii** [libjpeg-turbo/libjpeg-turbo#783]
**Clear and concise description of the bug:**
The jpeg_mem_dest_tj function in the libjpeg-turbo library may reallocate the output buffer (dstBuf) passed to it, potentially causing memory leaks, double-free vulnerabilities, or other memory-related security issues. This behavior imposes a hidden responsibility on the developers using the library to manage memory manually, which contradicts good memory management practices and can lead to serious security flaws.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
use my code and input，you can reproduce the bug. OR:
Allocate a buffer (dstBuf) and pass it to the tjTransform function.
Internally, tjTransform calls jpeg_mem_dest_tj, which may reallocate dstBuf if it is null or its size is zero.
The original memory allocated by the developer is overwritten, leading to a memory leak since the original buffer cannot be freed.
If the developer attempts to free the original buffer after the transformation, a double-free vulnerability could occur, potentially leading to a crash or exploitable condition.

**Image(s) needed in order to reproduce the bug (if applicable):**
![image](https://github.com/user-attachments/assets/f40d059e-7a7c-4edf-a354-1b9f62693ca2)

**Expected behavior:**
The jpeg_mem_dest_tj function should not reallocate dstBuf if it has been pre-allocated by the developer.
The library should handle memory consistently, either by documenting that dstBuf will be reallocated (and thus the developer should not allocate it) or by ensuring that any memory allocation and deallocation is entirely handled within the library.

**Observed behavior:**
jpeg_mem_dest_tj may reallocate dstBuf, leading to memory leaks or security vulnerabilities. Developers are left to manually track and free buffers, which is error-prone and can introduce serious security flaws.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
clang++ = 17.0
ubuntu 20.0

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
3.0.3

**Additional information:**
https://drive.google.com/drive/folders/1ICI3jETlUcI2LbZaYNohMslRIMQXUMGl?usp=sharing

**Comment by dcommander** [comment]
The [API documentation](https://rawcdn.githack.com/libjpeg-turbo/libjpeg-turbo/2.1.x/doc/html/group___turbo_j_p_e_g.html#ga9cb8abf4cc91881e04a0329b2270be25) clearly documents that behavior and how to avoid it.  It is not a bug if the API is behaving as documented.  There is no memory leak, because the destination manager frees the old buffer immediately after allocating a new one.  If the caller chooses to pass a caller-allocated destination buffer, then it is incumbent upon the caller to check the pointer upon return from `tjTransform()` to ensure that it hasn't changed.  Alternatives to that are passing a NULL pointer, which causes libjpeg-turbo to manage the buffer for you, or allocating the destination buffer to a worst-case size and setting `TJFLAG_NOREALLOC`/`TJPARAM_NOREALLOC` to ensure that it won't be reallocated.  (If that flag/parameter is set, then the function will fail if the buffer isn't large enough, but note that it relies upon the caller-supplied buffer size to determine that.  I will reiterate that C gives us no way of determining the size of a caller-supplied buffer.)  This is all documented.  Stateless buffer management, as proposed for the [TurboJPEG v4 API overhaul](https://github.com/libjpeg-turbo/libjpeg-turbo/issues/646), would be a more foolproof solution, but it is not a panacea.  There will always be applications that need to use caller-allocated buffers.  Stateless buffer management will merely consolidate allocation and access for those buffers.  It will still be necessary for callers to check the pointers if they pre-allocate a JPEG destination buffer and don't instruct the API not to reallocate it.  That is how the TurboJPEG API works, and it is how the libjpeg API works when using the memory destination manager as well.  The only 100% foolproof solution would be to provide API functions for buffer allocation and always require callers to use those functions to allocate buffers, but once again, there are applications that can't do that for various reasons.  (Some projects, including my own, have to pass buffers into libjpeg-turbo that were allocated using OpenGL or SysV shared memory or other mechanisms, in order to avoid buffer copies.)

There is basically no C API design that can 100% guard against caller buffer allocation/access mistakes, because the C language itself doesn't provide any way to guard against those mistakes.  That's why we have sanitizers and fuzz testing, but proper use of those tools depends upon proper use of the API.  If you don't use the API properly, then you're going to get false positives, and every one of these issues you have posted has been a false positive.

I am trying to be patient with you because you are a student, but I am not being paid to teach you.  Every minute I spend on these false positives has to be compensated from the very limited libjpeg-turbo General Fund, so you are drawing much-needed resources away from developing libjpeg-turbo.  I am always happy to investigate legitimate security issues, but false positives resulting from improper API usage are an unnecessary distraction.  Please try to be more respectful of my limited time and this project's limited resources in the future.

I would also ask you to please test the TurboJPEG v3 API rather than the legacy TurboJPEG v2.x API.  The legacy functions that your code calls are merely wrappers for TurboJPEG v3 functions.
