### ISSUE TITLE
Heap-Buffer-Overflow in tjDecompressToYUVPlanes due to Incorrect Memory Allocation for YUV Planes

### ISSUE THREAD

**Issue by YancyLii** [libjpeg-turbo/libjpeg-turbo#784]
**Clear and concise description of the bug:**
A heap-buffer-overflow vulnerability exists in the tjDecompressToYUVPlanes function within the libjpeg-turbo library. This issue arises due to incorrect memory allocation for YUV planes when decompressing JPEG images with chroma subsampling. The allocated memory for each YUV plane does not take into account the specific size requirements imposed by the subsampling scheme, leading to a buffer overflow when writing YUV data.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Use my code and input (provided by link) OR:
1.Use tjDecompressToYUVPlanes to decompress a JPEG image with chroma subsampling (e.g., 4:2:0 or 4:2:2).
2.Allocate memory for YUV planes using new unsigned char[width * height] for each plane.
3.Observe that the YUV data writing process causes a heap-buffer-overflow due to the underestimation of buffer sizes for the U and V planes.

**Image(s) needed in order to reproduce the bug (if applicable):**
![image](https://github.com/user-attachments/assets/32edbca9-4bd2-4473-9620-172d84671b56)

**Expected behavior:**
The function should correctly calculate and allocate the necessary memory for each YUV plane, based on the subsampling scheme, to prevent writing beyond the allocated memory.

**Observed behavior:**
The function allocates insufficient memory for the YUV planes, leading to a heap-buffer-overflow when decompressing the image, potentially leading to undefined behavior, crashes, or exploitable conditions.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
clang 17
ubuntu 20.04

**Additional information:**
https://drive.google.com/file/d/1NDWnTYhjEMYiCdzoa5HkO8HF6NZN43Dh/view?usp=sharing

**Comment by dcommander** [comment]
Your code is not using the TurboJPEG API properly.  I will repeat that a crash resulting from improper API usage is *****not***** a libjpeg-turbo bug.  More specifically, you need to use `tjPlaneSizeYUV()` to figure out the number of bytes in each plane.  The plane sizes are not width * height, because YUV planes must be padded to the nearest MCU boundary.  (This is a by-product of the fact that the TurboJPEG YUV functions expose the underlying JPEG algorithms.)  What is the API function supposed to do if the caller disobeys the clear API instructions and doesn't allocate enough memory?  C doesn't give us any way of determining the size of buffers passed to API functions, so it is absolutely incumbent upon the caller to allocate those buffers properly.  That is true of any API that uses caller-allocated buffers.  That's why we provide convenience functions to do the calculations for you, as well as example code that shows you how to use the API properly, as well as [Doxygen documentation](https://rawcdn.githack.com/libjpeg-turbo/libjpeg-turbo/2.1.x/doc/html/group___turbo_j_p_e_g.html#gaa59f901a5258ada5bd0185ad59368540) that clearly states "Use [tjPlaneSizeYUV()](https://rawcdn.githack.com/libjpeg-turbo/libjpeg-turbo/2.1.x/doc/html/group___turbo_j_p_e_g.html#gab4ab7b24f6e797d79abaaa670373961d) to determine the appropriate size for each plane based on the scaled image width, scaled image height, strides, and level of chrominance subsampling."
