### ISSUE TITLE
Possible bug in default_decompress_parms with a lossless image

### ISSUE THREAD

**Issue by dlemstra** [libjpeg-turbo/libjpeg-turbo#793]
The @ImageMagick library is using `libjpeg-turbo` to read `jpeg` files and we are wondering how to solve a specific issue with default_decompress_params that might be a bug. The issue we are experiencing is in this block:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6da05150efa9b7a190d05bf82295127c778d15ab/src/jdapimin.c#L141-L144

We have a user that has a dicom file with an embedded jpeg image (![embedded-in-dicom.jpg](https://github.com/user-attachments/assets/8de2550b-1c07-4aa1-a696-fa4098ac00ac)). This jpeg image is lossless compressed but because it contains a `JFIF` marker the `default_decompress_params` method guesses that the `jpeg_color_space` is `JCS_YCbCr`. The `default_decompress_params` already contains a couple checks that sets `jpeg_color_space` when `cinfo->master->lossless` is `true` and I am wondering if the code should be changed to this instead:

```c
  case 3:
    if (cinfo->master->lossless) {
      cinfo->jpeg_color_space = JCS_RGB;
    } else if (cinfo->saw_JFIF_marker) {
      cinfo->jpeg_color_space = JCS_YCbCr; /* JFIF implies YCbCr */
    } else if (cinfo->saw_Adobe_marker) {
      switch (cinfo->Adobe_transform) {
```
This patch would always make the `jpeg_color_space` `JCS_RGB` when the image is lossless and has `3` channels. I think this would be a good change because this library only has support for decoding a lossless image when `jpeg_color_space` is set to `JCS_RGB`. 

We also tried to see if we could make a patch for this inside ImageMagick after we call `jpeg_read_header` but because `cinfo->master` is an opaque type we are unable to check if the image is lossless and I could not find find an api call that we could use to get this value.

If you agree with the suggested change to `default_decompress_params` I can create a pull request to make this change.

**Comment by dcommander** [comment]
I wrestled with this issue prior to the release of libjpeg-turbo 3.1 beta and discussed it with Thomas Richter, who is in the ISO/IEC JPEG working group and was instrumental in getting libjpeg-turbo adopted as a reference implementation.  The basic problem is that lossless JPEG images that contain a JFIF marker are bogus.  JFIF images are supposed to be lossy and use YCbCr with 4:2:0 subsampling, so a lossless JPEG image cannot be a JFIF image.  Nothing in the spec forbids a lossless JPEG image from using YCbCr.  (The RGB<-->YCbCr color transform is not fully reversible/lossless, but you could encode a lossless JPEG image from a YCbCr source image and decode it into a YCbCr destination image, and it would be fully reversible in that case.)  Unfortunately, there are some lossless JPEG images in the wild that contain a JFIF marker and use the YCbCr colorspace.  Basically, libjpeg-turbo can either assume that all images that have a JFIF marker use the YCbCr colorspace, or it can assume that all lossless images use the RGB colorspace.  It can't do both.  Any lossless JPEG image with a JFIF marker is incorrect, but a lossless JPEG image that uses the YCbCr colorspace and has a JFIF marker is arguably less incorrect than a lossless JPEG image that uses the RGB colorspace and has a JFIF marker.  (At least the former image got the colorspace right when it claimed incorrectly that it was a JFIF image.)  Thus, libjpeg-turbo errs on the side of assuming that a JFIF marker implies YCbCr.

Calling applications are free to override that decision, since `default_decompress_parms()` is called in the body of `jpeg_read_header()`.  After the call to `jpeg_read_header()`, you can test for `cinfo->Se == 0 && cinfo->Ss >= 1 && cinfo->Ss <= 7` to detect whether the image is lossless.

I am very open to more feedback on this, based on images available in the wild.  If there are many more incorrect lossless images that use a JFIF marker and the RGB colorspace vs. lossless images that use a JFIF marker and the YCbCr colorspace, then I would consider changing the default behavior in libjpeg-turbo.  I would also love to know which lossless encoders are generating such images, since that could weight my decision in one direction or another as well.  Ultimately, however, it's a matter of choosing which response to an incorrect image is the lesser evil, i.e. deciding which incorrect behavior should be considered canonical.  libjpeg-turbo would actually be well within its rights to set the JPEG colorspace to unknown when it encounters such an image, thus forcing the calling application to make a decision.

**Comment by dlemstra** [comment]
Thanks for your detailed explanation and I can understand why this decision was made.

It looks like the attached image was created by LEADTOOLS v21.0. I suspect that the vendor wanted to store density and they are (ab)using the JFIF marker for this instead of adding an EXIF profile with that information.

**Comment by dcommander** [comment]
OK, that's a good data point.  I'll see if I can track down lossless images that specify a JFIF marker and use YCbCr.  You also just made me realize that I need to verify whether our own lossless encoder can store density information at all, since it never writes a JFIF header.  Probably not, which means I need to document that fact.

**Comment by dcommander** [comment]
@thorfdbg's opinion could change my mind about this, but at the moment, my reading of the JFIF spec suggests that we are doing the right thing by assuming that a JFIF marker in a 3-component JPEG image implies the YCbCr colorspace, and lossless images that have a JFIF marker and use the RGB colorspace are incorrect.  However, can you please re-upload the test image?  (The link does not work.)  I want to see if perhaps it's doing something non-standard, such as embedding both a JFIF marker and an Adobe marker.  If so, then we could take the color transform hint from the Adobe marker in images that have both.  Otherwise, the only potential action on my part may be to stop embedding a JFIF marker for images that aren't 8-bit-per-sample.  (libjpeg historically didn't support 12-bit data precision unless you changed the `BITS_PER_SAMPLE` macro and recompiled it, so embedding a JFIF marker when `BITS_PER_SAMPLE` was 12 may have been an oversight on Tom Lane's part.)

**Comment by dcommander** [comment]
The image in question does not contain an Adobe marker, so our hands are tied.  Per above, my reading of the JFIF spec is that lossless mode is allowed in JFIF images.  Nowhere does any spec say that lossless JPEG images must use the RGB colorspace, but the JFIF spec does say that JFIF images must always use the YCbCr or grayscale colorspace.  Thus, I believe that libjpeg-turbo's decompressor is making the correct assumption.  Downstream software is free to override that assumption.  The image does contain a comment that says "LEADTOOLS v21.0", so that comment might serve as a hint regarding the image's colorspace.  However, relying on a JPEG comment is way too fragile of a mechanism for upstream inclusion.

I am still open to allowing the Adobe marker to override the JFIF marker, if the LEADTOOLS authors would be willing to make that change on their end (i.e. to embed both markers, the JFIF marker with the density information and the Adobe marker that indicates the RGB colorspace.)
