### ISSUE TITLE
Uninitialized my_color_deconverter in _jinit_color_deconverter

### ISSUE THREAD

**Issue by PetrMinar** [libjpeg-turbo/libjpeg-turbo#798]
I am not 100% sure if it is a problem. In our app we have one hotfix that is applied to libjpeg-turbo codebase. It is there so long that I do not know the reason, why it was added in the first place and under which circumstances it caused problem. But there must be a reason, why it is there...

`jdcolor.c`, line `849` (`_jinit_color_deconverter` function) - the library allocates `my_color_deconverter` that is not memseted to 0. So there might remain uninitialized pointers to conversion tables in the structure. Or is it the case that `cinfo->mem->alloc_small` guarantees returned memory to be zero initialized?

**Comment by dcommander** [comment]
The memory manager's `alloc_small()` method doesn't zero memory by default.  (It does if you define `ZERO_BUFFERS` at compile time, but that mode is not meant for production use.  It's mainly used for testing libjpeg-turbo with MSan or valgrind if libjpeg-turbo's x86 SIMD extensions are enabled, because MSan and valgrind don't properly detect memory that has been initialized at the assembly level.)  However, bearing in mind that `_jinit_color_deconverter()` is a compile-time alias for generating three run-time functions (`jinit_color_deconverter()`, `j12init_color_deconverter()`, and `j16init_color_deconverter()`), those functions fully initialize all structure fields that will subsequently be used by the deconverter being initialized.  IOW, if you call `j12init_color_deconverter()`, then it will initialize the `color_convert_12()` method but not the `color_convert()` or `color_convert_16()` methods, but the library will not subsequently use the `color_convert()` or `color_convert_16()` methods.  Our CI system and OSS-Fuzz continuously and thoroughly test libjpeg-turbo with ASan, UBSan, and MSan, so it is very unlikely that any uninitialized memory issue exists.

That being said, if the calling program does something really stupid like changing `cinfo->data_precision` between calling `jpeg_start_decompress()` and `jpeg_read_scanlines()`, then a segfault will occur long before the color deconverter is accessed.  So I think it might be a good idea to harden the library against such mistakes, which would also include zeroing any structures that contain precision-specific methods and checking that a precision-specific method is non-NULL before calling it.  I'll look into that.
