### ISSUE TITLE
Can't decode 4:2:2 subsampled JPEG images

### ISSUE THREAD

**Issue by k-ross** [libjpeg-turbo/libjpeg-turbo#92]
Using the TurboJPEG API, I cannot decode images that have a chroma subsampling of 4:2:2.  4:2:0 works fine.  tjDecompressHeader fails, as well as tjDecompressToYUV.

Attached is a sample image that fails to decompress, but I can view in Windows Photo Viewer, as well as other image viewing programs, without issue.

![mjpeg_test_422p](https://cloud.githubusercontent.com/assets/523607/17226798/30235e1a-54d9-11e6-9627-059ca6d49805.jpg)

**Comment by dcommander** [comment]
The test image is doing something rather sneaky.  The SOF marker in the JPEG header specifies the horizontal and vertical "sampling factors", which in a 4:2:2 image would normally be 2x1 for the luminance component and 1x1 for the chrominance components.  The way to read that is:  "for every 2x1-pixel block in the source image, include 2x1 luminance components from that block in the output image, but only include one chrominance component."  Your test image specifies sampling factors of 2x2 for the luminance component and 1x2 for the chrominance components.  If you read that as "for every 2x2-pixel block in the source image, include 2x2 luminance components from that block in the output image, but only include 1x2 chrominance components", then that would specify a 4:2:2 image, but it's definitely not the normal way of specifying a 4:2:2 image.  Because the sum of the products of the horizontal and vertical sampling factors must not exceed 10, those sampling factors are normally specified using the smallest possible integers.  It just so happens that 4:2:2 and 4:4:0 images can be specified in two ways without exceeding this limit of 10.  That isn't the case for any of the other standard subsampling types.  You can't, for instance, specify a 4:4:4 image as 2x2,2x2,2x2, because 2x2 + 2x2 + 2x2 = 12, nor could you specify a 4:2:0 image as 4x4,2x2,2x2.  The referenced commit should fix the TurboJPEG such that it now allows for these non-standard images.

**Comment by k-ross** [comment]
First a little info about how the image was created.  It's a single frame from an MJPEG movie file.  The movie file was encoded with Adobe Media Encoder.  However, when I did the encode, I accidentally specified interlaced output, so instead of each frame being 720 pixels high as it should be, I think they are broken into two 360 pixel high fields with a 2x scaling factor.

Regardless, thanks for making this change so quickly!
