### ISSUE TITLE
Does libjpeg-turbo NEON SIMD support 12-bit encoding?

### ISSUE THREAD

**Issue by joewx1984** [libjpeg-turbo/libjpeg-turbo#93]
I've read the jsimd_arm64_neon.S. It seems that jsimd_fdct_islow_neon may support 12-bit DCT. Am I right?

**Comment by dcommander** [comment]
No.  None of the existing SIMD algorithms support 12-bit samples.  They would have to be completely rewritten from scratch to do so.

**Comment by joewx1984** [comment]
Thanks. I'm trying to find a way to accelerate the 12-bit encoding for supporting JPEG XT. I'll try the code in this condition.

**Comment by dcommander** [comment]
It is definitely possible to support 12-bit samples using SIMD instructions.  It would just take some effort to develop the algorithms, and they would not be as fast, because in 12-bit mode, libjpeg uses 16 bits for each sample and 32 bits for each DCT coefficient instead of 8 bits for each sample and 16 bits for each DCT coefficient.  To support that using SSE2 or NEON (both 128-bit instruction types) would take at least twice the instructions.  It would be a more natural fit for a 256-bit instruction set like AVX2, since that would involve fewer algorithmic changes.  The DCT algorithms, for instance, use the 128-bit word size of SSE2 to operate on eight 16-bit coefficients at a time.  Those same algorithms could be extended to use the 256-bit word size of AVX2 to operate on eight 32-bit coefficients at a time.  Otherwise, designing algorithms for 12-bit support would require going back to first principles, and based on my experience with other SIMD instruction sets, that's going to be hundreds of hours of work.

libjpeg[-turbo] doesn't inherently support JPEG XT, but my understanding is that those extensions are backward compatible, so it should be possible to add them at some point.  A while ago, I looked at adding Part 9 (alpha channel encoding), but it proved less straightforward than I imagined it would be, and I didn't have time to pursue it further.
