### ISSUE TITLE
Question about pixel data - Can we pass non-interleaved pixel data to the compression function?

### ISSUE THREAD

**Issue by kevingnet** [libjpeg-turbo/libjpeg-turbo#94]
Documentation says that several other color spaces are supported. In our use case, we have that the source jpeg files we start with have the pixel data split into channel arrays, such that the first array would be Red, etc.. Then, in our code, we use code to interleave the pixel data so that we pass to libjpeg-turbo pixel data in one array such that it would have RGB, so each pixel fits into a 24 bit value. 
All of that takes extra processing, and I was wondering if there is a way to pass in the pixel data when it's not interleaved. I searched the documentation and it reads that the jpeg specification supports either way, however, when I look at the code, specifically the locations with switch statements where it would indicate that non-interleaved data could be passed, I didn't see anything that appears to support it, at least from the look in that code.

Thanks,
Kevin

**Comment by dcommander** [comment]
"Interleaved" in the context of JPEG doesn't refer to pixels.  It refers to MCU blocks.  Normally, packed RGB pixels are fed into the compressor on a line-by-line basis.  The compressor first converts each line of packed RGB pixels into a line of packed YCbCr pixels.  It then feeds the line of packed YCbCr pixels into the downsampler, which downsamples the chroma components (if necessary) and separates the components into separate component planes.  Each component plane consists of 8x8-sample "MCU blocks."  Once enough lines of source data have been processed to build a complete "MCU row" (a block of samples the same width as the source image and whose height is 8 * the vertical subsampling factor), then each MCU block in the MCU row is fed into the subsequent stages of the pipeline (sample conversion, forward DCT, quantization, Huffman encoding.)  This is where the difference between interleaved and non-interleaved JPEGs comes into play.  To generate an interleaved JPEG scan, the compressor feeds the blocks from the MCU row into the subsequent pipeline stages in component order.  Thus, if you have an image that is subsampled with 4:2:0 subsampling, then for each 16x16-pixel block in the source image, the JPEG scan will contain four 8x8 luma blocks and four 8x8 chroma blocks (two each for both of the chroma components) in sequence, followed by the MCU blocks for the next 16x16-pixel block in the source image, etc.  A non-interleaved scan will contain all of the Y blocks from the image, followed by all of the Cb blocks, followed by all of the Cr blocks.

libjpeg can definitely accept planar data in YCbCr form, and the TurboJPEG API even takes advantage of this to allow applications to directly compress from/decompress to YCbCr planar data.  I *think* it should be possible to do this with raw planar RGB data as well, but it would require extending the TurboJPEG API to support that use case.  Also, since encoding a JPEG in this manner bypasses any color conversion, the JPEG image would have to use the RGB colorspace.  That will adversely affect the compression ratio, since RGB data can't be compressed as efficiently by the Huffman encoder as YCbCr data can (at least that's been my observation-- I have no idea why it's the case.)  Your other option would be to convert the planar RGB data into planar YCbCr data yourself and pass it into the compressor in planar YCbCr form, but unless you took advantage of some other SIMD-accelerated library to do that conversion, it's likely that that approach would be slower than what you're already doing.  Even with SIMD-accelerated conversion, that approach may still be slower, because converting the entire image from RGB planar to YCbCr planar would blow out of all of the CPU caches.  You'd be better off taking advantage of spatial locality by converting each row of the planar RGB data into a packed pixel row, feeding it into the compressor, then doing the same for the next row, etc.  If that's not what you're already doing, you might try it, because it may perform better than converting the full image prior to compression.  There unfortunately isn't any mechanism for converting planar RGB to planar YCbCr within libjpeg-turbo, which is really what you would need.

Using the "standard" interface, we can currently generate:
* YCbCr JPEGs from packed RGB (or extended RGB) pixels
* YCbCr JPEGs from packed non-subsampled YCbCr pixels
* YCCK JPEGs from packed CMYK pixels
* YCCK JPEGs from packed non-subsampled YCCK pixels
* Grayscale JPEGs from grayscale pixels
* Grayscale JPEGs from packed RGB (or extended RGB) pixels
* Grayscale JPEGs from non-subsampled YCbCr pixels
* RGB JPEGs from packed RGB (or extended RGB) pixels
* CMYK JPEGs from packed CMYK pixels

Using the "raw" interface, we can currently generate YCbCr, YCCK, and grayscale JPEGs from pre-subsampled planar data in the same colorspace.  With some API enhancements, we can probably generate RGB or CMYK JPEGs using the same mechanism.  But there isn't ever going to be a way of generating a YCbCr JPEG using RGB planar data, which seems to be what you need.

**Comment by dcommander** [comment]
You couldn't use the TurboJPEG API to do this, since it's a full-image API, but if you didn't mind getting your hands dirty in the libjpeg API, you could steal the code for tjCompressFromYUVPlanes() and make a similar function that converts planar RGB input to planar YCbCr on an MCU row basis, which would make slightly better use of the caches than converting the whole image at-large.

**Comment by kevingnet** [comment]
Thanks @dcommander for the detailed and prompt answers. I think your observations are correct, that's kind of what I had gathered by looking at the code. I'm trying to eliminate some of the steps, looks like I'm going to have some design work to do for this to happen.

**Comment by kevingnet** [comment]
That is correct, about the Huffman encoder. The conversion from RGB to YCbCr causes the data to lose some color definition which is considered to be imperceptible by the human eye. So it takes advantage of that, and that lossy conversion naturally the compression algorithms are able to obtain better rates due to said data loss.

**Comment by kevingnet** [comment]
The jpeg-turbo lib, when passed in RGB data, there's an extra step which is taken just before the data goes to the compressor. So, even if your data is RGB to begin with is coerced/converted into YCbCr.

**Comment by dcommander** [comment]
I don't understand your last comment.  Please clarify.  Are you referring to the TurboJPEG API?  There is no "jpeg-turbo lib".

**Comment by kevingnet** [comment]
Ah, sorry, yes it's libjpeg_turbo. Not so much the API itself, but more the internals, how it gets things done.
There is a function that setups a LUT for the conversion from RGB to YCbCr, then, depending on which mode you use, it will use that table. The table is very efficient, more so than a single LUT to convert from a 32 bit value, it uses one LUT for each component, so there are 255 entries for each and then it uses the formula for conversion. I added a single LUT with 24 bit max int val entries and was way slower, I think it had to do with data locality.
