### ISSUE TITLE
Fixes to RGB565 dithering code

### ISSUE THREAD

**Issue by dcommander** [libjpeg-turbo/libjpeg-turbo#95]
Moving this from the libjpeg-turbo SourceForge tracker, which is now closed to new issues.

As pointed out by @ssvb in the following tracker comment:

https://sourceforge.net/p/libjpeg-turbo/patches/24/#1066/84d9

jdcol565.c apparently has some bugs:
1. The PACK_NEED_ALIGNMENT branch is missing the DITHER_ROTATE operation
2. Only a single element of the dither_matrix is used, while we should move to a new element for each new row (otherwise we don't get proper dithering in the vertical direction)
(the big endian issues have already been fixed.)

Looking at the code, (1) seems to be true, but I can't find a way to actually make that branch activate at run time, so I'm having difficulty verifying whether the fix actually fixes anything.  (2) doesn't seem to be true, because of https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdcol565.c#L115, but I'm probably missing something.

**Comment by dcommander** [comment]
@ssvb, I was wondering if you could comment on this, since you were the first to point out these issues.  Is there an easy way to reproduce them?

**Comment by dcommander** [comment]
Closing as WFM, since further information regarding how to reproduce these issues is not forthcoming, and the feature in question has been in the code for years now with no complaints.  Specifically, this feature was implemented in order to support the integration of libjpeg-turbo into Android, which requires the ability to decompress JPEG images into RGB 5-6-5 buffers. libjpeg-turbo has been shipping with Android for a couple of years now, and no one has complained about incorrect RGB 5-6-5 decompression.

**Comment by hasinoff** [comment]
One potential issue with RGB565 that I can repro is that results seem to depend on whether "merged" upsampling is enabled or not. If I understand correctly, libjpeg-turbo's results are supposed to be bit exact regardless of whether upsampling and format conversion are "merged" or run separately. Because that "merging" isn't supported for fancy upsampling, so the two operations considered here are: (1) upsample with a box filter and (2) convert to rgb565.

The simple repro (on my Linux x86_64 machine) is to edit use_merged_upsample() to return FALSE up top, and then run tests:
$ autoreconf -fiv && sh ./configure && make clean ; make test
With this modification just one test case that fails:
./djpeg -dct int -nosmooth -rgb565 -bmp -outfile testout_420m_islow_565D.bmp ./testimages/testorig.jpg
md5/md5cmp d1be3a3339166255e76fa50a0d70d73e testout_420m_islow_565D.bmp
testout_420m_islow_565D.bmp: FAILED.  Checksum is ce034037d212bc403330df6f915c161b

Originally described here:
https://github.com/libjpeg-turbo/libjpeg-turbo/pull/81#issuecomment-218275390

**Comment by dcommander** [comment]
@hasinoff That should now be fixed.  The merged 4:2:0 upsampling/dithered RGB565 algorithm had a bug whereby it was using the wrong dither mask for the second column in each 4-pixel block.
